"""Mayo Clinic mirror — clinical trials catalog (40 entries)."""

# (nct_id, title, condition_keyword, phase, status, intervention,
#  brief_summary, eligibility_criteria, locations, principal_investigator_idx)
CLINICAL_TRIALS = [
    ("NCT05123456", "Phase 3 Study of Pembrolizumab Plus Chemotherapy in Stage III Non-Small Cell Lung Cancer", "lung cancer",
     "Phase 3", "Recruiting", "Pembrolizumab + Carboplatin + Pemetrexed",
     "This study evaluates the efficacy and safety of adding pembrolizumab to standard platinum-based chemotherapy in patients with newly diagnosed stage III non-small cell lung cancer who are candidates for definitive concurrent chemoradiotherapy.",
     "Adults 18+ with histologically confirmed stage IIIA-IIIB NSCLC, ECOG 0-1, adequate organ function, no prior systemic therapy. Excludes EGFR/ALK-driven tumors, active autoimmune disease, prior immunotherapy.",
     ["Rochester", "Jacksonville", "Phoenix"], 12),
    ("NCT05234567", "CAR-T Cell Therapy for Relapsed/Refractory Large B-Cell Lymphoma in Older Adults", "lymphoma",
     "Phase 2", "Recruiting", "Axicabtagene ciloleucel",
     "Single-arm trial evaluating safety and efficacy of CD19-directed CAR-T cell therapy in patients aged 65 and older with relapsed/refractory large B-cell lymphoma, including diffuse large B-cell lymphoma.",
     "Age 65+, biopsy-confirmed LBCL with relapse or refractory disease after at least two lines of therapy, measurable disease, ECOG 0-2, adequate cardiopulmonary function.",
     ["Rochester", "Jacksonville"], 15),
    ("NCT05345678", "Magnetic Resonance Guided Focused Ultrasound for Essential Tremor", "tremor",
     "Phase 3", "Recruiting", "MRgFUS thalamotomy",
     "This study evaluates incisionless MR-guided focused ultrasound thalamotomy for medication-refractory essential tremor, with primary endpoint of tremor reduction at 3 months.",
     "Adults 22+ with disabling essential tremor refractory to at least two medications, intact cognition, MRI compatible, signed informed consent.",
     ["Rochester"], 8),
    ("NCT05456789", "Tirzepatide for Heart Failure With Preserved Ejection Fraction and Obesity", "heart failure",
     "Phase 3", "Recruiting", "Tirzepatide",
     "Randomized placebo-controlled trial of weekly subcutaneous tirzepatide in patients with HFpEF and obesity, evaluating Kansas City Cardiomyopathy Questionnaire score and body weight at one year.",
     "Adults 40+ with documented HFpEF (LVEF >=50%, NT-proBNP elevation), BMI 30+, NYHA class II-IV, on stable heart failure therapy.",
     ["Rochester", "Jacksonville", "Phoenix"], 1),
    ("NCT05567890", "Lecanemab for Preclinical Alzheimer's Disease", "alzheimer",
     "Phase 3", "Recruiting", "Lecanemab",
     "Randomized double-blind placebo-controlled study of lecanemab in cognitively normal adults with elevated brain amyloid as detected by amyloid PET, evaluating progression to symptomatic Alzheimer's disease.",
     "Adults 55-80, cognitively normal (CDR 0), amyloid-positive on PET, MRI compatible, study partner available.",
     ["Rochester", "Jacksonville"], 17),
    ("NCT05678901", "Proton Beam Therapy vs Photon Therapy for Pediatric Medulloblastoma", "medulloblastoma",
     "Phase 3", "Recruiting", "Proton beam radiation",
     "Randomized comparison of proton beam therapy and intensity-modulated photon therapy in newly diagnosed pediatric medulloblastoma, evaluating progression-free survival and neurocognitive outcomes.",
     "Ages 3-21 with newly diagnosed average or high-risk medulloblastoma, surgical resection completed, no prior radiation.",
     ["Rochester"], 24),
    ("NCT05789012", "Empagliflozin for Cardiorenal Protection in Type 1 Diabetes With Albuminuria", "diabetes",
     "Phase 2", "Recruiting", "Empagliflozin",
     "Investigator-initiated trial evaluating empagliflozin in adults with type 1 diabetes and persistent albuminuria, with composite kidney function endpoints at 18 months.",
     "Adults 18-65 with type 1 diabetes for at least 5 years, urinary albumin-creatinine ratio 30-3000 mg/g, eGFR 45+, HbA1c under 11%.",
     ["Rochester", "Phoenix"], 6),
    ("NCT05890123", "Ablation vs Antiarrhythmic Therapy for Atrial Fibrillation in Heart Failure", "atrial fibrillation",
     "Phase 4", "Recruiting", "Catheter ablation",
     "Randomized trial comparing pulmonary vein isolation with optimized medical therapy in patients with persistent atrial fibrillation and heart failure with reduced ejection fraction.",
     "Adults 18+, persistent atrial fibrillation, LVEF <=40%, NYHA II-III, optimal medical heart failure therapy for >=3 months.",
     ["Rochester", "Jacksonville", "Phoenix"], 1),
    ("NCT05901234", "Belzutifan for Sporadic Renal Cell Carcinoma With Advanced Disease", "renal cell carcinoma",
     "Phase 2", "Recruiting", "Belzutifan",
     "Multicenter study evaluating the HIF-2 alpha inhibitor belzutifan in patients with advanced clear cell renal cell carcinoma progressing on standard therapy.",
     "Adults 18+ with advanced clear cell RCC, prior immunotherapy and VEGF-targeted therapy, measurable disease, ECOG 0-2.",
     ["Rochester", "Jacksonville"], 19),
    ("NCT06012345", "Mavacamten for Symptomatic Obstructive Hypertrophic Cardiomyopathy", "cardiomyopathy",
     "Phase 3", "Active, not recruiting", "Mavacamten",
     "Long-term extension study evaluating durable response to mavacamten in patients with symptomatic obstructive hypertrophic cardiomyopathy who completed pivotal trials.",
     "Adults 18+ with symptomatic obstructive HCM, prior participation in mavacamten clinical program, LVOT gradient documented.",
     ["Rochester"], 1),
    ("NCT06123456", "CFTR Modulator Therapy for Non-Responsive Genotypes in Cystic Fibrosis", "cystic fibrosis",
     "Phase 2", "Recruiting", "Investigational CFTR modulator",
     "Phase 2 dose-finding study of a next-generation CFTR modulator in people with cystic fibrosis and mutations not responsive to currently approved therapies.",
     "Ages 12+ with CF and at least one residual function or class V mutation, FEV1 40-90% predicted, clinically stable.",
     ["Rochester", "Jacksonville", "Phoenix"], 7),
    ("NCT06234567", "Resmetirom for Nonalcoholic Steatohepatitis With Bridging Fibrosis", "steatohepatitis",
     "Phase 3", "Recruiting", "Resmetirom",
     "Randomized study evaluating thyroid hormone receptor beta agonist resmetirom in adults with biopsy-confirmed nonalcoholic steatohepatitis and stage 2-3 fibrosis.",
     "Adults 18+ with biopsy-confirmed NASH and F2-F3 fibrosis, MRI-PDFF >=8%, not on weight loss medications.",
     ["Rochester", "Jacksonville", "Phoenix"], 5),
    ("NCT06345678", "Liso-cel for Mantle Cell Lymphoma in Second Line", "lymphoma",
     "Phase 2", "Recruiting", "Lisocabtagene maraleucel",
     "Single-arm study of CD19 CAR-T cell therapy in patients with relapsed or refractory mantle cell lymphoma after one prior line of therapy including BTK inhibitor.",
     "Adults 18+ with mantle cell lymphoma after at least one line including BTK inhibitor, measurable disease, adequate organ function.",
     ["Rochester", "Jacksonville"], 15),
    ("NCT06456789", "Endoscopic Sleeve Gastroplasty for Class II Obesity", "obesity",
     "Phase 4", "Recruiting", "Endoscopic sleeve gastroplasty",
     "Prospective cohort study evaluating sustained weight loss after endoscopic sleeve gastroplasty in adults with class II obesity who decline traditional bariatric surgery.",
     "Adults 22-65, BMI 35-40, failed at least 6 months of supervised weight loss, willing to attend follow-up at 1, 3, 6, 12, 24 months.",
     ["Rochester", "Jacksonville"], 2),
    ("NCT06567890", "Mitochondrial Donor Living Liver Transplant for Acute Liver Failure", "liver failure",
     "Phase 1", "Recruiting", "Auxiliary partial orthotopic liver transplant",
     "First-in-human study evaluating safety and feasibility of mitochondrial-augmented auxiliary partial liver transplantation in adults with acute liver failure from acetaminophen.",
     "Adults 18-65, acute liver failure from acetaminophen toxicity, INR >2.0 after vitamin K, no other transplant exclusions.",
     ["Rochester"], 25),
    ("NCT06678901", "Erenumab for Refractory Chronic Migraine in Adolescents", "migraine",
     "Phase 3", "Recruiting", "Erenumab",
     "Randomized trial of monthly erenumab in adolescents with chronic migraine refractory to oral preventive therapy.",
     "Ages 12-17, chronic migraine with at least 15 headache days per month, failed at least 2 preventive medications.",
     ["Rochester", "Jacksonville", "Phoenix"], 22),
    ("NCT06789012", "Robotic Versus Open Pancreaticoduodenectomy for Resectable Pancreatic Cancer", "pancreatic cancer",
     "Phase 3", "Recruiting", "Robotic Whipple",
     "Randomized non-inferiority study comparing robotic and open Whipple procedure in adults with resectable pancreatic head adenocarcinoma.",
     "Adults 18-80 with resectable pancreatic head adenocarcinoma, BMI <=40, no prior major abdominal surgery, fit for major surgery.",
     ["Rochester", "Jacksonville"], 21),
    ("NCT06890123", "Vagal Nerve Stimulation for Treatment Resistant Depression", "depression",
     "Phase 4", "Recruiting", "Vagal nerve stimulation",
     "Prospective registry of patients receiving VNS for treatment-resistant unipolar depression, evaluating response and remission at 12 months.",
     "Adults 18-75, major depression with 4+ failed adequate trials, currently on stable antidepressant therapy.",
     ["Rochester"], 14),
    ("NCT06901234", "Stereotactic Body Radiation for Liver-Limited Colorectal Metastases", "colon cancer",
     "Phase 2", "Recruiting", "Stereotactic body radiation",
     "Single-arm study evaluating SBRT for oligometastatic liver disease from colorectal cancer in patients unsuitable for surgical resection or ablation.",
     "Adults 18+ with up to 3 liver lesions, each <=5 cm, no extrahepatic disease, ECOG 0-2.",
     ["Rochester", "Jacksonville", "Phoenix"], 24),
    ("NCT07012345", "Mediterranean Diet for Cognitive Aging in Older Adults", "alzheimer",
     "Phase 4", "Recruiting", "Mediterranean diet counseling",
     "Randomized trial comparing intensive Mediterranean diet counseling with standard nutrition advice for cognitive function over 24 months in older adults.",
     "Ages 65-85, MCI or normal cognition, MMSE >=24, BMI 22-40, no recent stroke.",
     ["Rochester", "Jacksonville"], 17),
    ("NCT07123456", "TIL Therapy for Metastatic Cervical Cancer Refractory to Checkpoint Inhibitor", "cervical cancer",
     "Phase 2", "Recruiting", "Tumor-infiltrating lymphocyte therapy",
     "Single-arm study of autologous tumor-infiltrating lymphocyte therapy in patients with metastatic cervical cancer after progression on standard immunotherapy.",
     "Adults 18+ with metastatic cervical squamous, adenocarcinoma, or adenosquamous, prior checkpoint inhibitor, accessible tumor for harvest.",
     ["Rochester"], 13),
    ("NCT07234567", "Cardiac MRI Guided Catheter Ablation for Recurrent Ventricular Tachycardia", "arrhythmia",
     "Phase 2", "Recruiting", "MRI-guided VT ablation",
     "Comparative trial of cardiac MRI guided substrate ablation versus electroanatomic mapping in patients with recurrent ventricular tachycardia and ischemic cardiomyopathy.",
     "Adults 18+ with ICD, ischemic cardiomyopathy, recurrent VT despite antiarrhythmic, MRI compatible.",
     ["Rochester"], 1),
    ("NCT07345678", "Living Donor Lobar Lung Transplant for Pediatric End-Stage Lung Disease", "cystic fibrosis",
     "Phase 1", "Recruiting", "Living donor lobar lung transplant",
     "First US prospective study of living donor lobar lung transplantation in pediatric and young adult recipients with end-stage cystic fibrosis or pulmonary hypertension.",
     "Ages 8-25 awaiting deceased donor lung transplant, two compatible living donors, no contraindications to transplant.",
     ["Rochester"], 25),
    ("NCT07456789", "Olaparib Maintenance for BRCA-Mutated Pancreatic Cancer", "pancreatic cancer",
     "Phase 3", "Recruiting", "Olaparib",
     "Randomized maintenance trial of olaparib in patients with germline BRCA1/2 mutation and metastatic pancreatic adenocarcinoma after platinum chemotherapy.",
     "Adults 18+ with metastatic pancreatic adenocarcinoma, germline BRCA1/2, completed first-line platinum chemotherapy with stable disease.",
     ["Rochester", "Jacksonville", "Phoenix"], 21),
    ("NCT07567890", "Semaglutide for Polycystic Ovary Syndrome and Metabolic Dysfunction", "polycystic ovary syndrome",
     "Phase 3", "Recruiting", "Semaglutide",
     "Randomized double-blind trial of semaglutide compared to placebo in women with PCOS and obesity, evaluating menstrual regularity and metabolic parameters.",
     "Females 18-40 with confirmed PCOS, BMI 27+, not pregnant, not on hormonal contraception within 30 days.",
     ["Rochester", "Jacksonville"], 11),
    ("NCT07678901", "Tofersen for SOD1-ALS", "amyotrophic lateral sclerosis",
     "Phase 3", "Active, not recruiting", "Tofersen",
     "Open-label extension trial of intrathecal tofersen in adults with ALS and SOD1 mutations, evaluating long-term safety and function over 5 years.",
     "Adults 18+ with confirmed SOD1 mutation, ALS by El Escorial criteria, completed pivotal study.",
     ["Rochester", "Jacksonville"], 9),
    ("NCT07789012", "Bispecific Antibody Therapy for Refractory Multiple Myeloma", "multiple myeloma",
     "Phase 2", "Recruiting", "Teclistamab",
     "Single-arm trial of weekly subcutaneous teclistamab in patients with relapsed/refractory multiple myeloma after at least 3 prior lines.",
     "Adults 18+ with relapsed/refractory MM after 3+ lines including PI, IMiD, and CD38 antibody, measurable disease.",
     ["Rochester", "Jacksonville"], 15),
    ("NCT07890123", "DBS for Refractory OCD in Adolescents", "obsessive compulsive disorder",
     "Phase 2", "Recruiting", "Deep brain stimulation",
     "Investigator-initiated single-arm study of deep brain stimulation of the ventral capsule/ventral striatum in adolescents with severe treatment-resistant OCD.",
     "Ages 12-21, severe OCD (Y-BOCS >=28), failed 2+ SSRIs and CBT, stable home environment.",
     ["Rochester"], 14),
    ("NCT07901234", "Selpercatinib for RET-Altered Thyroid Cancer", "thyroid cancer",
     "Phase 2", "Recruiting", "Selpercatinib",
     "Single-arm study of selpercatinib in patients with RET-altered medullary thyroid cancer or RET-fusion-positive differentiated thyroid cancer.",
     "Adults 18+, RET-altered thyroid cancer, progressive disease, prior systemic therapy permitted.",
     ["Rochester", "Jacksonville"], 6),
    ("NCT08012345", "Photodynamic Therapy for Barrett's Esophagus With High-Grade Dysplasia", "barrett's esophagus",
     "Phase 2", "Recruiting", "Photodynamic therapy",
     "Prospective study of next-generation photodynamic therapy in patients with Barrett's esophagus and high-grade dysplasia who decline esophagectomy.",
     "Adults 18+ with biopsy-confirmed BE and high-grade dysplasia, no invasive carcinoma, not candidates for radiofrequency ablation.",
     ["Rochester", "Jacksonville"], 5),
    ("NCT08123456", "Genetic Counseling-First Approach for Hereditary Breast Cancer Screening", "breast cancer",
     "Phase 4", "Recruiting", "Genetic counseling intervention",
     "Pragmatic randomized trial comparing genetic counseling-first versus testing-first approaches in women at elevated risk for hereditary breast cancer.",
     "Females 25-65 with first-degree relative with breast cancer under 50, no prior genetic testing.",
     ["Rochester", "Jacksonville", "Phoenix"], 26),
    ("NCT08234567", "Robotic Endovascular Repair of Complex Aortic Aneurysm", "aortic aneurysm",
     "Phase 1", "Recruiting", "Robotic endovascular repair",
     "First-in-human study of robotic-assisted fenestrated endovascular repair for complex thoracoabdominal aortic aneurysms.",
     "Adults 50-85, thoracoabdominal aortic aneurysm >=5.5 cm, unsuitable for open surgical repair.",
     ["Rochester"], 1),
    ("NCT08345678", "Spinal Cord Stimulation for Chronic Painful Diabetic Neuropathy", "diabetes",
     "Phase 4", "Recruiting", "Spinal cord stimulation",
     "Randomized trial of high-frequency spinal cord stimulation versus optimized medical management in adults with painful diabetic neuropathy.",
     "Adults 22-75, painful diabetic neuropathy refractory to medications, HbA1c <10, pain VAS >=6.",
     ["Rochester", "Jacksonville"], 28),
    ("NCT08456789", "Plasma Exchange for Long COVID With Persistent Fatigue", "chronic fatigue",
     "Phase 2", "Recruiting", "Therapeutic plasma exchange",
     "Open-label single-arm trial of therapeutic plasma exchange for adults with post-acute COVID-19 fatigue and brain fog persisting more than 12 months.",
     "Adults 18-65 with persistent post-COVID symptoms >12 months, severe fatigue (Chalder >24), confirmed prior COVID-19.",
     ["Rochester"], 17),
    ("NCT08567890", "Aspirin for Primary Prevention in Older Adults With Elevated CRP", "coronary artery disease",
     "Phase 3", "Recruiting", "Aspirin",
     "Randomized placebo-controlled trial evaluating low-dose aspirin for primary cardiovascular prevention in older adults with elevated high-sensitivity CRP.",
     "Ages 65-80, hsCRP >=2.0 mg/L, no prior cardiovascular event, no contraindication to aspirin.",
     ["Rochester", "Jacksonville", "Phoenix"], 1),
    ("NCT08678901", "Voxelotor in Children With Sickle Cell Disease", "sickle cell",
     "Phase 3", "Recruiting", "Voxelotor",
     "Long-term safety and efficacy study of voxelotor in children ages 4-11 with sickle cell anemia.",
     "Ages 4-11 with confirmed HbSS or HbS-beta0 thalassemia, hemoglobin 5.5-10.5 g/dL.",
     ["Rochester", "Jacksonville"], 23),
    ("NCT08789012", "Liver Transplant Versus Locoregional Therapy for Early Hepatocellular Carcinoma", "liver cancer",
     "Phase 3", "Recruiting", "Liver transplantation",
     "Randomized study comparing living donor liver transplant with locoregional therapy in patients with early hepatocellular carcinoma within Milan criteria.",
     "Adults 18-70, HCC within Milan criteria, MELD <15, available living donor.",
     ["Rochester", "Jacksonville"], 25),
    ("NCT08890123", "Pembrolizumab Plus Chemoradiation for Locally Advanced Cervical Cancer", "cervical cancer",
     "Phase 3", "Recruiting", "Pembrolizumab",
     "Randomized trial of pembrolizumab added to standard chemoradiation in patients with locally advanced cervical cancer.",
     "Adults 18+ with FIGO stage IB3-IVA cervical cancer, no distant metastases, no prior systemic therapy for cervical cancer.",
     ["Rochester", "Jacksonville", "Phoenix"], 13),
    ("NCT08901234", "Anti-IL-23 Therapy for Severe Ulcerative Colitis", "ulcerative colitis",
     "Phase 3", "Recruiting", "Mirikizumab",
     "Open-label maintenance study of subcutaneous mirikizumab in patients with moderately to severely active ulcerative colitis who responded to induction.",
     "Adults 18-80 with active UC, prior biologic therapy permitted, in clinical response after induction.",
     ["Rochester", "Jacksonville", "Phoenix"], 5),
    ("NCT09012345", "Awake Craniotomy for Eloquent Brain Tumors With Functional MRI Mapping", "brain tumor",
     "Phase 2", "Recruiting", "Awake craniotomy with intraoperative mapping",
     "Prospective study evaluating language and motor preservation after awake craniotomy with intraoperative functional MRI mapping for tumors in eloquent brain regions.",
     "Adults 18+ with primary brain tumor adjacent to language or motor cortex, English-speaking, no severe cognitive impairment.",
     ["Rochester"], 21),
]

# ---------------------------------------------------------------------------
# Symptom Checker — rule table
# ---------------------------------------------------------------------------
# body_regions -> [symptom slugs]
BODY_REGIONS = [
    ("head", "Head", ["headache", "dizziness", "nasal-congestion", "sore-throat", "ear-pain"]),
    ("chest", "Chest", ["chest-pain", "shortness-of-breath", "cough", "heart-palpitations"]),
    ("abdomen", "Abdomen", ["abdominal-pain", "nausea-vomiting", "diarrhea", "constipation", "blood-in-stool"]),
    ("back", "Back", ["low-back-pain", "neck-pain", "upper-back-pain"]),
    ("limbs", "Arms / Legs", ["foot-pain", "knee-pain", "shoulder-pain", "hip-pain", "numbness-tingling-hands", "foot-swelling"]),
    ("urinary", "Urinary / Genital", ["urinary-problems", "pelvic-pain-female", "pelvic-pain-male"]),
    ("skin", "Skin", ["skin-rash"]),
    ("general", "General / Whole-body", ["fever", "fatigue", "weight-loss"]),
]

# (slug, name, region, demographic_applies)  demographic in {adult, both}
SYMPTOMS = [
    ("headache", "Headache", "head", "both"),
    ("dizziness", "Dizziness", "head", "both"),
    ("nasal-congestion", "Nasal congestion", "head", "both"),
    ("sore-throat", "Sore throat", "head", "both"),
    ("ear-pain", "Ear pain", "head", "both"),
    ("chest-pain", "Chest pain", "chest", "adult"),
    ("shortness-of-breath", "Shortness of breath", "chest", "both"),
    ("cough", "Cough", "chest", "both"),
    ("heart-palpitations", "Heart palpitations", "chest", "adult"),
    ("abdominal-pain", "Abdominal pain", "abdomen", "both"),
    ("nausea-vomiting", "Nausea or vomiting", "abdomen", "both"),
    ("diarrhea", "Diarrhea", "abdomen", "both"),
    ("constipation", "Constipation", "abdomen", "both"),
    ("blood-in-stool", "Blood in stool", "abdomen", "adult"),
    ("low-back-pain", "Low back pain", "back", "adult"),
    ("neck-pain", "Neck pain", "back", "adult"),
    ("upper-back-pain", "Upper back pain", "back", "adult"),
    ("foot-pain", "Foot or ankle pain", "limbs", "adult"),
    ("knee-pain", "Knee pain", "limbs", "adult"),
    ("shoulder-pain", "Shoulder pain", "limbs", "adult"),
    ("hip-pain", "Hip pain", "limbs", "adult"),
    ("numbness-tingling-hands", "Numbness or tingling in hands", "limbs", "adult"),
    ("foot-swelling", "Foot or leg swelling", "limbs", "adult"),
    ("urinary-problems", "Urinary problems", "urinary", "adult"),
    ("pelvic-pain-female", "Pelvic pain (female)", "urinary", "adult"),
    ("pelvic-pain-male", "Pelvic pain (male)", "urinary", "adult"),
    ("skin-rash", "Skin rash", "skin", "both"),
    ("fever", "Fever", "general", "both"),
    ("fatigue", "Fatigue", "general", "both"),
    ("weight-loss", "Unintentional weight loss", "general", "adult"),
]

# Symptom Checker rule table — deterministic rules: symptom + age_group + duration -> [possible causes]
# urgency: "urgent" (ER), "routine" (call physician within 24-48h), "self" (self-care first)
# rule: (symptom_slug, age_group, duration, [(condition_name, urgency, short_note)])
# age_group in {adult, child, any}; duration in {acute, chronic, any}
SC_RULES = [
    ("headache", "adult", "acute", [
        ("Migraine", "routine", "Unilateral throbbing headache, photophobia, often with nausea — see a clinician if frequent or severe."),
        ("Tension Headache", "self", "Pressure or band-like pain across the forehead, often related to stress or poor sleep."),
        ("Brain Aneurysm", "urgent", "Sudden 'thunderclap' headache, often described as the worst of life — seek emergency care immediately."),
        ("Meningitis", "urgent", "Headache with fever, neck stiffness, photophobia — emergency evaluation needed."),
        ("Acute Sinusitis", "routine", "Headache with nasal congestion and facial pressure after a cold."),
    ]),
    ("headache", "adult", "chronic", [
        ("Migraine", "routine", "Recurrent episodic disabling headaches — preventive medication may help."),
        ("Tension Headache", "self", "Chronic frequent low-grade headaches — assess stress, sleep, posture."),
        ("Brain Tumor", "routine", "New persistent headaches with neurologic symptoms warrant brain imaging."),
        ("Cervical Spondylosis", "routine", "Headache referred from neck arthritis."),
    ]),
    ("chest-pain", "adult", "acute", [
        ("Heart Attack", "urgent", "Pressure or squeezing chest pain, radiating to arm or jaw, with sweating or shortness of breath — call 911."),
        ("Angina", "urgent", "Exertional chest pressure relieved by rest — needs urgent cardiac evaluation."),
        ("Pulmonary Embolism", "urgent", "Sudden pleuritic chest pain with shortness of breath, especially after immobility — emergency care."),
        ("Acid Reflux", "self", "Burning chest pain after meals or lying down — try over-the-counter acid reducer."),
        ("Costochondritis", "self", "Sharp chest wall pain reproducible with pressure — usually self-limited."),
    ]),
    ("chest-pain", "adult", "chronic", [
        ("Coronary Artery Disease", "routine", "Recurrent exertional chest discomfort warrants outpatient cardiac evaluation."),
        ("Acid Reflux", "self", "Recurrent post-prandial chest burning."),
        ("Anxiety Disorders", "routine", "Chest tightness with panic features."),
    ]),
    ("shortness-of-breath", "adult", "acute", [
        ("Pulmonary Embolism", "urgent", "Sudden shortness of breath, especially with chest pain or after immobility — emergency care."),
        ("Asthma", "routine", "Wheezing with shortness of breath — use rescue inhaler and seek care if no improvement."),
        ("Pneumonia", "routine", "Shortness of breath with fever and cough — same-day evaluation."),
        ("Congestive Heart Failure", "urgent", "Shortness of breath worse lying flat or with leg swelling — needs urgent care."),
        ("Anaphylaxis", "urgent", "Sudden breathing difficulty with rash, throat tightness — call 911, use epinephrine."),
    ]),
    ("cough", "adult", "acute", [
        ("Common Cold", "self", "Dry cough with runny nose, sore throat — supportive care."),
        ("Flu (Influenza)", "self", "Fever, body aches, cough — consider antiviral if within 48 hours."),
        ("Pneumonia", "routine", "Productive cough with fever — same-day evaluation."),
        ("Asthma", "routine", "Cough with wheezing or shortness of breath."),
        ("COVID-19", "routine", "Cough with fever — test for SARS-CoV-2."),
    ]),
    ("cough", "adult", "chronic", [
        ("Chronic Obstructive Pulmonary Disease", "routine", "Chronic productive cough in a smoker — needs spirometry."),
        ("Acid Reflux", "routine", "Chronic dry cough, worse at night, may suggest GERD."),
        ("Asthma", "routine", "Chronic intermittent cough may be cough-variant asthma."),
        ("Lung Cancer", "routine", "New persistent cough in a smoker warrants chest imaging."),
    ]),
    ("abdominal-pain", "adult", "acute", [
        ("Appendicitis", "urgent", "Right lower abdominal pain with nausea, fever — surgical emergency."),
        ("Gallstones", "routine", "Right upper abdominal pain after fatty meals."),
        ("Pancreatitis", "urgent", "Severe upper abdominal pain radiating to back."),
        ("Diverticulitis", "routine", "Left lower abdominal pain, fever, change in bowel habits."),
        ("Gastroenteritis", "self", "Cramping pain with diarrhea and vomiting — hydration, rest."),
        ("Kidney Stones", "urgent", "Flank pain radiating to groin, often with blood in urine."),
    ]),
    ("abdominal-pain", "adult", "chronic", [
        ("Irritable Bowel Syndrome", "routine", "Recurrent cramping pain with bowel habit change."),
        ("Crohn's Disease", "routine", "Chronic abdominal pain with weight loss, diarrhea."),
        ("Ulcerative Colitis", "routine", "Chronic crampy pain with bloody diarrhea."),
        ("Peptic Ulcer", "routine", "Burning upper abdominal pain, relieved by food or worsened by it."),
    ]),
    ("nausea-vomiting", "adult", "acute", [
        ("Gastroenteritis", "self", "Sudden nausea and vomiting after exposure to ill contacts or contaminated food."),
        ("Food Poisoning", "self", "Vomiting within hours of suspect meal."),
        ("Migraine", "self", "Vomiting accompanying severe headache."),
        ("Cholecystitis", "routine", "Vomiting with right upper abdominal pain after fatty meal."),
        ("Pregnancy", "routine", "Morning sickness in early pregnancy — pregnancy test if applicable."),
    ]),
    ("diarrhea", "adult", "acute", [
        ("Gastroenteritis", "self", "Watery diarrhea, often with nausea, after exposure."),
        ("Food Poisoning", "self", "Sudden diarrhea within hours of suspect meal."),
        ("Inflammatory Bowel Disease", "routine", "New diarrhea with blood, weight loss, abdominal pain."),
        ("Irritable Bowel Syndrome", "routine", "Chronic intermittent diarrhea without alarm features."),
    ]),
    ("blood-in-stool", "adult", "any", [
        ("Hemorrhoids", "routine", "Bright red blood on tissue with bowel movements."),
        ("Anal Fissure", "routine", "Bleeding with painful bowel movements."),
        ("Colon Cancer", "urgent", "New unexplained blood in stool warrants colonoscopy."),
        ("Diverticulitis", "routine", "Blood with abdominal pain and fever."),
        ("Ulcerative Colitis", "routine", "Bloody diarrhea with cramping."),
    ]),
    ("low-back-pain", "adult", "any", [
        ("Low Back Pain", "self", "Mechanical low back pain after activity — heat, NSAIDs, gentle activity."),
        ("Sciatica", "routine", "Back pain radiating down the leg — physical therapy and pain relief."),
        ("Herniated Disk", "routine", "Persistent radicular pain with numbness or weakness — needs imaging."),
        ("Kidney Stones", "urgent", "Flank pain radiating to groin with blood in urine."),
        ("Ankylosing Spondylitis", "routine", "Chronic back pain with morning stiffness in young adult."),
    ]),
    ("knee-pain", "adult", "any", [
        ("Osteoarthritis", "routine", "Activity-related joint pain in older adults."),
        ("ACL Injury", "routine", "Knee pain with instability after twisting injury."),
        ("Bursitis", "self", "Localized swelling and tenderness over knee."),
        ("Gout", "urgent", "Sudden severe joint pain with redness and warmth."),
    ]),
    ("shoulder-pain", "adult", "any", [
        ("Tendinitis", "self", "Activity-related shoulder pain with overhead use."),
        ("Bursitis", "self", "Localized shoulder pain with tenderness."),
        ("Heart Attack", "urgent", "Left shoulder or jaw pain with exertion can signal cardiac event."),
    ]),
    ("urinary-problems", "adult", "any", [
        ("Urinary Tract Infection", "routine", "Burning with urination, frequency, urgency — needs urinalysis."),
        ("Benign Prostatic Hyperplasia", "routine", "Slow stream, frequency, nocturia in older men."),
        ("Kidney Stones", "urgent", "Flank pain with hematuria."),
        ("Bladder Cancer", "routine", "Painless visible blood in urine warrants cystoscopy."),
    ]),
    ("pelvic-pain-female", "adult", "any", [
        ("Endometriosis", "routine", "Cyclic pelvic pain with painful periods."),
        ("Uterine Fibroids", "routine", "Pelvic pressure with heavy menstrual bleeding."),
        ("Ovarian Cancer", "routine", "Persistent bloating, pelvic pain, urinary symptoms — needs evaluation."),
        ("Urinary Tract Infection", "routine", "Pelvic discomfort with urinary symptoms."),
        ("Ectopic Pregnancy", "urgent", "Pelvic pain with positive pregnancy test — emergency."),
    ]),
    ("pelvic-pain-male", "adult", "any", [
        ("Benign Prostatic Hyperplasia", "routine", "Pelvic pressure with urinary symptoms in older men."),
        ("Prostate Cancer", "routine", "Pelvic or back pain with urinary symptoms warrants evaluation."),
        ("Kidney Stones", "urgent", "Flank pain with hematuria."),
        ("Testicular Cancer", "routine", "Scrotal mass with possible referred pelvic pain."),
    ]),
    ("skin-rash", "adult", "acute", [
        ("Atopic Dermatitis", "self", "Itchy red patches in flexural areas."),
        ("Cellulitis", "urgent", "Spreading red warm tender skin — needs antibiotics."),
        ("Shingles", "routine", "Painful unilateral blistering rash following nerve distribution."),
        ("Allergies", "self", "Itchy hives after exposure — antihistamines."),
        ("Anaphylaxis", "urgent", "Rash with breathing difficulty or throat tightness — call 911."),
    ]),
    ("fever", "adult", "acute", [
        ("Flu (Influenza)", "self", "Fever with body aches, fatigue."),
        ("Pneumonia", "routine", "Fever with productive cough — needs evaluation."),
        ("Urinary Tract Infection", "routine", "Fever with urinary symptoms."),
        ("Sepsis", "urgent", "Fever with confusion, low blood pressure, fast breathing — emergency."),
        ("Meningitis", "urgent", "Fever with severe headache and neck stiffness — emergency."),
    ]),
    ("fatigue", "adult", "chronic", [
        ("Hypothyroidism", "routine", "Fatigue with weight gain, cold intolerance — check thyroid."),
        ("Anemia", "routine", "Fatigue with pallor and shortness of breath — check CBC."),
        ("Depression", "routine", "Fatigue with mood symptoms — mental health support."),
        ("Sleep Apnea", "routine", "Daytime fatigue with snoring and witnessed apneas."),
        ("Chronic Fatigue Syndrome", "routine", "Disabling fatigue >6 months, post-exertional malaise."),
    ]),
    ("weight-loss", "adult", "chronic", [
        ("Hyperthyroidism", "routine", "Weight loss with heat intolerance, tremor, palpitations."),
        ("Diabetes Type 1", "urgent", "Weight loss with thirst, urination, fatigue — check glucose."),
        ("Cancer", "routine", "Unexplained progressive weight loss warrants evaluation."),
        ("Inflammatory Bowel Disease", "routine", "Weight loss with chronic diarrhea, abdominal pain."),
        ("HIV/AIDS", "routine", "Weight loss with risk factors for HIV — testing indicated."),
    ]),
    ("numbness-tingling-hands", "adult", "any", [
        ("Carpal Tunnel Syndrome", "routine", "Numbness in median nerve distribution, worse at night."),
        ("Diabetic Neuropathy", "routine", "Symmetric distal numbness in patients with diabetes."),
        ("Multiple Sclerosis", "routine", "Patchy neurologic symptoms in young adults."),
        ("Stroke", "urgent", "Sudden unilateral numbness with weakness — call 911."),
    ]),
    ("nasal-congestion", "adult", "acute", [
        ("Common Cold", "self", "Congestion with runny nose, mild fatigue."),
        ("Acute Sinusitis", "routine", "Congestion with facial pain >10 days."),
        ("Allergic Rhinitis", "self", "Congestion with itchy eyes, clear runny nose."),
        ("Nasal Polyps", "routine", "Chronic congestion with loss of smell."),
    ]),
    ("sore-throat", "adult", "acute", [
        ("Common Cold", "self", "Sore throat with congestion."),
        ("Tonsillitis", "routine", "Severe sore throat with white spots — strep test."),
        ("Acid Reflux", "self", "Chronic morning sore throat may indicate GERD."),
    ]),
    ("heart-palpitations", "adult", "any", [
        ("Atrial Fibrillation", "urgent", "Irregular palpitations — ECG recommended."),
        ("Anxiety Disorders", "self", "Palpitations with anxiety symptoms."),
        ("Hyperthyroidism", "routine", "Palpitations with weight loss, tremor."),
        ("Mitral Valve Prolapse", "routine", "Palpitations with click-murmur on exam."),
    ]),
    ("dizziness", "adult", "any", [
        ("Vertigo", "routine", "Sensation of spinning, often inner ear cause."),
        ("Stroke", "urgent", "Sudden dizziness with neurologic deficits — call 911."),
        ("Anemia", "routine", "Dizziness with fatigue and pallor."),
        ("Dehydration", "self", "Dizziness with thirst, after exercise or illness."),
        ("Hypertension", "routine", "Dizziness with high blood pressure."),
    ]),
    ("hip-pain", "adult", "any", [
        ("Osteoarthritis", "routine", "Activity-related hip pain in older adults."),
        ("Bursitis", "self", "Lateral hip pain with tenderness."),
        ("Hip Replacement", "routine", "Discuss surgical options for severe arthritis."),
    ]),
    ("constipation", "adult", "any", [
        ("Constipation", "self", "Increase fiber, fluids, activity."),
        ("Irritable Bowel Syndrome", "routine", "Alternating constipation and diarrhea."),
        ("Hypothyroidism", "routine", "Constipation with fatigue, cold intolerance."),
        ("Colon Cancer", "routine", "New constipation with weight loss or blood — needs colonoscopy."),
    ]),
    ("foot-pain", "adult", "any", [
        ("Plantar Fasciitis", "self", "Heel pain worst with first steps in morning."),
        ("Gout", "urgent", "Sudden severe toe joint pain."),
        ("Bursitis", "self", "Localized foot pain with tenderness."),
        ("Tendinitis", "self", "Activity-related foot pain."),
    ]),
    ("foot-swelling", "adult", "any", [
        ("Congestive Heart Failure", "urgent", "Bilateral leg swelling with shortness of breath."),
        ("Deep Vein Thrombosis", "urgent", "Unilateral leg swelling with calf pain — needs ultrasound."),
        ("Chronic Kidney Disease", "routine", "Bilateral leg swelling with elevated creatinine."),
        ("Cirrhosis", "routine", "Leg swelling with abdominal distension."),
    ]),
    ("ear-pain", "adult", "any", [
        ("Acute Sinusitis", "routine", "Ear fullness and pressure with sinus symptoms."),
        ("Tonsillitis", "routine", "Referred ear pain with sore throat."),
        ("Earwax Blockage", "self", "Ear fullness, mild discomfort."),
    ]),
    ("neck-pain", "adult", "any", [
        ("Cervical Spondylosis", "routine", "Chronic neck pain in older adults."),
        ("Herniated Disk", "routine", "Neck pain radiating to arm with numbness."),
        ("Meningitis", "urgent", "Neck pain with fever and headache — emergency."),
    ]),
    ("upper-back-pain", "adult", "any", [
        ("Tension Headache", "self", "Upper back tension from posture, stress."),
        ("Heart Attack", "urgent", "Upper back pain between shoulder blades with chest pain or exertion."),
        ("Aortic Aneurysm", "urgent", "Tearing upper back or chest pain — emergency."),
    ]),
]
