"""Mayo Clinic mirror — healthy lifestyle articles, news, patient stories."""

# Healthy lifestyle: 60 articles across categories
# (slug, title, category, summary, body_para_count)
HEALTHY_LIFESTYLE = [
    ("mediterranean-diet-overview", "Mediterranean Diet: A Heart-Healthy Eating Plan", "Nutrition", "The Mediterranean diet emphasizes fruits, vegetables, whole grains, beans, nuts, legumes, olive oil, and herbs and spices."),
    ("dash-diet", "DASH Diet: Healthy Eating to Lower Blood Pressure", "Nutrition", "The Dietary Approaches to Stop Hypertension diet is a flexible balanced eating plan that helps create a heart-healthy eating style for life."),
    ("portion-control", "Portion Control: Why Smaller Plates Can Help", "Nutrition", "Portion control is a useful strategy for weight loss and balanced nutrition."),
    ("food-labels", "How to Read Food Labels", "Nutrition", "Understanding food labels can help you make healthier choices and avoid hidden sugars and excess sodium."),
    ("plant-based-protein", "Plant-Based Protein Sources for a Balanced Diet", "Nutrition", "Plant-based proteins from beans, lentils, tofu, and nuts can replace some animal protein in a healthy diet."),
    ("hydration", "How Much Water Should You Drink Each Day?", "Nutrition", "Adequate hydration supports many vital body functions, but recommended fluid intake varies by age, activity, and climate."),
    ("calcium-vitamin-d", "Calcium and Vitamin D: Important for Bone Health", "Nutrition", "Getting enough calcium and vitamin D throughout life helps build strong bones and reduces osteoporosis risk."),
    ("low-sodium-diet", "Low-Sodium Diet for Heart Health", "Nutrition", "Reducing sodium intake can lower blood pressure and reduce the risk of cardiovascular disease."),
    ("fiber-foods", "High-Fiber Foods: Why They Matter", "Nutrition", "Dietary fiber supports digestive health, helps maintain a healthy weight, and lowers risk of diabetes and heart disease."),
    ("intermittent-fasting", "Intermittent Fasting: Pros and Cons", "Nutrition", "Intermittent fasting may benefit weight loss and metabolic health for some people, but it is not appropriate for everyone."),
    ("walking-30-min", "Walking for Fitness: A 30-Minute-a-Day Guide", "Fitness", "Walking briskly for 30 minutes a day improves cardiovascular health, mood, and overall fitness."),
    ("strength-training", "Strength Training: Why and How to Get Started", "Fitness", "Resistance training preserves muscle mass and bone density and supports healthy metabolism with age."),
    ("running-beginner", "Beginner's Guide to Running", "Fitness", "A gradual approach to running reduces injury risk and helps new runners build sustainable habits."),
    ("yoga-back-pain", "Yoga Poses for Low Back Pain", "Fitness", "Specific yoga poses can ease low back tension and improve mobility for many people with back pain."),
    ("hiit-workouts", "High-Intensity Interval Training: What It Is", "Fitness", "HIIT alternates short intense bursts of exercise with recovery periods for efficient cardiovascular conditioning."),
    ("stretching-routine", "Daily Stretching Routine for Office Workers", "Fitness", "Short stretching breaks help counter the effects of prolonged sitting and reduce musculoskeletal complaints."),
    ("aquatic-exercise", "Aquatic Exercise: Low-Impact Fitness", "Fitness", "Water exercise provides resistance and cardiovascular benefits with minimal joint impact."),
    ("home-workout", "Effective Home Workout Without Equipment", "Fitness", "Body-weight exercises can deliver an effective workout without a gym or equipment."),
    ("exercise-after-50", "Exercise After 50: What to Focus On", "Fitness", "Adults over 50 benefit from a balanced exercise program emphasizing aerobic activity, strength, and balance."),
    ("steps-per-day", "How Many Steps Per Day Are Enough?", "Fitness", "Step count goals can be motivating, but the right number depends on age, fitness level, and goals."),
    ("stress-management", "Healthy Ways to Cope With Stress", "Stress", "Building healthy coping strategies can help you manage the emotional and physical effects of chronic stress."),
    ("meditation-beginners", "Meditation for Beginners: How to Start", "Stress", "Daily meditation practice can reduce stress, improve focus, and support emotional regulation."),
    ("breathing-exercises", "Breathing Exercises to Calm Anxiety", "Stress", "Slow diaphragmatic breathing activates the parasympathetic response and can help manage acute anxiety."),
    ("sleep-hygiene", "Sleep Hygiene: 10 Habits for Better Rest", "Stress", "Consistent sleep habits, screen limits, and a quiet sleep environment support restorative rest."),
    ("mindfulness-pain", "Mindfulness for Chronic Pain Management", "Stress", "Mindfulness-based practices can reduce pain interference and improve quality of life for people with chronic pain."),
    ("digital-detox", "Digital Detox: A Practical Plan", "Stress", "Periodic breaks from screens can support mental health, sleep, and connection with others."),
    ("burnout-recovery", "Burnout Recovery: Steps to Take", "Stress", "Recovery from occupational burnout typically requires structural changes, social support, and rest."),
    ("gratitude-practice", "Building a Gratitude Practice", "Stress", "Regular gratitude practices can improve mood and resilience."),
    ("nature-walking", "Walking in Nature: Benefits for Mental Health", "Stress", "Time outdoors has measurable benefits for mood, sleep, and cardiovascular health."),
    ("therapy-options", "When to See a Therapist", "Stress", "Professional mental health support can help with persistent emotional concerns, life transitions, or trauma."),
    ("annual-checkup", "What to Expect at Your Annual Physical", "Adult Health", "A yearly checkup covers vital signs, preventive screening, and discussion of personal health goals."),
    ("blood-pressure-home", "Measuring Blood Pressure at Home", "Adult Health", "Home blood pressure monitoring with a validated device complements office readings."),
    ("cholesterol-test", "Cholesterol Testing: What the Numbers Mean", "Adult Health", "A lipid panel measures total cholesterol, LDL, HDL, and triglycerides to estimate cardiovascular risk."),
    ("cancer-screening", "Cancer Screening Guide for Adults", "Adult Health", "Recommended screenings vary by age, sex, and risk factors and include colon, breast, cervical, lung, and prostate cancer."),
    ("immunizations-adults", "Recommended Immunizations for Adults", "Adult Health", "Adults need updates to several vaccines, including tetanus, influenza, shingles, and pneumonia."),
    ("smoking-cessation", "Quitting Smoking: Evidence-Based Strategies", "Adult Health", "Combining counseling and pharmacotherapy substantially increases the chance of successfully quitting."),
    ("alcohol-moderation", "Alcohol Use: Defining 'Moderate' Drinking", "Adult Health", "Moderate alcohol consumption is defined as up to one drink per day for women and two for men."),
    ("dental-oral-health", "Oral Health and Whole-Body Health", "Adult Health", "Oral hygiene impacts cardiovascular health, diabetes management, and pregnancy outcomes."),
    ("eye-exam", "Why Adults Need Regular Eye Exams", "Adult Health", "Regular eye exams detect glaucoma, macular degeneration, and diabetic retinopathy early."),
    ("hearing-screening", "Hearing Loss: When to Get Checked", "Adult Health", "Untreated hearing loss affects cognition and quality of life; screening is recommended for older adults."),
    ("pregnancy-nutrition", "Nutrition During Pregnancy", "Pregnancy", "Healthy eating during pregnancy supports fetal development and maternal health."),
    ("prenatal-vitamins-importance", "Why Prenatal Vitamins Matter", "Pregnancy", "Folic acid, iron, and other nutrients in prenatal vitamins support pregnancy outcomes."),
    ("exercise-pregnancy", "Safe Exercise During Pregnancy", "Pregnancy", "Most healthy pregnant people benefit from regular moderate exercise."),
    ("postpartum-recovery", "Postpartum Recovery: What to Expect", "Pregnancy", "Recovery after childbirth involves both physical and emotional changes over weeks to months."),
    ("breastfeeding-basics", "Breastfeeding Basics for New Parents", "Pregnancy", "Breastfeeding offers nutritional, immune, and bonding benefits for both parent and baby."),
    ("infant-sleep", "Safe Infant Sleep Practices", "Children", "Following safe sleep guidelines reduces the risk of sudden infant death syndrome."),
    ("childhood-vaccines", "Childhood Vaccine Schedule", "Children", "Following recommended childhood vaccines protects against many serious infectious diseases."),
    ("teen-mental-health", "Supporting Teen Mental Health", "Children", "Open communication, sleep, and connection are protective for adolescent mental health."),
    ("screen-time-kids", "Setting Healthy Screen Time Limits for Kids", "Children", "Balanced screen time supports children's social, emotional, and academic development."),
    ("childhood-obesity", "Preventing Childhood Obesity", "Children", "Family meals, physical activity, and limited sweetened beverages help prevent obesity in children."),
    ("menopause-changes", "Menopause: Understanding the Changes", "Women's Health", "Menopause brings hormonal changes that affect bones, heart, mood, and many other systems."),
    ("breast-self-exam", "Breast Self-Exam: What to Look For", "Women's Health", "Breast self-awareness helps identify changes that should be evaluated."),
    ("contraception-options", "Contraception Options: Choosing What's Right", "Women's Health", "Many effective contraception options exist, including long-acting reversible methods."),
    ("osteoporosis-prevention", "Preventing Osteoporosis", "Women's Health", "Weight-bearing exercise, calcium, and vitamin D support lifelong bone health."),
    ("mens-health-checkup", "Men's Health Checkup: What's Recommended", "Men's Health", "Men benefit from regular preventive care including cardiovascular and cancer screening."),
    ("prostate-screening", "Prostate Cancer Screening: The Conversation", "Men's Health", "Decisions about PSA screening should be individualized."),
    ("erectile-health", "Erectile Dysfunction: When to Seek Care", "Men's Health", "Erectile dysfunction can signal underlying cardiovascular or other health issues."),
    ("healthy-aging", "Healthy Aging: The Pillars", "Healthy Aging", "Physical activity, nutrition, social connection, and cognitive engagement support healthy aging."),
    ("brain-health", "Brain Health: Habits That Help", "Healthy Aging", "Cardiovascular health, sleep, and mental stimulation support cognitive health with age."),
    ("preventing-falls", "Preventing Falls in Older Adults", "Healthy Aging", "Strength, balance training, home safety, and medication review reduce fall risk."),
    ("medication-management", "Medication Management for Older Adults", "Healthy Aging", "Regular medication reviews can reduce polypharmacy and drug interactions."),
]

NEWS_ARTICLES = [
    ("mayo-tops-newsweek-2026", "Mayo Clinic Tops Newsweek World's Best Hospitals Ranking for Eighth Consecutive Year", "January 15, 2026", "Mayo Clinic again leads the global hospital rankings."),
    ("car-t-mantle-cell", "Mayo Clinic Researchers Report Long-Term Outcomes With CAR-T in Mantle Cell Lymphoma", "February 3, 2026", "Long-term remission rates highlight durable benefit of CAR-T therapy."),
    ("ai-cardiology", "AI-Enabled ECG Identifies Heart Failure Years Before Diagnosis", "February 18, 2026", "A new Mayo Clinic study shows artificial intelligence applied to ECG can predict heart failure risk."),
    ("transplant-program", "Mayo Clinic Surpasses 1,800 Annual Solid Organ Transplants", "March 5, 2026", "The integrated transplant program continues to set national records."),
    ("alzheimer-prevention", "Lecanemab Shows Promise in Preclinical Alzheimer's Trial", "March 22, 2026", "Anti-amyloid therapy appears to slow disease progression in patients with preclinical Alzheimer's."),
    ("rural-telehealth", "Mayo Clinic Expands Rural Telehealth Cardiology Program", "April 10, 2026", "Remote rural patients now have access to subspecialty cardiology consults."),
    ("proton-beam", "Mayo Clinic Proton Beam Therapy Treats 10,000th Patient", "April 25, 2026", "The proton beam therapy program reaches a major patient milestone."),
    ("women-cardiac-care", "Sex Differences in Cardiac Care Improve With New Mayo Initiative", "May 8, 2026", "A new program addresses disparities in women's cardiovascular care."),
    ("ai-pathology", "Mayo Clinic AI Pathology Tool Identifies Rare Cancers Faster", "May 21, 2026", "A new AI model assists pathologists in rare cancer diagnosis."),
    ("cf-modulator", "Next-Generation CFTR Modulator Reaches Phase 3 at Mayo Clinic", "June 4, 2026", "Mayo Clinic enrolls patients in a Phase 3 trial of a new CFTR modulator therapy."),
    ("microbiome-cancer", "Gut Microbiome Predicts Response to Cancer Immunotherapy", "June 18, 2026", "Mayo Clinic researchers identify microbiome signatures associated with checkpoint inhibitor response."),
    ("youth-mental-health", "Mayo Clinic Launches New Youth Mental Health Outreach Program", "July 2, 2026", "The new program targets adolescent mental health in underserved communities."),
    ("robot-surgery-pancreas", "Robotic Whipple Procedure Reduces Recovery Time", "July 16, 2026", "Robotic-assisted pancreatic surgery shows promising outcomes at Mayo Clinic."),
    ("genomics-individual", "Mayo Clinic Genomics Program Personalizes Cancer Treatment", "July 30, 2026", "Whole-genome sequencing guides treatment for advanced cancers."),
    ("vagal-stim-depression", "Vagal Nerve Stimulation Brings Hope for Treatment-Resistant Depression", "August 13, 2026", "VNS shows sustained benefit for patients with severe depression."),
    ("liver-living-donor", "Living-Donor Liver Transplant Program Expands", "August 27, 2026", "The program now serves more pediatric and adult patients."),
    ("women-stroke", "New Findings on Stroke Risk Factors Unique to Women", "September 10, 2026", "Pregnancy-related conditions emerge as important stroke risk factors."),
    ("kidney-stones-diet", "Dietary Approach Reduces Recurrent Kidney Stones", "September 24, 2026", "A new study finds dietary intervention significantly reduces stone recurrence."),
    ("diabetes-tech", "Continuous Glucose Monitoring Improves Outcomes in Type 2 Diabetes", "October 8, 2026", "CGM technology benefits a broader range of patients with diabetes."),
    ("integrative-cancer", "Mayo Clinic Integrative Cancer Center Opens New Wing", "October 22, 2026", "The new wing focuses on whole-person cancer care."),
]

PATIENT_STORIES = [
    ("kevin-pancreas-cancer", "Kevin's Story: Beating Pancreatic Cancer With Multidisciplinary Care", "Pancreatic Cancer",
     "When Kevin received a pancreatic cancer diagnosis at 52, he traveled to Mayo Clinic for a second opinion. A multidisciplinary team of surgeons, oncologists, and radiation oncologists developed an integrated treatment plan including neoadjuvant chemotherapy followed by a Whipple procedure and adjuvant therapy. Three years later, Kevin is back to running marathons and supporting other patients on the same journey."),
    ("maria-heart-transplant", "Maria's Story: Heart Transplant at 28", "Heart Transplant",
     "Maria was diagnosed with idiopathic dilated cardiomyopathy at age 26. After her condition progressed despite optimal medical therapy, she received a heart transplant at Mayo Clinic in Rochester. Two years post-transplant, she has returned to teaching and completed a half-marathon."),
    ("james-epilepsy", "James's Story: Seizure-Free After Awake Brain Surgery", "Epilepsy",
     "James lived with drug-resistant temporal lobe epilepsy for 18 years before being evaluated at Mayo Clinic's Epilepsy Center. After detailed mapping confirmed the seizure focus, he underwent awake brain surgery and has been seizure-free for over four years."),
    ("priya-breast-cancer", "Priya's Story: Genetic Testing Saved My Life", "Breast Cancer",
     "Following her mother's breast cancer diagnosis, Priya pursued genetic testing at Mayo Clinic, which revealed a BRCA1 mutation. She elected risk-reducing surgery and continues with surveillance, sharing her story with families considering hereditary cancer testing."),
    ("david-parkinsons", "David's Story: Deep Brain Stimulation for Parkinson's", "Parkinson's Disease",
     "After his Parkinson's symptoms progressed despite optimized medication, David underwent deep brain stimulation at Mayo Clinic. Within weeks, his tremor and mobility improved dramatically and he has returned to his woodworking hobby."),
    ("emma-lupus", "Emma's Story: Living Well With Lupus", "Lupus",
     "Diagnosed with systemic lupus erythematosus at 19, Emma worked with the Mayo Clinic rheumatology team to find a medication regimen that controlled her disease. She graduated from law school and continues to advocate for autoimmune patients."),
    ("samuel-stroke", "Samuel's Story: Recovery After Mechanical Thrombectomy", "Stroke",
     "When Samuel had a large vessel stroke, the Mayo Clinic stroke team performed mechanical thrombectomy within 90 minutes of arrival. He returned home with minimal residual deficits and continues outpatient rehabilitation."),
    ("aiko-cystic-fibrosis", "Aiko's Story: A New Chapter With CFTR Modulator Therapy", "Cystic Fibrosis",
     "Aiko grew up managing daily airway clearance and frequent hospitalizations for cystic fibrosis. After starting modulator therapy at Mayo Clinic, her lung function improved substantially and she now works as a pediatric nurse."),
    ("luis-prostate-cancer", "Luis's Story: Proton Beam Therapy for Prostate Cancer", "Prostate Cancer",
     "Luis chose proton beam therapy at Mayo Clinic for his localized prostate cancer because of the precise dose delivery. Two years out from treatment, he remains cancer-free with preserved urinary and sexual function."),
    ("hannah-ms", "Hannah's Story: Stability With Multiple Sclerosis Treatment", "Multiple Sclerosis",
     "Hannah was diagnosed with relapsing multiple sclerosis in college. With ocrelizumab infusions and lifestyle changes, she has remained relapse-free for five years and recently completed a graduate program."),
    ("malcolm-liver-transplant", "Malcolm's Story: Living-Donor Liver Transplant", "Liver Transplant",
     "When Malcolm's hepatitis C-related cirrhosis worsened, his daughter became his living donor. The Mayo Clinic transplant team performed the surgery in Rochester. Both Malcolm and his daughter recovered well."),
    ("rebecca-bariatric", "Rebecca's Story: 10 Years After Gastric Bypass", "Bariatric Surgery",
     "Rebecca had Roux-en-Y gastric bypass at Mayo Clinic ten years ago. She has maintained her weight loss, resolved her diabetes and sleep apnea, and now mentors prospective bariatric patients."),
]
