"""Mayo Clinic mirror — tests & procedures catalog (170 entries)."""

# (slug, name, dept_slug, category, summary)
# category in {test, procedure, surgery, imaging, therapy}
PROCEDURES = [
    ("acl-reconstruction", "ACL Reconstruction", "orthopedics", "surgery", "ACL reconstruction is surgery to replace a torn anterior cruciate ligament with a tendon graft, restoring knee stability for athletic activity."),
    ("acth-stimulation-test", "ACTH Stimulation Test", "endocrinology", "test", "The ACTH stimulation test measures how the adrenal glands respond to adrenocorticotropic hormone, used to diagnose adrenal insufficiency."),
    ("adrenalectomy", "Adrenalectomy", "general-surgery", "surgery", "Adrenalectomy is the surgical removal of one or both adrenal glands, often performed for tumors or hormonal disorders."),
    ("allergy-skin-testing", "Allergy Skin Testing", "internal-medicine", "test", "Allergy skin testing applies small amounts of allergens to the skin to identify substances that trigger allergic reactions."),
    ("ana-test", "Antinuclear Antibody Test", "rheumatology", "test", "The antinuclear antibody test is a blood test used to help diagnose autoimmune disorders, including lupus."),
    ("anca-test", "ANCA Test", "rheumatology", "test", "The ANCA test detects antineutrophil cytoplasmic antibodies in the blood, used in diagnosing certain types of vasculitis."),
    ("aneurysm-clipping", "Aneurysm Clipping", "neurosurgery", "surgery", "Aneurysm clipping is a neurosurgical procedure that places a metal clip across the neck of a brain aneurysm to stop blood flow."),
    ("ankle-brachial-index", "Ankle-Brachial Index Test", "cardiology", "test", "The ankle-brachial index test compares blood pressure measured at the ankle and the arm to screen for peripheral artery disease."),
    ("anoscopy", "Anoscopy", "gastroenterology", "test", "Anoscopy uses a short rigid tube to examine the anal canal for hemorrhoids, fissures, or other anal disease."),
    ("aortic-aneurysm-repair", "Aortic Aneurysm Repair", "cardiology", "surgery", "Aortic aneurysm repair is open or endovascular surgery to reinforce a weakened section of the aorta and prevent rupture."),
    ("appendectomy", "Appendectomy", "general-surgery", "surgery", "Appendectomy is the surgical removal of the appendix, most often performed for acute appendicitis."),
    ("artificial-tears", "Artificial Tears", "ophthalmology", "therapy", "Artificial tears are eye drops that supplement natural tear production to relieve dry eye symptoms."),
    ("asd-closure", "Atrial Septal Defect Closure", "cardiology", "surgery", "ASD closure is a catheter-based or surgical procedure that seals a hole between the heart's upper chambers."),
    ("audiogram", "Audiogram", "ent", "test", "An audiogram is a hearing test that measures the softest sounds a person can hear at different pitches across the audible range."),
    ("awake-brain-surgery", "Awake Brain Surgery", "neurosurgery", "surgery", "Awake brain surgery is performed while the patient is conscious, allowing real-time mapping of speech and motor areas during tumor resection."),
    ("barium-swallow", "Barium Swallow", "gastroenterology", "imaging", "A barium swallow is an X-ray test that examines the upper digestive tract using a chalky contrast liquid."),
    ("bcg-vaccine", "BCG Bladder Therapy", "urology", "therapy", "BCG bladder therapy uses a weakened tuberculosis bacterium delivered into the bladder to treat non-muscle-invasive bladder cancer."),
    ("biopsy", "Biopsy", "oncology", "test", "A biopsy removes a sample of tissue from the body for laboratory examination to diagnose disease."),
    ("blood-allergy-test", "Blood Allergy Test", "internal-medicine", "test", "Blood allergy testing measures the level of allergen-specific antibodies in the bloodstream."),
    ("blood-culture", "Blood Culture", "infectious-diseases", "test", "Blood cultures detect bacteria or fungi in the bloodstream, used to diagnose bacteremia and sepsis."),
    ("blood-pressure-monitoring", "Ambulatory Blood Pressure Monitoring", "cardiology", "test", "Ambulatory blood pressure monitoring uses a portable device to measure blood pressure over 24 hours during normal daily activity."),
    ("bnp-test", "BNP Test", "cardiology", "test", "BNP measures B-type natriuretic peptide in blood; elevated levels suggest heart failure."),
    ("bone-biopsy", "Bone Biopsy", "oncology", "test", "Bone biopsy removes a small piece of bone for microscopic examination."),
    ("bone-density-scan", "Bone Density Scan", "endocrinology", "imaging", "A bone density scan uses low-dose X-rays to measure bone mineral content and screen for osteoporosis."),
    ("bone-marrow-biopsy", "Bone Marrow Biopsy", "hematology", "test", "A bone marrow biopsy removes a sample of bone marrow tissue for examination, used to evaluate blood cell production and diagnose hematologic disease."),
    ("bone-marrow-transplant", "Bone Marrow Transplant", "hematology", "therapy", "Bone marrow transplant infuses healthy blood-forming stem cells to replace damaged or diseased marrow."),
    ("bone-scan", "Bone Scan", "radiology", "imaging", "A bone scan uses small amounts of radioactive material to look for areas of high bone turnover."),
    ("bowel-resection", "Bowel Resection", "general-surgery", "surgery", "Bowel resection removes a diseased portion of the small or large intestine and reconnects the healthy ends."),
    ("breast-biopsy", "Breast Biopsy", "oncology", "test", "Breast biopsy removes tissue from a suspicious breast area for pathology evaluation."),
    ("breast-ultrasound", "Breast Ultrasound", "radiology", "imaging", "Breast ultrasound uses sound waves to examine breast tissue, often paired with mammography."),
    ("bronchoscopy", "Bronchoscopy", "pulmonary", "test", "Bronchoscopy uses a thin lighted tube to look at the airways and lungs."),
    ("ca-125", "CA-125 Test", "oncology", "test", "The CA-125 blood test measures a tumor marker that may be elevated in ovarian cancer."),
    ("cabg", "Coronary Artery Bypass Grafting", "cardiology", "surgery", "CABG is heart surgery that creates a new route around a blocked or narrowed coronary artery."),
    ("calcium", "Calcium Supplements", "endocrinology", "therapy", "Calcium supplements help maintain bone strength when dietary calcium intake is inadequate."),
    ("cardiac-ablation", "Cardiac Ablation", "cardiology", "procedure", "Cardiac ablation uses heat or cold energy to scar small areas of heart tissue that cause abnormal heart rhythms."),
    ("cardiac-catheterization", "Cardiac Catheterization", "cardiology", "procedure", "Cardiac catheterization threads a thin tube through blood vessels to the heart to diagnose and treat heart conditions."),
    ("cardiac-mri", "Cardiac MRI", "radiology", "imaging", "Cardiac MRI uses magnetic fields to create detailed images of the heart's structure and function."),
    ("carotid-endarterectomy", "Carotid Endarterectomy", "cardiology", "surgery", "Carotid endarterectomy is surgery to remove plaque from the carotid arteries supplying the brain, reducing stroke risk."),
    ("carotid-ultrasound", "Carotid Ultrasound", "radiology", "imaging", "Carotid ultrasound uses sound waves to evaluate blood flow and identify narrowing in the neck arteries."),
    ("carpal-tunnel-release", "Carpal Tunnel Release Surgery", "orthopedics", "surgery", "Carpal tunnel release cuts the transverse carpal ligament to relieve median nerve compression at the wrist."),
    ("cataract-surgery", "Cataract Surgery", "ophthalmology", "surgery", "Cataract surgery removes the cloudy lens of the eye and replaces it with a clear artificial lens implant."),
    ("cbc", "Complete Blood Count", "hematology", "test", "Complete blood count is a blood test that evaluates red cells, white cells, and platelets."),
    ("ccp-antibody", "CCP Antibody Test", "rheumatology", "test", "The CCP antibody test detects anti-cyclic citrullinated peptide antibodies, used to diagnose rheumatoid arthritis."),
    ("ceruloplasmin-test", "Ceruloplasmin Test", "gastroenterology", "test", "The ceruloplasmin blood test helps diagnose Wilson's disease and other copper metabolism disorders."),
    ("cervical-fusion", "Cervical Spinal Fusion", "neurosurgery", "surgery", "Cervical spinal fusion is surgery that joins two or more neck vertebrae together permanently."),
    ("chemotherapy", "Chemotherapy", "oncology", "therapy", "Chemotherapy uses powerful drugs to kill rapidly growing cancer cells in the body."),
    ("chest-ct", "Chest CT Scan", "radiology", "imaging", "Chest CT uses X-rays to create detailed cross-sectional images of the lungs, heart, and chest structures."),
    ("chest-xray", "Chest X-ray", "radiology", "imaging", "A chest X-ray is a fast painless test that produces images of the structures inside the chest."),
    ("cholecystectomy", "Cholecystectomy", "general-surgery", "surgery", "Cholecystectomy is the surgical removal of the gallbladder, most often performed laparoscopically."),
    ("colectomy", "Colectomy", "general-surgery", "surgery", "Colectomy is the surgical removal of all or part of the colon."),
    ("colonoscopy", "Colonoscopy", "gastroenterology", "test", "Colonoscopy uses a flexible scope to examine the inside of the colon for polyps, cancer, or inflammation."),
    ("colposcopy", "Colposcopy", "obgyn", "test", "Colposcopy uses a lighted magnifying instrument to examine the cervix for abnormal cells."),
    ("coronary-ct-angiography", "Coronary CT Angiography", "radiology", "imaging", "Coronary CT angiography is a noninvasive imaging test that visualizes the heart's arteries to detect coronary disease."),
    ("cpap-therapy", "CPAP Therapy", "pulmonary", "therapy", "CPAP delivers continuous positive airway pressure through a mask to treat obstructive sleep apnea."),
    ("creatinine-test", "Creatinine Test", "nephrology", "test", "The creatinine blood test estimates kidney function based on the level of this waste product."),
    ("cryotherapy", "Cryotherapy", "dermatology", "procedure", "Cryotherapy uses extreme cold, usually liquid nitrogen, to destroy abnormal tissue such as warts or precancerous lesions."),
    ("ct-abdomen", "CT Abdomen", "radiology", "imaging", "CT abdomen provides detailed cross-sectional images of abdominal organs to diagnose disease and injury."),
    ("ct-adrenal", "CT Adrenal Glands", "radiology", "imaging", "CT of the adrenal glands provides detailed images to evaluate adrenal masses and tumors."),
    ("ct-angiography", "CT Angiography", "radiology", "imaging", "CT angiography uses contrast dye and CT to visualize blood vessels throughout the body."),
    ("ct-enterography", "CT Enterography", "radiology", "imaging", "CT enterography provides high-resolution images of the small intestine for inflammatory bowel disease evaluation."),
    ("ct-head", "CT Head", "radiology", "imaging", "CT of the head produces detailed images of the brain and skull to diagnose stroke, trauma, and tumors."),
    ("ct-pulmonary-angiogram", "CT Pulmonary Angiogram", "radiology", "imaging", "CT pulmonary angiography is the primary test for diagnosing pulmonary embolism."),
    ("ct-scan", "CT Scan", "radiology", "imaging", "CT scanning combines X-ray and computer technology to create cross-sectional images of the body."),
    ("ct-sinus", "CT Sinus", "radiology", "imaging", "CT of the sinuses provides detailed images of the paranasal sinus anatomy."),
    ("cystectomy", "Cystectomy", "urology", "surgery", "Cystectomy is the surgical removal of all or part of the bladder, most often to treat bladder cancer."),
    ("cystoscopy", "Cystoscopy", "urology", "test", "Cystoscopy uses a thin tube with a camera to look inside the bladder and urethra."),
    ("d-dimer", "D-Dimer Test", "hematology", "test", "The D-dimer blood test measures a substance released when a blood clot breaks down."),
    ("datscan", "DaTscan", "neurology", "imaging", "DaTscan is a nuclear medicine imaging study used to evaluate dopamine activity in the brain for Parkinson's disease."),
    ("deep-brain-stimulation", "Deep Brain Stimulation", "neurosurgery", "surgery", "Deep brain stimulation implants electrodes in specific brain regions to treat Parkinson's disease, tremor, and dystonia."),
    ("dermabrasion", "Dermabrasion", "dermatology", "procedure", "Dermabrasion is a skin-resurfacing procedure that uses a rotating instrument to remove the outer layers of skin."),
    ("dexamethasone-suppression-test", "Dexamethasone Suppression Test", "endocrinology", "test", "The dexamethasone suppression test helps diagnose Cushing syndrome by evaluating cortisol response."),
    ("dialysis", "Dialysis", "nephrology", "therapy", "Dialysis filters waste and excess fluid from the blood when the kidneys can no longer perform that function."),
    ("discectomy", "Discectomy", "neurosurgery", "surgery", "Discectomy is surgery to remove damaged portions of a herniated spinal disk."),
    ("doppler-ultrasound-penile", "Penile Doppler Ultrasound", "urology", "imaging", "Penile Doppler ultrasound evaluates blood flow in the penis to diagnose erectile dysfunction."),
    ("ecg", "Electrocardiogram (ECG)", "cardiology", "test", "An electrocardiogram records the electrical signals in the heart to detect heart conditions."),
    ("echocardiogram", "Echocardiogram", "cardiology", "imaging", "Echocardiogram uses sound waves to produce images of the heart, evaluating structure and function."),
    ("eeg", "Electroencephalogram (EEG)", "neurology", "test", "EEG records the electrical activity of the brain using sensors attached to the scalp."),
    ("emg", "Electromyography (EMG)", "neurology", "test", "EMG measures the electrical activity in muscles to diagnose neuromuscular disorders."),
    ("endometrial-biopsy", "Endometrial Biopsy", "obgyn", "test", "Endometrial biopsy removes tissue from the uterine lining to evaluate abnormal bleeding."),
    ("endoscopic-ultrasound", "Endoscopic Ultrasound", "gastroenterology", "imaging", "Endoscopic ultrasound combines endoscopy and ultrasound to evaluate the digestive tract and nearby organs."),
    ("epidural-injection", "Epidural Steroid Injection", "pain-medicine", "procedure", "An epidural steroid injection delivers anti-inflammatory medication into the space around the spinal nerves."),
    ("ercp", "ERCP", "gastroenterology", "procedure", "Endoscopic retrograde cholangiopancreatography combines endoscopy and X-ray to diagnose and treat conditions of the bile and pancreatic ducts."),
    ("esophageal-biopsy", "Esophageal Biopsy", "gastroenterology", "test", "Esophageal biopsy removes tissue from the esophagus during endoscopy to evaluate disease."),
    ("esophageal-manometry", "Esophageal Manometry", "gastroenterology", "test", "Esophageal manometry measures the muscle contractions and pressures of the esophagus during swallowing."),
    ("esophagectomy", "Esophagectomy", "general-surgery", "surgery", "Esophagectomy is the surgical removal of all or part of the esophagus, usually performed for cancer."),
    ("fibroscan", "FibroScan", "gastroenterology", "imaging", "FibroScan is a noninvasive ultrasound-based test that measures liver stiffness to assess fibrosis."),
    ("fine-needle-aspiration", "Fine Needle Aspiration", "oncology", "test", "Fine needle aspiration uses a thin needle to obtain a tissue sample from a mass or lesion."),
    ("fluorescein-angiography", "Fluorescein Angiography", "ophthalmology", "imaging", "Fluorescein angiography uses a fluorescent dye to evaluate blood flow in the retina."),
    ("fundus-photography", "Fundus Photography", "ophthalmology", "imaging", "Fundus photography captures detailed images of the back of the eye, including the retina and optic nerve."),
    ("gastrectomy", "Gastrectomy", "general-surgery", "surgery", "Gastrectomy is the surgical removal of all or part of the stomach, often performed for cancer."),
    ("genetic-testing", "Genetic Testing", "internal-medicine", "test", "Genetic testing analyzes DNA to identify variations associated with inherited disorders."),
    ("glucose-tolerance-test", "Glucose Tolerance Test", "endocrinology", "test", "The glucose tolerance test measures blood sugar response after consuming a sugary drink to diagnose diabetes."),
    ("h-pylori-test", "H. pylori Test", "gastroenterology", "test", "The H. pylori test detects the bacteria that cause peptic ulcers, using breath, stool, or biopsy samples."),
    ("hba1c", "Hemoglobin A1C Test", "endocrinology", "test", "Hemoglobin A1C measures average blood sugar over the past two to three months."),
    ("hbv-dna", "Hepatitis B Viral Load", "infectious-diseases", "test", "The hepatitis B viral load measures the amount of hepatitis B virus DNA in the blood."),
    ("hcv-rna", "Hepatitis C Viral Load", "infectious-diseases", "test", "The hepatitis C viral load test measures the amount of hepatitis C virus RNA in the bloodstream."),
    ("heart-transplant", "Heart Transplant", "transplant", "surgery", "Heart transplant replaces a diseased heart with a healthy donor heart for patients with end-stage heart failure."),
    ("hemoglobin-electrophoresis", "Hemoglobin Electrophoresis", "hematology", "test", "Hemoglobin electrophoresis separates and identifies abnormal hemoglobin types in the blood."),
    ("hemorrhoidectomy", "Hemorrhoidectomy", "general-surgery", "surgery", "Hemorrhoidectomy is the surgical removal of severe internal or external hemorrhoids."),
    ("hida-scan", "HIDA Scan", "radiology", "imaging", "A HIDA scan is a nuclear medicine imaging test that evaluates gallbladder function and bile flow."),
    ("hiv-rna", "HIV RNA Viral Load", "infectious-diseases", "test", "HIV viral load measures the amount of HIV genetic material in the blood, used to monitor antiretroviral therapy."),
    ("hla-b27", "HLA-B27 Test", "rheumatology", "test", "The HLA-B27 blood test detects a marker associated with ankylosing spondylitis and related conditions."),
    ("holter-monitor", "Holter Monitor", "cardiology", "test", "A Holter monitor is a portable device worn to record the heart's electrical activity over 24 to 48 hours."),
    ("hormone-panel", "Hormone Panel", "endocrinology", "test", "A hormone panel measures multiple hormone levels in the blood to evaluate endocrine function."),
    ("hip-replacement", "Hip Replacement", "orthopedics", "surgery", "Hip replacement removes damaged hip joint surfaces and replaces them with artificial components to relieve pain and restore function."),
    ("hysterectomy", "Hysterectomy", "obgyn", "surgery", "Hysterectomy is the surgical removal of the uterus, performed for various gynecologic conditions."),
    ("icd-placement", "Implantable Cardioverter-Defibrillator (ICD)", "cardiology", "procedure", "ICD placement implants a device that monitors heart rhythm and delivers shocks to treat dangerous arrhythmias."),
    ("insulin-pump", "Insulin Pump", "endocrinology", "therapy", "An insulin pump is a small wearable device that delivers continuous insulin to manage type 1 diabetes."),
    ("iron-panel", "Iron Studies", "hematology", "test", "Iron studies measure iron, ferritin, and related markers to evaluate iron deficiency or overload."),
    ("ivig", "IVIG Therapy", "neurology", "therapy", "Intravenous immunoglobulin therapy infuses pooled antibodies to treat various autoimmune and inflammatory conditions."),
    ("joint-aspiration", "Joint Aspiration", "rheumatology", "procedure", "Joint aspiration removes fluid from a swollen joint with a needle for diagnostic testing or symptomatic relief."),
    ("joint-injection", "Joint Injection", "rheumatology", "procedure", "Joint injection delivers corticosteroid or hyaluronic acid directly into a joint to reduce pain and inflammation."),
    ("kidney-biopsy", "Kidney Biopsy", "nephrology", "test", "Kidney biopsy removes a small piece of kidney tissue for microscopic evaluation."),
    ("knee-arthroscopy", "Knee Arthroscopy", "orthopedics", "surgery", "Knee arthroscopy uses a tiny camera and instruments to diagnose and repair knee problems through small incisions."),
    ("knee-replacement", "Knee Replacement", "orthopedics", "surgery", "Knee replacement removes damaged knee joint surfaces and replaces them with metal and plastic components."),
    ("lactose-tolerance-test", "Lactose Tolerance Test", "gastroenterology", "test", "The lactose tolerance test measures blood sugar response after consuming lactose to diagnose intolerance."),
    ("laparoscopy", "Laparoscopy", "general-surgery", "surgery", "Laparoscopy is a minimally invasive surgical technique using a camera and small instruments through tiny incisions."),
    ("laser-photocoagulation", "Laser Photocoagulation", "ophthalmology", "procedure", "Laser photocoagulation uses focused light to seal leaking blood vessels in the retina."),
    ("laser-resurfacing", "Laser Skin Resurfacing", "dermatology", "procedure", "Laser skin resurfacing uses focused laser light to treat wrinkles, scars, and skin discoloration."),
    ("limb-salvage-surgery", "Limb Salvage Surgery", "orthopedics", "surgery", "Limb salvage surgery removes bone tumors while preserving the limb using bone grafts or prostheses."),
    ("lipase-test", "Lipase Test", "gastroenterology", "test", "The lipase blood test measures an enzyme released by the pancreas, elevated in pancreatitis."),
    ("lithotripsy", "Lithotripsy", "urology", "procedure", "Lithotripsy uses shock waves to break kidney stones into smaller pieces that can pass naturally."),
    ("liver-biopsy", "Liver Biopsy", "gastroenterology", "test", "Liver biopsy removes a small piece of liver tissue for microscopic examination to diagnose liver disease."),
    ("liver-resection", "Liver Resection", "general-surgery", "surgery", "Liver resection is the surgical removal of part of the liver, performed to treat tumors and other liver diseases."),
    ("liver-transplant", "Liver Transplant", "transplant", "surgery", "Liver transplant replaces a diseased liver with a healthy liver from a donor."),
    ("lobectomy", "Lobectomy", "general-surgery", "surgery", "Lobectomy is the surgical removal of a lobe of an organ, most often a lobe of the lung for cancer treatment."),
    ("lumbar-puncture", "Lumbar Puncture", "neurology", "procedure", "Lumbar puncture removes a small amount of cerebrospinal fluid from the lower spine for laboratory analysis."),
    ("lumpectomy", "Lumpectomy", "general-surgery", "surgery", "Lumpectomy removes a breast tumor and a small margin of surrounding healthy tissue."),
    ("lung-transplant", "Lung Transplant", "transplant", "surgery", "Lung transplant replaces one or both diseased lungs with healthy donor lungs."),
    ("lyme-serology", "Lyme Disease Serology", "infectious-diseases", "test", "Lyme serology detects antibodies to Borrelia burgdorferi to diagnose Lyme disease."),
    ("lymph-node-biopsy", "Lymph Node Biopsy", "oncology", "test", "Lymph node biopsy removes lymph node tissue for evaluation, often used to diagnose lymphoma or stage cancer."),
    ("mammogram", "Mammogram", "radiology", "imaging", "A mammogram is a low-dose X-ray that examines the breasts for early signs of breast cancer."),
    ("mastectomy", "Mastectomy", "general-surgery", "surgery", "Mastectomy is the surgical removal of all breast tissue, performed to treat or prevent breast cancer."),
    ("mitral-valve-repair", "Mitral Valve Repair", "cardiology", "surgery", "Mitral valve repair preserves and reshapes the heart's mitral valve to restore proper function."),
    ("mohs-surgery", "Mohs Surgery", "dermatology", "surgery", "Mohs surgery progressively removes thin layers of skin cancer-containing skin and examines each layer."),
    ("mr-angiography", "MR Angiography", "radiology", "imaging", "MR angiography uses magnetic resonance imaging to visualize blood vessels without ionizing radiation."),
    ("mrcp", "MRCP", "radiology", "imaging", "Magnetic resonance cholangiopancreatography is a noninvasive MRI study of the bile ducts and pancreatic duct."),
    ("mri-bone", "MRI Bone", "radiology", "imaging", "MRI of the bone provides detailed images for evaluating tumors, infections, and other bone conditions."),
    ("mri-brain", "MRI Brain", "radiology", "imaging", "MRI of the brain provides detailed images for diagnosing strokes, tumors, multiple sclerosis, and other neurologic conditions."),
    ("mri-joint", "MRI Joint", "radiology", "imaging", "MRI of a joint produces detailed images of ligaments, tendons, cartilage, and other joint structures."),
    ("mri-pituitary", "MRI Pituitary", "radiology", "imaging", "MRI of the pituitary gland evaluates the small gland at the base of the brain for tumors and abnormalities."),
    ("mri-spine", "MRI Spine", "radiology", "imaging", "MRI of the spine produces detailed images of the spinal cord and surrounding structures."),
    ("muscle-biopsy", "Muscle Biopsy", "neurology", "test", "Muscle biopsy removes a small piece of muscle tissue to diagnose muscle and nerve disorders."),
    ("myomectomy", "Myomectomy", "obgyn", "surgery", "Myomectomy is the surgical removal of uterine fibroids while preserving the uterus."),
    ("nasal-endoscopy", "Nasal Endoscopy", "ent", "test", "Nasal endoscopy uses a thin flexible scope to examine the nasal passages and sinuses."),
    ("nephrectomy", "Nephrectomy", "urology", "surgery", "Nephrectomy is the surgical removal of all or part of a kidney."),
    ("nerve-conduction-study", "Nerve Conduction Study", "neurology", "test", "A nerve conduction study measures how fast electrical signals move through peripheral nerves."),
    ("neuropsychological-testing", "Neuropsychological Testing", "psychiatry", "test", "Neuropsychological testing evaluates cognitive, behavioral, and emotional function using standardized assessments."),
    ("nutrition-assessment", "Nutrition Assessment", "internal-medicine", "test", "Nutrition assessment evaluates dietary intake, nutritional status, and metabolic needs."),
    ("octreoscan", "OctreoScan", "radiology", "imaging", "OctreoScan is a nuclear medicine imaging test using radiolabeled octreotide to detect neuroendocrine tumors."),
    ("oct-eye", "Optical Coherence Tomography", "ophthalmology", "imaging", "OCT uses light waves to produce cross-sectional images of the retina."),
    ("oophorectomy", "Oophorectomy", "obgyn", "surgery", "Oophorectomy is the surgical removal of one or both ovaries."),
    ("orchiectomy", "Orchiectomy", "urology", "surgery", "Orchiectomy is the surgical removal of one or both testicles."),
    ("pap-smear", "Pap Smear", "obgyn", "test", "A Pap smear collects cells from the cervix to screen for cervical cancer and precancer."),
    ("paracentesis", "Paracentesis", "gastroenterology", "procedure", "Paracentesis removes fluid from the abdomen using a needle to relieve pressure or for diagnostic testing."),
    ("patch-testing", "Patch Testing", "dermatology", "test", "Patch testing applies small amounts of suspected allergens to the skin to identify causes of contact dermatitis."),
    ("pcr-test", "PCR Test", "infectious-diseases", "test", "Polymerase chain reaction testing detects specific genetic material from bacteria or viruses."),
    ("peak-flow-test", "Peak Flow Test", "pulmonary", "test", "The peak flow test measures how fast a person can blow air out of the lungs."),
    ("pelvic-examination", "Pelvic Examination", "obgyn", "test", "A pelvic examination evaluates the female reproductive organs as part of routine gynecologic care."),
    ("pelvic-floor-therapy", "Pelvic Floor Therapy", "obgyn", "therapy", "Pelvic floor physical therapy strengthens and coordinates the muscles supporting the bladder and uterus."),
    ("pelvic-ultrasound", "Pelvic Ultrasound", "obgyn", "imaging", "Pelvic ultrasound uses sound waves to evaluate the uterus, ovaries, and pelvic structures."),
    ("pet-scan", "PET Scan", "radiology", "imaging", "PET scan uses radioactive tracer to highlight metabolic activity, often used in cancer staging."),
    ("ph-monitoring", "Esophageal pH Monitoring", "gastroenterology", "test", "Esophageal pH monitoring records acid exposure in the esophagus over 24 hours to evaluate reflux disease."),
    ("physical-therapy", "Physical Therapy", "rehabilitation", "therapy", "Physical therapy uses exercise, manual techniques, and modalities to improve movement and reduce pain."),
    ("plasma-exchange", "Plasma Exchange", "neurology", "therapy", "Plasma exchange removes plasma from the blood and replaces it with donor plasma or substitute fluid."),
    ("polypectomy", "Polypectomy", "ent", "procedure", "Polypectomy removes polyps from the colon, nose, or other body sites."),
    ("prenatal-screening", "Prenatal Screening", "obgyn", "test", "Prenatal screening tests evaluate risk for genetic conditions and birth defects during pregnancy."),
    ("prostate-biopsy", "Prostate Biopsy", "urology", "test", "Prostate biopsy removes tissue samples from the prostate gland to evaluate for cancer."),
    ("prostatectomy", "Prostatectomy", "urology", "surgery", "Prostatectomy is the surgical removal of all or part of the prostate gland."),
    ("psa-test", "PSA Test", "urology", "test", "The prostate-specific antigen blood test screens for prostate cancer and monitors treatment."),
    ("psychiatric-evaluation", "Psychiatric Evaluation", "psychiatry", "test", "A psychiatric evaluation is a structured assessment of mental, emotional, and behavioral health."),
    ("ptca", "Percutaneous Coronary Intervention", "cardiology", "procedure", "PCI opens narrowed coronary arteries using a balloon and stent delivered through a catheter."),
    ("pulmonary-function-test", "Pulmonary Function Tests", "pulmonary", "test", "Pulmonary function tests measure how well the lungs take in and release air."),
    ("pulmonary-rehabilitation", "Pulmonary Rehabilitation", "pulmonary", "therapy", "Pulmonary rehabilitation combines exercise training, education, and behavior change for chronic lung disease."),
    ("radioactive-iodine", "Radioactive Iodine Therapy", "endocrinology", "therapy", "Radioactive iodine therapy uses radioactive iodine to destroy thyroid tissue in hyperthyroidism or thyroid cancer."),
    ("radioactive-iodine-uptake", "Radioactive Iodine Uptake Scan", "endocrinology", "imaging", "The radioactive iodine uptake scan measures thyroid function and identifies thyroid disorders."),
    ("radiofrequency-ablation", "Radiofrequency Ablation", "gastroenterology", "procedure", "Radiofrequency ablation uses heat to destroy abnormal tissue, used for arrhythmias, tumors, and Barrett's esophagus."),
    ("rapid-flu-test", "Rapid Flu Test", "infectious-diseases", "test", "Rapid flu testing detects influenza antigens from a nose or throat swab in about 15 minutes."),
    ("rheumatoid-factor", "Rheumatoid Factor Test", "rheumatology", "test", "Rheumatoid factor is a blood test that helps diagnose rheumatoid arthritis and other autoimmune disorders."),
    ("right-heart-catheterization", "Right Heart Catheterization", "cardiology", "procedure", "Right heart catheterization measures pressures and oxygen levels in the right side of the heart and pulmonary arteries."),
    ("rubber-band-ligation", "Rubber Band Ligation", "gastroenterology", "procedure", "Rubber band ligation cuts off the blood supply to internal hemorrhoids, causing them to shrink."),
    ("scalp-biopsy", "Scalp Biopsy", "dermatology", "test", "Scalp biopsy removes a small piece of scalp skin to diagnose hair loss and inflammatory disorders."),
    ("schirmer-test", "Schirmer Test", "ophthalmology", "test", "The Schirmer test measures tear production to evaluate dry eye disease."),
    ("scrotal-ultrasound", "Scrotal Ultrasound", "urology", "imaging", "Scrotal ultrasound uses sound waves to evaluate the testicles and surrounding structures."),
    ("sentinel-lymph-node-biopsy", "Sentinel Lymph Node Biopsy", "oncology", "surgery", "Sentinel lymph node biopsy removes the first few lymph nodes that drain a tumor to evaluate spread."),
    ("skin-biopsy", "Skin Biopsy", "dermatology", "test", "A skin biopsy removes a small sample of skin to diagnose skin conditions including cancer."),
    ("skin-culture", "Skin Culture", "infectious-diseases", "test", "Skin culture identifies bacteria, fungi, or viruses causing skin infections."),
    ("sleep-study", "Polysomnography (Sleep Study)", "pulmonary", "test", "A sleep study records breathing, brain activity, and heart rhythm during sleep to diagnose sleep disorders."),
    ("slit-lamp-examination", "Slit Lamp Examination", "ophthalmology", "test", "Slit lamp examination uses a microscope to evaluate the structures at the front of the eye."),
    ("small-bowel-biopsy", "Small Bowel Biopsy", "gastroenterology", "test", "Small bowel biopsy removes tissue from the small intestine to evaluate celiac disease and other disorders."),
    ("spinal-fusion", "Spinal Fusion", "neurosurgery", "surgery", "Spinal fusion permanently joins two or more vertebrae to eliminate motion at that segment."),
    ("spine-xray", "Spine X-ray", "radiology", "imaging", "Spine X-ray uses radiation to produce images of the bones of the spine."),
    ("spirometry", "Spirometry", "pulmonary", "test", "Spirometry measures how much and how fast a person can move air in and out of the lungs."),
    ("sputum-culture", "Sputum Culture", "infectious-diseases", "test", "Sputum culture identifies bacteria or fungi causing lung infections."),
    ("stereotactic-radiosurgery", "Stereotactic Radiosurgery", "radiation-oncology", "therapy", "Stereotactic radiosurgery delivers precisely targeted radiation to brain or spine tumors."),
    ("stool-culture", "Stool Culture", "gastroenterology", "test", "Stool culture identifies bacteria that cause gastrointestinal infections."),
    ("stress-test", "Cardiac Stress Test", "cardiology", "test", "A cardiac stress test evaluates heart function during exercise or medication-induced stress."),
    ("tavr", "Transcatheter Aortic Valve Replacement", "cardiology", "procedure", "TAVR replaces a narrowed aortic valve using a catheter, avoiding open heart surgery."),
    ("tear-osmolarity", "Tear Osmolarity Test", "ophthalmology", "test", "Tear osmolarity measures the salt concentration in tears to diagnose dry eye disease."),
    ("tender-point-evaluation", "Tender Point Evaluation", "rheumatology", "test", "Tender point evaluation assesses areas of musculoskeletal tenderness for fibromyalgia diagnosis."),
    ("thrombectomy", "Mechanical Thrombectomy", "neurosurgery", "procedure", "Mechanical thrombectomy uses a catheter to remove blood clots from arteries during acute stroke."),
    ("thyroid-ultrasound", "Thyroid Ultrasound", "radiology", "imaging", "Thyroid ultrasound uses sound waves to evaluate the thyroid gland and identify nodules."),
    ("thyroidectomy", "Thyroidectomy", "general-surgery", "surgery", "Thyroidectomy is the surgical removal of all or part of the thyroid gland."),
    ("tissue-transglutaminase", "Tissue Transglutaminase Test", "gastroenterology", "test", "The tissue transglutaminase blood test screens for celiac disease."),
    ("tonometry", "Tonometry", "ophthalmology", "test", "Tonometry measures the pressure inside the eye to screen for glaucoma."),
    ("tonsillectomy", "Tonsillectomy", "ent", "surgery", "Tonsillectomy is the surgical removal of the tonsils."),
    ("trabeculectomy", "Trabeculectomy", "ophthalmology", "surgery", "Trabeculectomy creates a new drainage channel in the eye to lower intraocular pressure in glaucoma."),
    ("transsphenoidal-surgery", "Transsphenoidal Surgery", "neurosurgery", "surgery", "Transsphenoidal surgery removes pituitary tumors through the nasal passage and sphenoid sinus."),
    ("tsh-test", "TSH Test", "endocrinology", "test", "The TSH blood test measures thyroid-stimulating hormone to evaluate thyroid function."),
    ("tuberculin-skin-test", "Tuberculin Skin Test", "infectious-diseases", "test", "The tuberculin skin test screens for tuberculosis infection by injecting purified protein derivative under the skin."),
    ("tumor-resection", "Tumor Resection", "oncology", "surgery", "Tumor resection surgically removes a tumor and a margin of surrounding healthy tissue."),
    ("turp", "Transurethral Resection of the Prostate", "urology", "surgery", "TURP removes prostate tissue blocking urine flow through the urethra."),
    ("ultrasound-doppler", "Doppler Ultrasound", "radiology", "imaging", "Doppler ultrasound uses sound waves to evaluate blood flow through blood vessels."),
    ("upper-endoscopy", "Upper Endoscopy", "gastroenterology", "test", "Upper endoscopy uses a flexible scope to examine the esophagus, stomach, and upper small intestine."),
    ("ureteroscopy", "Ureteroscopy", "urology", "procedure", "Ureteroscopy uses a thin scope to examine and treat conditions of the ureter and kidney."),
    ("uric-acid-test", "Uric Acid Test", "rheumatology", "test", "The uric acid blood test measures levels that may be elevated in gout."),
    ("urine-culture", "Urine Culture", "urology", "test", "Urine culture identifies bacteria causing urinary tract infections."),
    ("urinalysis", "Urinalysis", "urology", "test", "Urinalysis examines the appearance, concentration, and content of urine to detect disease."),
    ("urodynamic-testing", "Urodynamic Testing", "urology", "test", "Urodynamic testing evaluates how well the bladder, sphincters, and urethra store and release urine."),
    ("uroflowmetry", "Uroflowmetry", "urology", "test", "Uroflowmetry measures the speed and amount of urine flow."),
    ("urine-nucleic-acid-test", "Urine Nucleic Acid Test", "infectious-diseases", "test", "Urine nucleic acid testing detects sexually transmitted infections from urine samples."),
    ("vagal-nerve-stimulation", "Vagal Nerve Stimulation", "neurosurgery", "surgery", "Vagal nerve stimulation implants a device that sends electrical pulses to the vagus nerve to treat epilepsy and depression."),
    ("vaginal-swab-test", "Vaginal Swab Test", "obgyn", "test", "Vaginal swab tests identify infections by sampling vaginal secretions."),
    ("variceal-banding", "Variceal Band Ligation", "gastroenterology", "procedure", "Variceal banding places rubber bands around enlarged esophageal veins to prevent bleeding."),
    ("vestibular-testing", "Vestibular Testing", "ent", "test", "Vestibular testing evaluates the inner ear balance system to diagnose dizziness disorders."),
    ("visual-field-test", "Visual Field Test", "ophthalmology", "test", "Visual field testing maps the extent of peripheral vision to detect glaucoma and other eye disorders."),
    ("vitamin-d", "Vitamin D Supplements", "endocrinology", "therapy", "Vitamin D supplements support bone health, immune function, and many other physiologic processes."),
    ("whipple-procedure", "Whipple Procedure", "general-surgery", "surgery", "The Whipple procedure removes the head of the pancreas, duodenum, and gallbladder to treat pancreatic cancer."),
    ("wide-excision", "Wide Local Excision", "dermatology", "surgery", "Wide local excision removes a melanoma and a generous margin of surrounding healthy skin."),
    ("xray-joint", "Joint X-ray", "radiology", "imaging", "A joint X-ray uses radiation to produce images of joints to evaluate arthritis and injury."),
    ("zika-pcr", "Zika Virus PCR", "infectious-diseases", "test", "Zika PCR detects Zika virus genetic material in blood or urine samples."),
]
