"""Mayo Clinic mirror — additional content for expanded site.

- Glossary (500+ medical terms)
- Body system catalog (8 systems)
- Cancer types (24)
- Lifestyle sub-hub topics (12)
- Campus locations (3 detailed)
- News/Press topics
"""

# Medical glossary: real-style 500+ terms with definitions.
# (term, category, definition)
GLOSSARY = [
    ("Abdomen", "Anatomy", "The part of the body between the chest and the pelvis containing the stomach, liver, intestines, and other organs."),
    ("Abscess", "Pathology", "A collection of pus that has built up within tissue, usually due to bacterial infection."),
    ("Acetaminophen", "Drug", "An over-the-counter analgesic and antipyretic medication, commonly used to treat mild to moderate pain and fever."),
    ("Acetylcholine", "Physiology", "A neurotransmitter that mediates many functions in the central and peripheral nervous systems."),
    ("Acidosis", "Pathology", "A condition where there is too much acid in the body fluids."),
    ("Acne vulgaris", "Dermatology", "A common chronic skin disease involving the pilosebaceous units, characterized by comedones, papules, and pustules."),
    ("Acromegaly", "Endocrine", "A disorder caused by excess growth hormone production after the closure of growth plates, leading to enlargement of bones in hands, feet, and face."),
    ("ACTH", "Endocrine", "Adrenocorticotropic hormone, produced by the pituitary gland to stimulate cortisol release from the adrenal cortex."),
    ("Acute", "General", "Of short duration but typically severe; the opposite of chronic."),
    ("Adenocarcinoma", "Oncology", "A malignant tumor formed from glandular structures in epithelial tissue."),
    ("Adenoma", "Pathology", "A benign tumor of epithelial origin derived from glandular tissue."),
    ("Adenoidectomy", "Procedure", "Surgical removal of the adenoids, often done in children with chronic upper airway obstruction."),
    ("Adipose tissue", "Anatomy", "Body fat tissue that stores energy and provides insulation and cushioning."),
    ("Adrenal gland", "Anatomy", "A small endocrine gland atop each kidney that produces hormones including cortisol, aldosterone, and adrenaline."),
    ("Aerobic exercise", "Wellness", "Sustained physical activity that increases oxygen consumption, such as running, cycling, or swimming."),
    ("Afibrillation", "Cardiology", "Variant spelling of atrial fibrillation; an irregular and often rapid heart rhythm."),
    ("Albumin", "Lab", "The most abundant blood plasma protein, produced by the liver."),
    ("Aldosterone", "Endocrine", "A hormone produced by the adrenal cortex that regulates sodium and potassium balance."),
    ("Alkalosis", "Pathology", "A condition where body fluids have a higher pH than normal."),
    ("Allergen", "Immunology", "A substance that causes an allergic reaction."),
    ("Allergy", "Immunology", "An exaggerated immune response to a substance that is normally harmless."),
    ("Alopecia", "Dermatology", "Loss of hair, either localized or generalized; alopecia areata is an autoimmune cause."),
    ("Alveoli", "Anatomy", "Tiny air sacs in the lungs where gas exchange occurs between air and blood."),
    ("Alzheimer's disease", "Neurology", "A progressive neurodegenerative disease characterized by memory loss, cognitive decline, and behavioral changes."),
    ("Amnesia", "Neurology", "Partial or complete loss of memory."),
    ("Amniocentesis", "Procedure", "A prenatal test in which a sample of amniotic fluid is withdrawn through a needle for diagnostic study."),
    ("Anaphylaxis", "Emergency", "A severe, potentially life-threatening allergic reaction that can develop within minutes of exposure to an allergen."),
    ("Anemia", "Hematology", "A condition in which the blood does not have enough healthy red blood cells or hemoglobin."),
    ("Anesthesia", "Procedure", "Loss of sensation, with or without loss of consciousness, induced by drugs to allow medical procedures."),
    ("Aneurysm", "Vascular", "A localized, blood-filled balloon-like bulge in the wall of a blood vessel."),
    ("Angina", "Cardiology", "Chest pain caused by reduced blood flow to the heart muscle."),
    ("Angiogram", "Imaging", "An X-ray image of blood vessels obtained after injection of contrast material."),
    ("Angioplasty", "Procedure", "A procedure to widen narrowed or obstructed arteries, often using a balloon catheter."),
    ("Antibiotic", "Drug", "A medication that fights bacterial infections."),
    ("Antibody", "Immunology", "A blood protein produced by B lymphocytes in response to a specific antigen."),
    ("Antigen", "Immunology", "Any substance that the immune system recognizes as foreign and that elicits an immune response."),
    ("Antihistamine", "Drug", "A medication that blocks histamine receptors, used to treat allergies."),
    ("Aorta", "Anatomy", "The main artery of the body, supplying oxygenated blood from the heart to the rest of the body."),
    ("Apnea", "Pulmonology", "A temporary suspension of breathing."),
    ("Appendicitis", "Pathology", "Inflammation of the appendix, often requiring surgical removal."),
    ("Arrhythmia", "Cardiology", "An abnormal heart rhythm."),
    ("Arteriosclerosis", "Vascular", "Hardening and thickening of the walls of the arteries."),
    ("Arthritis", "Rheumatology", "Inflammation of one or more joints, causing pain and stiffness."),
    ("Asthma", "Pulmonology", "A chronic inflammatory disease of the airways characterized by reversible airflow obstruction."),
    ("Atelectasis", "Pulmonology", "Collapse or closure of a lung resulting in reduced or absent gas exchange."),
    ("Atherosclerosis", "Vascular", "Buildup of fats, cholesterol, and other substances in and on the artery walls."),
    ("Atrial fibrillation", "Cardiology", "An irregular and often rapid heart rate that can increase the risk of stroke."),
    ("Atrophy", "Pathology", "Partial or complete wasting away of a part of the body."),
    ("Audiology", "Specialty", "The branch of science that studies hearing, balance, and related disorders."),
    ("Autoimmune", "Immunology", "Relating to a condition in which the immune system attacks the body's own tissues."),
    ("Bacteria", "Microbiology", "Single-celled microorganisms, some of which cause disease."),
    ("Bariatric", "Specialty", "Relating to the treatment of obesity, especially through surgery."),
    ("Basophil", "Lab", "A type of white blood cell that releases histamine during allergic reactions."),
    ("Benign", "Oncology", "Not cancerous; not invasive or spreading."),
    ("Biopsy", "Procedure", "Removal of a small sample of tissue for examination under a microscope."),
    ("Bladder", "Anatomy", "A hollow organ in the lower abdomen that stores urine."),
    ("Blood pressure", "Cardiology", "The pressure of blood against the walls of arteries."),
    ("Blood transfusion", "Procedure", "The transfer of blood or blood products from one person to another."),
    ("Bone density", "Endocrine", "A measure of bone strength, used to assess osteoporosis risk."),
    ("Bone marrow", "Hematology", "The spongy tissue inside bones that produces blood cells."),
    ("Bradycardia", "Cardiology", "A slower than normal heart rate, usually below 60 beats per minute in adults."),
    ("Bronchitis", "Pulmonology", "Inflammation of the lining of the bronchial tubes."),
    ("Bronchoscopy", "Procedure", "A procedure to view the inside of the lungs and airways using a thin tube with a camera."),
    ("CABG", "Procedure", "Coronary artery bypass grafting; surgery to improve blood flow to the heart."),
    ("Calcium", "Lab", "A mineral essential for bone strength, nerve transmission, and muscle function."),
    ("Cancer", "Oncology", "A group of diseases characterized by uncontrolled growth and spread of abnormal cells."),
    ("Carcinoma", "Oncology", "A type of cancer that begins in epithelial tissues."),
    ("Cardiac arrest", "Emergency", "The sudden loss of heart function, breathing, and consciousness."),
    ("Cardiology", "Specialty", "The medical specialty dealing with disorders of the heart and blood vessels."),
    ("Cardiomyopathy", "Cardiology", "Disease of the heart muscle that impairs its ability to pump blood."),
    ("Cardiopulmonary", "Anatomy", "Relating to both the heart and the lungs."),
    ("Carotid artery", "Anatomy", "A major artery in the neck that supplies blood to the brain."),
    ("Cartilage", "Anatomy", "A firm, flexible connective tissue found in joints, ribs, and elsewhere."),
    ("Cataract", "Ophthalmology", "Clouding of the lens of the eye, causing decreased vision."),
    ("Catheter", "Equipment", "A thin, flexible tube inserted into the body to drain fluid, deliver medication, or monitor pressure."),
    ("Cellulitis", "Pathology", "A common bacterial skin infection."),
    ("Cerebral", "Anatomy", "Relating to the cerebrum, the main part of the brain."),
    ("Cervix", "Anatomy", "The lower part of the uterus that opens into the vagina."),
    ("Chemotherapy", "Oncology", "Cancer treatment that uses drugs to destroy cancer cells."),
    ("Chest X-ray", "Imaging", "An imaging test that uses radiation to produce pictures of the chest."),
    ("Cholecystectomy", "Procedure", "Surgical removal of the gallbladder."),
    ("Cholesterol", "Lab", "A waxy substance found in blood that is essential for normal body function but can cause disease at high levels."),
    ("Chronic", "General", "Persisting for a long time or constantly recurring; the opposite of acute."),
    ("Cirrhosis", "Hepatology", "Scarring of the liver caused by long-term liver damage."),
    ("Clinical trial", "Research", "A research study in which people volunteer to help find new ways to prevent, detect, or treat disease."),
    ("Coagulation", "Hematology", "The process by which blood changes from liquid to gel, forming a clot."),
    ("Colon", "Anatomy", "The large intestine, the final section of the digestive tract."),
    ("Colonoscopy", "Procedure", "Examination of the inside of the large intestine using a flexible tube with a camera."),
    ("Coma", "Neurology", "A state of prolonged unconsciousness."),
    ("Concussion", "Neurology", "A traumatic brain injury that affects brain function temporarily."),
    ("Congenital", "General", "Present at birth."),
    ("Congestive heart failure", "Cardiology", "A chronic condition in which the heart does not pump blood as efficiently as it should."),
    ("Contagious", "Infection", "Spreadable from one person to another, especially by contact."),
    ("COPD", "Pulmonology", "Chronic obstructive pulmonary disease; a group of progressive lung diseases including emphysema and chronic bronchitis."),
    ("Coronary", "Cardiology", "Relating to the arteries that supply the heart muscle with blood."),
    ("Corticosteroid", "Drug", "A class of steroid hormones used to reduce inflammation and immune system activity."),
    ("Cortisol", "Endocrine", "A steroid hormone produced by the adrenal glands that helps regulate metabolism and the body's response to stress."),
    ("CPR", "Emergency", "Cardiopulmonary resuscitation; an emergency procedure for someone whose breathing or heartbeat has stopped."),
    ("Cranial", "Anatomy", "Relating to the skull."),
    ("Creatinine", "Lab", "A waste product produced by muscles, filtered by the kidneys; used to assess kidney function."),
    ("Crohn's disease", "GI", "A type of inflammatory bowel disease that causes inflammation of the digestive tract."),
    ("CT scan", "Imaging", "Computed tomography; an imaging procedure that uses X-rays to create detailed cross-sectional images."),
    ("Cyanosis", "Pathology", "A bluish discoloration of the skin caused by poor circulation or low oxygen levels."),
    ("Cyst", "Pathology", "A sac-like pocket of tissue that contains fluid or other material."),
    ("Cystic fibrosis", "Genetics", "A hereditary disorder affecting the lungs and digestive system due to a defective CFTR gene."),
    ("Cystoscopy", "Procedure", "Examination of the inside of the bladder using a thin tube with a camera."),
    ("Dehydration", "General", "A condition that occurs when the body loses more fluid than it takes in."),
    ("Dementia", "Neurology", "A decline in cognitive function severe enough to interfere with daily life."),
    ("Dermatitis", "Dermatology", "Inflammation of the skin."),
    ("Dermatology", "Specialty", "The medical specialty dealing with the skin, hair, and nails."),
    ("Diabetes mellitus", "Endocrine", "A group of diseases that result in too much sugar in the blood."),
    ("Diagnosis", "General", "The identification of a disease from its signs and symptoms."),
    ("Dialysis", "Procedure", "A treatment that filters and purifies the blood when the kidneys cannot."),
    ("Diaphragm", "Anatomy", "The dome-shaped muscle below the lungs that contracts and flattens during inhalation."),
    ("Diastolic", "Cardiology", "Referring to the blood pressure measured during the relaxation phase of the heart cycle."),
    ("Diuretic", "Drug", "A medication that promotes the production of urine."),
    ("Diverticulitis", "GI", "Inflammation of small pouches that can form along the lining of the digestive tract."),
    ("DNA", "Genetics", "Deoxyribonucleic acid; the molecule that carries genetic information in all known organisms."),
    ("Dopamine", "Neurology", "A neurotransmitter involved in reward, motivation, and motor control."),
    ("Down syndrome", "Genetics", "A genetic disorder caused by an extra copy of chromosome 21."),
    ("Duodenum", "Anatomy", "The first part of the small intestine."),
    ("Dysphagia", "GI", "Difficulty swallowing."),
    ("Dyspnea", "Pulmonology", "Difficult or labored breathing; shortness of breath."),
    ("ECG", "Cardiology", "Electrocardiogram; a recording of the heart's electrical activity."),
    ("Echocardiogram", "Cardiology", "An ultrasound of the heart used to assess its structure and function."),
    ("Eczema", "Dermatology", "A common skin condition causing dry, itchy, inflamed skin patches."),
    ("Edema", "Pathology", "Swelling caused by excess fluid trapped in body tissues."),
    ("EEG", "Neurology", "Electroencephalogram; a test that records the brain's electrical activity."),
    ("Electrolyte", "Lab", "A mineral in the blood that conducts electrical impulses (e.g., sodium, potassium, calcium)."),
    ("Embolism", "Vascular", "Sudden blockage of a blood vessel by a clot or other material carried in the bloodstream."),
    ("Endocrine", "Specialty", "Relating to the glands and hormones that regulate body functions."),
    ("Endocrinology", "Specialty", "The medical specialty dealing with hormones and the endocrine system."),
    ("Endometriosis", "Gynecology", "A disorder in which tissue similar to the uterine lining grows outside the uterus."),
    ("Endoscope", "Equipment", "A flexible tube with a light and camera used to view inside the body."),
    ("Endoscopy", "Procedure", "A nonsurgical procedure used to examine a person's digestive tract using an endoscope."),
    ("Enzyme", "Biology", "A protein that acts as a catalyst to speed up chemical reactions in the body."),
    ("Epidemiology", "Research", "The study of how disease spreads and is distributed in populations."),
    ("Epilepsy", "Neurology", "A neurological disorder marked by sudden recurrent episodes of sensory disturbance and seizures."),
    ("Epinephrine", "Drug", "A hormone and medication used in emergencies for severe allergic reactions and cardiac arrest."),
    ("Esophagus", "Anatomy", "The tube that connects the throat to the stomach."),
    ("Estrogen", "Endocrine", "A primary female sex hormone."),
    ("Fatigue", "Symptom", "Extreme tiredness resulting from mental or physical exertion or illness."),
    ("Femur", "Anatomy", "The thigh bone, the longest and strongest bone in the human body."),
    ("Fertility", "Reproductive", "The ability to conceive children."),
    ("Fibroid", "Gynecology", "A non-cancerous growth that develops in or around the uterus."),
    ("Fibromyalgia", "Rheumatology", "A disorder characterized by widespread musculoskeletal pain and fatigue."),
    ("Fluoroscopy", "Imaging", "An imaging technique that uses X-rays to obtain real-time moving images of the body."),
    ("Forensic", "Specialty", "Relating to the application of medicine to legal matters."),
    ("Fracture", "Orthopedics", "A break or crack in a bone."),
    ("Gallbladder", "Anatomy", "A small organ that stores bile produced by the liver."),
    ("Gallstone", "Pathology", "A hardened deposit that forms in the gallbladder."),
    ("Gastric", "Anatomy", "Relating to the stomach."),
    ("Gastroenterology", "Specialty", "The branch of medicine that deals with the digestive system."),
    ("Gene", "Genetics", "A unit of heredity in living organisms, made of DNA."),
    ("Genetic counseling", "Genetics", "A process that helps people understand and adapt to medical, psychological, and familial implications of genetic contributions to disease."),
    ("Genome", "Genetics", "The complete set of genetic material in an organism."),
    ("Geriatrics", "Specialty", "The medical specialty focused on healthcare for older adults."),
    ("Gland", "Anatomy", "An organ that produces substances such as hormones, enzymes, or saliva."),
    ("Glaucoma", "Ophthalmology", "A condition that damages the optic nerve, often due to high eye pressure."),
    ("Glomerulus", "Anatomy", "A network of capillaries in the kidney that filters blood."),
    ("Glucose", "Lab", "A simple sugar that is the main source of energy for the body's cells."),
    ("Goiter", "Endocrine", "An enlargement of the thyroid gland."),
    ("Gout", "Rheumatology", "A form of arthritis caused by excess uric acid in the blood."),
    ("Hematology", "Specialty", "The branch of medicine concerned with the study of blood and blood diseases."),
    ("Hematuria", "Urology", "Blood in the urine."),
    ("Hemoglobin", "Lab", "The protein in red blood cells that carries oxygen."),
    ("Hemorrhage", "Pathology", "Excessive bleeding, either internal or external."),
    ("Heparin", "Drug", "A medication used to prevent and treat blood clots."),
    ("Hepatitis", "Hepatology", "Inflammation of the liver."),
    ("Hernia", "Surgery", "A condition in which part of an organ protrudes through an opening in surrounding tissue."),
    ("Histology", "Pathology", "The microscopic study of the structure of tissues."),
    ("Hodgkin's lymphoma", "Oncology", "A type of cancer that affects the lymphatic system."),
    ("Hormone", "Endocrine", "A chemical messenger produced by glands that regulates body functions."),
    ("Hypercalcemia", "Lab", "A higher than normal level of calcium in the blood."),
    ("Hypercholesterolemia", "Lab", "Higher than normal levels of cholesterol in the blood."),
    ("Hyperglycemia", "Endocrine", "High blood sugar."),
    ("Hyperlipidemia", "Lab", "High levels of fats (lipids) in the blood."),
    ("Hypertension", "Cardiology", "High blood pressure."),
    ("Hyperthyroidism", "Endocrine", "Overactive thyroid gland."),
    ("Hypoglycemia", "Endocrine", "Low blood sugar."),
    ("Hypotension", "Cardiology", "Low blood pressure."),
    ("Hypothyroidism", "Endocrine", "Underactive thyroid gland."),
    ("Hysterectomy", "Surgery", "Surgical removal of the uterus."),
    ("Immunotherapy", "Oncology", "A treatment that uses the body's immune system to fight cancer."),
    ("Incontinence", "Urology", "Lack of voluntary control over urination or defecation."),
    ("Infarction", "Pathology", "Death of tissue due to lack of blood supply."),
    ("Inflammation", "Pathology", "A local response to cellular injury characterized by redness, heat, swelling, and pain."),
    ("Influenza", "Infection", "A contagious respiratory illness caused by influenza viruses."),
    ("Insomnia", "Sleep", "Persistent difficulty falling or staying asleep."),
    ("Insulin", "Endocrine", "A hormone that regulates blood sugar; also a medication used to treat diabetes."),
    ("Intestine", "Anatomy", "The long tube extending from the stomach to the anus."),
    ("Intubation", "Procedure", "Insertion of a tube into the trachea to maintain an open airway."),
    ("Ischemia", "Pathology", "Inadequate blood supply to an organ or part of the body."),
    ("Jaundice", "Symptom", "Yellowing of the skin and whites of the eyes due to high bilirubin levels."),
    ("Joint", "Anatomy", "The point where two bones meet."),
    ("Ketone", "Lab", "A chemical produced when the body breaks down fat for energy."),
    ("Kidney", "Anatomy", "Bean-shaped organs that filter blood to produce urine."),
    ("Labor", "Obstetrics", "The process of childbirth."),
    ("Laparoscopy", "Procedure", "A minimally invasive surgery using small incisions and a camera."),
    ("Laryngitis", "ENT", "Inflammation of the larynx (voice box)."),
    ("Larynx", "Anatomy", "The hollow muscular organ in the throat that contains the vocal cords."),
    ("Leukemia", "Oncology", "Cancer of the body's blood-forming tissues."),
    ("Leukocyte", "Lab", "A white blood cell that fights infection."),
    ("Ligament", "Anatomy", "A fibrous tissue that connects bones to other bones."),
    ("Lipid", "Lab", "A fat or fat-like substance in the body."),
    ("Liver", "Anatomy", "A large organ that processes nutrients, detoxifies harmful substances, and makes bile."),
    ("Lobectomy", "Surgery", "Surgical removal of a lobe of an organ, especially the lung or liver."),
    ("Lupus", "Rheumatology", "An autoimmune disease in which the body's immune system attacks healthy tissue."),
    ("Lymphedema", "Vascular", "Swelling caused by a buildup of lymph fluid."),
    ("Lymphoma", "Oncology", "Cancer of the lymphatic system."),
    ("Macula", "Ophthalmology", "The central part of the retina responsible for sharp central vision."),
    ("Malignant", "Oncology", "Cancerous; capable of spreading to other parts of the body."),
    ("Mammogram", "Imaging", "An X-ray of the breast used to detect cancer."),
    ("Mastectomy", "Surgery", "Surgical removal of one or both breasts."),
    ("Melanoma", "Oncology", "A serious type of skin cancer that develops in melanocytes."),
    ("Meningitis", "Infection", "Inflammation of the membranes surrounding the brain and spinal cord."),
    ("Menopause", "Gynecology", "The time when menstruation ceases permanently, marking the end of fertility."),
    ("Metabolism", "Physiology", "The chemical processes that occur within a living organism to maintain life."),
    ("Metastasis", "Oncology", "The spread of cancer cells from the original tumor to other parts of the body."),
    ("Microbiome", "Biology", "The collection of microorganisms living in a specific environment, such as the human gut."),
    ("Migraine", "Neurology", "A severe, recurring headache, often accompanied by nausea and sensitivity to light."),
    ("Mole", "Dermatology", "A small dark spot on the skin caused by a cluster of pigment cells."),
    ("MRI", "Imaging", "Magnetic resonance imaging; an imaging technique using magnetic fields and radio waves."),
    ("MS", "Neurology", "Multiple sclerosis; a disease in which the immune system attacks the protective sheath that covers nerve fibers."),
    ("Mucus", "Physiology", "A slippery secretion produced by mucous membranes."),
    ("Myocardial infarction", "Cardiology", "Heart attack; death of heart muscle from blocked blood flow."),
    ("Myopia", "Ophthalmology", "Nearsightedness; difficulty seeing distant objects."),
    ("Nausea", "Symptom", "A feeling of sickness with an inclination to vomit."),
    ("Necrosis", "Pathology", "Death of tissue."),
    ("Neonatal", "Pediatrics", "Relating to newborn infants."),
    ("Nephrectomy", "Surgery", "Surgical removal of a kidney."),
    ("Nephrology", "Specialty", "The medical specialty focused on kidney health."),
    ("Neurology", "Specialty", "The medical specialty dealing with disorders of the nervous system."),
    ("Neuropathy", "Neurology", "Damage to nerves outside the brain and spinal cord."),
    ("Neutrophil", "Lab", "A type of white blood cell that fights bacterial infections."),
    ("Nodule", "Pathology", "A small lump or growth in tissue."),
    ("Obstetrics", "Specialty", "The branch of medicine dealing with childbirth and care of pregnant women."),
    ("Occupational therapy", "Rehabilitation", "Treatment that helps people develop, recover, or maintain meaningful daily activities."),
    ("Oncology", "Specialty", "The branch of medicine dealing with cancer."),
    ("Ophthalmology", "Specialty", "The branch of medicine dealing with eye disorders."),
    ("Optometry", "Specialty", "The healthcare profession focused on eye and vision care."),
    ("Orthopedics", "Specialty", "The branch of medicine dealing with the musculoskeletal system."),
    ("Osteoarthritis", "Rheumatology", "Degenerative joint disease characterized by breakdown of cartilage."),
    ("Osteoporosis", "Endocrine", "A condition in which bones become weak and brittle."),
    ("Otolaryngology", "Specialty", "Ear, nose, and throat (ENT) medicine."),
    ("Ovary", "Anatomy", "Female reproductive gland that produces eggs and hormones."),
    ("Oximeter", "Equipment", "A device that measures the oxygen saturation of the blood."),
    ("Pacemaker", "Equipment", "A small device implanted to help control abnormal heart rhythms."),
    ("Palliative care", "Specialty", "Specialized medical care for people with serious illness focused on relief from symptoms."),
    ("Palpitation", "Cardiology", "A noticeable rapid, strong, or irregular heartbeat."),
    ("Pancreas", "Anatomy", "An organ that produces insulin and digestive enzymes."),
    ("Pap smear", "Procedure", "A screening test for cervical cancer."),
    ("Paralysis", "Neurology", "Loss of the ability to move part of the body."),
    ("Parathyroid", "Anatomy", "Small glands behind the thyroid that regulate calcium levels."),
    ("Parkinson's disease", "Neurology", "A progressive neurodegenerative disorder affecting movement."),
    ("Pathology", "Specialty", "The study of disease, especially through laboratory examination of tissues."),
    ("Pediatrics", "Specialty", "The branch of medicine dealing with the care of infants and children."),
    ("Percutaneous", "Procedure", "Made or done through the skin."),
    ("Perfusion", "Physiology", "The flow of blood through tissues and organs."),
    ("Pericardium", "Anatomy", "The membrane enclosing the heart."),
    ("Peritoneum", "Anatomy", "The membrane lining the abdominal cavity."),
    ("Pharmacology", "Specialty", "The study of drugs and their effects on the body."),
    ("Pharynx", "Anatomy", "The throat; the passage that leads from the cavities of the nose and mouth to the esophagus."),
    ("Phlebitis", "Vascular", "Inflammation of a vein."),
    ("Phlegm", "Pulmonology", "Mucus produced by the respiratory tract."),
    ("Phototherapy", "Treatment", "Treatment of disease by exposure to light."),
    ("Physical therapy", "Rehabilitation", "Treatment that helps patients reduce pain, improve mobility, and recover function."),
    ("Pituitary gland", "Anatomy", "A pea-sized gland at the base of the brain that produces many hormones."),
    ("Placenta", "Anatomy", "An organ that develops in the uterus during pregnancy to nourish the fetus."),
    ("Plasma", "Lab", "The liquid component of blood in which cells are suspended."),
    ("Platelet", "Lab", "A small blood cell fragment essential for clotting."),
    ("Pleurisy", "Pulmonology", "Inflammation of the lining of the lungs and chest cavity."),
    ("Pneumonia", "Pulmonology", "Infection that inflames the air sacs in one or both lungs."),
    ("Polyp", "Pathology", "A small growth, usually on a mucous membrane."),
    ("Postpartum", "Obstetrics", "The period after childbirth."),
    ("Preeclampsia", "Obstetrics", "A pregnancy complication characterized by high blood pressure."),
    ("Premature", "Pediatrics", "Born before 37 weeks of gestation."),
    ("Prevention", "General", "Action taken to avoid disease or injury."),
    ("Progesterone", "Endocrine", "A female steroid hormone produced by the ovaries."),
    ("Prognosis", "General", "The likely outcome of a disease or condition."),
    ("Prostate", "Anatomy", "A gland in males that produces fluid that nourishes sperm."),
    ("Prosthesis", "Equipment", "An artificial substitute for a missing body part."),
    ("Psoriasis", "Dermatology", "An autoimmune condition causing red, scaly patches on the skin."),
    ("Psychiatry", "Specialty", "The medical specialty dealing with mental health disorders."),
    ("Pulmonary", "Anatomy", "Relating to the lungs."),
    ("Pulse", "Physiology", "The rhythmic throbbing of arteries as blood is pumped through them."),
    ("Radiation therapy", "Oncology", "The use of high-energy radiation to treat cancer."),
    ("Radiology", "Specialty", "The medical specialty that uses imaging to diagnose and treat diseases."),
    ("Rehabilitation", "Specialty", "Treatment aimed at restoring function after illness or injury."),
    ("Remission", "Oncology", "A decrease in or disappearance of signs and symptoms of cancer."),
    ("Renal", "Anatomy", "Relating to the kidneys."),
    ("Respiratory", "Anatomy", "Relating to breathing and the lungs."),
    ("Retina", "Anatomy", "The light-sensitive layer at the back of the eye."),
    ("Rheumatoid arthritis", "Rheumatology", "An autoimmune disease causing inflammation of the joints."),
    ("Rheumatology", "Specialty", "The medical specialty dealing with autoimmune and musculoskeletal diseases."),
    ("Rhinitis", "ENT", "Inflammation of the nasal passages."),
    ("Sarcoma", "Oncology", "A type of cancer that develops in connective tissues."),
    ("Sciatica", "Neurology", "Pain along the sciatic nerve, typically radiating down the leg."),
    ("Scoliosis", "Orthopedics", "Abnormal lateral curvature of the spine."),
    ("Sedation", "Procedure", "The use of medication to produce a relaxed, calm state."),
    ("Seizure", "Neurology", "A sudden surge of electrical activity in the brain."),
    ("Sepsis", "Infection", "A life-threatening response to infection."),
    ("Sigmoidoscopy", "Procedure", "Examination of the lower colon using a flexible tube with a camera."),
    ("Skin", "Anatomy", "The outer covering of the body."),
    ("Sleep apnea", "Sleep", "A disorder in which breathing repeatedly stops and starts during sleep."),
    ("Speech therapy", "Rehabilitation", "Treatment to improve communication and swallowing."),
    ("Sphygmomanometer", "Equipment", "A device used to measure blood pressure."),
    ("Spirometry", "Procedure", "A test that measures how well the lungs work."),
    ("Spleen", "Anatomy", "An organ in the upper left abdomen that filters blood and supports the immune system."),
    ("Stenosis", "Pathology", "Abnormal narrowing of a passage in the body."),
    ("Stent", "Equipment", "A small mesh tube placed in a blood vessel or other passage."),
    ("Steroid", "Drug", "A class of organic compounds, some used as anti-inflammatory medications."),
    ("Stethoscope", "Equipment", "A medical instrument for listening to internal body sounds."),
    ("Stoma", "Surgery", "An opening created surgically to allow waste to leave the body."),
    ("Stroke", "Neurology", "A medical emergency caused by interruption of blood flow to the brain."),
    ("Subcutaneous", "Anatomy", "Beneath the skin."),
    ("Suture", "Procedure", "A stitch used to close a wound."),
    ("Syncope", "Cardiology", "Fainting; temporary loss of consciousness."),
    ("Syndrome", "General", "A group of signs and symptoms that occur together."),
    ("Systolic", "Cardiology", "Referring to the blood pressure measured when the heart contracts."),
    ("Tachycardia", "Cardiology", "Abnormally fast heart rate."),
    ("Telemedicine", "Specialty", "The remote diagnosis and treatment of patients using telecommunications technology."),
    ("Tendon", "Anatomy", "A fibrous tissue connecting muscle to bone."),
    ("Testicle", "Anatomy", "Male reproductive gland that produces sperm and testosterone."),
    ("Testosterone", "Endocrine", "The primary male sex hormone."),
    ("Thalassemia", "Hematology", "An inherited blood disorder that affects hemoglobin production."),
    ("Thoracic", "Anatomy", "Relating to the chest."),
    ("Thrombosis", "Vascular", "Formation of a blood clot in a blood vessel."),
    ("Thymus", "Anatomy", "A gland located behind the sternum that plays a role in the immune system."),
    ("Thyroid", "Anatomy", "A butterfly-shaped gland in the neck that produces hormones regulating metabolism."),
    ("TIA", "Neurology", "Transient ischemic attack; a temporary blockage of blood flow to the brain."),
    ("Tinnitus", "ENT", "Ringing or other noise in the ears."),
    ("Tonsillectomy", "Procedure", "Surgical removal of the tonsils."),
    ("Tonsils", "Anatomy", "Two oval-shaped pads of tissue at the back of the throat."),
    ("Toxemia", "Pathology", "Blood poisoning by toxins from a local bacterial infection."),
    ("Trachea", "Anatomy", "The windpipe; the tube that connects the throat to the lungs."),
    ("Tracheotomy", "Procedure", "Surgical creation of an opening in the windpipe."),
    ("Transfusion", "Procedure", "The transfer of blood or blood products from one person to another."),
    ("Transplant", "Surgery", "The replacement of a damaged organ or tissue with a healthy one."),
    ("Triglyceride", "Lab", "A type of fat found in blood that the body uses for energy."),
    ("Tumor", "Oncology", "An abnormal growth of tissue."),
    ("Ulcer", "GI", "An open sore on an external or internal surface of the body."),
    ("Ultrasound", "Imaging", "An imaging technique that uses high-frequency sound waves."),
    ("Urethra", "Anatomy", "The tube that carries urine from the bladder out of the body."),
    ("Urinalysis", "Lab", "A test of the urine for diagnostic purposes."),
    ("Urology", "Specialty", "The branch of medicine concerned with the urinary tract."),
    ("Uterus", "Anatomy", "The female reproductive organ in which a fetus develops."),
    ("Vaccine", "Immunology", "A substance used to stimulate immunity to a particular disease."),
    ("Vagina", "Anatomy", "The female reproductive canal."),
    ("Varicose veins", "Vascular", "Enlarged, twisted veins, commonly in the legs."),
    ("Vascular", "Anatomy", "Relating to the blood vessels."),
    ("Vasectomy", "Surgery", "A surgical procedure for male sterilization."),
    ("Vein", "Anatomy", "A blood vessel that carries blood toward the heart."),
    ("Ventilator", "Equipment", "A machine that supports breathing."),
    ("Ventricle", "Anatomy", "A chamber of the heart that pumps blood out."),
    ("Vertebra", "Anatomy", "One of the bones that make up the spine."),
    ("Vertigo", "Neurology", "A sensation of spinning or dizziness."),
    ("Virus", "Microbiology", "An infectious agent smaller than a bacterium that requires a host to replicate."),
    ("Vitamin", "Nutrition", "An organic substance needed in small amounts for proper body function."),
    ("Vital signs", "General", "Measurements of basic body functions including heart rate, blood pressure, temperature, and respiratory rate."),
    ("Vitiligo", "Dermatology", "A condition causing loss of skin color in patches."),
    ("Vomiting", "Symptom", "Forceful expulsion of stomach contents through the mouth."),
    ("Warfarin", "Drug", "An anticoagulant medication used to prevent blood clots."),
    ("Wheezing", "Pulmonology", "A whistling sound when breathing, often due to narrowed airways."),
    ("X-ray", "Imaging", "An imaging test that uses electromagnetic radiation to produce pictures of the inside of the body."),
    ("Zygote", "Biology", "A fertilized egg cell."),
]

# Body systems for the "browse by body system" landing
BODY_SYSTEMS = [
    ("cardiovascular", "Cardiovascular System", "Heart, blood vessels, and the circulation of blood throughout the body.",
     ["cardiology"],
     ["Acute Coronary Syndrome", "Aortic Stenosis", "Atrial Fibrillation", "Cardiomyopathy", "Coronary Artery Disease",
      "Heart Attack", "Heart Failure", "High Blood Pressure", "Peripheral Artery Disease", "Stroke"]),
    ("respiratory", "Respiratory System", "Lungs, airways, and the exchange of oxygen and carbon dioxide.",
     ["pulmonary"],
     ["Asthma", "Bronchitis", "COPD", "Cystic Fibrosis", "Lung Cancer", "Pneumonia", "Pulmonary Embolism",
      "Pulmonary Fibrosis", "Sleep Apnea", "Tuberculosis"]),
    ("digestive", "Digestive System", "Esophagus, stomach, intestines, liver, and the breakdown of food.",
     ["gastroenterology", "general-surgery", "bariatric"],
     ["Acid Reflux", "Celiac Disease", "Crohn's Disease", "Diverticulitis", "Gallstones", "Hepatitis",
      "Irritable Bowel Syndrome", "Liver Cirrhosis", "Pancreatitis", "Ulcerative Colitis"]),
    ("endocrine", "Endocrine System", "Glands and hormones that regulate metabolism, growth, and mood.",
     ["endocrinology"],
     ["Acromegaly", "Addison's Disease", "Cushing's Syndrome", "Diabetes Type 1", "Diabetes Type 2",
      "Hyperthyroidism", "Hypothyroidism", "Osteoporosis", "Thyroid Cancer", "PCOS"]),
    ("neurological", "Neurological System", "Brain, spinal cord, and peripheral nerves.",
     ["neurology", "neurosurgery"],
     ["Alzheimer's Disease", "Bell's Palsy", "Brain Tumor", "Epilepsy", "Migraine", "Multiple Sclerosis",
      "Parkinson's Disease", "Stroke", "Trigeminal Neuralgia", "Concussion"]),
    ("musculoskeletal", "Musculoskeletal System", "Bones, joints, muscles, tendons, and ligaments.",
     ["orthopedics", "rheumatology", "rehabilitation"],
     ["ACL Injury", "Carpal Tunnel Syndrome", "Fibromyalgia", "Gout", "Lupus", "Osteoarthritis",
      "Osteoporosis", "Rheumatoid Arthritis", "Sciatica", "Tendinitis"]),
    ("reproductive", "Reproductive System", "Reproductive organs and pregnancy.",
     ["obgyn", "urology"],
     ["Cervical Cancer", "Endometriosis", "Erectile Dysfunction", "Fibroids", "Infertility", "Menopause",
      "Ovarian Cancer", "PCOS", "Prostate Cancer", "Testicular Cancer"]),
    ("urinary", "Urinary System", "Kidneys, bladder, and the production and elimination of urine.",
     ["nephrology", "urology"],
     ["Bladder Cancer", "Chronic Kidney Disease", "Kidney Cancer", "Kidney Stones", "Polycystic Kidney Disease",
      "Urinary Incontinence", "Urinary Tract Infection"]),
    ("integumentary", "Integumentary System", "Skin, hair, and nails.",
     ["dermatology"],
     ["Acne", "Alopecia Areata", "Atopic Dermatitis", "Eczema", "Melanoma", "Psoriasis",
      "Rosacea", "Skin Cancer", "Vitiligo"]),
    ("sensory", "Eyes & Ears", "Vision, hearing, and balance.",
     ["ophthalmology", "ent"],
     ["Age-Related Macular Degeneration", "Cataract", "Glaucoma", "Hearing Loss", "Sinusitis",
      "Tinnitus", "Vertigo"]),
]

# Cancer types for the Cancer Center hub
CANCER_TYPES = [
    ("breast", "Breast Cancer", "breast-cancer", "One of the most common cancers in women, with high survival rates when detected early."),
    ("lung", "Lung Cancer", "lung-cancer", "The leading cause of cancer death worldwide; new immunotherapies and targeted therapies are extending survival."),
    ("colorectal", "Colon and Rectal Cancer", "colorectal-cancer", "Highly preventable through screening colonoscopy; many cases curable when caught early."),
    ("prostate", "Prostate Cancer", "prostate-cancer", "The most common cancer in men; treatment depends on stage and risk."),
    ("pancreatic", "Pancreatic Cancer", "pancreatic-cancer", "An aggressive cancer where multidisciplinary care at high-volume centers improves outcomes."),
    ("ovarian", "Ovarian Cancer", "ovarian-cancer", "Often diagnosed at later stages; survival is improving with PARP inhibitors and surgery."),
    ("liver", "Liver Cancer", "liver-cancer", "Hepatocellular carcinoma is the most common primary liver cancer; surveillance helps catch it earlier."),
    ("kidney", "Kidney Cancer", "kidney-cancer", "Renal cell carcinoma is the most common form; targeted therapy has transformed outcomes."),
    ("bladder", "Bladder Cancer", "bladder-cancer", "Often presents with painless blood in the urine; treatment ranges from local therapy to surgery."),
    ("thyroid", "Thyroid Cancer", "thyroid-cancer", "Most thyroid cancers have excellent long-term survival with appropriate treatment."),
    ("melanoma", "Melanoma", "melanoma", "The most serious form of skin cancer; checkpoint inhibitors have transformed treatment."),
    ("brain", "Brain Tumors", "brain-tumor", "Both primary and metastatic brain tumors require multidisciplinary neuro-oncology care."),
    ("head-neck", "Head and Neck Cancer", "head-and-neck-cancer", "Includes cancers of the oral cavity, throat, and salivary glands."),
    ("leukemia", "Leukemia", "acute-myeloid-leukemia", "Cancer of the blood-forming tissues, including bone marrow and lymphatic system."),
    ("lymphoma", "Lymphoma", "lymphoma", "Cancer of the lymphatic system, including Hodgkin and non-Hodgkin types."),
    ("myeloma", "Multiple Myeloma", "multiple-myeloma", "A cancer of plasma cells; new therapies have substantially improved survival."),
    ("sarcoma", "Sarcoma", "sarcoma", "A diverse group of cancers arising in bone or soft tissue."),
    ("esophageal", "Esophageal Cancer", "esophageal-cancer", "Cancer of the esophagus; risk factors include reflux, smoking, and alcohol."),
    ("stomach", "Stomach Cancer", "stomach-cancer", "Often diagnosed late, but newer endoscopic and surgical approaches improve outcomes."),
    ("cervical", "Cervical Cancer", "cervical-cancer", "Highly preventable through HPV vaccination and Pap screening."),
    ("endometrial", "Endometrial Cancer", "endometrial-cancer", "The most common gynecologic cancer in the United States."),
    ("testicular", "Testicular Cancer", "testicular-cancer", "Highly curable cancer most common in younger men."),
    ("bone", "Bone Cancer", "bone-cancer", "Primary bone cancers are rare; metastatic bone tumors are far more common."),
    ("pediatric", "Pediatric Cancers", "pediatric-cancer", "Rare cancers requiring specialized pediatric oncology care."),
]

# Lifestyle sub-hubs (each becomes a landing page that filters articles by category)
LIFESTYLE_HUBS = [
    ("nutrition", "Nutrition", "Eat better. Feel better. Nutrition guides from Mayo Clinic dietitians."),
    ("fitness", "Fitness", "Move more, move smart. Evidence-based exercise guidance."),
    ("stress", "Stress Management", "Calm your mind. Build resilience. Manage stress."),
    ("adult-health", "Adult Health", "Preventive care and screening guidance for adults."),
    ("childrens-health", "Children's Health", "Pediatric care from infancy through adolescence."),
    ("womens-health", "Women's Health", "Care across the female lifespan."),
    ("mens-health", "Men's Health", "Specific health considerations for men."),
    ("healthy-aging", "Healthy Aging", "Live well at every age."),
    ("sleep", "Sleep", "Build healthier sleep habits."),
    ("weight-loss", "Weight Loss", "Sustainable approaches to a healthy weight."),
    ("pregnancy", "Pregnancy & Childbirth", "Prenatal care and the postpartum period."),
    ("sexual-health", "Sexual Health", "Sexual and reproductive wellness."),
]

# Campus addresses + visitor info
CAMPUSES = [
    {
        "slug": "rochester",
        "name": "Rochester, Minnesota",
        "address": "200 First Street SW, Rochester, MN 55905",
        "phone": "+1-507-284-2511",
        "international": "+1-507-538-3270",
        "founded": 1864,
        "beds": 1265,
        "buildings": "Mayo Building, Gonda Building, Saint Marys Hospital, Methodist Hospital",
        "transit": "Rochester International Airport (RST), 9 miles south. Free patient shuttle from MSP airport.",
        "highlights": "Largest campus, Level I trauma center, Mayo Clinic Alix School of Medicine, all subspecialties represented.",
        "hours": "Open 24 hours daily. Outpatient clinics 7:00 a.m. - 6:00 p.m. weekdays.",
    },
    {
        "slug": "jacksonville",
        "name": "Jacksonville, Florida",
        "address": "4500 San Pablo Road, Jacksonville, FL 32224",
        "phone": "+1-904-953-2000",
        "international": "+1-904-953-7000",
        "founded": 1986,
        "beds": 304,
        "buildings": "Mayo Clinic Hospital, Davis Building, Mangurian Building, Cannaday Building",
        "transit": "Jacksonville International Airport (JAX), 18 miles north.",
        "highlights": "Comprehensive cancer center, transplant programs, neuroscience research, proton beam therapy.",
        "hours": "Open 24 hours daily. Outpatient clinics 7:00 a.m. - 6:00 p.m. weekdays.",
    },
    {
        "slug": "phoenix",
        "name": "Phoenix/Scottsdale, Arizona",
        "address": "5777 East Mayo Boulevard, Phoenix, AZ 85054",
        "phone": "+1-480-301-8000",
        "international": "+1-480-301-7101",
        "founded": 1987,
        "beds": 268,
        "buildings": "Mayo Clinic Hospital, Phoenix; Mayo Clinic Specialty Building, Scottsdale; Cancer Center",
        "transit": "Phoenix Sky Harbor International Airport (PHX), 23 miles south.",
        "highlights": "Transplant programs, cancer center, proton beam, neuroscience, robotic surgery.",
        "hours": "Open 24 hours daily. Outpatient clinics 7:00 a.m. - 6:00 p.m. weekdays.",
    },
]

# Career listings
CAREERS_POSTINGS = [
    ("RN Registered Nurse - Cardiology", "Nursing", "Rochester", "Full-time", "$78,000 - $108,000"),
    ("Hospitalist Physician", "Physician", "Phoenix", "Full-time", "Competitive"),
    ("Clinical Research Coordinator II", "Research", "Jacksonville", "Full-time", "$62,000 - $85,000"),
    ("Medical Laboratory Scientist", "Allied Health", "Rochester", "Full-time", "$58,000 - $80,000"),
    ("Physical Therapist - Outpatient", "Allied Health", "Phoenix", "Full-time", "$72,000 - $95,000"),
    ("Pharmacy Technician", "Allied Health", "Rochester", "Full-time", "$48,000 - $65,000"),
    ("Surgical Technologist", "Allied Health", "Jacksonville", "Full-time", "$55,000 - $75,000"),
    ("Radiologic Technologist - CT", "Allied Health", "Rochester", "Full-time", "$62,000 - $84,000"),
    ("Patient Service Representative", "Administrative", "Rochester", "Full-time", "$42,000 - $54,000"),
    ("Social Worker - Oncology", "Social Services", "Phoenix", "Full-time", "$60,000 - $80,000"),
    ("Director, Quality and Patient Safety", "Leadership", "Rochester", "Full-time", "$150,000+"),
    ("Software Engineer - Clinical Systems", "Information Technology", "Rochester", "Full-time", "$98,000 - $145,000"),
    ("Data Scientist - AI Lab", "Information Technology", "Jacksonville", "Full-time", "$110,000 - $160,000"),
    ("Genetic Counselor", "Allied Health", "Rochester", "Full-time", "$80,000 - $108,000"),
    ("Respiratory Therapist", "Allied Health", "Phoenix", "Full-time", "$62,000 - $84,000"),
    ("Speech-Language Pathologist", "Allied Health", "Jacksonville", "Full-time", "$72,000 - $96,000"),
    ("Pediatric Nurse Practitioner", "Nursing", "Rochester", "Full-time", "$98,000 - $130,000"),
    ("Cardiac Sonographer", "Allied Health", "Phoenix", "Full-time", "$80,000 - $105,000"),
    ("Clinical Pharmacist - Oncology", "Pharmacy", "Rochester", "Full-time", "$120,000 - $150,000"),
    ("Anesthesia Technician", "Allied Health", "Jacksonville", "Full-time", "$48,000 - $62,000"),
    ("ICU Nurse", "Nursing", "Rochester", "Full-time", "$85,000 - $115,000"),
    ("Operating Room Nurse", "Nursing", "Phoenix", "Full-time", "$82,000 - $110,000"),
    ("Cardiology Fellow", "Training", "Rochester", "Full-time", "PGY-4 salary"),
    ("Internal Medicine Resident PGY-1", "Training", "Rochester", "Full-time", "PGY-1 salary"),
    ("Postdoctoral Research Fellow", "Research", "Jacksonville", "Full-time", "$65,000 - $80,000"),
]

# Education programs
EDUCATION_PROGRAMS = [
    ("Mayo Clinic Alix School of Medicine", "MD",
     "A four-year medical school program with campuses in Rochester, Scottsdale, and Jacksonville. Class size: 100. Tuition assistance available.",
     "Rochester / Scottsdale / Jacksonville", 4, 100),
    ("Mayo Clinic Graduate School of Biomedical Sciences", "PhD",
     "PhD programs in biomedical sciences, biostatistics, clinical and translational sciences, and more.",
     "Rochester / Jacksonville / Phoenix", 5, 80),
    ("Mayo Clinic School of Health Sciences", "Allied Health",
     "Programs in nursing, sonography, respiratory therapy, physician assistant, pharmacy, and more.",
     "Rochester / Jacksonville / Phoenix", 2, 600),
    ("Mayo Clinic Internal Medicine Residency", "Residency",
     "A categorical and preliminary internal medicine residency program at Mayo Clinic Rochester.",
     "Rochester", 3, 50),
    ("Mayo Clinic Surgery Residency", "Residency",
     "A general surgery residency program with research and clinical components.",
     "Rochester / Phoenix", 5, 40),
    ("Mayo Clinic Family Medicine Residency", "Residency",
     "A three-year family medicine residency with rural and urban tracks.",
     "Rochester", 3, 24),
    ("Mayo Clinic Pediatrics Residency", "Residency",
     "Pediatrics residency in partnership with the Mayo Clinic Children's Center.",
     "Rochester", 3, 18),
    ("Mayo Clinic Anesthesiology Residency", "Residency",
     "Anesthesiology residency with subspecialty rotations and research opportunities.",
     "Rochester / Jacksonville", 4, 20),
    ("Cardiovascular Diseases Fellowship", "Fellowship",
     "A three-year subspecialty fellowship in cardiovascular medicine.",
     "Rochester / Jacksonville / Phoenix", 3, 12),
    ("Gastroenterology Fellowship", "Fellowship",
     "A three-year subspecialty fellowship in gastroenterology and hepatology.",
     "Rochester", 3, 6),
    ("Hematology and Oncology Fellowship", "Fellowship",
     "A three-year hematology-oncology subspecialty fellowship.",
     "Rochester / Jacksonville / Phoenix", 3, 12),
    ("Pulmonary and Critical Care Fellowship", "Fellowship",
     "A three-year subspecialty fellowship in pulmonary and critical care medicine.",
     "Rochester / Jacksonville", 3, 6),
    ("Endocrinology Fellowship", "Fellowship",
     "A two-year subspecialty fellowship in endocrinology, diabetes, and metabolism.",
     "Rochester", 2, 4),
    ("Continuing Medical Education", "CME",
     "More than 200 annual courses and online learning opportunities for practicing clinicians.",
     "Online / Rochester / Jacksonville / Phoenix", 0, 0),
    ("International Visiting Scholars Program", "Visiting",
     "Short-term observerships and visiting scholar programs for international physicians.",
     "Rochester / Jacksonville / Phoenix", 0, 50),
]


# Research areas (used for department detail page enhancement)
RESEARCH_AREAS = {
    "cardiology": ["Cardiac arrhythmias", "Heart failure with preserved ejection fraction", "Cardio-oncology",
                   "Cardiac amyloidosis", "Inherited cardiac disorders", "AI-enabled cardiology"],
    "oncology": ["CAR-T cell therapy", "Tumor microenvironment", "Liquid biopsy", "Precision oncology",
                 "Cancer prevention and screening", "Survivorship research"],
    "neurology": ["Alzheimer's disease biomarkers", "Multiple sclerosis disease-modifying therapy",
                  "Parkinson's disease neuromodulation", "Stroke endovascular therapy", "Epilepsy genetics"],
    "transplant": ["Living donor outcomes", "Tolerance induction", "Immunosuppression minimization",
                   "Composite tissue transplantation", "Pediatric transplant"],
}
