"""Mayo Clinic mirror — drugs & supplements catalog (~110 entries)."""

# (slug, name, kind, route, treats, side_effects_short, warnings_short)
# kind in {prescription, otc, supplement}; route freeform
DRUGS = [
    ("acetaminophen", "Acetaminophen", "otc", "Oral", "Pain, fever", "Nausea, rash; rare liver injury with overdose.", "Do not exceed 3 g/day in adults with liver disease."),
    ("acyclovir", "Acyclovir", "prescription", "Oral / IV", "Herpes simplex, varicella zoster", "Nausea, headache, fatigue; rare kidney dysfunction.", "Maintain hydration; adjust dose in renal impairment."),
    ("adalimumab", "Adalimumab", "prescription", "Subcutaneous injection", "Rheumatoid arthritis, Crohn's disease, psoriasis", "Injection site reaction, infection, rash.", "Screen for tuberculosis and hepatitis B before use."),
    ("aflibercept", "Aflibercept", "prescription", "Intravitreal injection", "Macular degeneration, diabetic retinopathy", "Eye pain, increased eye pressure.", "Administered by ophthalmologist."),
    ("albuterol", "Albuterol", "prescription", "Inhaled", "Asthma, COPD bronchospasm", "Tremor, tachycardia, headache.", "Overuse may indicate inadequate asthma control."),
    ("alendronate", "Alendronate", "prescription", "Oral", "Osteoporosis, Paget's disease", "Heartburn, abdominal pain, jaw osteonecrosis (rare).", "Take with full glass of water; stay upright 30 minutes."),
    ("allopurinol", "Allopurinol", "prescription", "Oral", "Gout, tumor lysis syndrome", "Rash, gastrointestinal upset.", "Rare severe skin reactions; HLA-B*5801 risk in Asian patients."),
    ("alprazolam", "Alprazolam", "prescription", "Oral", "Anxiety, panic disorder", "Drowsiness, dependence, memory impairment.", "Avoid alcohol; risk of dependence."),
    ("alprostadil", "Alprostadil", "prescription", "Injection / Urethral", "Erectile dysfunction", "Local pain, prolonged erection.", "Seek care for erections lasting over 4 hours."),
    ("alteplase", "Alteplase (tPA)", "prescription", "IV", "Acute ischemic stroke, pulmonary embolism, STEMI", "Major bleeding, intracranial hemorrhage.", "Strict eligibility window after symptom onset."),
    ("amiodarone", "Amiodarone", "prescription", "Oral / IV", "Atrial and ventricular arrhythmias", "Pulmonary toxicity, thyroid dysfunction, photosensitivity.", "Baseline thyroid, liver, and lung evaluation required."),
    ("amitriptyline", "Amitriptyline", "prescription", "Oral", "Neuropathic pain, migraine prevention, depression", "Dry mouth, sedation, weight gain.", "Caution in elderly; arrhythmia risk in overdose."),
    ("amlodipine", "Amlodipine", "prescription", "Oral", "Hypertension, angina", "Ankle swelling, flushing, headache.", "Calcium channel blocker; titrate to response."),
    ("amoxicillin", "Amoxicillin", "prescription", "Oral", "Strep throat, ear infection, sinusitis, H. pylori", "Diarrhea, rash, candidiasis.", "Penicillin allergy; rash in mononucleosis."),
    ("amoxicillin-clavulanate", "Amoxicillin-Clavulanate", "prescription", "Oral", "Sinusitis, otitis media, cellulitis, dog bites", "Diarrhea, abdominal pain.", "Penicillin allergy; take with food."),
    ("amphetamine", "Amphetamine", "prescription", "Oral", "ADHD, narcolepsy", "Decreased appetite, insomnia, elevated blood pressure.", "Controlled substance; monitor cardiac status."),
    ("anastrozole", "Anastrozole", "prescription", "Oral", "Hormone receptor-positive breast cancer", "Hot flashes, joint pain, osteoporosis.", "Postmenopausal women only; monitor bone density."),
    ("antithymocyte-globulin", "Antithymocyte Globulin", "prescription", "IV", "Aplastic anemia, transplant rejection", "Infusion reactions, infection, cytopenias.", "Administered in hospital with monitoring."),
    ("apixaban", "Apixaban", "prescription", "Oral", "Atrial fibrillation, DVT, PE", "Bleeding, bruising.", "Hold prior to surgery; reversal agent available."),
    ("aripiprazole", "Aripiprazole", "prescription", "Oral / IM", "Schizophrenia, bipolar disorder, depression adjunct", "Akathisia, weight gain, sedation.", "Monitor for metabolic side effects."),
    ("artificial-tears", "Artificial Tears", "otc", "Eye drops", "Dry eye", "Mild blurring after instillation.", "Preservative-free preferred for frequent use."),
    ("aspirin", "Aspirin", "otc", "Oral", "Pain, fever, cardiovascular prevention", "GI bleeding, tinnitus at high doses.", "Avoid in children with viral illness (Reye syndrome)."),
    ("atomoxetine", "Atomoxetine", "prescription", "Oral", "ADHD", "Decreased appetite, nausea, blood pressure changes.", "Not a controlled substance; suicidality warning in youth."),
    ("atorvastatin", "Atorvastatin", "prescription", "Oral", "High cholesterol, cardiovascular prevention", "Muscle aches, transaminase elevation.", "Monitor liver enzymes; statin myopathy risk."),
    ("azathioprine", "Azathioprine", "prescription", "Oral", "Crohn's disease, lupus, transplant rejection", "Bone marrow suppression, hepatotoxicity.", "Check TPMT genotype before initiation."),
    ("azithromycin", "Azithromycin", "prescription", "Oral / IV", "Pneumonia, chlamydia, pertussis", "GI upset, QT prolongation.", "Avoid in patients with prolonged QT interval."),
    ("baclofen", "Baclofen", "prescription", "Oral / Intrathecal", "Muscle spasticity", "Drowsiness, weakness, withdrawal seizures.", "Do not stop abruptly; risk of severe withdrawal."),
    ("baloxavir", "Baloxavir", "prescription", "Oral", "Influenza A and B", "Diarrhea, headache.", "Most effective within 48 hours of symptom onset."),
    ("baricitinib", "Baricitinib", "prescription", "Oral", "Rheumatoid arthritis, alopecia areata, COVID-19", "Infection, thrombosis, lipid changes.", "Screen for TB and hepatitis."),
    ("belimumab", "Belimumab", "prescription", "IV / SubQ", "Systemic lupus erythematosus", "Infection, infusion reaction, depression.", "Monitor for serious infections and psychiatric changes."),
    ("bevacizumab", "Bevacizumab", "prescription", "IV", "Colorectal cancer, glioblastoma, ovarian cancer, macular degeneration", "Hypertension, bleeding, impaired wound healing.", "Hold around surgery; monitor blood pressure."),
    ("bictegravir", "Bictegravir", "prescription", "Oral", "HIV infection", "Nausea, headache.", "Component of co-formulated HIV regimens."),
    ("bleomycin", "Bleomycin", "prescription", "IV / IM", "Hodgkin lymphoma, testicular cancer", "Pulmonary fibrosis, skin changes.", "Cumulative dose limit; pulmonary monitoring."),
    ("bortezomib", "Bortezomib", "prescription", "SubQ / IV", "Multiple myeloma, mantle cell lymphoma", "Peripheral neuropathy, thrombocytopenia.", "Antiviral prophylaxis for herpes zoster recommended."),
    ("bosentan", "Bosentan", "prescription", "Oral", "Pulmonary arterial hypertension", "Hepatotoxicity, anemia, edema.", "Monthly liver function and pregnancy testing required."),
    ("botulinum-toxin", "Botulinum Toxin", "prescription", "Injection", "Migraine prevention, dystonia, spasticity, blepharospasm", "Injection site reactions, weakness.", "Effects typically last 3 months."),
    ("brentuximab", "Brentuximab Vedotin", "prescription", "IV", "Hodgkin lymphoma, anaplastic large cell lymphoma", "Peripheral neuropathy, neutropenia.", "PML risk; report neurologic symptoms."),
    ("brexanolone", "Brexanolone", "prescription", "IV infusion", "Postpartum depression", "Sedation, dizziness.", "Continuous monitoring during 60-hour infusion."),
    ("brimonidine", "Brimonidine", "prescription", "Eye drops", "Glaucoma", "Eye irritation, dry mouth, fatigue.", "Avoid in children under 2 years."),
    ("bupropion", "Bupropion", "prescription", "Oral", "Depression, smoking cessation, seasonal affective disorder", "Insomnia, headache, lowered seizure threshold.", "Avoid in patients with seizure disorders or eating disorders."),
    ("buspirone", "Buspirone", "prescription", "Oral", "Generalized anxiety disorder", "Dizziness, nausea, headache.", "Slow onset; not for acute anxiety."),
    ("cabergoline", "Cabergoline", "prescription", "Oral", "Hyperprolactinemia, Parkinson's disease", "Nausea, headache, valvulopathy.", "Echocardiogram monitoring for long-term use."),
    ("calcipotriene", "Calcipotriene", "prescription", "Topical", "Plaque psoriasis", "Skin irritation, photosensitivity.", "Avoid use on face."),
    ("carbamazepine", "Carbamazepine", "prescription", "Oral", "Seizures, trigeminal neuralgia, bipolar disorder", "Diplopia, ataxia, blood dyscrasias, rash.", "HLA-B*1502 screening in Asian patients; CBC monitoring."),
    ("carbidopa-levodopa", "Carbidopa-Levodopa", "prescription", "Oral", "Parkinson's disease", "Dyskinesia, nausea, orthostatic hypotension.", "Avoid abrupt discontinuation."),
    ("carboplatin", "Carboplatin", "prescription", "IV", "Ovarian, lung, head and neck, breast cancers", "Myelosuppression, neuropathy, nausea.", "Dose by renal function and target AUC."),
    ("cefepime", "Cefepime", "prescription", "IV / IM", "Pneumonia, neutropenic fever, complicated UTI", "Diarrhea, encephalopathy in renal failure.", "Adjust dose in kidney impairment."),
    ("ceftriaxone", "Ceftriaxone", "prescription", "IV / IM", "Pneumonia, meningitis, gonorrhea, sepsis", "Diarrhea, rash, biliary sludging.", "Avoid with calcium in neonates."),
    ("celecoxib", "Celecoxib", "prescription", "Oral", "Osteoarthritis, rheumatoid arthritis", "GI bleeding (lower risk than nsNSAIDs), cardiovascular events.", "Use lowest effective dose for shortest duration."),
    ("cephalexin", "Cephalexin", "prescription", "Oral", "Skin and soft tissue infection, UTI", "Diarrhea, rash.", "Penicillin allergy: caution but usually tolerated."),
    ("cetirizine", "Cetirizine", "otc", "Oral", "Allergic rhinitis, hives", "Drowsiness, dry mouth.", "Less sedating than first-generation antihistamines."),
    ("ciprofloxacin", "Ciprofloxacin", "prescription", "Oral / IV", "Complicated UTI, GI infection, anthrax", "Tendinopathy, QT prolongation, C. difficile.", "Black box warning: tendon rupture, neuropathy."),
    ("ciprofloxacin-drops", "Ciprofloxacin Eye Drops", "prescription", "Eye drops", "Bacterial conjunctivitis, corneal ulcer", "Eye irritation, taste change.", "Complete the full course."),
    ("cisplatin", "Cisplatin", "prescription", "IV", "Testicular, ovarian, bladder, lung, head and neck cancers", "Nephrotoxicity, ototoxicity, neuropathy, nausea.", "Aggressive hydration with each dose."),
    ("clarithromycin", "Clarithromycin", "prescription", "Oral", "Pneumonia, H. pylori, pertussis", "GI upset, taste alteration, QT prolongation.", "Many drug-drug interactions."),
    ("clindamycin", "Clindamycin", "prescription", "Oral / IV / Topical", "Skin and soft tissue infection, dental infection, bacterial vaginosis", "Diarrhea (C. difficile risk), rash.", "Higher risk of C. difficile colitis."),
    ("clomipramine", "Clomipramine", "prescription", "Oral", "Obsessive-compulsive disorder", "Anticholinergic effects, weight gain.", "Toxic in overdose; monitor for cardiac effects."),
    ("clopidogrel", "Clopidogrel", "prescription", "Oral", "Acute coronary syndrome, stent thrombosis prevention, stroke prevention", "Bleeding, bruising, rare thrombotic microangiopathy.", "Avoid with strong CYP2C19 inhibitors."),
    ("clotrimazole", "Clotrimazole", "otc", "Topical / Vaginal", "Yeast infection, tinea", "Local irritation.", "Consult clinician if symptoms persist."),
    ("clozapine", "Clozapine", "prescription", "Oral", "Treatment-resistant schizophrenia", "Agranulocytosis, myocarditis, sedation, weight gain.", "Mandatory CBC monitoring program."),
    ("colchicine", "Colchicine", "prescription", "Oral", "Acute gout, familial Mediterranean fever, pericarditis", "Diarrhea, myopathy, marrow suppression.", "Significant drug interactions; renal/hepatic dose adjustment."),
    ("crizanlizumab", "Crizanlizumab", "prescription", "IV", "Sickle cell disease pain crises", "Joint pain, nausea, back pain.", "Infusion reactions; monitor closely."),
    ("cyclophosphamide", "Cyclophosphamide", "prescription", "Oral / IV", "Lymphoma, breast cancer, lupus nephritis, vasculitis", "Cytopenias, hemorrhagic cystitis, infertility.", "Aggressive hydration; mesna for high doses."),
    ("cyclobenzaprine", "Cyclobenzaprine", "prescription", "Oral", "Muscle spasms", "Drowsiness, dry mouth, dizziness.", "Avoid in elderly per Beers criteria."),
    ("cyclosporine", "Cyclosporine", "prescription", "Oral / IV", "Transplant rejection, autoimmune disease", "Nephrotoxicity, hypertension, hirsutism.", "Monitor drug levels and renal function."),
    ("cyclosporine-drops", "Cyclosporine Eye Drops", "prescription", "Eye drops", "Chronic dry eye", "Eye burning, redness.", "Effects may take weeks to develop."),
    ("cyanocobalamin", "Cyanocobalamin (Vitamin B12)", "supplement", "Oral / IM", "Vitamin B12 deficiency, pernicious anemia", "Rare allergic reactions.", "IM route for severe deficiency or malabsorption."),
    ("cytarabine", "Cytarabine", "prescription", "IV / Intrathecal", "Acute myeloid leukemia, lymphoma", "Myelosuppression, neurotoxicity at high doses.", "Steroid eye drops with high-dose regimens."),
    ("dabrafenib", "Dabrafenib", "prescription", "Oral", "BRAF V600-mutated melanoma", "Fever, rash, joint pain, hyperglycemia.", "Confirm BRAF mutation before use."),
    ("daunorubicin", "Daunorubicin", "prescription", "IV", "Acute leukemias", "Cardiotoxicity, myelosuppression.", "Cumulative dose limits; cardiac monitoring."),
    ("daratumumab", "Daratumumab", "prescription", "IV / SubQ", "Multiple myeloma, amyloidosis", "Infusion reaction, infection.", "Premedication required for first infusions."),
    ("deflazacort", "Deflazacort", "prescription", "Oral", "Duchenne muscular dystrophy", "Weight gain, hyperglycemia, growth suppression.", "Long-term corticosteroid monitoring."),
    ("denosumab", "Denosumab", "prescription", "SubQ", "Osteoporosis, bone metastases", "Hypocalcemia, osteonecrosis of jaw, atypical fractures.", "Dental exam before initiation; do not stop without alternative."),
    ("desmopressin", "Desmopressin", "prescription", "Oral / Intranasal", "Diabetes insipidus, nocturnal enuresis, von Willebrand disease", "Hyponatremia, headache.", "Monitor sodium with chronic use."),
    ("dexamethasone", "Dexamethasone", "prescription", "Oral / IV", "Cerebral edema, multiple myeloma, COVID-19, autoimmune disease", "Hyperglycemia, weight gain, mood changes, infection risk.", "Long-term use requires monitoring; taper to discontinue."),
    ("deutetrabenazine", "Deutetrabenazine", "prescription", "Oral", "Huntington chorea, tardive dyskinesia", "Drowsiness, depression, insomnia.", "Monitor for suicidality."),
    ("diazepam", "Diazepam", "prescription", "Oral / IV / Rectal", "Anxiety, seizures, muscle spasm, alcohol withdrawal", "Sedation, dependence.", "Avoid abrupt discontinuation."),
    ("dicyclomine", "Dicyclomine", "prescription", "Oral", "Irritable bowel syndrome", "Dry mouth, blurred vision, constipation.", "Avoid in elderly; anticholinergic burden."),
    ("diphtheria-antitoxin", "Diphtheria Antitoxin", "prescription", "IV / IM", "Diphtheria treatment", "Serum sickness, hypersensitivity.", "Test dose before full administration."),
    ("diphenhydramine", "Diphenhydramine", "otc", "Oral / IV / IM", "Allergic reactions, insomnia, motion sickness", "Sedation, anticholinergic effects.", "Avoid in elderly; daytime drowsiness."),
    ("diltiazem", "Diltiazem", "prescription", "Oral / IV", "Atrial fibrillation rate control, hypertension, angina", "Edema, bradycardia, constipation.", "Avoid in systolic heart failure with reduced EF."),
    ("docusate", "Docusate", "otc", "Oral", "Constipation prevention", "Mild GI upset.", "Stool softener; not effective alone for constipation."),
    ("docusate-drops", "Docusate Ear Drops", "otc", "Ear drops", "Cerumen impaction", "Local irritation.", "Stop if pain or drainage."),
    ("dolutegravir", "Dolutegravir", "prescription", "Oral", "HIV infection", "Headache, insomnia, weight gain.", "Monitor for neuropsychiatric symptoms."),
    ("donepezil", "Donepezil", "prescription", "Oral", "Alzheimer's disease", "Nausea, diarrhea, vivid dreams, bradycardia.", "Cholinergic effects; titrate slowly."),
    ("dornase-alfa", "Dornase Alfa", "prescription", "Inhaled", "Cystic fibrosis", "Pharyngitis, voice change.", "Use with nebulizer; refrigerate."),
    ("doxorubicin", "Doxorubicin", "prescription", "IV", "Many solid tumors and hematologic malignancies", "Cardiotoxicity, myelosuppression, alopecia.", "Cumulative dose limit; cardiac monitoring."),
    ("doxycycline", "Doxycycline", "prescription", "Oral / IV", "Lyme disease, pneumonia, acne, malaria prophylaxis", "Photosensitivity, esophagitis.", "Avoid in pregnancy and children under 8."),
    ("dupilumab", "Dupilumab", "prescription", "SubQ", "Atopic dermatitis, asthma, eosinophilic esophagitis", "Conjunctivitis, injection site reaction.", "Monitor for eosinophilia."),
    ("dutasteride", "Dutasteride", "prescription", "Oral", "Benign prostatic hyperplasia", "Decreased libido, gynecomastia.", "Affects PSA interpretation."),
    ("edaravone", "Edaravone", "prescription", "IV / Oral", "Amyotrophic lateral sclerosis", "Bruising, gait disturbance.", "Cyclic dosing schedule."),
    ("eltrombopag", "Eltrombopag", "prescription", "Oral", "Immune thrombocytopenia, aplastic anemia", "Hepatotoxicity, cataracts, thrombosis.", "Avoid with calcium-rich foods at dosing."),
    ("empagliflozin", "Empagliflozin", "prescription", "Oral", "Type 2 diabetes, heart failure, chronic kidney disease", "Genital infections, hypovolemia, ketoacidosis.", "SGLT2 inhibitor class."),
    ("emtricitabine", "Emtricitabine", "prescription", "Oral", "HIV infection, PrEP", "Nausea, headache, hyperpigmentation.", "Confirm negative HIV before PrEP."),
    ("entecavir", "Entecavir", "prescription", "Oral", "Chronic hepatitis B", "Headache, fatigue, lactic acidosis (rare).", "Take on empty stomach."),
    ("enzalutamide", "Enzalutamide", "prescription", "Oral", "Prostate cancer", "Fatigue, hot flashes, seizures.", "Caution in patients with seizure history."),
    ("epinephrine", "Epinephrine Auto-injector", "prescription", "Intramuscular", "Anaphylaxis", "Tachycardia, anxiety, tremor.", "First-line treatment; carry two devices."),
    ("epoetin", "Epoetin Alfa", "prescription", "SubQ / IV", "Anemia of chronic kidney disease, chemotherapy-induced anemia", "Hypertension, thrombosis, pure red cell aplasia.", "Target hemoglobin 10-11; do not exceed."),
    ("erenumab", "Erenumab", "prescription", "SubQ", "Migraine prevention", "Injection site reaction, constipation.", "Monthly administration."),
    ("erythromycin", "Erythromycin", "prescription", "Oral / IV", "Pertussis, gastroparesis prokinetic", "GI upset, QT prolongation.", "Many drug interactions."),
    ("erythromycin-ointment", "Erythromycin Ophthalmic Ointment", "prescription", "Ointment", "Bacterial conjunctivitis, neonatal prophylaxis", "Eye irritation.", "Brief blurring after instillation."),
    ("escitalopram", "Escitalopram", "prescription", "Oral", "Depression, generalized anxiety disorder", "Nausea, insomnia, sexual dysfunction.", "Boxed warning: suicidality in young adults."),
    ("esomeprazole", "Esomeprazole", "prescription", "Oral / IV", "Acid reflux, peptic ulcer", "Headache, diarrhea, hypomagnesemia with long use.", "Re-evaluate need for long-term PPI use."),
    ("estradiol", "Estradiol", "prescription", "Oral / Transdermal / Vaginal", "Menopausal symptoms, hormone replacement", "Headache, breast tenderness, thromboembolism risk.", "Use lowest effective dose; not for osteoporosis-only indication."),
    ("estradiol-cream", "Estradiol Vaginal Cream", "prescription", "Topical vaginal", "Atrophic vaginitis", "Local irritation.", "Lowest systemic exposure of estrogen products."),
    ("etanercept", "Etanercept", "prescription", "SubQ", "Rheumatoid arthritis, psoriasis, ankylosing spondylitis", "Infection, injection site reaction.", "Screen for TB and hepatitis B."),
    ("eteplirsen", "Eteplirsen", "prescription", "IV", "Duchenne muscular dystrophy with exon 51 deletion", "Balance disorder, vomiting.", "Confirm dystrophin gene mutation."),
    ("ethambutol", "Ethambutol", "prescription", "Oral", "Tuberculosis", "Optic neuritis, peripheral neuropathy.", "Monitor color vision and visual acuity."),
    ("etoposide", "Etoposide", "prescription", "Oral / IV", "Lung, testicular, lymphoma", "Myelosuppression, hypotension.", "Risk of secondary leukemia."),
    ("famotidine", "Famotidine", "otc", "Oral / IV", "Acid reflux, peptic ulcer", "Headache, constipation.", "Adjust dose in renal impairment."),
    ("febuxostat", "Febuxostat", "prescription", "Oral", "Gout", "Liver enzyme elevation, cardiovascular events.", "Boxed warning: cardiovascular death risk."),
    ("ferrous-sulfate", "Ferrous Sulfate", "otc", "Oral", "Iron deficiency anemia", "Constipation, dark stools, nausea.", "Take with vitamin C; avoid with calcium."),
    ("finasteride", "Finasteride", "prescription", "Oral", "BPH, male pattern hair loss", "Decreased libido, gynecomastia.", "Pregnancy category X; avoid handling crushed tablets."),
    ("fluconazole", "Fluconazole", "prescription", "Oral / IV", "Candidiasis, cryptococcal meningitis", "Headache, nausea, hepatotoxicity.", "Many CYP interactions."),
    ("fludrocortisone", "Fludrocortisone", "prescription", "Oral", "Addison's disease, orthostatic hypotension", "Edema, hypertension, hypokalemia.", "Monitor blood pressure and potassium."),
    ("fluorouracil", "Fluorouracil", "prescription", "IV / Topical", "Colorectal, breast, head and neck cancers; skin precancer", "Mucositis, diarrhea, myelosuppression.", "DPD deficiency: increased toxicity risk."),
    ("fluoxetine", "Fluoxetine", "prescription", "Oral", "Depression, OCD, bulimia, premenstrual dysphoric disorder", "Nausea, insomnia, sexual dysfunction.", "Long half-life; suicidality warning in youth."),
    ("fluticasone", "Fluticasone", "prescription", "Inhaled / Nasal", "Asthma, allergic rhinitis", "Oral candidiasis (rinse mouth), hoarseness.", "Rinse mouth after inhalation."),
    ("fluvoxamine", "Fluvoxamine", "prescription", "Oral", "Obsessive-compulsive disorder", "Nausea, somnolence, sexual dysfunction.", "Many drug interactions via CYP."),
    ("folic-acid", "Folic Acid", "supplement", "Oral", "Folate deficiency, pregnancy prevention of neural tube defects", "Generally well tolerated.", "All women of reproductive age should consider supplementation."),
    ("furosemide", "Furosemide", "prescription", "Oral / IV", "Heart failure, edema, hypertension", "Hypokalemia, dehydration, hearing loss with rapid IV.", "Monitor electrolytes and renal function."),
    ("gabapentin", "Gabapentin", "prescription", "Oral", "Neuropathic pain, postherpetic neuralgia, partial seizures", "Sedation, dizziness, edema.", "Renal dose adjustment."),
    ("gemcitabine", "Gemcitabine", "prescription", "IV", "Pancreatic, lung, bladder, breast, ovarian cancers", "Myelosuppression, flu-like symptoms.", "Monitor blood counts."),
    ("glecaprevir-pibrentasvir", "Glecaprevir-Pibrentasvir", "prescription", "Oral", "Chronic hepatitis C", "Headache, fatigue.", "Pan-genotypic; 8-week course for treatment-naive."),
    ("glucagon", "Glucagon", "prescription", "Injection / Nasal", "Severe hypoglycemia", "Nausea, vomiting.", "Emergency rescue therapy."),
    ("guaifenesin", "Guaifenesin", "otc", "Oral", "Cough with congestion", "Mild GI upset.", "Drink fluids to support mucus thinning."),
    ("haloperidol", "Haloperidol", "prescription", "Oral / IM / IV", "Acute psychosis, delirium", "Extrapyramidal symptoms, QT prolongation.", "Monitor for tardive dyskinesia with chronic use."),
    ("heparin", "Heparin", "prescription", "IV / SubQ", "DVT, PE, acute coronary syndrome", "Bleeding, heparin-induced thrombocytopenia.", "Monitor aPTT and platelets."),
    ("hydrochlorothiazide", "Hydrochlorothiazide", "prescription", "Oral", "Hypertension, edema", "Hypokalemia, hyponatremia, hyperuricemia.", "Photosensitivity reported."),
    ("hydrocortisone", "Hydrocortisone", "prescription", "Oral / IV / Topical", "Adrenal insufficiency, autoimmune disease, skin inflammation", "Hyperglycemia, hypertension, infection risk.", "Stress dosing during illness for adrenal insufficiency."),
    ("hydrocortisone-cream", "Hydrocortisone Cream", "otc", "Topical", "Mild eczema, hemorrhoid itching", "Skin atrophy with prolonged use.", "Avoid prolonged use on face."),
    ("hydromorphone", "Hydromorphone", "prescription", "Oral / IV", "Severe pain, palliative care", "Sedation, respiratory depression, constipation.", "Opioid; risk of dependence."),
    ("hydroxychloroquine", "Hydroxychloroquine", "prescription", "Oral", "Lupus, rheumatoid arthritis, malaria", "Retinal toxicity, GI upset, cardiomyopathy.", "Annual eye examination."),
    ("hydroxyurea", "Hydroxyurea", "prescription", "Oral", "Sickle cell disease, CML, polycythemia vera", "Myelosuppression, skin ulcers.", "Avoid in pregnancy; monitor blood counts."),
    ("ibrutinib", "Ibrutinib", "prescription", "Oral", "Chronic lymphocytic leukemia, mantle cell lymphoma, Waldenström", "Atrial fibrillation, bleeding, hypertension.", "Hold around procedures."),
    ("ibuprofen", "Ibuprofen", "otc", "Oral", "Pain, fever, inflammation", "GI bleeding, kidney injury, cardiovascular events.", "Use lowest effective dose; avoid in kidney disease."),
    ("imatinib", "Imatinib", "prescription", "Oral", "Chronic myeloid leukemia, GIST", "Edema, nausea, myalgia.", "Take with food."),
    ("imipramine", "Imipramine", "prescription", "Oral", "Depression, enuresis", "Anticholinergic effects, arrhythmia.", "Toxic in overdose."),
    ("imiquimod", "Imiquimod", "prescription", "Topical", "Genital warts, actinic keratosis, superficial basal cell carcinoma", "Skin irritation, flu-like symptoms.", "Avoid healthy skin around treatment area."),
    ("infliximab", "Infliximab", "prescription", "IV", "Crohn's, ulcerative colitis, rheumatoid arthritis, psoriasis", "Infusion reaction, infection.", "Screen for TB and hepatitis B."),
    ("insulin", "Insulin", "prescription", "SubQ / IV / Pump", "Type 1 and type 2 diabetes", "Hypoglycemia, weight gain, injection site reactions.", "Many formulations; basal-bolus strategy in T1D."),
    ("interferon-beta", "Interferon Beta", "prescription", "SubQ / IM", "Relapsing multiple sclerosis", "Flu-like symptoms, depression, liver enzyme elevation.", "Monitor mood and liver function."),
    ("ivermectin-cream", "Ivermectin Cream", "prescription", "Topical", "Inflammatory rosacea", "Skin irritation.", "Avoid contact with eyes."),
    ("iron", "Iron Supplement", "otc", "Oral / IV", "Iron deficiency anemia", "Constipation, GI upset, dark stools.", "IV iron for malabsorption or intolerance."),
    ("isoniazid", "Isoniazid", "prescription", "Oral", "Tuberculosis", "Hepatotoxicity, neuropathy.", "Coadminister pyridoxine; monitor liver enzymes."),
    ("isotretinoin", "Isotretinoin", "prescription", "Oral", "Severe acne", "Dry skin, hyperlipidemia, teratogenic.", "Strict pregnancy prevention program required."),
    ("ivacaftor", "Ivacaftor", "prescription", "Oral", "Cystic fibrosis with gating mutations", "Headache, upper respiratory symptoms.", "Take with fat-containing food."),
    ("ketoconazole", "Ketoconazole", "prescription", "Oral / Topical", "Cushing syndrome, severe fungal infections, dandruff", "Hepatotoxicity, adrenal suppression.", "Oral form restricted due to liver risk."),
    ("lactase", "Lactase", "supplement", "Oral", "Lactose intolerance", "Generally well tolerated.", "Take with dairy-containing meals."),
    ("lactulose", "Lactulose", "prescription", "Oral", "Hepatic encephalopathy, constipation", "Bloating, diarrhea.", "Titrate to 2-3 soft stools per day in encephalopathy."),
    ("lamotrigine", "Lamotrigine", "prescription", "Oral", "Epilepsy, bipolar disorder", "Rash (Stevens-Johnson syndrome), dizziness.", "Slow titration to reduce rash risk."),
    ("lanreotide", "Lanreotide", "prescription", "SubQ", "Acromegaly, neuroendocrine tumors", "Diarrhea, gallstones.", "Long-acting; monthly administration."),
    ("latanoprost", "Latanoprost", "prescription", "Eye drops", "Open-angle glaucoma", "Iris pigmentation, eyelash growth, eye redness.", "Once daily at bedtime."),
    ("lecanemab", "Lecanemab", "prescription", "IV", "Early Alzheimer's disease", "Infusion reaction, ARIA (brain edema/microhemorrhage).", "MRI monitoring required."),
    ("ledipasvir", "Ledipasvir", "prescription", "Oral", "Chronic hepatitis C genotype 1", "Headache, fatigue.", "Used with sofosbuvir."),
    ("lenalidomide", "Lenalidomide", "prescription", "Oral", "Multiple myeloma, myelodysplastic syndromes", "Thrombocytopenia, neutropenia, teratogenic.", "REMS program required."),
    ("lenvatinib", "Lenvatinib", "prescription", "Oral", "Thyroid, hepatocellular, renal cell cancers", "Hypertension, diarrhea, hand-foot syndrome.", "Manage blood pressure aggressively."),
    ("leuprolide", "Leuprolide", "prescription", "IM / SubQ", "Prostate cancer, endometriosis, central precocious puberty", "Hot flashes, decreased bone density.", "Initial tumor flare; consider androgen blocker overlap."),
    ("levetiracetam", "Levetiracetam", "prescription", "Oral / IV", "Partial and generalized seizures", "Drowsiness, mood changes, weakness.", "Renal dose adjustment."),
    ("levothyroxine", "Levothyroxine", "prescription", "Oral", "Hypothyroidism", "Symptoms of hyperthyroidism if dosed high.", "Take on empty stomach; consistent timing."),
    ("linaclotide", "Linaclotide", "prescription", "Oral", "Constipation predominant IBS, chronic idiopathic constipation", "Diarrhea, abdominal pain.", "Avoid in children under 6."),
    ("lisinopril", "Lisinopril", "prescription", "Oral", "Hypertension, heart failure, post-MI, diabetic nephropathy", "Cough, hyperkalemia, angioedema.", "Avoid in pregnancy; monitor renal function and potassium."),
    ("lithium", "Lithium", "prescription", "Oral", "Bipolar disorder, treatment-resistant depression adjunct", "Tremor, polyuria, hypothyroidism, nephrotoxicity.", "Narrow therapeutic window; monitor levels."),
    ("loperamide", "Loperamide", "otc", "Oral", "Acute diarrhea", "Constipation, abdominal pain.", "High doses cause cardiac arrhythmia."),
    ("loratadine", "Loratadine", "otc", "Oral", "Allergic rhinitis, hives", "Dry mouth, headache.", "Non-sedating second-generation antihistamine."),
    ("losartan", "Losartan", "prescription", "Oral", "Hypertension, diabetic nephropathy, heart failure", "Hyperkalemia, dizziness, decreased renal function.", "Avoid in pregnancy."),
    ("macitentan", "Macitentan", "prescription", "Oral", "Pulmonary arterial hypertension", "Anemia, headache.", "Pregnancy testing required for women."),
    ("meclizine", "Meclizine", "otc", "Oral", "Motion sickness, vertigo", "Drowsiness, dry mouth.", "Use with caution in elderly."),
    ("memantine", "Memantine", "prescription", "Oral", "Moderate to severe Alzheimer's disease", "Dizziness, headache, confusion.", "Slow titration."),
    ("meperidine", "Meperidine", "prescription", "Oral / IM / IV", "Acute pain", "Sedation, seizures (with normeperidine accumulation).", "Avoid prolonged use and renal impairment."),
    ("mesalamine", "Mesalamine", "prescription", "Oral / Rectal", "Ulcerative colitis, Crohn's disease", "Headache, abdominal pain, pancreatitis.", "Renal monitoring with long-term use."),
    ("metformin", "Metformin", "prescription", "Oral", "Type 2 diabetes, polycystic ovary syndrome", "GI upset, vitamin B12 deficiency, rare lactic acidosis.", "Hold for contrast studies; renal function check."),
    ("methimazole", "Methimazole", "prescription", "Oral", "Hyperthyroidism, Graves' disease", "Rash, agranulocytosis (rare), hepatotoxicity.", "Stop and seek care if fever or sore throat."),
    ("methotrexate", "Methotrexate", "prescription", "Oral / SubQ / IM", "Rheumatoid arthritis, psoriasis, ectopic pregnancy, leukemia", "Hepatotoxicity, pneumonitis, myelosuppression.", "Weekly dosing for autoimmune; coadminister folic acid."),
    ("methylphenidate", "Methylphenidate", "prescription", "Oral / Transdermal", "ADHD, narcolepsy", "Decreased appetite, insomnia, elevated heart rate.", "Controlled substance; monitor growth in children."),
    ("metoprolol", "Metoprolol", "prescription", "Oral / IV", "Hypertension, heart failure, post-MI, angina", "Fatigue, bradycardia, bronchospasm.", "Do not stop abruptly."),
    ("metronidazole", "Metronidazole", "prescription", "Oral / IV / Topical", "Anaerobic infections, C. difficile (mild), bacterial vaginosis", "Metallic taste, peripheral neuropathy.", "Avoid alcohol during and 48 hours after."),
    ("metronidazole-cream", "Metronidazole Cream", "prescription", "Topical", "Rosacea", "Mild skin irritation.", "Apply twice daily."),
    ("metyrapone", "Metyrapone", "prescription", "Oral", "Cushing syndrome", "Adrenal insufficiency, hirsutism, hypertension.", "Monitor cortisol levels."),
    ("mifepristone", "Mifepristone", "prescription", "Oral", "Cushing syndrome (hyperglycemia), early pregnancy termination", "Adrenal insufficiency, GI upset.", "Different dosing for different indications."),
    ("miconazole", "Miconazole", "otc", "Topical / Vaginal", "Vaginal yeast infection, tinea", "Local irritation.", "Available without prescription."),
    ("minoxidil", "Minoxidil", "otc", "Topical / Oral", "Androgenetic alopecia, severe hypertension", "Scalp irritation, hypertrichosis, fluid retention.", "Topical OTC; oral form for resistant hypertension."),
    ("mirabegron", "Mirabegron", "prescription", "Oral", "Overactive bladder", "Hypertension, headache, urinary retention.", "Monitor blood pressure."),
    ("mitomycin", "Mitomycin", "prescription", "IV / Topical", "Anal, bladder, GI cancers", "Myelosuppression, hemolytic uremic syndrome.", "Cumulative dose limits."),
    ("mitotane", "Mitotane", "prescription", "Oral", "Adrenocortical carcinoma", "Adrenal insufficiency, GI upset, neurotoxicity.", "Steroid replacement during therapy."),
    ("montelukast", "Montelukast", "prescription", "Oral", "Asthma, allergic rhinitis", "Headache, mood changes, suicidality.", "Boxed warning for neuropsychiatric events."),
    ("nab-paclitaxel", "Nab-paclitaxel", "prescription", "IV", "Pancreatic, breast, lung cancer", "Neuropathy, myelosuppression, alopecia.", "No premedication required."),
    ("naproxen", "Naproxen", "otc", "Oral", "Pain, inflammation, fever", "GI bleeding, kidney injury, cardiovascular events.", "Use lowest effective dose."),
    ("natalizumab", "Natalizumab", "prescription", "IV", "Multiple sclerosis, Crohn's disease", "Progressive multifocal leukoencephalopathy (PML).", "TOUCH program; JC virus monitoring."),
    ("nifedipine-ointment", "Nifedipine Ointment", "prescription", "Topical", "Anal fissure", "Headache, local irritation.", "Compounded preparation."),
    ("nimodipine", "Nimodipine", "prescription", "Oral", "Subarachnoid hemorrhage", "Hypotension, headache.", "Reduces cerebral vasospasm."),
    ("nintedanib", "Nintedanib", "prescription", "Oral", "Idiopathic pulmonary fibrosis, scleroderma ILD", "Diarrhea, hepatotoxicity, bleeding.", "Monitor liver enzymes."),
    ("nitrofurantoin", "Nitrofurantoin", "prescription", "Oral", "Uncomplicated UTI", "Nausea, pulmonary toxicity with long use.", "Avoid in renal impairment."),
    ("nitroglycerin", "Nitroglycerin", "prescription", "Sublingual / Topical / IV", "Angina, acute heart failure", "Headache, hypotension.", "Avoid with PDE5 inhibitors."),
    ("nitroglycerin-ointment", "Nitroglycerin Ointment", "prescription", "Topical", "Chronic anal fissure", "Headache.", "Apply to anal verge."),
    ("nivolumab", "Nivolumab", "prescription", "IV", "Melanoma, lung, kidney, lymphoma", "Immune-related adverse events.", "Watch for colitis, pneumonitis, endocrinopathy."),
    ("norethindrone", "Norethindrone", "prescription", "Oral", "Endometriosis, contraception, abnormal bleeding", "Breakthrough bleeding, headache.", "Progestin-only options."),
    ("norepinephrine", "Norepinephrine", "prescription", "IV", "Shock, hypotension", "Arrhythmia, hypertension if titrated high.", "Central venous administration preferred."),
    ("nystatin", "Nystatin", "prescription", "Topical / Oral suspension", "Candidiasis", "Local irritation, GI upset.", "Not systemically absorbed."),
    ("ocrelizumab", "Ocrelizumab", "prescription", "IV", "Relapsing and primary progressive MS", "Infusion reaction, infection, hepatitis B reactivation.", "Screen for hepatitis B."),
    ("octreotide", "Octreotide", "prescription", "SubQ / IV", "Acromegaly, neuroendocrine tumors, variceal bleeding", "Diarrhea, gallstones.", "Long-acting depot for monthly dosing."),
    ("olanzapine", "Olanzapine", "prescription", "Oral / IM", "Schizophrenia, bipolar disorder", "Weight gain, hyperglycemia, sedation.", "Metabolic monitoring required."),
    ("olaparib", "Olaparib", "prescription", "Oral", "Ovarian, breast, prostate, pancreatic cancers with BRCA mutation", "Anemia, fatigue, nausea.", "Confirm BRCA mutation."),
    ("omeprazole", "Omeprazole", "otc", "Oral", "Acid reflux, peptic ulcer", "Headache, diarrhea, hypomagnesemia with chronic use.", "Re-evaluate need beyond 8 weeks."),
    ("ondansetron", "Ondansetron", "prescription", "Oral / IV / IM", "Nausea, vomiting", "Constipation, QT prolongation.", "ECG check in patients with risk factors."),
    ("oral-contraceptives", "Oral Contraceptives", "prescription", "Oral", "Contraception, menstrual regulation, acne, PCOS", "Thromboembolism, hypertension, breakthrough bleeding.", "Smokers over 35 at increased risk."),
    ("oral-rehydration-solution", "Oral Rehydration Solution", "otc", "Oral", "Dehydration from diarrhea", "Generally well tolerated.", "First-line for mild-to-moderate dehydration."),
    ("oseltamivir", "Oseltamivir", "prescription", "Oral", "Influenza A and B", "Nausea, headache, behavioral changes (rare in children).", "Start within 48 hours of symptom onset."),
    ("osimertinib", "Osimertinib", "prescription", "Oral", "EGFR-mutated non-small cell lung cancer", "Diarrhea, rash, cardiomyopathy.", "Confirm EGFR mutation."),
    ("ospemifene", "Ospemifene", "prescription", "Oral", "Vulvovaginal atrophy", "Hot flashes, thromboembolism.", "Selective estrogen receptor modulator."),
    ("oxaliplatin", "Oxaliplatin", "prescription", "IV", "Colorectal cancer", "Neuropathy (cold-induced), nausea.", "Avoid cold during and after infusion."),
    ("oxybutynin", "Oxybutynin", "prescription", "Oral / Transdermal", "Overactive bladder", "Dry mouth, constipation, confusion.", "Anticholinergic burden in elderly."),
    ("paclitaxel", "Paclitaxel", "prescription", "IV", "Breast, ovarian, lung cancers", "Neuropathy, hypersensitivity, alopecia.", "Premedication for hypersensitivity."),
    ("pantoprazole", "Pantoprazole", "prescription", "Oral / IV", "Acid reflux, peptic ulcer, ZE syndrome", "Headache, diarrhea.", "Long-term effects similar to other PPIs."),
    ("paroxetine", "Paroxetine", "prescription", "Oral", "Depression, anxiety, PTSD, menopausal hot flashes", "Sexual dysfunction, weight gain, discontinuation syndrome.", "Avoid in pregnancy due to cardiac defects risk."),
    ("pegvisomant", "Pegvisomant", "prescription", "SubQ", "Acromegaly", "Liver enzyme elevation, injection site reactions.", "Monitor LFTs and IGF-1."),
    ("pembrolizumab", "Pembrolizumab", "prescription", "IV", "Melanoma, lung, head and neck, many solid tumors", "Immune-related adverse events.", "Watch for colitis, hepatitis, endocrinopathy."),
    ("penicillamine", "Penicillamine", "prescription", "Oral", "Wilson's disease, rheumatoid arthritis", "Rash, proteinuria, marrow suppression.", "Pyridoxine supplementation."),
    ("penicillin", "Penicillin", "prescription", "Oral / IM / IV", "Strep throat, syphilis, rheumatic fever prevention", "Hypersensitivity reactions, GI upset.", "Confirm true allergy vs intolerance."),
    ("pentoxifylline", "Pentoxifylline", "prescription", "Oral", "Intermittent claudication, alcoholic hepatitis", "GI upset, dizziness.", "Modest benefit; not first-line."),
    ("pilocarpine", "Pilocarpine", "prescription", "Oral / Eye drops", "Glaucoma, dry mouth", "Sweating, miosis, GI upset.", "Cholinergic effects."),
    ("piperacillin-tazobactam", "Piperacillin-Tazobactam", "prescription", "IV", "Severe infections including sepsis, intra-abdominal, pneumonia", "Diarrhea, rash, hypokalemia.", "Broad-spectrum; reserve for serious infections."),
    ("polyethylene-glycol", "Polyethylene Glycol", "otc", "Oral", "Chronic constipation, bowel prep", "Bloating, diarrhea.", "Mix with 8 oz fluid."),
    ("potassium-citrate", "Potassium Citrate", "prescription", "Oral", "Kidney stone prevention", "GI upset, hyperkalemia in kidney disease.", "Adjust for renal function."),
    ("pramipexole", "Pramipexole", "prescription", "Oral", "Parkinson's disease, restless legs syndrome", "Somnolence, impulse control disorders, hallucinations.", "Counsel about gambling and other impulse behaviors."),
    ("prednisolone", "Prednisolone", "prescription", "Oral", "Alcoholic hepatitis, autoimmune flare", "Hyperglycemia, hypertension, mood changes.", "Taper with longer courses."),
    ("prednisone", "Prednisone", "prescription", "Oral", "Asthma exacerbation, autoimmune disease, inflammatory bowel disease, allergic reaction", "Weight gain, hyperglycemia, mood changes, osteoporosis.", "Taper if used more than 2 weeks."),
    ("pregabalin", "Pregabalin", "prescription", "Oral", "Neuropathic pain, fibromyalgia, partial seizures", "Sedation, dizziness, edema.", "Renal dose adjustment."),
    ("primidone", "Primidone", "prescription", "Oral", "Essential tremor, seizures", "Sedation, ataxia.", "Slow titration to reduce side effects."),
    ("progesterone", "Progesterone", "prescription", "Oral / Vaginal / IM", "Hormone replacement, amenorrhea, pregnancy support", "Drowsiness, breast tenderness.", "Various formulations and uses."),
    ("propranolol", "Propranolol", "prescription", "Oral / IV", "Migraine prevention, essential tremor, hypertension, hyperthyroid symptoms", "Bradycardia, fatigue, bronchospasm.", "Avoid in asthma."),
    ("propylthiouracil", "Propylthiouracil", "prescription", "Oral", "Hyperthyroidism in pregnancy first trimester", "Hepatotoxicity, agranulocytosis.", "First trimester preferred over methimazole."),
    ("pseudoephedrine", "Pseudoephedrine", "otc", "Oral", "Nasal congestion", "Insomnia, hypertension, palpitations.", "Sold from behind the counter due to misuse."),
    ("pyridostigmine", "Pyridostigmine", "prescription", "Oral", "Myasthenia gravis", "Cramping, diarrhea, sweating.", "Adjust dose to symptoms."),
    ("pyrazinamide", "Pyrazinamide", "prescription", "Oral", "Tuberculosis", "Hepatotoxicity, hyperuricemia.", "Monitor liver enzymes."),
    ("quetiapine", "Quetiapine", "prescription", "Oral", "Schizophrenia, bipolar disorder, depression adjunct", "Sedation, weight gain, metabolic effects.", "Metabolic monitoring."),
    ("racemic-epinephrine", "Racemic Epinephrine", "prescription", "Inhaled", "Croup, post-extubation stridor", "Tachycardia, anxiety.", "Observe for rebound after nebulization."),
    ("ranibizumab", "Ranibizumab", "prescription", "Intravitreal", "Macular degeneration, diabetic macular edema", "Endophthalmitis (rare), increased eye pressure.", "Administered by ophthalmologist."),
    ("rasagiline", "Rasagiline", "prescription", "Oral", "Parkinson's disease", "Headache, dyskinesia.", "MAO-B inhibitor; tyramine interactions less than with MAO-A."),
    ("rifampin", "Rifampin", "prescription", "Oral / IV", "Tuberculosis, leprosy, prosthetic joint infection adjunct", "Orange body fluids, hepatotoxicity, drug interactions.", "Strong CYP3A4 inducer."),
    ("rifaximin", "Rifaximin", "prescription", "Oral", "IBS-D, hepatic encephalopathy, traveler's diarrhea", "Headache, peripheral edema.", "Minimal systemic absorption."),
    ("riluzole", "Riluzole", "prescription", "Oral", "Amyotrophic lateral sclerosis", "Nausea, dizziness, liver enzyme elevation.", "Monitor liver function."),
    ("risperidone", "Risperidone", "prescription", "Oral / IM", "Schizophrenia, bipolar disorder, autism irritability", "Weight gain, hyperprolactinemia, EPS.", "Monitor metabolic parameters."),
    ("rituximab", "Rituximab", "prescription", "IV / SubQ", "Lymphoma, leukemia, rheumatoid arthritis, vasculitis", "Infusion reaction, infection, hepatitis B reactivation.", "Screen for hepatitis B."),
    ("rivastigmine", "Rivastigmine", "prescription", "Oral / Transdermal", "Alzheimer's, Parkinson's disease dementia", "Nausea, vomiting, weight loss.", "Patch may reduce GI side effects."),
    ("roflumilast", "Roflumilast", "prescription", "Oral", "Severe COPD with chronic bronchitis", "Weight loss, diarrhea, psychiatric effects.", "Monitor weight and mood."),
    ("ropinirole", "Ropinirole", "prescription", "Oral", "Parkinson's disease, restless legs syndrome", "Somnolence, impulse control disorders, hallucinations.", "Counsel about sudden sleep onset."),
    ("ruxolitinib-cream", "Ruxolitinib Cream", "prescription", "Topical", "Atopic dermatitis, vitiligo", "Application site irritation.", "Limit body surface area treated."),
    ("salicylic-acid", "Salicylic Acid", "otc", "Topical", "Warts, acne, psoriasis", "Local irritation.", "Avoid on healthy skin."),
    ("sodium-bicarbonate", "Sodium Bicarbonate", "prescription", "Oral / IV", "Metabolic acidosis, hyperkalemia, kidney stone prevention", "Fluid retention, alkalosis.", "Monitor electrolytes."),
    ("sofosbuvir", "Sofosbuvir", "prescription", "Oral", "Chronic hepatitis C", "Fatigue, headache.", "Used in combination regimens."),
    ("semaglutide", "Semaglutide", "prescription", "SubQ / Oral", "Type 2 diabetes, chronic weight management", "Nausea, vomiting, pancreatitis (rare).", "Boxed warning: thyroid C-cell tumors in rodents."),
    ("senna", "Senna", "otc", "Oral", "Constipation", "Cramping, electrolyte loss.", "Short-term use preferred."),
    ("sertraline", "Sertraline", "prescription", "Oral", "Depression, OCD, PTSD, panic disorder, premenstrual dysphoric disorder", "Nausea, insomnia, sexual dysfunction.", "Suicidality warning in young adults."),
    ("sildenafil", "Sildenafil", "prescription", "Oral", "Erectile dysfunction, pulmonary hypertension", "Headache, flushing, vision changes.", "Avoid with nitrates."),
    ("sorafenib", "Sorafenib", "prescription", "Oral", "Hepatocellular, renal cell, thyroid cancers", "Hand-foot syndrome, hypertension, diarrhea.", "Manage skin reactions."),
    ("spironolactone", "Spironolactone", "prescription", "Oral", "Heart failure, ascites, resistant hypertension, hirsutism, acne", "Hyperkalemia, gynecomastia.", "Monitor potassium."),
    ("sumatriptan", "Sumatriptan", "prescription", "Oral / SubQ / Nasal", "Migraine, cluster headache", "Chest tightness, paresthesia, fatigue.", "Avoid in coronary artery disease."),
    ("sunitinib", "Sunitinib", "prescription", "Oral", "Renal cell carcinoma, GIST, neuroendocrine tumors", "Hypertension, fatigue, hand-foot syndrome.", "Cardiac function monitoring."),
    ("tacrolimus", "Tacrolimus", "prescription", "Oral / IV / Topical", "Transplant rejection, atopic dermatitis (topical)", "Nephrotoxicity, neurotoxicity, hyperglycemia.", "Narrow therapeutic window; monitor levels."),
    ("tadalafil", "Tadalafil", "prescription", "Oral", "Erectile dysfunction, BPH, pulmonary hypertension", "Headache, back pain, flushing.", "Avoid with nitrates."),
    ("tamoxifen", "Tamoxifen", "prescription", "Oral", "Hormone receptor-positive breast cancer, risk reduction", "Hot flashes, thromboembolism, endometrial cancer.", "Endometrial surveillance with symptoms."),
    ("tamsulosin", "Tamsulosin", "prescription", "Oral", "Benign prostatic hyperplasia", "Orthostatic hypotension, retrograde ejaculation.", "Intraoperative floppy iris syndrome."),
    ("tenofovir", "Tenofovir", "prescription", "Oral", "HIV, hepatitis B, PrEP", "Renal dysfunction, bone mineral density loss.", "Renal function monitoring."),
    ("temozolomide", "Temozolomide", "prescription", "Oral", "Glioblastoma, anaplastic astrocytoma", "Myelosuppression, nausea, lymphopenia.", "PCP prophylaxis during concurrent radiation."),
    ("tetanus-immune-globulin", "Tetanus Immune Globulin", "prescription", "IM", "Tetanus treatment", "Injection site reaction.", "Combine with tetanus toxoid."),
    ("tetrabenazine", "Tetrabenazine", "prescription", "Oral", "Huntington disease chorea", "Depression, parkinsonism, somnolence.", "Monitor for suicidality."),
    ("timolol-drops", "Timolol Eye Drops", "prescription", "Eye drops", "Open-angle glaucoma", "Bradycardia, bronchospasm.", "Avoid in asthma; punctal occlusion to minimize systemic effects."),
    ("tiotropium", "Tiotropium", "prescription", "Inhaled", "COPD, asthma", "Dry mouth, urinary retention.", "Long-acting; once daily."),
    ("tobramycin", "Tobramycin", "prescription", "Inhaled / IV", "Cystic fibrosis Pseudomonas, severe infections", "Nephrotoxicity, ototoxicity (systemic).", "Cycle on/off for inhaled use."),
    ("tolvaptan", "Tolvaptan", "prescription", "Oral", "Autosomal dominant polycystic kidney disease, hyponatremia", "Hepatotoxicity, thirst, polyuria.", "Liver enzyme monitoring."),
    ("topiramate", "Topiramate", "prescription", "Oral", "Migraine prevention, seizures, weight loss adjunct", "Paresthesia, cognitive slowing, kidney stones.", "Acidosis monitoring."),
    ("tranexamic-acid", "Tranexamic Acid", "prescription", "Oral / IV", "Heavy menstrual bleeding, surgical bleeding", "Thromboembolism, headache.", "Caution in thrombosis risk."),
    ("trastuzumab", "Trastuzumab", "prescription", "IV / SubQ", "HER2-positive breast and gastric cancer", "Cardiotoxicity, infusion reaction.", "Echocardiogram monitoring."),
    ("trazodone", "Trazodone", "prescription", "Oral", "Insomnia, depression", "Sedation, priapism (rare), orthostatic hypotension.", "Often used off-label for sleep."),
    ("tretinoin", "Tretinoin", "prescription", "Topical / Oral", "Acne, photoaging, acute promyelocytic leukemia", "Skin irritation, photosensitivity.", "Sun protection essential."),
    ("triamcinolone", "Triamcinolone", "prescription", "Topical / Intra-articular / IM", "Inflammatory skin disease, joint inflammation, allergic conditions", "Skin thinning, hyperglycemia.", "Avoid excessive use."),
    ("trientine", "Trientine", "prescription", "Oral", "Wilson's disease", "Iron deficiency, GI upset.", "Take on empty stomach."),
    ("trimethoprim-sulfamethoxazole", "Trimethoprim-Sulfamethoxazole", "prescription", "Oral / IV", "UTI, MRSA, PCP prophylaxis", "Rash, hyperkalemia, photosensitivity.", "Avoid in late pregnancy."),
    ("ursodiol", "Ursodiol", "prescription", "Oral", "Gallstone dissolution, primary biliary cholangitis", "Diarrhea, back pain.", "Slow effect."),
    ("ustekinumab", "Ustekinumab", "prescription", "SubQ / IV", "Plaque psoriasis, psoriatic arthritis, Crohn's, UC", "Infection, infusion reaction.", "Screen for TB."),
    ("valacyclovir", "Valacyclovir", "prescription", "Oral", "Herpes simplex, shingles", "Headache, nausea.", "Adjust dose in renal impairment."),
    ("valproate", "Valproate", "prescription", "Oral / IV", "Seizures, bipolar disorder, migraine prevention", "Hepatotoxicity, weight gain, teratogenic.", "Avoid in pregnancy; monitor LFTs and platelets."),
    ("vancomycin", "Vancomycin", "prescription", "Oral / IV", "MRSA, C. difficile (oral), severe gram-positive infections", "Nephrotoxicity, red man syndrome, ototoxicity.", "Monitor trough levels."),
    ("vedolizumab", "Vedolizumab", "prescription", "IV", "Ulcerative colitis, Crohn's disease", "Infusion reaction, nasopharyngitis.", "Gut-selective integrin inhibitor."),
    ("venetoclax", "Venetoclax", "prescription", "Oral", "CLL, AML", "Tumor lysis syndrome, neutropenia.", "Ramp-up dose to reduce TLS risk."),
    ("venlafaxine", "Venlafaxine", "prescription", "Oral", "Depression, anxiety, panic disorder", "Hypertension, nausea, sexual dysfunction.", "Taper to discontinue."),
    ("vincristine", "Vincristine", "prescription", "IV", "Acute lymphoblastic leukemia, lymphoma", "Neuropathy, constipation.", "Never administer intrathecal (fatal)."),
    ("vinblastine", "Vinblastine", "prescription", "IV", "Hodgkin lymphoma, testicular cancer", "Myelosuppression, neuropathy.", "Vesicant: avoid extravasation."),
    ("voxelotor", "Voxelotor", "prescription", "Oral", "Sickle cell disease", "Headache, diarrhea, rash.", "Hemoglobin S binding."),
    ("warfarin", "Warfarin", "prescription", "Oral", "Atrial fibrillation, mechanical valve, VTE", "Bleeding, drug interactions, teratogenic.", "Frequent INR monitoring; vitamin K consistency."),
    ("zanamivir", "Zanamivir", "prescription", "Inhaled", "Influenza A and B", "Bronchospasm.", "Avoid in airway disease."),
    ("zinc", "Zinc Supplement", "supplement", "Oral", "Wilson's disease (maintenance), zinc deficiency", "GI upset, copper deficiency with chronic use.", "Take separately from antibiotics."),
    ("zinc-oxide", "Zinc Oxide Cream", "otc", "Topical", "Diaper rash, minor skin irritation", "Generally well tolerated.", "Apply with each diaper change."),
    ("zolpidem", "Zolpidem", "prescription", "Oral", "Short-term insomnia", "Sleep behaviors, daytime drowsiness, dependence.", "Use lowest effective dose; complex sleep behaviors warning."),
    ("acidophilus", "Acidophilus", "supplement", "Oral", "Maintaining digestive flora, antibiotic-associated diarrhea", "Bloating, gas.", "Probiotic; refrigerate."),
    ("aloe", "Aloe", "supplement", "Oral / Topical", "Minor burns, constipation", "Diarrhea, skin irritation.", "Oral aloe latex linked to colon cancer in animals."),
    ("coenzyme-q10", "Coenzyme Q10", "supplement", "Oral", "Heart failure, statin-associated myalgia", "GI upset, headache.", "Limited but suggestive evidence."),
    ("creatine", "Creatine", "supplement", "Oral", "Athletic performance, muscle disease", "Weight gain, GI upset.", "Adequate hydration."),
    ("fish-oil", "Fish Oil", "supplement", "Oral", "Hypertriglyceridemia, cardiovascular support", "Fishy aftertaste, bleeding at high doses.", "Variable EPA/DHA content."),
    ("flaxseed", "Flaxseed and Flaxseed Oil", "supplement", "Oral", "Constipation, cardiovascular support", "GI upset.", "Take with adequate fluids."),
    ("ginkgo", "Ginkgo", "supplement", "Oral", "Memory support, claudication", "Bleeding, headache.", "Avoid with anticoagulants."),
    ("glucosamine", "Glucosamine", "supplement", "Oral", "Osteoarthritis", "GI upset, headache.", "Modest evidence."),
    ("honey", "Honey", "supplement", "Oral / Topical", "Cough, wound care", "Botulism risk in infants.", "Do not give to infants under 12 months."),
    ("l-arginine", "L-arginine", "supplement", "Oral", "Erectile dysfunction, preeclampsia prevention", "GI upset.", "Variable response."),
    ("marijuana", "Marijuana", "prescription", "Oral / Inhaled", "Chemotherapy-induced nausea, chronic pain, spasticity", "Cognitive impairment, dependence.", "Legal status varies by jurisdiction."),
    ("melatonin", "Melatonin", "supplement", "Oral", "Jet lag, sleep onset insomnia", "Headache, dizziness.", "Lower doses (0.3-1 mg) often effective."),
    ("milk-thistle", "Milk Thistle", "supplement", "Oral", "Liver support", "GI upset.", "Limited evidence for liver disease."),
    ("niacin", "Niacin", "supplement", "Oral", "Pellagra, low HDL", "Flushing, hepatotoxicity, hyperglycemia.", "Cardiovascular outcome benefit unproven."),
    ("prenatal-vitamins", "Prenatal Vitamins", "supplement", "Oral", "Pregnancy nutritional support", "Constipation, nausea.", "Start before conception when possible."),
    ("red-yeast-rice", "Red Yeast Rice", "supplement", "Oral", "Cholesterol management", "Muscle pain, liver enzyme elevation.", "Contains natural statin-like compound."),
    ("same", "SAMe", "supplement", "Oral", "Depression, osteoarthritis", "GI upset, anxiety.", "May trigger mania in bipolar disorder."),
    ("st-johns-wort", "St. John's Wort", "supplement", "Oral", "Mild to moderate depression", "Photosensitivity, drug interactions.", "Many serious drug interactions."),
    ("tea-tree-oil", "Tea Tree Oil", "supplement", "Topical", "Acne, athlete's foot", "Skin irritation, contact dermatitis.", "Do not ingest."),
    ("vitamin-a", "Vitamin A", "supplement", "Oral", "Vitamin A deficiency", "Hypervitaminosis with excess intake.", "Avoid high doses in pregnancy."),
    ("vitamin-b6", "Vitamin B-6", "supplement", "Oral", "Vitamin B6 deficiency, peripheral neuropathy prevention", "Peripheral neuropathy with high doses.", "Limit to under 100 mg daily long-term."),
    ("vitamin-b12", "Vitamin B-12", "supplement", "Oral / IM", "B12 deficiency, pernicious anemia", "Generally well tolerated.", "Larger oral doses effective for many."),
    ("vitamin-c", "Vitamin C", "supplement", "Oral", "Scurvy, immune support", "GI upset at high doses, kidney stones.", "Megadoses not supported by evidence."),
    ("vitamin-e", "Vitamin E", "supplement", "Oral", "Antioxidant support", "Bleeding at high doses.", "Avoid high doses with anticoagulants."),
    ("dhea", "DHEA", "supplement", "Oral", "Adrenal insufficiency, aging support", "Acne, hair loss, mood changes.", "Limited evidence in healthy adults."),
    ("evening-primrose", "Evening Primrose", "supplement", "Oral", "Atopic dermatitis, premenstrual symptoms", "GI upset, headache.", "Limited evidence."),
    ("folate", "Folate (folic acid)", "supplement", "Oral", "Folate deficiency, prevention of neural tube defects", "Generally well tolerated.", "Recommended for women planning pregnancy."),
]
