"""Mayo Clinic mirror — content corpus.

Real-style content for diseases, procedures, drugs, departments,
doctors, clinical trials, and symptom-checker rules. Paraphrased for
copyright safety but structurally faithful to mayoclinic.org.
"""

# ---------------------------------------------------------------------------
# 30 Mayo Clinic departments (real names, three campuses)
# ---------------------------------------------------------------------------
DEPARTMENTS = [
    ("Cardiovascular Medicine", "cardiology",
     "Mayo Clinic cardiovascular medicine experts diagnose and treat the full spectrum of heart and vascular disease. The department performs more than 10,000 cardiac procedures and 4,000 heart surgeries each year, ranking #1 in Newsweek's hospital rankings for cardiology and cardiac surgery for over 25 consecutive years.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Coronary artery disease, heart failure, valve disease, atrial fibrillation, congenital heart disease, cardiac imaging, electrophysiology"),
    ("Neurology", "neurology",
     "The Department of Neurology evaluates and treats disorders of the brain, spinal cord, peripheral nerves, and muscles. The team manages epilepsy, stroke, multiple sclerosis, Parkinson's disease, and Alzheimer's disease at all three Mayo Clinic campuses, with subspecialty clinics for each area.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Epilepsy, stroke, movement disorders, multiple sclerosis, neuro-oncology, headache, sleep disorders, neuromuscular disease, dementia"),
    ("Neurosurgery", "neurosurgery",
     "Mayo Clinic neurosurgeons perform approximately 7,000 operations per year, including awake brain surgery, minimally invasive spine surgery, deep brain stimulation, and stereotactic radiosurgery for tumors and vascular malformations.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Brain tumor, epilepsy surgery, deep brain stimulation, spinal cord tumors, complex spine, cerebrovascular surgery, pediatric neurosurgery"),
    ("Oncology", "oncology",
     "The Mayo Clinic Comprehensive Cancer Center is one of only a few NCI-designated comprehensive cancer centers in the United States. It offers proton beam therapy, CAR-T cell therapy, immunotherapy trials, and integrated multidisciplinary tumor boards across more than 40 cancer types.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Breast cancer, lung cancer, colorectal cancer, hematologic malignancies, melanoma, gynecologic oncology, sarcoma, head and neck"),
    ("Orthopedics", "orthopedics",
     "Mayo Clinic orthopedic surgeons treat the full range of musculoskeletal conditions, performing more than 28,000 surgeries each year. The department is consistently ranked among the top three for orthopedics in the United States.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Joint replacement, sports medicine, spine surgery, hand surgery, foot and ankle, pediatric orthopedics, orthopedic oncology, trauma"),
    ("Gastroenterology and Hepatology", "gastroenterology",
     "The Division of Gastroenterology and Hepatology evaluates and treats disorders of the digestive system and liver, performing more than 60,000 endoscopic procedures each year and providing specialized hepatology, motility, and inflammatory bowel disease programs.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Inflammatory bowel disease, hepatology, liver transplant evaluation, advanced endoscopy, GI motility, pancreatic disease, esophageal disease"),
    ("Endocrinology, Diabetes, Metabolism, and Nutrition", "endocrinology",
     "Mayo Clinic endocrinologists treat thyroid, parathyroid, adrenal, pituitary, and diabetes-related disorders, with a dedicated diabetes care team and an internationally recognized thyroid and pituitary tumor program.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Diabetes, thyroid disorders, adrenal disease, pituitary disorders, osteoporosis, obesity medicine, lipid clinic"),
    ("Pulmonary and Critical Care Medicine", "pulmonary",
     "The division treats respiratory, sleep, and critical-care illnesses including COPD, pulmonary fibrosis, asthma, sleep apnea, and acute respiratory failure, and operates one of the largest interstitial lung disease clinics in the country.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "COPD, interstitial lung disease, asthma, sleep disorders, lung transplant evaluation, pulmonary hypertension, cystic fibrosis"),
    ("Nephrology and Hypertension", "nephrology",
     "Mayo Clinic nephrologists care for patients with chronic kidney disease, glomerular disease, kidney stones, polycystic kidney disease, and hypertensive disorders, and manage the largest living-donor kidney transplant program in the United States.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Chronic kidney disease, polycystic kidney disease, glomerulonephritis, kidney stones, dialysis, transplant nephrology, hypertension"),
    ("Urology", "urology",
     "The Department of Urology treats benign and malignant disorders of the kidney, bladder, prostate, and reproductive organs. The team performs more than 7,000 urologic surgeries annually, with leadership in robotic prostatectomy, urologic oncology, and male infertility.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Prostate cancer, kidney cancer, bladder cancer, BPH, male infertility, stones, female urology, pediatric urology"),
    ("Obstetrics and Gynecology", "obgyn",
     "Mayo Clinic obstetricians and gynecologists provide care across pregnancy, gynecologic surgery, infertility, gynecologic oncology, and minimally invasive procedures, with a high-risk maternal-fetal medicine team.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Maternal-fetal medicine, gynecologic surgery, infertility, gynecologic oncology, urogynecology, menopause, fibroids, endometriosis"),
    ("Dermatology", "dermatology",
     "The Department of Dermatology evaluates and treats more than 110,000 patients each year, with subspecialty programs in melanoma, complex medical dermatology, dermatopathology, pediatric dermatology, and Mohs surgery.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Melanoma, psoriasis, atopic dermatitis, Mohs surgery, dermatopathology, autoimmune skin disease, hair disorders"),
    ("Ophthalmology", "ophthalmology",
     "Mayo Clinic ophthalmologists treat diseases and disorders of the eye, including cataract, glaucoma, macular degeneration, diabetic retinopathy, and pediatric eye disease, with a corneal transplant and ocular oncology program.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Cataract, glaucoma, retinal disease, oculoplastics, pediatric ophthalmology, corneal disease, neuro-ophthalmology, ocular oncology"),
    ("Otorhinolaryngology (ENT)", "ent",
     "The Department of Otorhinolaryngology — Head and Neck Surgery treats hearing loss, sinus disease, head and neck cancers, and voice and swallowing disorders, performing more than 12,000 procedures annually.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Head and neck cancer, hearing loss, cochlear implants, rhinology, voice disorders, sleep surgery, skull base surgery"),
    ("Psychiatry and Psychology", "psychiatry",
     "Mayo Clinic psychiatrists and psychologists evaluate and treat mood, anxiety, psychotic, neurodevelopmental, addictive, and behavioral disorders across the lifespan, with integrated psychotherapy, neurostimulation, and addiction programs.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Depression, bipolar disorder, anxiety, addiction, eating disorders, ADHD, transcranial magnetic stimulation, child and adolescent psychiatry"),
    ("Pediatrics and Adolescent Medicine", "pediatrics",
     "Mayo Clinic Children's Center provides comprehensive pediatric care across more than 60 subspecialty programs, from neonatology to pediatric cardiology, hematology-oncology, neurology, and complex congenital surgery.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "General pediatrics, neonatology, pediatric cardiology, pediatric hematology-oncology, pediatric neurology, adolescent medicine, genetics"),
    ("Family Medicine", "family-medicine",
     "Family medicine physicians provide longitudinal, whole-family primary care across all ages, with embedded behavioral health, pharmacy, and care-management teams.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Primary care, preventive medicine, chronic disease management, women's health, geriatrics, sports medicine, integrative medicine"),
    ("Internal Medicine", "internal-medicine",
     "The Division of General Internal Medicine cares for adult patients across the spectrum of primary, preventive, and complex chronic medical conditions with embedded subspecialty consultation.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Adult primary care, preventive medicine, hospital medicine, chronic disease, executive health, post-acute care, geriatrics"),
    ("Rheumatology", "rheumatology",
     "The Division of Rheumatology evaluates and treats autoimmune and musculoskeletal disorders, including rheumatoid arthritis, lupus, vasculitis, gout, and inflammatory myopathies.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Rheumatoid arthritis, lupus, vasculitis, gout, psoriatic arthritis, spondyloarthritis, scleroderma, polymyalgia rheumatica"),
    ("Hematology", "hematology",
     "Mayo Clinic hematologists treat benign and malignant blood disorders including leukemias, lymphomas, multiple myeloma, sickle cell disease, hemophilia, and clotting disorders.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Leukemia, lymphoma, multiple myeloma, MDS, sickle cell disease, hemophilia, thrombosis, bone marrow transplant"),
    ("Infectious Diseases", "infectious-diseases",
     "The Division of Infectious Diseases evaluates and treats bacterial, viral, fungal, and parasitic infections, with subspecialty programs in HIV care, travel medicine, transplant infectious diseases, and antimicrobial stewardship.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "HIV, transplant infectious disease, travel medicine, antimicrobial stewardship, tuberculosis, prosthetic joint infection, hepatitis C"),
    ("General Surgery", "general-surgery",
     "Mayo Clinic general surgeons perform abdominal, hernia, breast, endocrine, colon and rectal, foregut, and minimally invasive operations, with high-volume robotic and bariatric programs.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Hernia repair, colon and rectal surgery, foregut surgery, breast surgery, endocrine surgery, bariatric surgery, robotic surgery"),
    ("Bariatric and Metabolic Surgery", "bariatric",
     "The Mayo Clinic bariatric surgery program treats severe obesity with sleeve gastrectomy, Roux-en-Y gastric bypass, revisional bariatric surgery, and an integrated medical and behavioral weight program.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Sleeve gastrectomy, gastric bypass, revisional bariatric surgery, medical weight management, behavioral weight management, adolescent bariatrics"),
    ("Transplant Center", "transplant",
     "Mayo Clinic is the largest integrated transplant provider in the United States, performing more than 1,800 solid organ transplants per year, including heart, lung, liver, kidney, pancreas, and intestinal transplant.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Kidney transplant, liver transplant, heart transplant, lung transplant, pancreas transplant, living donor programs, transplant oncology"),
    ("Radiation Oncology", "radiation-oncology",
     "Mayo Clinic radiation oncologists deliver advanced external beam, stereotactic, brachytherapy, and proton beam radiation for cancer at all three campuses, with one of the largest proton beam programs in the world.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Proton beam therapy, stereotactic radiosurgery, IMRT, brachytherapy, pediatric radiation oncology, palliative radiation"),
    ("Anesthesiology and Perioperative Medicine", "anesthesiology",
     "The department provides anesthesia and perioperative care for more than 130,000 surgeries each year, with subspecialty teams for cardiac, transplant, obstetric, regional, and pediatric anesthesia.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Cardiac anesthesia, regional anesthesia, transplant anesthesia, obstetric anesthesia, pediatric anesthesia, chronic pain"),
    ("Emergency Medicine", "emergency-medicine",
     "Mayo Clinic emergency departments treat more than 200,000 patient visits per year across the three campuses, with Level I trauma designation in Rochester and integrated stroke, STEMI, and sepsis programs.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Trauma, resuscitation, stroke, STEMI, sepsis, pediatric emergency, observation medicine, emergency ultrasound"),
    ("Radiology", "radiology",
     "Mayo Clinic radiologists perform more than 1.3 million imaging exams annually and provide subspecialty interpretation across body imaging, cardiothoracic imaging, neuroradiology, breast imaging, and interventional radiology.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "MRI, CT, PET, ultrasound, neuroradiology, body imaging, breast imaging, interventional radiology, nuclear medicine"),
    ("Pain Medicine", "pain-medicine",
     "The Mayo Clinic Pain Clinic evaluates and treats acute, chronic, and cancer-related pain using a multidisciplinary model that combines medications, interventional procedures, physical therapy, and behavioral health.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Chronic pain, neuropathic pain, spine pain, cancer pain, headache, interventional procedures, integrative pain management"),
    ("Physical Medicine and Rehabilitation", "rehabilitation",
     "Mayo Clinic physiatrists and rehabilitation therapists care for patients recovering from stroke, brain injury, spinal cord injury, amputation, and complex musculoskeletal conditions with inpatient and outpatient programs.",
     ["Rochester", "Jacksonville", "Phoenix"],
     "Stroke rehabilitation, spinal cord injury, brain injury, amputation, sports medicine, EMG, musculoskeletal rehabilitation"),
]
