"""Genshin Impact Wiki seed data."""
from seed_helpers import expand_article

GS_CATEGORIES = [
    {"name": "Characters"},
    {"name": "Playable Characters", "parent": "Characters"},
    {"name": "Five-Star Characters", "parent": "Playable Characters"},
    {"name": "Four-Star Characters", "parent": "Playable Characters"},
    {"name": "NPCs", "parent": "Characters"},
    {"name": "Mondstadt Characters", "parent": "Playable Characters"},
    {"name": "Liyue Characters", "parent": "Playable Characters"},
    {"name": "Inazuma Characters", "parent": "Playable Characters"},
    {"name": "Sumeru Characters", "parent": "Playable Characters"},
    {"name": "Fontaine Characters", "parent": "Playable Characters"},
    {"name": "Regions"},
    {"name": "Weapons"},
    {"name": "Five-Star Weapons", "parent": "Weapons"},
    {"name": "Quests"},
    {"name": "Archon Quests", "parent": "Quests"},
    {"name": "Story Quests", "parent": "Quests"},
    {"name": "Events"},
    {"name": "Items"},
    {"name": "Artifacts", "parent": "Items"},
    {"name": "Materials", "parent": "Items"},
]

_PLAYABLE = [
    dict(title="Diluc Ragnvindr",
        blurb="is a Five-Star Pyro [[Claymore]] character and the owner of the [[Dawn Winery]] of [[Mondstadt]].",
        bio=("Diluc was the rising star of the [[Knights of Favonius]] until his father Crepus's death at the "
             "hands of an ancient delusion. He resigned from the Knights, exiled himself to investigate the "
             "[[Fatui]], and now operates as Mondstadt's [[Darknight Hero]]."),
        powers=["Pyro Vision granted at age 18",
                "Claymore mastery — burst Dawn ignites all enemies in a wide AoE",
                "Owner of the Wolf's Gravestone forged from his father's claymore"],
        relationships=[("Kaeya Alberich", "adoptive brother"), ("Crepus Ragnvindr", "father"),
                       ("Adelinde", "Dawn Winery head maid"), ("Jean", "former Knights peer")],
        appearances=["Mondstadt Archon Quest", "Diluc Story Quest"],
        infobox={"real_name": "Diluc Ragnvindr",
                 "alias": ["Darknight Hero"],
                 "vision": "Pyro", "weapon": "Claymore",
                 "rarity": "5-star", "region": "Mondstadt",
                 "constellation": "Noctua",
                 "release_version": "1.0",
                 "voice_actor_en": "Sean Chiplock",
                 "birthday": "April 30"},
        image="gs_diluc.jpg", categories=["Five-Star Characters", "Mondstadt Characters", "Playable Characters"],
        views=72_100, featured=True,
    ),
    dict(title="Venti",
        blurb="is the bard incarnation of the [[Anemo Archon]] '''Barbatos''', adopting the name of a forgotten friend.",
        bio=("[[Barbatos]] is the freedom-loving god of [[Mondstadt]]. After the fall of [[Decarabian]] he "
             "took the form of his deceased mortal friend Venti to walk among the people. He now busks for "
             "wine outside the [[Cathedral]] and intervenes in archon matters only when freedom is at stake."),
        powers=["Anemo Vision — bow user, master of windsong",
                "True identity: the Anemo Archon Barbatos",
                "Capable of summoning a Stormeye 'Wind's Grand Ode'"],
        relationships=[("Dvalin", "longtime friend"), ("Jean", "ally"),
                       ("Mondstadt", "his city")],
        appearances=["Mondstadt Archon Quest", "Trail of the God-Conqueror"],
        infobox={"real_name": "Venti (Barbatos)",
                 "vision": "Anemo", "weapon": "Bow",
                 "rarity": "5-star", "region": "Mondstadt",
                 "constellation": "Carmen Dei",
                 "release_version": "1.0",
                 "voice_actor_en": "Erika Harlacher",
                 "birthday": "June 16",
                 "archon_title": "God of Freedom"},
        image="gs_venti.jpg", categories=["Five-Star Characters", "Mondstadt Characters", "Playable Characters"],
        views=83_400,
    ),
    dict(title="Zhongli",
        blurb="is the [[Geo Archon]] '''Rex Lapis''' in his retired mortal form, currently working as a consultant at the [[Wangsheng Funeral Parlor]].",
        bio=("Morax — the Geo Archon known to mortals as Rex Lapis — ruled [[Liyue Harbor]] for over six "
             "millennia. After staging his own death in 1.0 he passed governance to the [[Liyue Qixing]] and "
             "now lives as the consultant Zhongli, advising [[Hu Tao]] on burial customs."),
        powers=["Geo Vision (publicly) — spear user; consumate Geo elemental",
                "True power: the Geo Archon Morax — summons jade meteors",
                "Six millennia of historical knowledge"],
        relationships=[("Hu Tao", "boss"), ("Childe / Tartaglia", "frenemy"),
                       ("Guizhong", "deceased predecessor"), ("Xiao", "former adeptus")],
        appearances=["Liyue Archon Quest", "Zhongli Story Quest"],
        infobox={"real_name": "Morax",
                 "alias": ["Rex Lapis", "Zhongli"],
                 "vision": "Geo", "weapon": "Polearm",
                 "rarity": "5-star", "region": "Liyue",
                 "constellation": "Lapidus",
                 "release_version": "1.1",
                 "voice_actor_en": "Keith Silverstein",
                 "birthday": "December 31",
                 "archon_title": "God of Contracts"},
        image="gs_zhongli.jpg", categories=["Five-Star Characters", "Liyue Characters", "Playable Characters"],
        views=104_900, featured=False,
    ),
    dict(title="Hu Tao",
        blurb="is the 77th Director of the [[Wangsheng Funeral Parlor]] in [[Liyue Harbor]] and a five-star [[Pyro]] [[polearm]] character.",
        bio=("Hu Tao is the rambunctious 77th Director of Wangsheng, hand-picked by her grandfather. She "
             "balances ledgers, recites unsettling poetry, and walks the line between the living and the [[Three Realms]]."),
        powers=["Pyro Vision — HP-based scaling",
                "Burst 'Spirit Soother' deals scaling DMG and self-heals",
                "Walks between realms during burial rituals"],
        relationships=[("Zhongli", "consultant"), ("Qiqi", "long-standing rivalry"),
                       ("Xiao", "concerned friend")],
        appearances=["Hu Tao Story Quest", "Moonchase Festival"],
        infobox={"real_name": "Hu Tao",
                 "alias": ["77th Director", "Director Hu"],
                 "vision": "Pyro", "weapon": "Polearm",
                 "rarity": "5-star", "region": "Liyue",
                 "constellation": "Papilio Charontis",
                 "release_version": "1.3",
                 "voice_actor_en": "Brianna Knickerbocker",
                 "birthday": "July 15"},
        image="gs_hutao.jpg", categories=["Five-Star Characters", "Liyue Characters", "Playable Characters"],
        views=88_700,
    ),
    dict(title="Raiden Shogun",
        blurb="(the Electro Archon '''Beelzebul''') rules [[Inazuma]] from her seat in [[Tenshukaku]].",
        bio=("Ei is the current Electro Archon. After losing her sister Makoto, she retreated into the Plane "
             "of Euthymia and entrusted her duties to the [[Raiden Shogun]] puppet. The puppet enforced the "
             "[[Vision Hunt Decree]] and the Sakoku Decree, both later rescinded."),
        powers=["Electro Vision (publicly) — polearm user",
                "True name: Beelzebul, Electro Archon",
                "Musou no Hitotachi — a stroke that severs even concepts"],
        relationships=[("Makoto", "deceased twin"), ("Yae Miko", "oldest friend"),
                       ("Sara Kujou", "loyal samurai"), ("Scaramouche", "former prototype")],
        appearances=["Inazuma Archon Quest", "Imperatrix Umbrosa Story Quest"],
        infobox={"real_name": "Ei",
                 "alias": ["Raiden Shogun", "Beelzebul"],
                 "vision": "Electro", "weapon": "Polearm",
                 "rarity": "5-star", "region": "Inazuma",
                 "constellation": "Imperatrix Umbrosa",
                 "release_version": "2.1",
                 "voice_actor_en": "Anne Yatco",
                 "birthday": "June 26",
                 "archon_title": "God of Eternity"},
        image="gs_raiden.jpg", categories=["Five-Star Characters", "Inazuma Characters", "Playable Characters"],
        views=96_200,
    ),
    dict(title="Yae Miko",
        blurb="is the [[Guuji]] of the [[Grand Narukami Shrine]] and owner of [[Yae Publishing House]].",
        bio=("Yae Miko, a kitsune of nearly five centuries, is the eternal companion of the [[Raiden Shogun]] "
             "and the highest priestess of [[Inazuma]]. She publishes light novels under the pen-name Sora "
             "Hitomi and runs the [[Yashiro Commission]]'s spiritual affairs."),
        powers=["Electro Vision — catalyst user",
                "Summons three Sesshou Sakura tower turrets",
                "Kitsune longevity and shape-shifting"],
        relationships=[("Raiden Shogun (Ei)", "oldest friend"), ("Sara Kujou", "subordinate"),
                       ("Gorou", "occasional contractor")],
        appearances=["Inazuma Archon Quest", "Divina Vulpes Story Quest"],
        infobox={"real_name": "Yae Miko",
                 "vision": "Electro", "weapon": "Catalyst",
                 "rarity": "5-star", "region": "Inazuma",
                 "constellation": "Divina Vulpes",
                 "release_version": "2.5",
                 "voice_actor_en": "Risa Mei",
                 "birthday": "June 27"},
        image="gs_yae.jpg", categories=["Five-Star Characters", "Inazuma Characters", "Playable Characters"],
        views=64_300,
    ),
    dict(title="Nahida",
        blurb="(the Dendro Archon '''Kusanali''') is the youngest of the [[Seven Archons]].",
        bio=("Buer, called Kusanali by her people and Nahida by friends, took the throne after Greater Lord "
             "Rukkhadevata's sacrifice 500 years ago. She was held captive in the [[Sanctuary of Surasthana]] "
             "by [[Sumeru Akademiya]] sages until liberated during the [[Sumeru Archon Quest]]."),
        powers=["Dendro Vision — catalyst user",
                "Mind-reading via direct dream insertion",
                "Genius theory of [[Irminsul]] tree pruning"],
        relationships=[("Greater Lord Rukkhadevata", "deceased predecessor"),
                       ("Tighnari", "ally"), ("Cyno", "ally"), ("Alhaitham", "ally")],
        appearances=["Sumeru Archon Quest", "Sapientia Oromasdis Story Quest"],
        infobox={"real_name": "Buer", "alias": ["Kusanali", "Nahida"],
                 "vision": "Dendro", "weapon": "Catalyst",
                 "rarity": "5-star", "region": "Sumeru",
                 "constellation": "Sapientia Oromasdis",
                 "release_version": "3.2",
                 "voice_actor_en": "Kimberley Anne Campbell",
                 "birthday": "October 27",
                 "archon_title": "God of Wisdom"},
        image="gs_nahida.jpg", categories=["Five-Star Characters", "Sumeru Characters", "Playable Characters"],
        views=78_900,
    ),
    dict(title="Furina",
        blurb="(the false Hydro Archon '''Focalors''') was the [[Hydro Archon]] of [[Fontaine]] until the prophecy unraveled.",
        bio=("For 500 years Furina played the role of the Hydro Archon while the true Focalors prepared the "
             "dissolution of all [[Fontaine]]ans. Furina now lives as a mortal celebrity in the [[Court of "
             "Fontaine]]."),
        powers=["Hydro Vision — sword user",
                "Burst 'Let the People Rejoice' alternates damage and heal phases",
                "Half a millennium of stage-presence"],
        relationships=[("Neuvillette", "successor as Hydro Sovereign"),
                       ("Focalors", "true god she portrayed"),
                       ("Lyney", "performance peer")],
        appearances=["Fontaine Archon Quest", "Furina Story Quest"],
        infobox={"real_name": "Furina de Fontaine",
                 "vision": "Hydro", "weapon": "Sword",
                 "rarity": "5-star", "region": "Fontaine",
                 "constellation": "Animula Choragi",
                 "release_version": "4.2",
                 "voice_actor_en": "Amber Lee Connors",
                 "birthday": "October 13"},
        image="gs_furina.jpg", categories=["Five-Star Characters", "Fontaine Characters", "Playable Characters"],
        views=109_300,
    ),
    dict(title="Neuvillette",
        blurb="is the [[Iudex]] of [[Fontaine]] and the true [[Hydro Sovereign]] [[Egeria]]'s successor.",
        bio=("Neuvillette is the Iudex of the [[Opera Epiclese]] and the reborn Hydro Dragon. After [[Furina]] "
             "surrendered the throne he reclaimed the [[Hydro Authority]] for the dragons."),
        powers=["Hydro Vision — catalyst user",
                "True identity: the Hydro Dragon Sovereign",
                "Charged Attack: Equitable Judgment summons judgmental water droplets"],
        relationships=[("Furina", "former superior"), ("Sigewinne", "head maid"),
                       ("Wriothesley", "warden ally")],
        appearances=["Fontaine Archon Quest"],
        infobox={"real_name": "Neuvillette",
                 "vision": "Hydro", "weapon": "Catalyst",
                 "rarity": "5-star", "region": "Fontaine",
                 "constellation": "Leukocephalus",
                 "release_version": "4.1",
                 "voice_actor_en": "Sean Chiplock",
                 "birthday": "September 11"},
        image="gs_neuvillette.jpg", categories=["Five-Star Characters", "Fontaine Characters", "Playable Characters"],
        views=66_400,
    ),
    dict(title="Xiao",
        blurb="is a 2,000-year-old [[yaksha]] adeptus and the last of the [[Five Yakshas of Liyue]].",
        bio=("Xiao was indentured to [[Morax]] during the [[Archon War]] and remains the [[Conqueror of Demons]]. "
             "He defended Liyue at the [[Battle of Guili]] and continues to purge demons from the periphery of "
             "the [[Wangshu Inn]]."),
        powers=["Anemo Vision — polearm user",
                "Yaksha Mask transformation — Bane of All Evil",
                "Karma — slowly consumes the wielder"],
        relationships=[("Zhongli / Morax", "former master"), ("Hu Tao", "occasional helper"),
                       ("Verr Goldet", "Wangshu Inn proprietor")],
        appearances=["Liyue Archon Quest", "Xiao Story Quest", "Lantern Rite"],
        infobox={"real_name": "Alatus", "alias": ["Xiao", "Conqueror of Demons"],
                 "vision": "Anemo", "weapon": "Polearm",
                 "rarity": "5-star", "region": "Liyue",
                 "constellation": "Alatus",
                 "release_version": "1.3",
                 "voice_actor_en": "Laila Berzins",
                 "birthday": "April 17"},
        image="gs_xiao.jpg", categories=["Five-Star Characters", "Liyue Characters", "Playable Characters"],
        views=58_900,
    ),
    dict(title="Ganyu",
        blurb="is the half-[[adeptus]] [[General Secretary]] of the [[Liyue Qixing]].",
        bio=("Ganyu is the daughter of an unnamed adeptus and a mortal. She has served the [[Qixing]] for "
             "over three thousand years as bureaucrat, archer, and emissary between mortals and the adepti."),
        powers=["Cryo Vision — bow user",
                "Charged Frostflake Arrows shatter on impact",
                "Adeptal stamina — three millennia of overtime"],
        relationships=[("Cloud Retainer", "adoptive guardian"), ("Keqing", "fellow Qixing"),
                       ("Ningguang", "Tianquan superior")],
        appearances=["Liyue Archon Quest", "Lantern Rite", "Ganyu Story Quest"],
        infobox={"real_name": "Ganyu",
                 "alias": ["General Secretary of the Liyue Qixing"],
                 "vision": "Cryo", "weapon": "Bow",
                 "rarity": "5-star", "region": "Liyue",
                 "constellation": "Sinae Unicornis",
                 "release_version": "1.2",
                 "voice_actor_en": "Jenny Yokobori",
                 "birthday": "December 2"},
        image="gs_ganyu.jpg", categories=["Five-Star Characters", "Liyue Characters", "Playable Characters"],
        views=71_300,
    ),
    dict(title="Keqing",
        blurb="is the [[Yuheng]] of the [[Liyue Qixing]], champion of mortal autonomy.",
        bio=("Keqing climbed the Qixing ranks at uncommon speed, becoming Yuheng at twenty-six. She opposes "
              "reliance on adepti and gods, believing mortals must shape their own future."),
        powers=["Electro Vision — sword user",
                "Stiletto Lightning Stiletto teleport-strike",
                "Famous archetype of mortal self-determination"],
        relationships=[("Ningguang", "fellow Qixing"), ("Ganyu", "peer"),
                       ("Zhongli", "respectful rival of philosophy")],
        appearances=["Liyue Archon Quest", "Keqing Story Quest", "Lantern Rite"],
        infobox={"vision": "Electro", "weapon": "Sword",
                 "rarity": "5-star", "region": "Liyue",
                 "constellation": "Trulla Cementarii",
                 "release_version": "1.0",
                 "voice_actor_en": "Kimberley Anne Campbell",
                 "birthday": "November 20"},
        image="gs_keqing.jpg", categories=["Five-Star Characters", "Liyue Characters", "Playable Characters"],
        views=47_200,
    ),
    dict(title="Jean Gunnhildr",
        blurb="is the [[Acting Grand Master]] of the [[Knights of Favonius]] of [[Mondstadt]].",
        bio=("Jean became Acting Grand Master following the disappearance of [[Varka]]. She works tirelessly "
             "to balance bureaucratic duty with field rescues; her sister [[Barbara]] keeps her grounded."),
        powers=["Anemo Vision — sword user",
                "Burst 'Dandelion Breeze' heals every nearby ally"],
        relationships=[("Barbara", "younger sister"), ("Diluc", "former peer"),
                       ("Lisa", "librarian friend"), ("Venti", "respectful subordinate")],
        appearances=["Mondstadt Archon Quest", "Jean Story Quest"],
        infobox={"vision": "Anemo", "weapon": "Sword",
                 "rarity": "5-star", "region": "Mondstadt",
                 "constellation": "Leo Minor",
                 "release_version": "1.0",
                 "voice_actor_en": "Mara Junot",
                 "birthday": "March 14"},
        image="gs_jean.jpg", categories=["Five-Star Characters", "Mondstadt Characters", "Playable Characters"],
        views=36_400,
    ),
    dict(title="Kazuha",
        blurb="(full name '''Kaedehara Kazuha''') is an [[Inazuman]] samurai-poet exiled from the Vision Hunt era.",
        bio=("Kazuha fled Inazuma aboard [[Beidou]]'s ship the [[Alcor]] after his friend was executed by the "
              "[[Raiden Shogun]]'s puppet. He now wanders [[Teyvat]] composing verses about the wind."),
        powers=["Anemo Vision — sword user",
                "Burst 'Manifest Razor' summons a swordfighting slash",
                "Master at swirling Elemental reactions for his team"],
        relationships=[("Beidou", "captain and ally"), ("Tomo", "deceased friend"),
                       ("Kazari", "estranged grandfather")],
        appearances=["Inazuma Archon Quest", "Kazuha Story Quest"],
        infobox={"real_name": "Kaedehara Kazuha",
                 "vision": "Anemo", "weapon": "Sword",
                 "rarity": "5-star", "region": "Inazuma",
                 "constellation": "Acer Palmatum",
                 "release_version": "1.6",
                 "voice_actor_en": "Brandon Winckler",
                 "birthday": "October 29"},
        image="gs_kazuha.jpg", categories=["Five-Star Characters", "Inazuma Characters", "Playable Characters"],
        views=82_400,
    ),
    dict(title="Ayaka",
        blurb="(full name '''Kamisato Ayaka''') is the eldest daughter of the [[Kamisato Clan]] and the [[Shirasagi Himegimi]].",
        bio=("Ayaka heads the [[Yashiro Commission]] alongside her brother [[Ayato]]. Renowned for her grace "
              "and prowess as a [[kenjutsu]] master, she balances political pressure with deep dedication to the people."),
        powers=["Cryo Vision — sword user",
                "Burst 'Soumetsu' — drifting frost lotus",
                "Master of Kamisato Art swordsmanship"],
        relationships=[("Kamisato Ayato", "elder brother"), ("Thoma", "house staff"),
                       ("Raiden Shogun", "sovereign")],
        appearances=["Inazuma Archon Quest", "Ayaka Story Quest"],
        infobox={"real_name": "Kamisato Ayaka",
                 "alias": ["Shirasagi Himegimi"],
                 "vision": "Cryo", "weapon": "Sword",
                 "rarity": "5-star", "region": "Inazuma",
                 "constellation": "Grus Nivis",
                 "release_version": "2.0",
                 "voice_actor_en": "Erica Mendez",
                 "birthday": "September 28"},
        image="gs_ayaka.jpg", categories=["Five-Star Characters", "Inazuma Characters", "Playable Characters"],
        views=64_200,
    ),
    dict(title="Tighnari",
        blurb="is the General Mahamatra-junior of the [[Avidya Forest]] [[Forest Rangers]] and a senior researcher.",
        bio=("Tighnari grew up in the rainforest under the [[Aranara]]'s tutelage and now leads the Forest Watchers. "
              "He has occasional spats with [[Cyno]] over puns versus precision."),
        powers=["Dendro Vision — bow user",
                "Tightly tuned Charged Attack — Wreath Arrow",
                "Forest survival, herbalism, monster identification"],
        relationships=[("Collei", "junior ranger"), ("Cyno", "frenemy"),
                       ("Nahida", "Archon")],
        appearances=["Sumeru Archon Quest", "Tighnari Story Quest"],
        infobox={"real_name": "Tighnari",
                 "vision": "Dendro", "weapon": "Bow",
                 "rarity": "5-star", "region": "Sumeru",
                 "constellation": "Vulpes Zerda",
                 "release_version": "3.0",
                 "voice_actor_en": "Elliot Gindi",
                 "birthday": "February 2"},
        image="gs_tighnari.jpg", categories=["Five-Star Characters", "Sumeru Characters", "Playable Characters"],
        views=39_700,
    ),
    dict(title="Alhaitham",
        blurb="is the [[Scribe]] of the [[Sumeru Akademiya]], renowned for blunt brilliance.",
        bio=("Alhaitham scored top of his year at the [[House of Daena]] and chose Scribe over Sage so that he "
              "could read in peace. He has co-authored several research papers with [[Kaveh]] and tolerates the architect's roommate status."),
        powers=["Dendro Vision — sword user",
                "Burst 'Particular Field Generator' projects floating chisel-edge mirrors",
                "Photographic memory and language gift"],
        relationships=[("Kaveh", "roommate frenemy"), ("Cyno", "Akademiya colleague"),
                       ("Nahida", "Archon")],
        appearances=["Sumeru Archon Quest", "Alhaitham Story Quest"],
        infobox={"real_name": "Alhaitham",
                 "vision": "Dendro", "weapon": "Sword",
                 "rarity": "5-star", "region": "Sumeru",
                 "constellation": "Vultur Volans",
                 "release_version": "3.4",
                 "voice_actor_en": "Brian Beacock",
                 "birthday": "February 11"},
        image="gs_alhaitham.jpg", categories=["Five-Star Characters", "Sumeru Characters", "Playable Characters"],
        views=46_800,
    ),
    dict(title="Lyney",
        blurb="is the star magician of the [[Fontaine]] [[Steambird]] cabaret circuit and a [[Fatui]] member.",
        bio=("Lyney and his sister [[Lynette]] are foundlings raised by Father [[Arlecchino]]. The siblings "
              "double as Fatui investigators in the [[Court of Fontaine]] under cover of celebrity."),
        powers=["Pyro Vision — bow user",
                "Skill: Bewildering Lights",
                "Stage magic and illusion craft"],
        relationships=[("Lynette", "twin sister"), ("Freminet", "younger brother"),
                       ("Arlecchino", "Father"), ("Furina", "frequent stage partner")],
        appearances=["Fontaine Archon Quest", "Lyney Story Quest"],
        infobox={"real_name": "Lyney",
                 "vision": "Pyro", "weapon": "Bow",
                 "rarity": "5-star", "region": "Fontaine",
                 "constellation": "Lustra Cattus",
                 "release_version": "4.0",
                 "voice_actor_en": "Robbie Daymond",
                 "birthday": "January 2"},
        image="gs_lyney.jpg", categories=["Five-Star Characters", "Fontaine Characters", "Playable Characters"],
        views=42_700,
    ),
    dict(title="Wriothesley",
        blurb="is the [[Duke]] of the [[Fortress of Meropide]] underwater prison.",
        bio=("Wriothesley was orphaned and tried for a justifiable killing as a child. He rose through the "
              "Meropide ranks to become its administrator, balancing tough rule with rehabilitation."),
        powers=["Cryo Vision — catalyst user (boxing-glove punching style)",
                "Master pugilist", "Administrative pragmatism"],
        relationships=[("Sigewinne", "head nurse"), ("Neuvillette", "official superior"),
                       ("Clorinde", "fellow Fontainian officer")],
        appearances=["Fontaine Archon Quest"],
        infobox={"real_name": "Wriothesley",
                 "vision": "Cryo", "weapon": "Catalyst",
                 "rarity": "5-star", "region": "Fontaine",
                 "constellation": "Leo Captus",
                 "release_version": "4.1",
                 "voice_actor_en": "Joe Zieja",
                 "birthday": "February 10"},
        image="gs_wriothesley.jpg", categories=["Five-Star Characters", "Fontaine Characters", "Playable Characters"],
        views=37_900,
    ),
    dict(title="Bennett",
        blurb="is the unluckiest adventurer in the [[Mondstadt Adventurers' Guild]].",
        bio=("Bennett was found in a cave as a baby and adopted by [[Benny's Adventure Team]]'s rotating "
              "guardian list. Every adventurer who has tried to officially adopt him has had to retire from "
              "field work; he himself remains spectacularly cursed yet unstoppably cheerful."),
        powers=["Pyro Vision — sword user",
                "Burst 'Fantastic Voyage' creates the team's most beloved heal-and-buff field",
                "Survives encounters that statistically should not be survivable"],
        relationships=[("Benny's Adventure Team", "guardians"), ("Razor", "wolf friend"),
                       ("Klee", "explosives buddy")],
        appearances=["Bennett Story Quest"],
        infobox={"vision": "Pyro", "weapon": "Sword",
                 "rarity": "4-star", "region": "Mondstadt",
                 "constellation": "Viator",
                 "release_version": "1.0",
                 "voice_actor_en": "Joe Zieja",
                 "birthday": "February 29"},
        image="gs_bennett.jpg", categories=["Four-Star Characters", "Mondstadt Characters", "Playable Characters"],
        views=58_900,
    ),
    dict(title="Xingqiu",
        blurb="is the second son of the Feiyun Commerce Guild and an aspiring scholar-warrior of [[Liyue]].",
        bio=("Xingqiu hides a wuxia-fan's heart under a scholar's robe. He partners with his best friend "
              "[[Chongyun]] on chivalric escapades, leaving anonymous donations and dramatic catchphrases."),
        powers=["Hydro Vision — sword user",
                "Burst 'Raincutter' summons orbiting rain swords",
                "Vast reading of wuxia novels"],
        relationships=[("Chongyun", "best friend"), ("Yun Jin", "operatic friend"),
                       ("Hu Tao", "occasional thorn-in-side")],
        appearances=["Xingqiu Story Quest", "Lantern Rite"],
        infobox={"vision": "Hydro", "weapon": "Sword",
                 "rarity": "4-star", "region": "Liyue",
                 "constellation": "Fabulae Textile",
                 "release_version": "1.0",
                 "voice_actor_en": "Jackson Dunn",
                 "birthday": "October 9"},
        image="gs_xingqiu.jpg", categories=["Four-Star Characters", "Liyue Characters", "Playable Characters"],
        views=44_200,
    ),
    dict(title="Fischl",
        blurb="(self-styled '''Prinzessin der Verurteilung''') is an investigator of the [[Mondstadt Adventurers' Guild]] accompanied by her Night Raven [[Oz]].",
        bio=("Amy Gunnhildr, who insists she be addressed as Fischl, claims to hail from the Immernachtreich. "
              "Her chuunibyou narration aside, her contracts with Oz are genuine and her marksmanship is excellent."),
        powers=["Electro Vision — bow user",
                "Summons Oz, the Prinz der Verurteilung",
                "Endurance for elaborate self-narration"],
        relationships=[("Oz", "Night Raven contract"), ("Mona", "intellectual rival"),
                       ("Albedo", "Knights of Favonius colleague")],
        appearances=["Fischl Story Quest", "Hypostatic Symphony Event"],
        infobox={"real_name": "Amy Gunnhildr",
                 "vision": "Electro", "weapon": "Bow",
                 "rarity": "4-star", "region": "Mondstadt",
                 "constellation": "Nycteris",
                 "release_version": "1.0",
                 "voice_actor_en": "Brianna Knickerbocker",
                 "birthday": "May 27"},
        image="gs_fischl.jpg", categories=["Four-Star Characters", "Mondstadt Characters", "Playable Characters"],
        views=39_400,
    ),
    dict(title="Childe",
        blurb="(real name '''Ajax''') is the youngest of the [[Eleven Fatui Harbingers]] and bears the title '''Tartaglia'''.",
        bio=("Childe stumbled into the [[Abyss]] as a child and was rescued by [[Skirk]], who trained him in "
              "another world before he returned to Snezhnaya. He now plays the cheerful sociopath for the "
              "[[Tsaritsa]]'s amusement."),
        powers=["Hydro Vision — bow / dual-blade switch",
                "Master of weapon styles across nine ranges",
                "Combat addiction matched only by [[Signora]]"],
        relationships=[("Skirk", "master"), ("Zhongli", "frenemy"),
                       ("Tsaritsa", "queen"), ("Teucer", "younger brother")],
        appearances=["Liyue Archon Quest", "Childe Story Quest", "Fontaine Archon Quest"],
        infobox={"real_name": "Ajax",
                 "alias": ["Childe", "Tartaglia"],
                 "vision": "Hydro", "weapon": "Bow / Dual blades",
                 "rarity": "5-star", "region": "Snezhnaya",
                 "constellation": "Monoceros Caeli",
                 "release_version": "1.1",
                 "voice_actor_en": "Griffin Burns",
                 "birthday": "July 20",
                 "harbinger_rank": "Eleventh"},
        image="gs_childe.jpg", categories=["Five-Star Characters", "Playable Characters"],
        views=68_400,
    ),
    dict(title="Albedo",
        blurb="is the [[Chief Alchemist]] of the [[Knights of Favonius]] and the [[Kreideprinz]] of artificial humans.",
        bio=("Albedo is a homunculus created by the alchemist Rhinedottir. He studies geological samples in "
              "[[Dragonspine]] and signs his work with the chalk-prince glyph."),
        powers=["Geo Vision — sword user",
                "Solar Isotoma platform — stationary geo construct",
                "Master alchemist and cryostudies pioneer"],
        relationships=[("Sucrose", "research assistant"), ("Klee", "older-sibling figure"),
                       ("Rhinedottir", "creator")],
        appearances=["Dragonspine update arc", "Albedo Story Quest"],
        infobox={"alias": ["Kreideprinz"],
                 "vision": "Geo", "weapon": "Sword",
                 "rarity": "5-star", "region": "Mondstadt",
                 "constellation": "Princeps Cretaceus",
                 "release_version": "1.2",
                 "voice_actor_en": "Khoi Dao",
                 "birthday": "September 13"},
        image="gs_albedo.jpg", categories=["Five-Star Characters", "Mondstadt Characters", "Playable Characters"],
        views=42_800,
    ),
    dict(title="Ningguang",
        blurb="is the [[Tianquan]] of the [[Liyue Qixing]] and proprietor of the floating [[Jade Chamber]].",
        bio=("Ningguang built her commercial empire from nothing on the harbor's docks. She runs Liyue's law "
              "and finance from the airborne Jade Chamber and is one of the most influential mortals in the Seven Nations."),
        powers=["Geo Vision — catalyst user",
                "Jade Screen barrier and Starshatter rain",
                "Encyclopedic knowledge of Liyue's economy"],
        relationships=[("Beidou", "rival"), ("Ganyu", "subordinate"),
                       ("Keqing", "fellow Qixing")],
        appearances=["Liyue Archon Quest", "Lantern Rite"],
        infobox={"vision": "Geo", "weapon": "Catalyst",
                 "rarity": "4-star", "region": "Liyue",
                 "constellation": "Opus Aequilibrium",
                 "release_version": "1.0",
                 "voice_actor_en": "Anne Yatco",
                 "birthday": "August 26"},
        image="gs_ningguang.jpg", categories=["Four-Star Characters", "Liyue Characters", "Playable Characters"],
        views=36_900,
    ),
    dict(title="Eula",
        blurb="is the [[Spindrift Knight]] of the [[Knights of Favonius]] reconnaissance company.",
        bio=("Eula is the sole adult surviving heir of the disgraced Lawrence Clan. She cultivates an air of "
              "elegant vengeance and choreographs her physical-DPS attacks like ballet."),
        powers=["Cryo Vision — claymore user",
                "Burst 'Glacial Illumination' delays a massive physical strike",
                "Master physical-damage scaler"],
        relationships=[("Amber", "outrider colleague"), ("Mika", "subordinate"),
                       ("Lawrence Clan", "estranged family")],
        appearances=["Eula Story Quest", "Hypostatic Symphony"],
        infobox={"real_name": "Eula Lawrence",
                 "vision": "Cryo", "weapon": "Claymore",
                 "rarity": "5-star", "region": "Mondstadt",
                 "constellation": "Aphros Delos",
                 "release_version": "1.5",
                 "voice_actor_en": "Suzie Yeung",
                 "birthday": "October 25"},
        image="gs_eula.jpg", categories=["Five-Star Characters", "Mondstadt Characters", "Playable Characters"],
        views=27_500,
    ),
    dict(title="Yoimiya",
        blurb="is the proprietor of [[Naganohara Fireworks]] in [[Inazuma City]] and a celebrated artisan.",
        bio=("Yoimiya inherited her family's fireworks workshop and her father's passion for community. She "
              "operates a parallel trade on the side delivering Visions abroad during the Vision Hunt era."),
        powers=["Pyro Vision — bow user",
                "Niwabi Fire-Dance rapid-fire arrows",
                "Master pyrotechnician"],
        relationships=[("Thoma", "best friend"), ("Hu Tao", "guest at festivals"),
                       ("Ayaka", "occasional customer")],
        appearances=["Inazuma Archon Quest", "Yoimiya Story Quest"],
        infobox={"real_name": "Naganohara Yoimiya",
                 "vision": "Pyro", "weapon": "Bow",
                 "rarity": "5-star", "region": "Inazuma",
                 "constellation": "Carassius Auratus",
                 "release_version": "2.0",
                 "voice_actor_en": "Jennifer Losi",
                 "birthday": "June 21"},
        image="gs_yoimiya.jpg", categories=["Five-Star Characters", "Inazuma Characters", "Playable Characters"],
        views=44_200,
    ),
    dict(title="Cyno",
        blurb="is the [[General Mahamatra]] of the [[Sumeru Akademiya]] — the inquisitor of academic misconduct.",
        bio=("Cyno was an Avidya Forest orphan adopted by [[Cyrus]] and trained as the Akademiya's executioner. "
              "He hosts the trading-card game [[Genius Invokation TCG]] and tells extremely bad jokes."),
        powers=["Electro Vision — polearm user",
                "Pactsword Judgment of Euthymia — Pharaoh-themed enhanced state",
                "Bad-pun arsenal"],
        relationships=[("Tighnari", "friend"), ("Collei", "junior"),
                       ("Cyrus", "adoptive father"), ("Nahida", "Archon")],
        appearances=["Sumeru Archon Quest", "Cyno Story Quest"],
        infobox={"real_name": "Cyno",
                 "alias": ["General Mahamatra"],
                 "vision": "Electro", "weapon": "Polearm",
                 "rarity": "5-star", "region": "Sumeru",
                 "constellation": "Lupus Aureus",
                 "release_version": "3.1",
                 "voice_actor_en": "Eric Vale",
                 "birthday": "July 27"},
        image="gs_cyno.jpg", categories=["Five-Star Characters", "Sumeru Characters", "Playable Characters"],
        views=38_800,
    ),
    dict(title="Arlecchino",
        blurb="is the [[Fourth of the Eleven Fatui Harbingers]], known as '''The Knave'''.",
        bio=("Father of the [[House of the Hearth]], Arlecchino oversees the [[Fatui]]'s orphan-soldier "
              "programme. Lyney, Lynette, and Freminet are among her most prized children."),
        powers=["Pyro Vision — polearm user (Blood-Debt Directive)",
                "Capable of casting curses by signing in blood",
                "Strategic mind feared even by the Tsaritsa"],
        relationships=[("Lyney", "child"), ("Lynette", "child"),
                       ("Freminet", "child"), ("Tsaritsa", "queen")],
        appearances=["Fontaine Archon Quest", "Arlecchino Story Quest"],
        infobox={"real_name": "Peruere", "alias": ["The Knave"],
                 "vision": "Pyro", "weapon": "Polearm",
                 "rarity": "5-star", "region": "Snezhnaya",
                 "constellation": "Ignis Purgatorius",
                 "release_version": "4.6",
                 "voice_actor_en": "Erica Lindbeck",
                 "birthday": "September 26",
                 "harbinger_rank": "Fourth"},
        image="gs_arlecchino.jpg", categories=["Five-Star Characters", "Playable Characters"],
        views=87_600,
    ),
]

_LOCATIONS = [
    dict(kind="location", title="Mondstadt",
        blurb="is the '''City of Freedom''', nation of the [[Anemo Archon]] [[Barbatos]].",
        region="Northwestern Teyvat",
        desc=("Mondstadt is the nation of wind and song, governed by the [[Knights of Favonius]] and overseen "
              "by Acting Grand Master [[Jean]]. Its city is built atop a small island in [[Cider Lake]]."),
        landmarks=["Mondstadt Cathedral", "Dawn Winery", "Stormbearer Mountains",
                   "Dragonspine"],
        inhabitants=["Jean", "Diluc", "Venti", "Lisa"],
        events=["Stormterror crisis (1.0)", "Albedo's Dragonspine expedition (1.2)"],
        infobox={"archon": "Barbatos", "element": "Anemo",
                 "ideal": "Freedom", "capital": "Mondstadt City"},
        image="gs_mondstadt.jpg", categories=["Regions"], views=66_200, featured=False,
    ),
    dict(kind="location", title="Liyue",
        blurb="is the nation of '''Contracts''', land of the [[Geo Archon]] [[Morax]].",
        region="Southeastern Teyvat",
        desc=("Liyue is the largest and oldest of the seven nations, governed politically by the [[Liyue Qixing]] "
              "and spiritually by the [[Adepti]]. Its harbor is the trade nexus of Teyvat."),
        landmarks=["Liyue Harbor", "Jueyun Karst", "Guili Plains", "Mt. Hulao"],
        inhabitants=["Zhongli", "Hu Tao", "Ningguang", "Ganyu", "Xiao"],
        events=["Rite of Descension (1.1)", "Liyue–Osial confrontation (1.1)"],
        infobox={"archon": "Morax", "element": "Geo",
                 "ideal": "Contracts", "capital": "Liyue Harbor"},
        image="gs_liyue.jpg", categories=["Regions"], views=78_400,
    ),
    dict(kind="location", title="Inazuma",
        blurb="is the '''Eternal''' island nation of the [[Electro Archon]] [[Raiden Shogun]].",
        region="Northeastern Teyvat",
        desc=("Inazuma is a chain of volcanic islands isolated by the Sakoku Decree. Ruled by the Raiden Shogun "
              "from [[Tenshukaku]] in [[Inazuma City]] on [[Narukami Island]]."),
        landmarks=["Tenshukaku", "Grand Narukami Shrine", "Watatsumi Island",
                   "Tatarasuna"],
        inhabitants=["Raiden Shogun", "Yae Miko", "Ayaka", "Kazuha"],
        events=["Vision Hunt Decree (2.0-2.1)", "Resolution of the Hyakkano Battle (2.5)"],
        infobox={"archon": "Beelzebul", "element": "Electro",
                 "ideal": "Eternity", "capital": "Inazuma City"},
        image="gs_inazuma.jpg", categories=["Regions"], views=72_900,
    ),
    dict(kind="location", title="Sumeru",
        blurb="is the '''Nation of Wisdom''', home of the [[Dendro Archon]] [[Nahida]].",
        region="Central Teyvat",
        desc=("Sumeru hosts the world's foremost academic institution, the [[Akademiya]] (built around the "
              "great tree [[Irminsul]]). The nation spans desert and rainforest."),
        landmarks=["Sumeru City / House of Daena", "Avidya Forest", "Sanctuary of Surasthana",
                   "Caravan Ribat"],
        inhabitants=["Nahida", "Tighnari", "Cyno", "Alhaitham"],
        events=["Withering crisis (3.0-3.2)", "Liberation of Nahida (3.2)"],
        infobox={"archon": "Kusanali", "element": "Dendro",
                 "ideal": "Wisdom", "capital": "Sumeru City"},
        image="gs_sumeru.jpg", categories=["Regions"], views=63_800,
    ),
    dict(kind="location", title="Fontaine",
        blurb="is the '''Nation of Justice''', once ruled by the [[Hydro Archon]] [[Focalors]].",
        region="Western Teyvat",
        desc=("Fontaine combines a Belle Époque opera-house aesthetic with Aether-punk engineering. The "
              "[[Court of Fontaine]] sits above the [[Fortress of Meropide]] underwater prison."),
        landmarks=["Court of Fontaine", "Opera Epiclese", "Fortress of Meropide",
                   "Fontaine Research Institute"],
        inhabitants=["Furina", "Neuvillette", "Lyney", "Wriothesley"],
        events=["Prophecy crisis (4.0-4.2)", "Dissolution of Focalors"],
        infobox={"archon": "Focalors / Furina",
                 "element": "Hydro", "ideal": "Justice",
                 "capital": "Court of Fontaine"},
        image="gs_fontaine.jpg", categories=["Regions"], views=98_400,
    ),
    dict(kind="location", title="Natlan",
        blurb="is the '''Nation of War''', home of the [[Pyro Archon]] [[Murata]].",
        region="South-central Teyvat",
        desc=("Natlan is a volcanic continent home to tribal civilizations bound by ancestor-saurian pacts. "
              "Released in version 5.0."),
        landmarks=["Children of Echoes village", "Speakers of the Wind perch",
                   "Stadium of the Sacred Flame"],
        inhabitants=["Mavuika", "Kachina", "Mualani"],
        events=["Awakening of the Sacred Flame (5.0)"],
        infobox={"archon": "Mavuika", "element": "Pyro",
                 "ideal": "War", "capital": "Natlan City"},
        image="gs_natlan.jpg", categories=["Regions"], views=48_400,
    ),
    dict(kind="location", title="Snezhnaya",
        blurb="is the as-yet-unexplored '''Nation of the [[Tsaritsa]]''', home of the [[Cryo Archon]].",
        region="Northern Teyvat",
        desc=("Snezhnaya is the seat of the Fatui and the Cryo Archon. The Eleven Harbingers operate from "
              "[[Zapolyarny Palace]] and conduct missions across all other nations."),
        landmarks=["Zapolyarny Palace"],
        inhabitants=["Tsaritsa", "Childe", "Arlecchino", "La Signora"],
        events=["Fatui Harbingers' coordinated Vision retrievals"],
        infobox={"archon": "Tsaritsa", "element": "Cryo", "status": "Unexplored"},
        image="gs_snezhnaya.jpg", categories=["Regions"], views=44_900,
    ),
]

_WEAPONS = [
    dict(kind="item", title="Wolf's Gravestone",
        blurb="is a five-star [[Claymore]] forged from the claymore of [[Crepus Ragnvindr]].",
        history=("Wolf's Gravestone was reforged at the [[Dawn Winery]] by [[Diluc]] himself after his father's "
                 "death. Its howl in battle is said to be a memory of the Lone Wolf."),
        powers=["Base ATK 608 — high physical scaling",
                "Passive: nearby allies gain +20% ATK on hit",
                "Iconic Diluc signature weapon"],
        wielders=["Diluc"],
        infobox={"type": "Claymore", "rarity": "5-star",
                 "base_atk": 608, "sub_stat": "ATK%"},
        image="gs_wolfsgravestone.jpg", categories=["Five-Star Weapons", "Weapons"], views=33_400,
    ),
    dict(kind="item", title="Staff of Homa",
        blurb="is a five-star [[Polearm]] of the [[Mt. Hulao]] adepti, signature of [[Hu Tao]].",
        history=("The Staff of Homa was reforged in the lower depths of Hulao by adepti craftsmen and gifted to "
                 "the Wangsheng Funeral Parlor."),
        powers=["Base ATK 608 — HP-scaled bonus damage",
                "Passive: +20% HP, +0.8% ATK per 1% HP missing",
                "Pairs natively with Hu Tao"],
        wielders=["Hu Tao", "Xiao (less optimal)"],
        infobox={"type": "Polearm", "rarity": "5-star",
                 "base_atk": 608, "sub_stat": "CRIT DMG"},
        image="gs_staffofhoma.jpg", categories=["Five-Star Weapons", "Weapons"], views=37_900,
    ),
    dict(kind="item", title="Aqua Simulacra",
        blurb="is a five-star [[Bow]] crafted from a HP/Crit-scaling Aetheria simulacrum.",
        history=("Aqua Simulacra was found in the Chasm — a wonder of long-extinct Liyue craft. Its lattice glows "
                 "when wielded by anyone with sufficient willpower."),
        powers=["Base ATK 542", "Passive: +16% HP and +20% DMG to enemies within range",
                "Yelan and Tighnari signature option"],
        wielders=["Yelan", "Tighnari"],
        infobox={"type": "Bow", "rarity": "5-star",
                 "base_atk": 542, "sub_stat": "CRIT DMG"},
        image="gs_aquasimulacra.jpg", categories=["Five-Star Weapons", "Weapons"], views=24_700,
    ),
    dict(kind="item", title="Light of Foliar Incision",
        blurb="is a five-star [[Sword]] tied to the [[Akademiya]]'s research.",
        history=("Forged in the [[House of Daena]] vaults, Light of Foliar Incision channels Dendro reactions "
                 "directly through the wielder's mind."),
        powers=["Base ATK 542",
                "Passive: Triggering Elemental reactions grants Foliar Incision",
                "Signature of [[Alhaitham]]"],
        wielders=["Alhaitham"],
        infobox={"type": "Sword", "rarity": "5-star",
                 "base_atk": 542, "sub_stat": "CRIT DMG"},
        image="gs_foliarincision.jpg", categories=["Five-Star Weapons", "Weapons"], views=18_900,
    ),
    dict(kind="item", title="Skyward Atlas",
        blurb="is a five-star [[Catalyst]] from the [[Sky Whale]] era of Mondstadt.",
        history=("Skyward Atlas was one of the original five Skyward weapons distributed across [[Teyvat]] "
                 "after the [[Cataclysm]]."),
        powers=["Base ATK 674",
                "Passive: Mod-spirits dive at enemies for additional DMG",
                "Reliable five-star catalyst BiS or near-BiS"],
        wielders=["Nahida (sub-optimal)", "Yae Miko (sub-optimal)"],
        infobox={"type": "Catalyst", "rarity": "5-star",
                 "base_atk": 674, "sub_stat": "ATK%"},
        image="gs_skyward.jpg", categories=["Five-Star Weapons", "Weapons"], views=17_200,
    ),
]

_ARTIFACTS = [
    dict(kind="item", title="Crimson Witch of Flames",
        blurb="is a five-star [[Pyro]] artifact set found in the [[Hidden Palace of Zhou Formula]] domain.",
        history=("The Crimson Witch of Flames set commemorates the alchemists who turned the Cataclysm's flames "
                 "into testable transmutation theory."),
        powers=["2-piece: +15% Pyro DMG bonus",
                "4-piece: Increases Overloaded and Burning DMG by 40%, Vaporize/Melt by 15%",
                "Pyro-DPS go-to set"],
        wielders=["Hu Tao", "Diluc", "Yoimiya"],
        infobox={"type": "Artifact set", "rarity": "5-star",
                 "domain": "Hidden Palace of Zhou Formula"},
        image="gs_crimsonwitch.jpg", categories=["Artifacts", "Items"], views=26_300,
    ),
    dict(kind="item", title="Emblem of Severed Fate",
        blurb="is a five-star artifact set boosting Burst damage from Energy Recharge.",
        history=("Emblem of Severed Fate was crafted by Inazuman blacksmiths during the Sakoku Decree."),
        powers=["2-piece: +20% Energy Recharge",
                "4-piece: +25% of Energy Recharge added to Burst DMG (cap 75%)",
                "Burst-DPS go-to set"],
        wielders=["Raiden Shogun", "Xiangling", "Eula", "Yelan"],
        infobox={"type": "Artifact set", "rarity": "5-star",
                 "domain": "Momiji-Dyed Court"},
        image="gs_emblemfate.jpg", categories=["Artifacts", "Items"], views=22_100,
    ),
]

_QUESTS = [
    ("Song of the Dragon and Freedom", "Archon Quests",
     "The Mondstadt Archon Quest where the [[Traveler]] meets [[Venti]] and faces [[Dvalin]]."),
    ("Farewell, Archaic Lord", "Archon Quests",
     "The Liyue Archon Quest where the [[Traveler]] investigates [[Rex Lapis]]'s apparent murder."),
    ("Omnipresence Over Mortals", "Archon Quests",
     "The Inazuma Archon Quest second half — defeat of the Raiden Shogun puppet."),
    ("Akasha Pulses, the Kalpa Flame Rises", "Archon Quests",
     "The Sumeru Archon Quest where [[Nahida]] is liberated."),
    ("Masquerade of the Guilty", "Archon Quests",
     "The Fontaine Archon Quest leading to Furina's confession and Focalors's dissolution."),
    ("Lupus Minor Chapter", "Story Quests", "[[Razor]]'s Story Quest about life in the Wolvendom."),
    ("Vulpes Zerda Chapter", "Story Quests", "[[Tighnari]]'s Story Quest about the Avidya Forest."),
]

_QUEST_DICTS = []
for title, cat, summary in _QUESTS:
    _QUEST_DICTS.append(dict(
        kind="quest", title=title,
        infobox={"type": "Quest", "category": cat},
        image="gs_quest.jpg", categories=["Quests", cat],
        blurb="is a Genshin Impact quest.",
        bio=summary,
        powers=[], appearances=[],
    ))

GS_ARTICLES = (
    [expand_article(d, "genshin") for d in _PLAYABLE] +
    [expand_article(d, "genshin") for d in _LOCATIONS] +
    [expand_article(d, "genshin") for d in _WEAPONS] +
    [expand_article(d, "genshin") for d in _ARTIFACTS] +
    [expand_article(d, "genshin") for d in _QUEST_DICTS]
)


GS_TALK = [
    dict(article="Diluc_Ragnvindr", subject="Best Pyro DPS?",
         body="With 5.0 power creep is Diluc still S-tier? Should we update the meta section?",
         author="HoYoLore", age_days=15),
    dict(article="Zhongli", subject="Constellation cost table",
         body="The C2 'Stone, the Cradle of Jade' description is incomplete. Adding the +20% shield strength text now.",
         author="ShinyCelestia", age_days=22),
    dict(article="Furina", subject="Animula Choragi vs Animula Choragae",
         body="The constellation name appears spelled two ways across the wiki. The official text is Choragi.",
         author="WikiBot", age_days=8),
    dict(article="Raiden_Shogun", subject="True name in lore",
         body="Article alternates between 'Ei' and 'Beelzebul' — let's set a convention. I propose 'Beelzebul (Ei)' on first mention.",
         author="HoYoLore", age_days=44),
    dict(article="Nahida", subject="Age vs lifespan",
         body="500 years old but biologically 5 years — please don't keep 'reverting' the lifespan section.",
         author="76.121.44.92", age_days=29),
    dict(article="Mondstadt", subject="Capital naming",
         body="Is the capital 'Mondstadt' or 'Mondstadt City'? Real-world parallel: 'Vatican (City)'.",
         author="EnabranTain", age_days=51),
    dict(article="Childe", subject="Hydro Vision lore",
         body="If Childe's blood is technically half-Abyssal, does his Vision still work normally? Skirk's training section needs clarification.",
         author="HoYoLore", age_days=10),
]
