"""Wookieepedia (Star Wars) wiki seed data."""
from seed_helpers import expand_article

SW_CATEGORIES = [
    {"name": "Characters"},
    {"name": "Jedi", "parent": "Characters"},
    {"name": "Sith", "parent": "Characters"},
    {"name": "Rebel Alliance", "parent": "Characters"},
    {"name": "Galactic Empire", "parent": "Characters"},
    {"name": "Mandalorians", "parent": "Characters"},
    {"name": "Bounty Hunters", "parent": "Characters"},
    {"name": "Films"},
    {"name": "Original Trilogy", "parent": "Films"},
    {"name": "Prequel Trilogy", "parent": "Films"},
    {"name": "Sequel Trilogy", "parent": "Films"},
    {"name": "Series"},
    {"name": "Locations"},
    {"name": "Planets", "parent": "Locations"},
    {"name": "Ships and Vehicles"},
    {"name": "Weapons"},
    {"name": "Lightsabers", "parent": "Weapons"},
    {"name": "Organizations"},
    {"name": "Jedi Order", "parent": "Organizations"},
    {"name": "Sith Order", "parent": "Organizations"},
]

_CHARACTERS = [
    dict(title="Luke Skywalker",
        blurb="was a [[Jedi]] Master, son of [[Anakin Skywalker]], and the hero who redeemed his father and ended the [[Galactic Empire]].",
        bio=("Luke Skywalker was born in 19 BBY on [[Polis Massa]] and raised by his uncle and aunt on [[Tatooine]]. "
             "He destroyed the first [[Death Star]] at the [[Battle of Yavin]] in 0 BBY, trained briefly under "
             "[[Yoda]] on [[Dagobah]], and turned [[Darth Vader]] back to the light in 4 ABY. He later trained "
             "[[Rey]] and projected himself across the galaxy to face [[Kylo Ren]] on [[Crait]] in 34 ABY."),
        powers=["Master of the [[Force]] — telekinesis, mind influence, projection",
                "Master lightsaber duelist (Form V — Djem So)",
                "Skilled pilot of T-65B X-wing starfighter",
                "Mechanically gifted; built his own green-bladed lightsaber"],
        relationships=[("Anakin Skywalker", "father"), ("Padmé Amidala", "mother"),
                       ("Leia Organa", "twin sister"), ("Han Solo", "brother-in-law"),
                       ("Rey", "padawan"), ("Yoda", "master")],
        appearances=["A New Hope", "The Empire Strikes Back", "Return of the Jedi",
                     "The Force Awakens", "The Last Jedi", "The Rise of Skywalker",
                     "The Mandalorian", "The Book of Boba Fett"],
        quote="No. I am a Jedi, like my father before me.",
        infobox={"real_name": "Luke Skywalker",
                 "species": "Human", "gender": "Male",
                 "born": "19 BBY", "died": "34 ABY",
                 "affiliation": ["Rebel Alliance", "New Jedi Order"],
                 "first_appearance": "A New Hope (1977)",
                 "status": "Force ghost",
                 "portrayed_by": "Mark Hamill",
                 "lightsaber_color": "Blue (later Green)"},
        image="sw_luke.jpg", categories=["Jedi", "Rebel Alliance"],
        views=92_100, featured=True,
    ),
    dict(title="Leia Organa",
        blurb="was a princess of [[Alderaan]], a leader of the [[Rebel Alliance]], a New Republic Senator, and the General of the [[Resistance]].",
        bio=("Leia Skywalker Organa Solo was born in 19 BBY, the twin sister of [[Luke Skywalker]]. As an "
             "Alderaanian princess and Imperial Senator she leaked plans of the [[Death Star]] to the Rebels. "
             "She helped destroy two Death Stars, married [[Han Solo]], lost her son [[Ben Solo]] to the dark "
             "side, and founded the [[Resistance]] against the [[First Order]]."),
        powers=["Sensitive in the Force — telekinesis, premonition",
                "Master politician and diplomat",
                "Skilled combatant with blaster and lightsaber",
                "Polyglot — 6+ languages"],
        relationships=[("Anakin Skywalker", "father"), ("Padmé Amidala", "mother"),
                       ("Luke Skywalker", "twin brother"), ("Han Solo", "husband"),
                       ("Ben Solo", "son"), ("Bail Organa", "adoptive father")],
        appearances=["A New Hope", "The Empire Strikes Back", "Return of the Jedi",
                     "The Force Awakens", "The Last Jedi", "The Rise of Skywalker"],
        quote="Help me, Obi-Wan Kenobi. You're my only hope.",
        infobox={"real_name": "Leia Amidala Skywalker",
                 "species": "Human", "gender": "Female",
                 "born": "19 BBY", "died": "35 ABY",
                 "affiliation": ["Rebel Alliance", "New Republic", "Resistance"],
                 "first_appearance": "A New Hope (1977)",
                 "status": "Deceased (one with the Force)",
                 "portrayed_by": "Carrie Fisher"},
        image="sw_leia.jpg", categories=["Rebel Alliance"], views=75_400,
    ),
    dict(title="Han Solo",
        blurb="was a [[Corellian]] smuggler, captain of the [[Millennium Falcon]], and a [[General]] of the [[Rebel Alliance]].",
        bio=("Han Solo grew up an orphan on [[Corellia]] before defecting from the Imperial Navy and partnering "
             "with [[Chewbacca]]. He joined the Rebel Alliance after meeting [[Luke Skywalker]] and [[Obi-Wan "
             "Kenobi]] on [[Tatooine]], helped destroy the second [[Death Star]] at the [[Battle of Endor]], "
             "and was killed by his own son [[Ben Solo]] on [[Starkiller Base]] in 34 ABY."),
        powers=["Master pilot — the Millennium Falcon Kessel Run in less than twelve parsecs",
                "Sharpshooter with DL-44 heavy blaster pistol",
                "Smuggler's ear for hyperspace lanes"],
        relationships=[("Chewbacca", "co-pilot and best friend"), ("Leia Organa", "wife"),
                       ("Ben Solo", "son"), ("Lando Calrissian", "frenemy"),
                       ("Luke Skywalker", "brother-in-law"), ("Qi'ra", "first love")],
        appearances=["A New Hope", "The Empire Strikes Back", "Return of the Jedi",
                     "Solo: A Star Wars Story", "The Force Awakens"],
        quote="Never tell me the odds.",
        infobox={"real_name": "Han Solo", "species": "Human", "gender": "Male",
                 "born": "32 BBY", "died": "34 ABY",
                 "affiliation": ["Rebel Alliance", "New Republic", "Smugglers"],
                 "first_appearance": "A New Hope (1977)",
                 "status": "Deceased",
                 "portrayed_by": "Harrison Ford"},
        image="sw_han.jpg", categories=["Rebel Alliance"], views=68_700,
    ),
    dict(title="Anakin Skywalker",
        blurb="was a [[Jedi Knight]] who fell to the dark side as [[Darth Vader]] before redeeming himself in 4 ABY.",
        bio=("Anakin Skywalker was born to Shmi Skywalker on [[Tatooine]] in 41 BBY, conceived by the [[Force]] "
             "itself. Trained by [[Obi-Wan Kenobi]] as a [[Jedi]] during the Clone Wars, his fear of losing "
             "[[Padmé Amidala]] led him to fall to the dark side as [[Darth Vader]]. After 23 years as Sith Lord, "
             "he killed [[Darth Sidious]] to save his son [[Luke Skywalker]] aboard the second [[Death Star]]."),
        powers=["Most powerful natural Force-sensitive recorded — Chosen One prophecy",
                "Master of all seven lightsaber forms (Form V — Djem So preferred)",
                "Force lightning (as Vader, limited by suit)",
                "Pod-racing prodigy"],
        relationships=[("Obi-Wan Kenobi", "master and brother"), ("Padmé Amidala", "wife"),
                       ("Luke Skywalker", "son"), ("Leia Organa", "daughter"),
                       ("Ahsoka Tano", "padawan"), ("Darth Sidious", "Sith master")],
        appearances=["The Phantom Menace", "Attack of the Clones", "Revenge of the Sith",
                     "The Clone Wars", "Obi-Wan Kenobi", "Rogue One", "A New Hope",
                     "The Empire Strikes Back", "Return of the Jedi"],
        quote="I am a Jedi, like my father before me.",
        infobox={"real_name": "Anakin Skywalker",
                 "alias": ["Darth Vader"],
                 "species": "Human", "gender": "Male",
                 "born": "41 BBY", "died": "4 ABY",
                 "affiliation": ["Jedi Order", "Galactic Empire"],
                 "first_appearance": "The Phantom Menace (1999)",
                 "status": "Deceased (Force ghost)",
                 "portrayed_by": "Hayden Christensen / James Earl Jones",
                 "lightsaber_color": "Blue (Jedi); Red (Sith)"},
        image="sw_anakin.jpg", categories=["Jedi", "Sith", "Galactic Empire"],
        views=98_400, featured=False,
    ),
    dict(title="Obi-Wan Kenobi",
        blurb="was a [[Jedi]] Master who trained both [[Anakin Skywalker]] and [[Luke Skywalker]].",
        bio=("Obi-Wan 'Ben' Kenobi was born in 57 BBY and trained by Qui-Gon Jinn. He was Anakin's master "
             "throughout the Clone Wars, defeated his fallen apprentice on [[Mustafar]] in 19 BBY, and exiled "
             "himself to Tatooine to watch over Luke. He died at the hands of Vader on the [[Death Star]] in "
             "0 BBY, becoming one with the Force."),
        powers=["Form III (Soresu) lightsaber master",
                "Mind influence — \"these aren't the droids you're looking for\"",
                "Negotiation: \"the negotiator\"",
                "Skilled starfighter pilot"],
        relationships=[("Qui-Gon Jinn", "master"), ("Anakin Skywalker", "padawan"),
                       ("Luke Skywalker", "later student"), ("Satine Kryze", "love interest")],
        appearances=["The Phantom Menace", "Attack of the Clones", "Revenge of the Sith",
                     "The Clone Wars", "Obi-Wan Kenobi", "A New Hope"],
        quote="Hello there.",
        infobox={"real_name": "Obi-Wan Kenobi", "alias": ["Ben Kenobi"],
                 "species": "Human", "gender": "Male",
                 "born": "57 BBY", "died": "0 BBY",
                 "affiliation": ["Jedi Order"],
                 "first_appearance": "A New Hope (1977)",
                 "status": "Deceased (Force ghost)",
                 "portrayed_by": "Ewan McGregor / Alec Guinness",
                 "lightsaber_color": "Blue"},
        image="sw_obiwan.jpg", categories=["Jedi"], views=66_400,
    ),
    dict(title="Yoda",
        blurb="was the [[Grand Master]] of the [[Jedi Order]] for over eight centuries.",
        bio=("Yoda's species is unknown. Born around 896 BBY, he led the Jedi Order through the Clone Wars, "
             "went into exile on [[Dagobah]] after the rise of the Empire, trained [[Luke Skywalker]] in 3 ABY, "
             "and died at age 900 — becoming one with the Force."),
        powers=["900 years of Force mastery — telekinesis, foresight, Force lightning deflection",
                "Form IV (Ataru) lightsaber master despite small stature",
                "Trained over 20,000 Jedi across his career"],
        relationships=[("Mace Windu", "council peer"), ("Luke Skywalker", "later student"),
                       ("Count Dooku", "former apprentice")],
        appearances=["The Phantom Menace", "Attack of the Clones", "Revenge of the Sith",
                     "The Empire Strikes Back", "Return of the Jedi", "The Last Jedi"],
        quote="Do, or do not. There is no try.",
        infobox={"real_name": "Yoda", "species": "Unknown",
                 "gender": "Male", "born": "c. 896 BBY", "died": "4 ABY",
                 "affiliation": ["Jedi Order"], "status": "Force ghost",
                 "portrayed_by": "Frank Oz (voice/puppet)",
                 "lightsaber_color": "Green"},
        image="sw_yoda.jpg", categories=["Jedi"], views=84_500,
    ),
    dict(title="Darth Vader",
        blurb="was the [[Sith]] Lord identity of fallen [[Jedi]] [[Anakin Skywalker]].",
        bio=("Anakin Skywalker fell to the dark side after [[Darth Sidious]]'s manipulation, was renamed "
             "Darth Vader, and was nearly killed on [[Mustafar]] in 19 BBY. Encased in life-support armor "
             "for 23 years, he hunted the surviving Jedi and served the Emperor until his redemption."),
        powers=["Mastery of the dark side", "Choke through the Force",
                "Custom sith lightsaber (red)", "Encased in life-support armor"],
        relationships=[("Darth Sidious", "Sith master"), ("Luke Skywalker", "son"),
                       ("Leia Organa", "daughter")],
        appearances=["Revenge of the Sith", "Rogue One", "A New Hope",
                     "The Empire Strikes Back", "Return of the Jedi", "Obi-Wan Kenobi"],
        quote="I find your lack of faith disturbing.",
        infobox={"real_name": "Anakin Skywalker", "alias": ["Darth Vader"],
                 "species": "Human (cyborg)", "gender": "Male",
                 "born": "41 BBY", "died": "4 ABY",
                 "affiliation": ["Sith Order", "Galactic Empire"],
                 "first_appearance": "A New Hope (1977)",
                 "status": "Deceased (redeemed)",
                 "portrayed_by": "David Prowse / James Earl Jones",
                 "lightsaber_color": "Red"},
        image="sw_vader.jpg", categories=["Sith", "Galactic Empire"],
        views=104_900, featured=False,
    ),
    dict(title="Darth Sidious",
        blurb="(public identity '''Sheev Palpatine''') was the [[Dark Lord of the Sith]] and the [[Galactic Emperor]].",
        bio=("Sheev Palpatine of [[Naboo]] secretly trained as a Sith under Darth Plagueis the Wise. As "
             "Supreme Chancellor he orchestrated the Clone Wars, dissolved the Republic, exterminated the "
             "Jedi via Order 66, and reigned for 23 years until his death over Endor — only to return as "
             "a clone-vessel on [[Exegol]] before being destroyed by [[Rey]]."),
        powers=["Master of dark side — Force lightning, life drain",
                "Mastery of Sith philosophy and politics across 60 years"],
        relationships=[("Darth Plagueis", "Sith master"), ("Darth Maul", "first apprentice"),
                       ("Count Dooku", "second apprentice"), ("Darth Vader", "third apprentice"),
                       ("Rey", "granddaughter via cloning")],
        appearances=["The Phantom Menace", "Attack of the Clones", "Revenge of the Sith",
                     "Return of the Jedi", "The Rise of Skywalker"],
        quote="Unlimited POWER!",
        infobox={"real_name": "Sheev Palpatine", "alias": ["Darth Sidious", "The Emperor"],
                 "species": "Human", "gender": "Male",
                 "born": "82 BBY", "died": "35 ABY",
                 "affiliation": ["Sith Order", "Galactic Empire"],
                 "first_appearance": "The Empire Strikes Back (1980)",
                 "status": "Deceased",
                 "portrayed_by": "Ian McDiarmid",
                 "lightsaber_color": "Red"},
        image="sw_sidious.jpg", categories=["Sith"], views=58_300,
    ),
    dict(title="Rey",
        blurb="(later '''Rey Skywalker''') is a [[Jedi]] trained by [[Luke Skywalker]] and [[Leia Organa]].",
        bio=("Rey was abandoned on [[Jakku]] in 11 ABY by her parents — the unfortunate granddaughter of "
             "[[Darth Sidious]]. She joined the Resistance, trained under Luke and Leia, defeated the cloned "
             "Sidious on [[Exegol]] in 35 ABY, and took the Skywalker name."),
        powers=["Strong in the Force — telepathy, healing, lightning",
                "Master scavenger, mechanic, and pilot",
                "Wields a yellow-bladed lightsaber"],
        relationships=[("Luke Skywalker", "master"), ("Leia Organa", "master"),
                       ("Ben Solo / Kylo Ren", "dyad"), ("Finn", "best friend"),
                       ("Poe Dameron", "ally")],
        appearances=["The Force Awakens", "The Last Jedi", "The Rise of Skywalker"],
        quote="I am all the Jedi.",
        infobox={"real_name": "Rey", "alias": ["Rey Skywalker"],
                 "species": "Human", "gender": "Female",
                 "born": "11 ABY",
                 "affiliation": ["Resistance", "New Jedi Order"],
                 "first_appearance": "The Force Awakens (2015)",
                 "status": "Alive",
                 "portrayed_by": "Daisy Ridley",
                 "lightsaber_color": "Yellow"},
        image="sw_rey.jpg", categories=["Jedi"], views=44_300,
    ),
    dict(title="Kylo Ren",
        blurb="(birth name '''Ben Solo''') was the apprentice of [[Snoke]] and later [[Supreme Leader]] of the [[First Order]].",
        bio=("Ben Solo, born 5 ABY to [[Han Solo]] and [[Leia Organa]], was corrupted by [[Snoke]] and razed "
             "[[Luke Skywalker]]'s new Jedi temple. As Kylo Ren he led the [[Knights of Ren]] and the "
             "[[First Order]]. He turned back to the light to fight beside [[Rey]] on [[Exegol]] and sacrificed "
             "himself to revive her."),
        powers=["Powerful Force user — telekinesis, mind probe, freeze midair",
                "Wields cross-guard red lightsaber",
                "Skilled TIE silencer pilot"],
        relationships=[("Han Solo", "father"), ("Leia Organa", "mother"),
                       ("Luke Skywalker", "uncle and master"), ("Snoke", "Sith master"),
                       ("Rey", "dyad")],
        appearances=["The Force Awakens", "The Last Jedi", "The Rise of Skywalker"],
        infobox={"real_name": "Ben Solo", "alias": ["Kylo Ren"],
                 "species": "Human", "gender": "Male",
                 "born": "5 ABY", "died": "35 ABY",
                 "affiliation": ["First Order", "Knights of Ren"],
                 "status": "Deceased (redeemed)",
                 "portrayed_by": "Adam Driver",
                 "lightsaber_color": "Red (cross-guard)"},
        image="sw_kylo.jpg", categories=["Sith"], views=52_900,
    ),
    dict(title="Ahsoka Tano",
        blurb="is a [[Togruta]] former [[Jedi]] padawan of [[Anakin Skywalker]] who became one of the wandering Force users of the post-Empire era.",
        bio=("Ahsoka Tano was assigned as Anakin's padawan at fourteen during the Clone Wars. She left the "
             "Jedi Order after being framed by Barriss Offee, survived Order 66 by dueling Maul on Mandalore, "
             "trained [[Sabine Wren]], and now seeks [[Ezra Bridger]] and [[Thrawn]] in the wider galaxy."),
        powers=["Wields white-bladed lightsabers (purified Inquisitor sabers)",
                "Form V (Jar'Kai) dual-wielding specialist",
                "Long survivor of multiple Force traumas"],
        relationships=[("Anakin Skywalker", "master"), ("Sabine Wren", "padawan"),
                       ("Captain Rex", "longtime ally"), ("Ezra Bridger", "lost friend")],
        appearances=["The Clone Wars", "Rebels", "The Mandalorian", "Ahsoka"],
        quote="I am no Jedi.",
        infobox={"real_name": "Ahsoka Tano", "alias": ["Snips", "Fulcrum"],
                 "species": "Togruta", "gender": "Female",
                 "born": "36 BBY",
                 "affiliation": ["Jedi Order (former)"],
                 "first_appearance": "The Clone Wars (2008)",
                 "status": "Alive",
                 "portrayed_by": "Rosario Dawson / Ashley Eckstein",
                 "lightsaber_color": "White"},
        image="sw_ahsoka.jpg", categories=["Jedi"], views=49_200,
    ),
    dict(title="Mace Windu",
        blurb="was a [[Jedi]] Master and member of the [[Jedi High Council]].",
        bio=("Mace Windu of [[Haruun Kal]] was second only to [[Yoda]] in influence on the Council. He wielded "
             "a unique purple-bladed lightsaber and was the only Jedi to master Form VII (Vaapad). He nearly "
             "killed [[Darth Sidious]] before [[Anakin Skywalker]] intervened."),
        powers=["Master of Form VII (Vaapad) — the channeling of dark emotion",
                "Wielder of a unique amethyst-crystal lightsaber"],
        relationships=[("Yoda", "council peer"), ("Anakin Skywalker", "council ward")],
        appearances=["The Phantom Menace", "Attack of the Clones", "Revenge of the Sith",
                     "The Clone Wars"],
        infobox={"real_name": "Mace Windu", "species": "Human", "gender": "Male",
                 "born": "72 BBY", "died": "19 BBY",
                 "affiliation": ["Jedi Order"], "status": "Deceased",
                 "portrayed_by": "Samuel L. Jackson",
                 "lightsaber_color": "Purple"},
        image="sw_windu.jpg", categories=["Jedi"], views=40_100,
    ),
    dict(title="Chewbacca",
        blurb="was a [[Wookiee]] warrior, [[Han Solo]]'s lifelong co-pilot, and decorated [[Rebel Alliance]] hero.",
        bio=("Chewbacca of [[Kashyyyk]] was rescued from Imperial slavery by Han Solo. The two became inseparable "
             "smugglers, then Rebels, and later New Republic veterans. After Han's death he flew with the "
             "Resistance and lived to see [[Sidious]]'s final fall."),
        powers=["Wookiee strength — capable of dismembering droids barehanded",
                "Bowcaster marksmanship", "Mechanically gifted"],
        relationships=[("Han Solo", "lifelong partner"), ("Lumpawaroo", "son")],
        appearances=["A New Hope", "The Empire Strikes Back", "Return of the Jedi",
                     "The Force Awakens", "The Last Jedi", "The Rise of Skywalker",
                     "Solo: A Star Wars Story"],
        infobox={"real_name": "Chewbacca", "alias": ["Chewie"],
                 "species": "Wookiee", "gender": "Male",
                 "born": "200 BBY",
                 "affiliation": ["Rebel Alliance", "Resistance"],
                 "first_appearance": "A New Hope (1977)",
                 "status": "Alive",
                 "portrayed_by": "Peter Mayhew / Joonas Suotamo"},
        image="sw_chewie.jpg", categories=["Rebel Alliance"], views=42_700,
    ),
    dict(title="Boba Fett",
        blurb="was the unaltered clone son of [[Jango Fett]] and a feared [[Mandalorian]] bounty hunter.",
        bio=("Boba Fett was raised by his bounty-hunter father Jango on [[Kamino]] and witnessed his decapitation "
             "by [[Mace Windu]]. He became the galaxy's most feared bounty hunter, captured Han Solo for "
             "[[Jabba the Hutt]], survived the Sarlacc pit, and currently rules [[Mos Espa]] alongside [[Fennec "
             "Shand]] as a daimyo."),
        powers=["Master marksman with EE-3 carbine and Z-6 rocket launcher",
                "Mandalorian armor with jet pack, flame projector, missile",
                "Skilled tracker and hand-to-hand combatant"],
        relationships=[("Jango Fett", "father / unaltered template"), ("Fennec Shand", "partner"),
                       ("Cad Bane", "rival")],
        appearances=["Attack of the Clones", "The Empire Strikes Back", "Return of the Jedi",
                     "The Mandalorian", "The Book of Boba Fett"],
        infobox={"real_name": "Boba Fett", "species": "Human (clone)",
                 "gender": "Male", "born": "32 BBY",
                 "affiliation": ["Bounty Hunters' Guild", "Mos Espa"],
                 "first_appearance": "The Empire Strikes Back (1980)",
                 "status": "Alive",
                 "portrayed_by": "Temuera Morrison"},
        image="sw_boba.jpg", categories=["Bounty Hunters", "Mandalorians"], views=58_700,
    ),
    dict(title="Din Djarin",
        blurb="(known as '''The Mandalorian''') is a Mandalorian bounty hunter and guardian of [[Grogu]].",
        bio=("Din Djarin was orphaned during the Mandalorian Purge and raised in the Way of the Watch on "
             "[[Concordia]]. After accepting a bounty for the child known as Grogu in 9 ABY, he reneged on "
             "the contract, dueled [[Bo-Katan Kryze]] for the [[Darksaber]], and now leads efforts to retake "
             "[[Mandalore]]."),
        powers=["Beskar armor of his order",
                "Wields the [[Darksaber]] (won; later passed)",
                "Whistling birds, vibro-blade, jet pack",
                "Pilot of the Razor Crest and the N-1 starfighter"],
        relationships=[("Grogu", "foundling"), ("Bo-Katan Kryze", "ally"),
                       ("Greef Karga", "associate"), ("Fennec Shand", "ally")],
        appearances=["The Mandalorian", "The Book of Boba Fett", "Ahsoka"],
        quote="This is the way.",
        infobox={"real_name": "Din Djarin", "alias": ["Mando"],
                 "species": "Human", "gender": "Male",
                 "affiliation": ["Children of the Watch", "Bounty Hunters' Guild"],
                 "first_appearance": "The Mandalorian (2019)",
                 "status": "Alive",
                 "portrayed_by": "Pedro Pascal"},
        image="sw_mando.jpg", categories=["Mandalorians", "Bounty Hunters"], views=72_300,
    ),
    dict(title="Grogu",
        blurb="is a [[Yoda]]-species infant Force-sensitive raised by [[Din Djarin]].",
        bio=("Grogu was born in 41 BBY at the [[Jedi Temple]]. He survived [[Order 66]] in cryostasis, was "
             "experimented on by [[Moff Gideon]] for his Force-rich blood, and now rides with the [[Mandalorian]] "
             "as his adopted son. He briefly trained under [[Luke Skywalker]] before choosing the way."),
        powers=["Strong in the Force despite extreme youth",
                "Telekinesis, healing, mind-influence",
                "Cuteness sufficient to disarm Mandalorian creeds"],
        relationships=[("Din Djarin", "adoptive father"), ("Luke Skywalker", "Jedi instructor")],
        appearances=["The Mandalorian", "The Book of Boba Fett"],
        infobox={"real_name": "Grogu", "alias": ["The Child", "Baby Yoda"],
                 "species": "Unknown (Yoda's species)",
                 "gender": "Male", "born": "41 BBY",
                 "affiliation": ["The Tribe (Mandalore foundling)"],
                 "first_appearance": "The Mandalorian (2019)",
                 "status": "Alive",
                 "portrayed_by": "Puppet (Joe Walker)"},
        image="sw_grogu.jpg", categories=["Mandalorians"], views=86_400,
    ),
    dict(title="Padmé Amidala",
        blurb="was the [[Queen]] and later [[Senator]] of [[Naboo]] and the secret wife of [[Anakin Skywalker]].",
        bio=("Padmé Amidala Naberrie was elected Queen of Naboo at fourteen. As Senator she opposed Palpatine's "
             "rise and founded the Delegation of the 2000 — precursor of the [[Rebel Alliance]]. She died after "
             "the birth of [[Luke Skywalker]] and [[Leia Organa]] in 19 BBY."),
        powers=["Master politician and diplomat",
                "Capable hand-to-hand combatant",
                "Symbol of moral authority on the Senate floor"],
        relationships=[("Anakin Skywalker", "husband"), ("Luke Skywalker", "son"),
                       ("Leia Organa", "daughter"), ("Bail Organa", "ally"),
                       ("Mon Mothma", "ally")],
        appearances=["The Phantom Menace", "Attack of the Clones", "Revenge of the Sith"],
        infobox={"real_name": "Padmé Amidala Naberrie",
                 "species": "Human", "gender": "Female",
                 "born": "46 BBY", "died": "19 BBY",
                 "affiliation": ["Galactic Republic"], "status": "Deceased",
                 "portrayed_by": "Natalie Portman"},
        image="sw_padme.jpg", categories=["Rebel Alliance"], views=37_800,
    ),
    dict(title="Lando Calrissian",
        blurb="is a [[Sabacc]] gambler, the former [[Baron Administrator]] of [[Cloud City]], and a [[General]] of the [[Rebel Alliance]].",
        bio=("Lando Calrissian won the [[Millennium Falcon]] from [[Han Solo]] in a Sabacc game, then lost it "
             "back. As baron of Cloud City on [[Bespin]] he reluctantly handed Han over to [[Boba Fett]] before "
             "joining the Rebellion. He led the assault on the second Death Star at the [[Battle of Endor]]."),
        powers=["Master Sabacc player and con artist",
                "Skilled pilot — captained both the Falcon and a Mon Cala cruiser",
                "Veteran diplomat and businessman"],
        relationships=[("Han Solo", "frenemy"), ("L3-37", "co-pilot"),
                       ("Jannah", "daughter")],
        appearances=["The Empire Strikes Back", "Return of the Jedi",
                     "Solo: A Star Wars Story", "The Rise of Skywalker"],
        infobox={"real_name": "Lando Calrissian", "species": "Human",
                 "gender": "Male", "affiliation": ["Rebel Alliance", "Cloud City"],
                 "first_appearance": "The Empire Strikes Back (1980)",
                 "status": "Alive",
                 "portrayed_by": "Billy Dee Williams / Donald Glover"},
        image="sw_lando.jpg", categories=["Rebel Alliance"], views=31_200,
    ),
    dict(title="R2-D2",
        blurb="is an [[Astromech]] droid who served the [[Royal House of Naboo]], the [[Jedi]], and the [[Rebel Alliance]].",
        bio=("R2-D2 served as a Naboo royal mechanic before being assigned to [[Anakin Skywalker]] and later "
             "[[Luke Skywalker]]. He has flown more astromech sorties than any other surviving unit and never had "
             "his memory wiped — making him the galaxy's most knowledgeable droid."),
        powers=["Astromech multitool — welding, slicing, projector",
                "Holographic projection",
                "Never had memory wiped"],
        relationships=[("C-3PO", "best friend"), ("Anakin Skywalker", "first owner"),
                       ("Luke Skywalker", "later owner")],
        appearances=["The Phantom Menace", "A New Hope", "The Empire Strikes Back",
                     "Return of the Jedi", "The Force Awakens", "The Last Jedi"],
        infobox={"real_name": "R2-D2", "species": "Astromech droid",
                 "gender": "Masculine programming",
                 "affiliation": ["Rebel Alliance"], "status": "Active",
                 "manufacturer": "Industrial Automaton"},
        image="sw_r2.jpg", categories=["Rebel Alliance"], views=38_500,
    ),
    dict(title="C-3PO",
        blurb="is a fastidious [[Protocol droid]] fluent in over six million forms of communication.",
        bio=("C-3PO was built by a young Anakin Skywalker on Tatooine in 32 BBY. He served Padmé, then the "
             "Skywalker twins, has had his memory wiped twice, and survived every major battle of the Skywalker "
             "saga in a more or less neurotic state."),
        powers=["Fluent in over 6 million forms of communication",
                "Etiquette and diplomacy programs"],
        relationships=[("R2-D2", "best friend"), ("Anakin Skywalker", "creator"),
                       ("Leia Organa", "owner")],
        appearances=["The Phantom Menace", "Attack of the Clones", "Revenge of the Sith",
                     "A New Hope", "The Empire Strikes Back", "Return of the Jedi",
                     "The Force Awakens", "The Last Jedi", "The Rise of Skywalker"],
        infobox={"real_name": "C-3PO", "species": "Protocol droid",
                 "gender": "Masculine programming",
                 "status": "Active",
                 "portrayed_by": "Anthony Daniels"},
        image="sw_3po.jpg", categories=["Rebel Alliance"], views=29_300,
    ),
    dict(title="Mon Mothma",
        blurb="was the founding [[Senator]] of the [[Rebel Alliance]] and first [[Chancellor]] of the [[New Republic]].",
        bio=("Mon Mothma of [[Chandrila]] was the youngest sitting Senator in the Galactic Republic. She founded "
             "the Rebel Alliance with [[Bail Organa]] and Padmé Amidala's Delegation, signed the Declaration of "
             "Rebellion in 2 BBY, and led the New Republic until 28 ABY."),
        powers=["Master politician and orator",
                "Architect of inter-system rebellion logistics"],
        relationships=[("Bail Organa", "co-founder"), ("Cassian Andor", "operative"),
                       ("Luthen Rael", "shadow contact")],
        appearances=["Return of the Jedi", "Rogue One", "Andor"],
        infobox={"real_name": "Mon Mothma", "species": "Human", "gender": "Female",
                 "affiliation": ["Rebel Alliance", "New Republic"], "status": "Alive",
                 "portrayed_by": "Genevieve O'Reilly"},
        image="sw_mothma.jpg", categories=["Rebel Alliance"], views=24_100,
    ),
    dict(title="Cassian Andor",
        blurb="was a [[Rebel Intelligence]] officer and one of the key architects of the Death Star theft on [[Scarif]].",
        bio=("Cassian Jeron Andor of Kenari grew from a rebellious thief into the most pragmatic spy of the Rebel "
             "Alliance. He led the theft of the Death Star plans on Scarif in 0 BBY and died in the same operation."),
        powers=["Master spy, slicer, and saboteur",
                "Marksman and tactician",
                "Decisive moral compass for the early Rebellion"],
        relationships=[("Jyn Erso", "partner"), ("K-2SO", "reprogrammed droid"),
                       ("Luthen Rael", "handler"), ("Mon Mothma", "patron")],
        appearances=["Rogue One", "Andor"],
        infobox={"real_name": "Cassian Jeron Andor", "species": "Human",
                 "gender": "Male", "born": "26 BBY", "died": "0 BBY",
                 "affiliation": ["Rebel Alliance"], "status": "Deceased",
                 "portrayed_by": "Diego Luna"},
        image="sw_cassian.jpg", categories=["Rebel Alliance"], views=33_400,
    ),
    dict(title="Jyn Erso",
        blurb="was the daughter of [[Death Star]] architect [[Galen Erso]] and leader of the [[Rogue One]] strike team.",
        bio=("Jyn Erso of [[Lah'mu]] was raised in hiding after her father was conscripted by the Empire. She "
             "led the Rebel team that stole the Death Star plans on [[Scarif]], dying in the operation."),
        powers=["Skilled scavenger and small-arms specialist",
                "Resilient survivor of an Imperial childhood"],
        relationships=[("Galen Erso", "father"), ("Cassian Andor", "partner"),
                       ("Saw Gerrera", "guardian")],
        appearances=["Rogue One"],
        infobox={"real_name": "Jyn Erso", "species": "Human", "gender": "Female",
                 "born": "21 BBY", "died": "0 BBY",
                 "affiliation": ["Rebel Alliance"], "status": "Deceased",
                 "portrayed_by": "Felicity Jones"},
        image="sw_jyn.jpg", categories=["Rebel Alliance"], views=27_900,
    ),
    dict(title="Bo-Katan Kryze",
        blurb="is the rightful [[Mand'alor]] and former [[Death Watch]] lieutenant.",
        bio=("Princess Bo-Katan Kryze of Clan Kryze fought beside her sister [[Satine]] and against [[Maul]] during "
             "the Clone Wars. After the [[Night of a Thousand Tears]] she leads the Mandalorian remnant — currently "
             "wielding the [[Darksaber]] returned to her by [[Din Djarin]]."),
        powers=["Master Mandalorian warrior with rocket-pack",
                "Wielder of the Darksaber"],
        relationships=[("Satine Kryze", "elder sister"), ("Din Djarin", "ally"),
                       ("Sabine Wren", "ally")],
        appearances=["The Clone Wars", "Rebels", "The Mandalorian", "The Book of Boba Fett"],
        infobox={"real_name": "Bo-Katan Kryze", "species": "Human", "gender": "Female",
                 "affiliation": ["House Kryze", "Death Watch (former)"], "status": "Alive",
                 "portrayed_by": "Katee Sackhoff"},
        image="sw_bokatan.jpg", categories=["Mandalorians"], views=31_500,
    ),
    dict(title="Grand Admiral Thrawn",
        blurb="is a [[Chiss]] military genius and a Grand Admiral of the [[Galactic Empire]].",
        bio=("Mitth'raw'nuruodo, called Thrawn, joined the Imperial Navy from the unknown regions and rose to "
             "Grand Admiral on raw tactical brilliance. He was lost into hyperspace with [[Ezra Bridger]] in "
             "1 BBY and recently returned to the known galaxy."),
        powers=["Tactical genius — studies opponents' culture and art before engagement",
                "Cool, calculating commander"],
        relationships=[("Ezra Bridger", "rival"), ("Eli Vanto", "former aide"),
                       ("Morgan Elsbeth", "ally")],
        appearances=["Rebels", "Ahsoka"],
        infobox={"real_name": "Mitth'raw'nuruodo", "alias": ["Thrawn"],
                 "species": "Chiss", "gender": "Male",
                 "affiliation": ["Galactic Empire"], "status": "Alive",
                 "portrayed_by": "Lars Mikkelsen"},
        image="sw_thrawn.jpg", categories=["Galactic Empire"], views=44_900,
    ),
    dict(title="Darth Maul",
        blurb="was a [[Dathomirian Zabrak]] Sith Lord and former apprentice of [[Darth Sidious]].",
        bio=("Maul was raised on [[Dathomir]] by the [[Nightsisters]] and given to [[Sidious]] as apprentice. "
             "He killed [[Qui-Gon Jinn]] on [[Naboo]], was bisected by [[Obi-Wan Kenobi]], rebuilt himself, "
             "led the Shadow Collective on Mandalore, and was finally killed by [[Obi-Wan Kenobi]] on [[Tatooine]] "
             "in 2 BBY."),
        powers=["Master of Form VII (Juyo) acrobatic dual-blade combat",
                "Wielder of a unique double-bladed lightsaber",
                "Hatred-fueled longevity"],
        relationships=[("Darth Sidious", "former master"), ("Savage Opress", "brother"),
                       ("Obi-Wan Kenobi", "arch-rival")],
        appearances=["The Phantom Menace", "The Clone Wars", "Rebels", "Solo: A Star Wars Story"],
        infobox={"real_name": "Maul", "alias": ["Darth Maul"],
                 "species": "Dathomirian Zabrak", "gender": "Male",
                 "born": "54 BBY", "died": "2 BBY",
                 "affiliation": ["Sith Order (former)", "Shadow Collective"],
                 "first_appearance": "The Phantom Menace (1999)",
                 "status": "Deceased",
                 "portrayed_by": "Ray Park / Sam Witwer",
                 "lightsaber_color": "Red (double-bladed)"},
        image="sw_maul.jpg", categories=["Sith"], views=47_300,
    ),
    dict(title="Count Dooku",
        blurb="was a [[Jedi]] Master turned [[Sith]] Lord under the title '''Darth Tyranus'''.",
        bio=("Count Dooku of Serenno fell to disillusion with the Jedi Order and was recruited by [[Sidious]] "
             "as second apprentice. He led the Separatist Confederacy through the Clone Wars and was beheaded "
             "by Anakin Skywalker on the [[Invisible Hand]] in 19 BBY."),
        powers=["Form II (Makashi) lightsaber master — elegant precise fencing",
                "Powerful in the dark side — Force lightning",
                "Master politician and orator"],
        relationships=[("Yoda", "former master"), ("Qui-Gon Jinn", "former padawan"),
                       ("Asajj Ventress", "apprentice"), ("Darth Sidious", "Sith master")],
        appearances=["Attack of the Clones", "Revenge of the Sith", "The Clone Wars"],
        infobox={"real_name": "Dooku", "alias": ["Darth Tyranus"],
                 "species": "Human", "gender": "Male",
                 "born": "102 BBY", "died": "19 BBY",
                 "affiliation": ["Jedi Order (former)", "Sith Order"],
                 "status": "Deceased",
                 "portrayed_by": "Christopher Lee",
                 "lightsaber_color": "Red (curved hilt)"},
        image="sw_dooku.jpg", categories=["Sith"], views=29_800,
    ),
    dict(title="General Grievous",
        blurb="was a cyborg [[Kaleesh]] warlord and the [[Supreme Commander]] of the [[Confederacy of Independent Systems]] droid army.",
        bio=("Grievous of Kalee was reborn as a cyborg after a catastrophic shuttle accident. He served as "
             "[[Count Dooku]]'s public-facing general during the Clone Wars and was killed by [[Obi-Wan Kenobi]] "
             "on [[Utapau]] in 19 BBY."),
        powers=["Four-armed lightsaber wielding — collector of fallen Jedi blades",
                "Cyborg physiology — strength, agility, but failing lungs"],
        relationships=[("Count Dooku", "commander"), ("Obi-Wan Kenobi", "rival")],
        appearances=["Revenge of the Sith", "The Clone Wars"],
        infobox={"real_name": "Grievous", "species": "Kaleesh (cyborg)",
                 "gender": "Male", "died": "19 BBY",
                 "affiliation": ["Confederacy of Independent Systems"], "status": "Deceased",
                 "portrayed_by": "Matthew Wood (voice)"},
        image="sw_grievous.jpg", categories=["Sith", "Galactic Empire"], views=33_700,
    ),
    dict(title="Sabine Wren",
        blurb="is a [[Mandalorian]] artist-warrior who trained under [[Ahsoka Tano]].",
        bio=("Sabine Wren of Clan Wren was a graffiti artist and explosives engineer who joined the Ghost crew of "
             "the [[Rebel Alliance]]. She wielded the [[Darksaber]], rallied her clan during the Imperial Era, "
             "and began Force training under [[Ahsoka]] in 9 ABY."),
        powers=["Mandalorian armor with rocket pack",
                "Master demolitionist and artist",
                "Apprentice Jedi"],
        relationships=[("Ahsoka Tano", "master"), ("Ezra Bridger", "best friend"),
                       ("Hera Syndulla", "captain")],
        appearances=["Rebels", "Ahsoka"],
        infobox={"real_name": "Sabine Wren", "species": "Human", "gender": "Female",
                 "affiliation": ["Clan Wren", "Rebel Alliance"], "status": "Alive",
                 "portrayed_by": "Natasha Liu Bordizzo"},
        image="sw_sabine.jpg", categories=["Mandalorians", "Rebel Alliance"], views=27_200,
    ),
]

_LOCATIONS = [
    dict(kind="location", title="Tatooine",
        blurb="is a remote desert planet on the [[Outer Rim]], home of the [[Skywalker]] saga's most pivotal moments.",
        region="Outer Rim Territories",
        desc=("Tatooine orbits twin suns and is famous for its moisture farms, podracing on [[Boonta Eve]], "
              "and its long association with the Hutt cartels. Anakin and Luke Skywalker were both raised here."),
        landmarks=["Mos Eisley", "Mos Espa", "Jabba's Palace", "Lars Homestead"],
        inhabitants=["Luke Skywalker (former)", "Anakin Skywalker (former)",
                     "Boba Fett", "Jabba the Hutt"],
        events=["Anakin's freedom (32 BBY)", "Cantina shootout (0 BBY)",
                "Battle of the Sarlacc (4 ABY)"],
        infobox={"region": "Outer Rim Territories",
                 "climate": "Hot, arid", "moons": 3,
                 "primary_terrain": "Desert"},
        image="sw_tatooine.jpg", categories=["Locations", "Planets"],
        views=58_100, featured=False,
    ),
    dict(kind="location", title="Coruscant",
        blurb="is the [[Galactic Republic]]'s and later [[Empire]]'s ecumenopolis capital.",
        region="Core Worlds",
        desc=("Coruscant is a single planet-wide city in the Core, home to the [[Senate Building]] and the "
              "[[Jedi Temple]]. After the Empire's fall it became the New Republic capital."),
        landmarks=["Galactic Senate Building", "Jedi Temple", "Imperial Palace",
                   "Coruscant Underworld"],
        events=["Battle of Coruscant (19 BBY)", "Operation: Cinder (4 ABY)"],
        infobox={"region": "Core Worlds", "type": "Ecumenopolis",
                 "population": "1 trillion+"},
        image="sw_coruscant.jpg", categories=["Locations", "Planets"], views=37_400,
    ),
    dict(kind="location", title="Naboo",
        blurb="is a peaceful [[Mid Rim]] planet, homeworld of [[Padmé Amidala]], [[Sheev Palpatine]], and the [[Gungan]] people.",
        region="Chommell Sector",
        desc=("Naboo is famed for its rolling green plains, royal city of Theed, and the underwater Gungan "
              "capital of Otoh Gunga. It was the site of the Trade Federation invasion in 32 BBY."),
        landmarks=["Theed Royal Palace", "Otoh Gunga", "Naboo plains"],
        inhabitants=["Padmé Amidala", "Sheev Palpatine", "Jar Jar Binks"],
        events=["Battle of Naboo (32 BBY)", "State funeral of Padmé Amidala (19 BBY)"],
        infobox={"region": "Mid Rim", "climate": "Temperate"},
        image="sw_naboo.jpg", categories=["Locations", "Planets"], views=24_100,
    ),
    dict(kind="location", title="Mandalore",
        blurb="is the homeworld of the [[Mandalorians]] and site of the catastrophic [[Night of a Thousand Tears]].",
        region="Mandalore Sector",
        desc=("Mandalore was once the seat of a warrior culture before the Empire's purge devastated it. "
              "Currently being rebuilt under [[Bo-Katan Kryze]] and [[Din Djarin]]."),
        landmarks=["Sundari", "Living Waters", "Forge of the Watch"],
        events=["Mandalorian Civil War", "Night of a Thousand Tears (5 ABY)",
                "Liberation of Mandalore (9 ABY)"],
        infobox={"region": "Mandalore Sector", "climate": "Arid (post-purge)"},
        image="sw_mandalore.jpg", categories=["Locations", "Planets"], views=31_800,
    ),
    dict(kind="location", title="Endor",
        blurb="is the forest moon orbiting the [[Endor]] gas giant, site of the [[Battle of Endor]].",
        region="Outer Rim Territories",
        desc=("The forest moon of Endor is home to the [[Ewoks]] and was the site of the second Death Star's "
              "shield bunker during the Battle of Endor in 4 ABY."),
        landmarks=["Bright Tree Village", "Shield Generator Bunker"],
        events=["Battle of Endor (4 ABY)"],
        infobox={"region": "Outer Rim", "climate": "Temperate"},
        image="sw_endor.jpg", categories=["Locations", "Planets"], views=29_300,
    ),
    dict(kind="location", title="Dagobah",
        blurb="is a swampy [[Outer Rim]] planet, the hiding place of [[Yoda]] for over twenty years.",
        region="Sluis sector",
        desc=("Dagobah is a humid bog world saturated with the [[Force]]. Its swamps hosted [[Yoda]]'s exile "
              "and the training of [[Luke Skywalker]] in 3 ABY."),
        landmarks=["Yoda's Hut", "Cave of Evil"],
        inhabitants=["Yoda"],
        infobox={"region": "Outer Rim", "climate": "Swampy"},
        image="sw_dagobah.jpg", categories=["Locations", "Planets"], views=22_700,
    ),
    dict(kind="location", title="Hoth",
        blurb="is an icy [[Outer Rim]] planet where the [[Rebel Alliance]] briefly hid Echo Base.",
        region="Outer Rim",
        desc=("Hoth is a frozen world bombarded by ice meteors. The Rebel Alliance built [[Echo Base]] "
              "here in 3 ABY before being driven off in the [[Battle of Hoth]]."),
        landmarks=["Echo Base", "Wampa Cave"],
        events=["Battle of Hoth (3 ABY)"],
        infobox={"region": "Outer Rim", "climate": "Frozen"},
        image="sw_hoth.jpg", categories=["Locations", "Planets"], views=27_500,
    ),
    dict(kind="location", title="Exegol",
        blurb="is a hidden [[Sith]] world in the Unknown Regions and the secret seat of the [[Sith Eternal]].",
        region="Unknown Regions",
        desc=("Exegol was the Sith refuge where [[Palpatine]] sustained himself in cloned forms until 35 ABY. "
              "Its sky-dock fleet of [[Xyston-class Star Destroyers]] was the climactic threat of the Sequel "
              "Trilogy."),
        landmarks=["Sith Citadel", "Wayfinder pedestals"],
        events=["Battle of Exegol (35 ABY)"],
        infobox={"region": "Unknown Regions", "climate": "Stormy, lit only by lightning"},
        image="sw_exegol.jpg", categories=["Locations", "Planets"], views=22_900,
    ),
]

_ITEMS = [
    dict(kind="item", title="Lightsaber",
        blurb="is the iconic weapon of the [[Jedi]] and [[Sith]] orders.",
        history=("Lightsabers were developed before the Hundred-Year Darkness by the Jedi. They use a [[kyber crystal]] "
                 "to focus plasma into a contained blade. Each Jedi traditionally builds their own as part of the "
                 "Padawan trials."),
        powers=["Plasma blade capable of cutting nearly any material",
                "Kyber crystal heart attuned to the wielder",
                "Color reflects the wielder's connection (blue/green: Jedi; red: bled by Sith; purple: rare;"
                " yellow: Temple Guard; white: purified)"],
        wielders=["Luke Skywalker", "Anakin Skywalker", "Obi-Wan Kenobi", "Yoda",
                  "Darth Vader", "Rey", "Kylo Ren"],
        infobox={"type": "Energy sword", "uses": "Combat, cutting, deflection"},
        image="sw_lightsaber.jpg", categories=["Weapons", "Lightsabers"],
        views=63_400, featured=True,
    ),
    dict(kind="item", title="Millennium Falcon",
        blurb="is the modified YT-1300 [[Corellian]] light freighter famously piloted by [[Han Solo]] and [[Chewbacca]].",
        history=("The Millennium Falcon was built by the [[Corellian Engineering Corporation]] in 60 BBY. "
                 "[[Lando Calrissian]] won her in a Sabacc game, then lost her to [[Han Solo]]. She made the "
                 "[[Kessel Run]] in 'less than twelve parsecs'."),
        powers=["Class 0.5 hyperdrive — fastest light freighter in service",
                "Twin quad laser cannons",
                "Mandalorian armor plating retrofits"],
        wielders=["Han Solo", "Chewbacca", "Lando Calrissian", "Rey"],
        infobox={"type": "Light freighter (YT-1300)",
                 "manufacturer": "Corellian Engineering Corporation",
                 "captain": "Han Solo (former)",
                 "famous_run": "Kessel Run in less than 12 parsecs"},
        image="sw_falcon.jpg", categories=["Ships and Vehicles"], views=58_700,
    ),
    dict(kind="item", title="Death Star",
        blurb="was the [[Galactic Empire]]'s planet-killing battle station, twice built, twice destroyed.",
        history=("The first Death Star was completed in 0 BBY and destroyed [[Alderaan]] before being blown up "
                 "at the [[Battle of Yavin]]. The second Death Star was destroyed at the [[Battle of Endor]] "
                 "in 4 ABY."),
        powers=["Superlaser — planet-destroying primary weapon",
                "Hundreds of thousands of crew",
                "Capable of housing entire Imperial fleets"],
        wielders=["Galactic Empire"],
        infobox={"type": "Battle station", "manufacturer": "Imperial Department of Military Research",
                 "status": "Destroyed (twice)"},
        image="sw_deathstar.jpg", categories=["Ships and Vehicles"], views=49_300,
    ),
    dict(kind="item", title="Darksaber",
        blurb="is a unique black-bladed [[Mandalorian]] [[lightsaber]] symbol of leadership.",
        history=("The Darksaber was created by [[Tarre Vizsla]], the first Mandalorian Jedi, around 1000 BBY. "
                 "It has been the symbol of the Mand'alor ever since, currently wielded by [[Bo-Katan Kryze]] "
                 "after [[Din Djarin]] passed it to her."),
        powers=["Unique black plasma blade", "Mandalorian symbol of unifying rulership",
                "Compatible with Mandalorian beskar"],
        wielders=["Tarre Vizsla", "Pre Vizsla", "Maul", "Sabine Wren",
                  "Bo-Katan Kryze", "Moff Gideon", "Din Djarin"],
        infobox={"type": "Unique Mandalorian lightsaber",
                 "creator": "Tarre Vizsla", "age": "approx. 1000 years"},
        image="sw_darksaber.jpg", categories=["Weapons", "Lightsabers"], views=41_800,
    ),
    dict(kind="item", title="X-wing starfighter",
        blurb="is the iconic [[Incom]] T-65B starfighter of the [[Rebel Alliance]] and [[Resistance]].",
        history=("Designed by Incom engineers who defected to the Rebellion, the T-65B X-wing has been the "
                 "Alliance's primary starfighter from 0 BBY through the Resistance era. [[Luke Skywalker]] "
                 "flew the most famous trench-run sortie in galactic history."),
        powers=["Four laser cannons", "Proton torpedoes",
                "Hyperdrive-capable", "Astromech socket"],
        wielders=["Luke Skywalker", "Wedge Antilles", "Poe Dameron"],
        infobox={"type": "Starfighter", "model": "T-65B",
                 "manufacturer": "Incom Corporation"},
        image="sw_xwing.jpg", categories=["Ships and Vehicles"], views=39_700,
    ),
    dict(kind="item", title="TIE fighter",
        blurb="is the standard [[Galactic Empire]] starfighter — Twin Ion Engine model.",
        history=("Designed by Sienar Fleet Systems, the TIE/ln has been the workhorse of the Imperial Navy. "
                 "Although unarmored and short-ranged, it overwhelms enemies by sheer numbers."),
        powers=["Twin ion engines — fast and quiet",
                "Twin laser cannons",
                "No hyperdrive, no shields, no life support"],
        wielders=["Galactic Empire", "First Order"],
        infobox={"type": "Starfighter", "model": "TIE/ln",
                 "manufacturer": "Sienar Fleet Systems"},
        image="sw_tie.jpg", categories=["Ships and Vehicles"], views=29_400,
    ),
]

_FILMS = [
    ("A New Hope", "Original Trilogy", "1977 film that started the franchise; Luke Skywalker destroys the first Death Star."),
    ("The Empire Strikes Back", "Original Trilogy", "1980 sequel; Vader reveals he is Luke's father."),
    ("Return of the Jedi", "Original Trilogy", "1983 capstone; Vader sacrifices himself, the Empire falls."),
    ("The Phantom Menace", "Prequel Trilogy", "1999 prequel; introduction of Anakin Skywalker."),
    ("Attack of the Clones", "Prequel Trilogy", "2002 sequel; the Clone Wars begin."),
    ("Revenge of the Sith", "Prequel Trilogy", "2005 finale; Anakin becomes Darth Vader."),
    ("The Force Awakens", "Sequel Trilogy", "2015 sequel-trilogy launch; introduction of Rey, Finn, Poe."),
    ("The Last Jedi", "Sequel Trilogy", "2017 sequel; Luke trains Rey on Ahch-To."),
    ("The Rise of Skywalker", "Sequel Trilogy", "2019 sequel-trilogy finale; Palpatine returns and falls."),
    ("Rogue One", "Films", "2016 standalone; the Rebel team that stole the Death Star plans."),
    ("Solo: A Star Wars Story", "Films", "2018 prequel covering Han Solo's youth."),
]

_SERIES = [
    ("The Mandalorian", "Series", "2019- series following Din Djarin and Grogu."),
    ("The Book of Boba Fett", "Series", "2021 spin-off about Boba's rise as crime lord of Tatooine."),
    ("The Clone Wars", "Series", "2008-2020 animated series covering the Clone Wars."),
    ("Rebels", "Series", "2014-2018 animated series leading into A New Hope."),
    ("Andor", "Series", "2022- live-action prequel to Rogue One."),
    ("Ahsoka", "Series", "2023- live-action series following Ahsoka Tano."),
    ("Obi-Wan Kenobi (series)", "Series", "2022 limited series with Ewan McGregor."),
]

_FILM_DICTS = [dict(kind="film", title=t, infobox={"type": "Film"},
                    image="sw_film.jpg", categories=["Films", cat],
                    blurb="is a Star Wars film.", bio=s, powers=[], appearances=[])
               for t, cat, s in _FILMS]
_SERIES_DICTS = [dict(kind="series", title=t, infobox={"type": "Series"},
                      image="sw_series.jpg", categories=[cat],
                      blurb="is a Star Wars series.", bio=s, powers=[], appearances=[])
                 for t, cat, s in _SERIES]

SW_ARTICLES = (
    [expand_article(d, "starwars") for d in _CHARACTERS] +
    [expand_article(d, "starwars") for d in _LOCATIONS] +
    [expand_article(d, "starwars") for d in _ITEMS] +
    [expand_article(d, "starwars") for d in _FILM_DICTS] +
    [expand_article(d, "starwars") for d in _SERIES_DICTS]
)

SW_TALK = [
    dict(article="Luke_Skywalker", subject="The Last Jedi characterization",
         body="Some editors keep adding 'depressed' to the lead. Per MoS we should describe in-universe events, not viewer reception.",
         author="LucasCanon", age_days=22),
    dict(article="Anakin_Skywalker", subject="Birthdate sources",
         body="Are we using AotC novelization for the 41 BBY date? Or the Visual Dictionary?",
         author="EnabranTain", age_days=11),
    dict(article="Darth_Vader", subject="Helmet damage timeline",
         body="The helmet is shown intact in Kenobi (2022) but cracked in Rebels. Continuity needs a paragraph.",
         author="WikiBot", age_days=4),
    dict(article="Mandalore", subject="Spelling of 'Mand'alor'",
         body="Per Mando S3 the apostrophe is canonical. Updating throughout.",
         author="76.121.44.92", age_days=39),
    dict(article="Darksaber", subject="Current wielder?",
         body="Bo-Katan wields it after Mando passed it to her in S3. Article needs update.",
         author="LucasCanon", age_days=16),
    dict(article="Tatooine", subject="Sand people page link",
         body="We're missing a link to the Tusken Raiders article in the inhabitants section.",
         author="EnabranTain", age_days=33),
]
