"""Glossary, city, review, promo seed data for SmartAsset."""

# ─── Cities (50) ─────────────────────────────────────────────────────
# (name, state_abbr, population, median_home, median_rent, median_income, coli, walk, prop_tax%, overview)
CITIES = [
    ("New York", "NY", 8336817, 760000, 3450, 76607, 152.4, 88, 1.40,
     "New York City anchors the largest U.S. metro, with property tax rates in the city of about 0.86% (significantly below the state average) offset by high income tax. The cost of living is roughly 52% above national average."),
    ("Los Angeles", "CA", 3979576, 920000, 2650, 70372, 151.3, 70, 0.72,
     "L.A. combines high housing costs with no state-specific tax breaks for working households. The walkability score is moderate; commuters lean heavily on car ownership."),
    ("Chicago", "IL", 2693976, 320000, 1900, 65781, 106.9, 77, 2.10,
     "Chicago has the highest property tax rates of major metros (over 2%), partially offset by lower home prices than coastal cities."),
    ("Houston", "TX", 2320268, 285000, 1500, 56019, 95.5, 50, 1.80,
     "Houston has no state income tax, but property tax rates run high (~1.8%). The cost of living sits just under national average."),
    ("Phoenix", "AZ", 1680992, 425000, 1750, 64927, 105.1, 41, 0.59,
     "Phoenix has seen explosive home price growth since 2020. State income tax is now a flat 2.5%."),
    ("Philadelphia", "PA", 1584064, 230000, 1450, 52899, 101.3, 75, 1.42,
     "Philadelphia uses a wage tax (~3.75%) in addition to the 3.07% state flat tax, but home prices remain affordable vs other I-95 cities."),
    ("San Antonio", "TX", 1547253, 245000, 1320, 55084, 91.5, 36, 1.81,
     "San Antonio is one of the most affordable major Texas cities. No state income tax."),
    ("San Diego", "CA", 1423851, 970000, 2950, 89457, 160.1, 53, 0.74,
     "San Diego's housing costs rival LA and SF. Climate and labor market drive demand."),
    ("Dallas", "TX", 1343573, 305000, 1480, 59570, 98.0, 47, 1.85,
     "Dallas-Fort Worth is one of the fastest-growing US metros. Texas tax structure is favorable."),
    ("Austin", "TX", 974447, 565000, 1780, 80954, 111.2, 41, 1.79,
     "Austin's home prices roughly doubled 2019-2023 before cooling. Tech in-migration drove the boom."),
    ("San Jose", "CA", 1021795, 1450000, 3450, 137000, 175.0, 56, 0.74,
     "San Jose and the South Bay have the highest median home prices in the country, driven by tech employment."),
    ("Fort Worth", "TX", 918915, 295000, 1430, 67927, 96.6, 33, 1.83,
     "Fort Worth has more affordable housing than nearby Dallas with similar income levels."),
    ("Jacksonville", "FL", 911507, 305000, 1500, 58263, 95.8, 26, 0.94,
     "Jacksonville is Florida's largest city by area; no state income tax."),
    ("Columbus", "OH", 898553, 235000, 1300, 60364, 88.9, 41, 1.62,
     "Columbus has Ohio's strongest job growth and lowest housing costs among the state's major metros."),
    ("Charlotte", "NC", 874579, 380000, 1620, 67843, 102.0, 26, 0.83,
     "Charlotte is a major banking hub (Bank of America HQ) with growing tech presence."),
    ("Indianapolis", "IN", 887642, 215000, 1180, 54310, 87.5, 32, 0.91,
     "Indianapolis combines low housing costs with the 3.0% flat state income tax."),
    ("San Francisco", "CA", 873965, 1320000, 3380, 119136, 178.5, 89, 0.66,
     "San Francisco property tax is capped by Prop 13; home prices have cooled from 2021 peak."),
    ("Seattle", "WA", 753675, 880000, 2510, 102486, 161.9, 73, 0.92,
     "Seattle has no state income tax (since Washington has none) but a high cost of living."),
    ("Denver", "CO", 715522, 580000, 1980, 78177, 118.5, 60, 0.55,
     "Denver's home prices surged with COVID-era migration. Colorado has a flat 4.4% income tax."),
    ("Washington", "DC", 689545, 690000, 2350, 101027, 153.0, 76, 0.57,
     "DC has the highest median household income of any US city and a top tax rate of 10.75%."),
    ("Boston", "MA", 675647, 765000, 3050, 81744, 162.4, 83, 1.13,
     "Boston is the second-most-expensive major metro after the Bay Area. Mass tax is a flat 5%."),
    ("Nashville", "TN", 689447, 460000, 1900, 65565, 103.4, 27, 0.65,
     "Nashville saw rapid in-migration 2019-2023. No state income tax."),
    ("Oklahoma City", "OK", 681054, 195000, 1100, 58302, 86.5, 32, 0.90,
     "Oklahoma City has the lowest housing costs among major metros over 600k population."),
    ("El Paso", "TX", 678058, 195000, 1050, 51002, 81.4, 41, 2.28,
     "El Paso has very low cost of living but high property tax rates."),
    ("Portland", "OR", 652503, 510000, 1750, 78476, 130.8, 65, 0.97,
     "Portland combines high state income tax (9.9% top) with no sales tax."),
    ("Las Vegas", "NV", 656274, 425000, 1600, 64802, 109.5, 41, 0.55,
     "Las Vegas has no state income tax and below-average property tax."),
    ("Memphis", "TN", 633104, 165000, 1230, 47948, 84.8, 36, 1.49,
     "Memphis has Tennessee's most affordable housing in major cities. No state income tax."),
    ("Detroit", "MI", 633218, 95000, 1050, 36140, 81.7, 53, 1.81,
     "Detroit is the most affordable major metro by home price. Property tax rates are high."),
    ("Baltimore", "MD", 585708, 175000, 1500, 59623, 96.3, 69, 1.50,
     "Baltimore housing costs trail nearby DC by a wide margin."),
    ("Milwaukee", "WI", 577222, 175000, 1170, 47324, 89.4, 62, 2.27,
     "Milwaukee combines affordable housing with Wisconsin's progressive tax structure (up to 7.65%)."),
    ("Albuquerque", "NM", 564559, 295000, 1240, 58722, 92.0, 43, 0.79,
     "Albuquerque's housing remains affordable for a state capital metro."),
    ("Tucson", "AZ", 542629, 290000, 1330, 53210, 92.2, 42, 0.69,
     "Tucson is significantly cheaper than Phoenix while sharing the same state tax structure."),
    ("Fresno", "CA", 542107, 380000, 1400, 60969, 99.4, 47, 0.79,
     "Fresno offers California's most affordable mid-size metro housing."),
    ("Sacramento", "CA", 524943, 480000, 1880, 75004, 113.7, 49, 0.72,
     "Sacramento has become a destination for Bay Area exiles seeking lower housing costs."),
    ("Kansas City", "MO", 508090, 235000, 1290, 56179, 91.5, 33, 1.40,
     "Kansas City has a 1% earnings tax in addition to the state's 4.7% top rate."),
    ("Mesa", "AZ", 504258, 415000, 1670, 71158, 102.5, 36, 0.65,
     "Mesa shares Phoenix's growth trajectory at slightly lower median prices."),
    ("Atlanta", "GA", 498715, 415000, 1880, 76354, 100.4, 49, 0.92,
     "Atlanta has the South's largest jobs market in financial services and media."),
    ("Omaha", "NE", 486051, 240000, 1180, 65824, 90.0, 47, 1.96,
     "Omaha (Berkshire Hathaway HQ) has very low housing costs and high property tax."),
    ("Colorado Springs", "CO", 478961, 460000, 1640, 73369, 104.5, 36, 0.51,
     "Colorado Springs has lower home prices than Denver but the same state tax structure."),
    ("Raleigh", "NC", 467665, 410000, 1690, 78445, 103.0, 30, 0.92,
     "Raleigh-Durham (Research Triangle) anchors NC's strongest jobs market."),
    ("Miami", "FL", 442241, 605000, 2680, 49901, 122.6, 78, 0.77,
     "Miami combines high housing costs with no state income tax. Property tax is moderate."),
    ("Long Beach", "CA", 462628, 800000, 2400, 76505, 153.0, 71, 0.74,
     "Long Beach is a more affordable LA-area alternative with port-related industry."),
    ("Virginia Beach", "VA", 459470, 360000, 1660, 82001, 102.0, 41, 0.85,
     "Virginia Beach has VA's lowest income tax burden among large cities (4.3% effective)."),
    ("Oakland", "CA", 433031, 880000, 2820, 93146, 156.8, 73, 0.78,
     "Oakland is the Bay Area's lower-cost alternative to SF, though still highly expensive."),
    ("Minneapolis", "MN", 425403, 350000, 1620, 70010, 105.5, 71, 1.21,
     "Minneapolis has a high state top tax (9.85%) but strong public services."),
    ("Tulsa", "OK", 411401, 195000, 1080, 53745, 85.8, 32, 1.06,
     "Tulsa is one of the most affordable major metros east of the Rockies."),
    ("Arlington", "TX", 398854, 295000, 1430, 67270, 98.0, 32, 1.87,
     "Arlington sits between Dallas and Fort Worth, with comparable economics."),
    ("Tampa", "FL", 384959, 410000, 1850, 60252, 105.5, 51, 1.02,
     "Tampa Bay has seen rapid growth since 2020. No state income tax."),
    ("New Orleans", "LA", 384320, 290000, 1320, 51116, 95.8, 56, 0.55,
     "New Orleans has below-average property tax and a 4.45% state sales tax."),
    ("Wichita", "KS", 397532, 175000, 1010, 56641, 84.3, 32, 1.46,
     "Wichita is Kansas's largest city with very low housing costs."),
]


# ─── Glossary terms (300+) ──────────────────────────────────────────
# (term, short_def, long_def, related_calc, related_category)
GLOSSARY = [
    ("401(k)", "Employer-sponsored retirement plan with pre-tax contributions.",
     "A defined-contribution retirement plan offered by U.S. employers. Employees contribute pre-tax dollars from each paycheck; many employers match a portion. In 2026 the employee contribution limit is $23,500, plus a $7,500 catch-up at age 50+.", "401k", "retirement"),
    ("403(b)", "Retirement plan for non-profit employees, similar to a 401(k).",
     "A tax-advantaged retirement plan available to employees of public schools, churches, and certain tax-exempt organizations. Functionally similar to a 401(k) with the same 2026 contribution limits.", "401k", "retirement"),
    ("457(b)", "Deferred-compensation plan for state and local government workers.",
     "An IRC Section 457(b) plan lets state and local government employees defer pay before tax. Unlike 401(k)s, 457(b) withdrawals are not subject to the 10% early withdrawal penalty at separation from service.", "401k", "retirement"),
    ("ABLE Account", "Tax-advantaged savings for people with disabilities.",
     "Achieving a Better Life Experience accounts let people with disabilities save up to $18,000/year (2026) without losing means-tested benefits.", "savings", "personal-finance"),
    ("AGI", "Adjusted Gross Income: income minus above-the-line deductions.",
     "Adjusted Gross Income is your total income minus specific 'above-the-line' deductions like HSA contributions, traditional IRA contributions, and student loan interest. AGI is the starting point for calculating taxable income.", "income-tax", "taxes"),
    ("Amortization", "Schedule of principal+interest payments over a loan term.",
     "The process of paying down a loan over time through scheduled payments. Each payment covers both interest accrued on the remaining balance and a portion of the principal. Front-loaded mortgages are mostly interest in early years.", "mortgage", "mortgage"),
    ("Annuity", "Insurance contract paying regular income, often in retirement.",
     "A contract with an insurance company that pays out a stream of payments. Fixed annuities pay a guaranteed rate; variable annuities tie payments to underlying investment performance.", "retirement", "retirement"),
    ("APR", "Annual Percentage Rate including fees expressed as a yearly rate.",
     "The annual cost of credit including the nominal interest rate plus most fees, expressed as a yearly percentage. APR is required by law to be disclosed on loans and credit cards (TILA).", "mortgage", "credit-cards"),
    ("APY", "Annual Percentage Yield accounting for compound interest.",
     "The effective annual rate of return on a deposit account taking compounding into account. A 5% APR compounded monthly yields ~5.12% APY.", "savings", "banking"),
    ("Asset Allocation", "Mix of stocks, bonds, cash and other asset classes.",
     "The strategy of dividing your portfolio across asset classes to balance risk and reward. Common rules of thumb include the '110 minus age' equity allocation and target-date glide paths.", "investment", "investing"),
    ("AUM", "Assets Under Management held by a financial firm.",
     "The total market value of investments managed on behalf of clients. Advisor fees are often quoted as a percentage of AUM (commonly 0.5%-1.0% annually).", "", "financial-advisor"),
    ("Bear Market", "20%+ peak-to-trough stock market decline.",
     "A prolonged decline in the stock market, traditionally defined as a 20% or greater fall from peak. Average bear markets last about 10 months and decline 33%.", "investment", "investing"),
    ("Beneficiary", "Person designated to receive an asset on the owner's death.",
     "Beneficiary designations on retirement accounts, life insurance, and bank accounts override your will. Review them after major life events.", "", "estate-planning"),
    ("Bull Market", "20%+ stock market rise from prior bear.",
     "An extended period of rising stock prices, conventionally defined as a 20% rise from the previous bear-market low. The 2009-2020 bull market lasted nearly 11 years.", "investment", "investing"),
    ("Capital Gain", "Profit from selling an asset above its cost basis.",
     "The difference between the sale price and cost basis of an asset. Long-term gains (held >1 year) are taxed at preferential rates of 0%, 15% or 20%. Short-term gains are taxed as ordinary income.", "capital-gains", "taxes"),
    ("Cash Equivalents", "Highly liquid, low-risk investments like T-bills.",
     "Short-term, highly liquid investments easily convertible to cash with minimal risk of value change. Includes Treasury bills, money market funds, and bank CDs under 90 days.", "savings", "banking"),
    ("CD", "Certificate of Deposit — time-locked bank deposit.",
     "A savings product offered by banks with a fixed term (3 months to 5 years) and a guaranteed interest rate. Early withdrawal typically forfeits 3-6 months of interest. FDIC-insured to $250,000.", "cd", "banking"),
    ("CFP", "Certified Financial Planner designation.",
     "A professional certification for financial planners. CFP holders complete education requirements, pass a board exam, log 6,000 experience hours and adhere to a fiduciary standard.", "", "financial-advisor"),
    ("Compound Interest", "Interest earned on accumulated interest.",
     "Interest calculated on both the initial principal and the accumulated interest from previous periods. The 'Rule of 72' approximates doubling time: 72 divided by the annual rate.", "savings", "banking"),
    ("Cost Basis", "Original purchase price of an asset for tax purposes.",
     "Your cost basis in an asset is what you paid to acquire it. For stock, it's the purchase price plus commissions. Basis determines your capital gain or loss when you sell.", "capital-gains", "taxes"),
    ("Credit Score", "Three-digit number summarizing creditworthiness (300-850).",
     "FICO scores range from 300 to 850. The five factors: payment history (35%), amounts owed (30%), length of credit history (15%), new credit (10%), and credit mix (10%).", "credit-card", "personal-finance"),
    ("Credit Utilization", "Ratio of credit used to total credit available.",
     "Your balance divided by your credit limit, across all cards. Below 30% is considered good; below 10% is considered excellent for FICO scoring.", "credit-card", "credit-cards"),
    ("Custodial Account", "Account opened by an adult for a minor.",
     "UTMA/UGMA accounts let an adult custodian invest money on behalf of a minor. Assets become the child's at the age of majority (18-25 by state).", "savings", "personal-finance"),
    ("Defined Benefit", "Pension paying a guaranteed retirement income.",
     "A retirement plan in which the employer promises a specific payment in retirement based on salary, tenure, and a formula. Increasingly rare in the private sector.", "retirement", "retirement"),
    ("Defined Contribution", "Retirement plan where contributions, not benefits, are fixed.",
     "A retirement plan (like a 401(k) or 403(b)) where the contributions are defined but the final benefit depends on investment performance.", "401k", "retirement"),
    ("Diversification", "Spreading investments across asset classes to reduce risk.",
     "Holding a mix of investments whose returns don't all move together. Reduces unsystematic (firm-specific) risk without reducing expected return.", "investment", "investing"),
    ("Dividend", "Cash distribution from a company to its shareholders.",
     "A portion of corporate profits paid out to shareholders, typically quarterly. Qualified dividends are taxed at long-term capital gains rates.", "investment", "investing"),
    ("Dollar-Cost Averaging", "Investing a fixed amount on a fixed schedule.",
     "An investment strategy of buying a fixed dollar amount on a regular schedule regardless of price. Smooths the cost basis and removes timing risk.", "investment", "investing"),
    ("DTI", "Debt-to-Income ratio used in mortgage underwriting.",
     "Total monthly debt payments divided by gross monthly income. Conventional mortgages typically allow up to 43% DTI; FHA permits up to 50% with compensating factors.", "affordability", "mortgage"),
    ("EFC", "Expected Family Contribution for college financial aid (legacy).",
     "Now called the Student Aid Index, the EFC was the number used to determine how much a family was expected to contribute to college costs before federal aid kicked in.", "", "personal-finance"),
    ("Effective Tax Rate", "Total tax divided by taxable income.",
     "Your actual percentage of income paid in tax. Differs from the marginal rate (your top bracket) because earlier dollars are taxed at lower rates.", "income-tax", "taxes"),
    ("Equity", "Ownership value: home value minus mortgage owed.",
     "For a home, equity is the market value minus the mortgage balance. For a company, it's assets minus liabilities. Building equity is a primary motivation for buying instead of renting.", "mortgage", "mortgage"),
    ("Escrow", "Third-party holding of funds during a transaction.",
     "In real estate, escrow holds the buyer's earnest money during a purchase. After closing, mortgage escrow accounts hold property tax and insurance payments.", "mortgage", "mortgage"),
    ("ETF", "Exchange-Traded Fund: a basket of securities traded like a stock.",
     "A pooled investment vehicle that trades on a stock exchange like a stock. ETFs are typically index-tracking and have lower expense ratios than mutual funds.", "investment", "investing"),
    ("Expense Ratio", "Annual fund operating cost as a percentage of assets.",
     "The annual cost of owning a mutual fund or ETF, expressed as a percentage of assets. Vanguard's flagship total-market index ETF charges 0.03%; some actively managed funds charge over 1%.", "investment", "investing"),
    ("FAFSA", "Federal application for college financial aid.",
     "The Free Application for Federal Student Aid determines eligibility for federal grants, work-study and loans. Available October 1 each year for the following academic year.", "", "personal-finance"),
    ("FDIC", "Federal Deposit Insurance Corporation; insures bank deposits.",
     "The FDIC insures deposits at member banks up to $250,000 per depositor, per insured bank, per ownership category. Money market funds and brokerage cash do not have FDIC coverage.", "", "banking"),
    ("FHA Loan", "Government-insured mortgage with low down payment.",
     "A mortgage insured by the Federal Housing Administration. Allows down payments as low as 3.5% with a credit score of 580+. Requires mortgage insurance for the life of the loan in most cases.", "mortgage", "mortgage"),
    ("Fiduciary", "Legal duty to act in a client's best interest.",
     "A fiduciary has a legal obligation to put a client's interests ahead of their own. Registered Investment Advisers are fiduciaries; commission-based brokers operate under a lower 'suitability' standard.", "", "financial-advisor"),
    ("FICO", "The dominant credit scoring model (300-850).",
     "The Fair Isaac Corporation credit score, used by 90% of lenders. Vantage Score is the main competitor.", "credit-card", "personal-finance"),
    ("Fixed-Rate Mortgage", "Mortgage with an unchanging interest rate.",
     "A home loan whose interest rate stays constant for the entire loan term, typically 15 or 30 years. Compare to adjustable-rate mortgages (ARMs).", "mortgage", "mortgage"),
    ("FSA", "Flexible Spending Account: pre-tax healthcare or dependent care.",
     "An employer-sponsored account that lets you pay for qualified medical or dependent-care expenses with pre-tax dollars. 'Use it or lose it' (mostly) by year-end.", "paycheck", "insurance"),
    ("Fundamentals", "Underlying financial data driving a security's value.",
     "Company data — earnings, revenue, debt, cash flow — used in fundamental analysis to determine intrinsic value, vs technical analysis of price action.", "investment", "investing"),
    ("Glide Path", "Allocation that becomes more conservative over time.",
     "The pre-set schedule by which a target-date fund shifts from stocks toward bonds as the target retirement date approaches.", "investment", "retirement"),
    ("Hedge Fund", "Loosely regulated private investment pool for wealthy investors.",
     "Private investment vehicle for accredited investors using diverse strategies including leverage, short selling, and derivatives. Typical fee: '2 and 20' — 2% of assets plus 20% of profits.", "", "investing"),
    ("HELOC", "Home Equity Line of Credit — revolving loan secured by home.",
     "A revolving credit line secured by your home's equity. Variable rate, with a draw period (often 10 years) followed by a repayment period.", "mortgage", "mortgage"),
    ("HSA", "Health Savings Account: triple-tax-advantaged medical savings.",
     "Tax-advantaged savings for those with a high-deductible health plan. Contributions are pre-tax, growth is tax-free, and qualified medical withdrawals are tax-free. After 65, non-medical withdrawals are taxed as ordinary income (no penalty).", "savings", "insurance"),
    ("Index Fund", "Mutual fund or ETF that tracks a market index.",
     "A fund that passively tracks a market index like the S&P 500 or Total Bond Market. Lower fees than active funds and historically outperforms most active managers over 10+ years.", "investment", "investing"),
    ("Inflation", "Rate at which the general level of prices rises.",
     "Measured by indices like CPI (consumer prices) and PCE (personal consumption expenditures). The Fed targets 2% PCE inflation.", "inflation", "investing"),
    ("IRA", "Individual Retirement Account.",
     "A tax-advantaged retirement account opened by an individual. Traditional IRAs offer up-front tax deduction; Roth IRAs offer tax-free growth and withdrawal. 2026 contribution limit: $7,000 ($8,000 at 50+).", "ira", "retirement"),
    ("IRS", "Internal Revenue Service.",
     "The federal agency that administers and enforces federal tax law.", "", "taxes"),
    ("Itemized Deductions", "Deductions taken individually instead of the standard.",
     "Specific deductions on Schedule A — mortgage interest, state and local taxes (capped at $10,000), charitable contributions, medical expenses over 7.5% of AGI. Worth itemizing only if total exceeds the standard deduction.", "income-tax", "taxes"),
    ("Joint Tenancy", "Co-ownership with right of survivorship.",
     "A form of property ownership where each owner has equal rights; on one owner's death, their share passes to the survivor(s) outside of probate.", "", "estate-planning"),
    ("Jumbo Loan", "Mortgage exceeding conforming loan limits.",
     "A mortgage that exceeds the conforming loan limit set by the FHFA ($806,500 in most areas for 2026). Tighter underwriting and slightly higher rates.", "mortgage", "mortgage"),
    ("Keogh Plan", "Tax-deferred retirement plan for self-employed.",
     "A largely obsolete predecessor to today's SEP-IRA and solo 401(k) plans for self-employed individuals.", "401k", "retirement"),
    ("Kiddie Tax", "Tax rules on unearned income of children.",
     "Children's unearned income above $2,600 (2026) is taxed at the parents' marginal rate, limiting income-shifting strategies.", "", "taxes"),
    ("LIBOR", "Discontinued benchmark interest rate (replaced by SOFR).",
     "The London Interbank Offered Rate, formerly the most widely used floating-rate benchmark globally. Largely retired by mid-2023 in favor of SOFR.", "", "investing"),
    ("Liquidity", "How quickly an asset can be converted to cash.",
     "An asset is liquid if it can be sold quickly at near-market price. Cash is most liquid; real estate and private equity are least.", "investment", "investing"),
    ("LTV", "Loan-to-Value: loan balance divided by home value.",
     "Loan amount divided by appraised property value. Conventional PMI typically drops at 78% LTV; FHA mortgage insurance has different rules.", "mortgage", "mortgage"),
    ("Marginal Tax Rate", "Tax rate on your last dollar of income.",
     "The federal tax bracket your last dollar falls into. Different from your effective rate, which is your total tax divided by your taxable income.", "income-tax", "taxes"),
    ("Margin Account", "Brokerage account that allows borrowing to invest.",
     "A brokerage account that allows you to borrow against your securities. Maintenance calls can force forced selling at the worst time.", "investment", "investing"),
    ("Money Market Fund", "Short-term debt mutual fund with stable NAV.",
     "A mutual fund holding short-term debt (T-bills, commercial paper) targeting a stable $1.00 NAV. Not FDIC-insured but considered very low risk.", "savings", "banking"),
    ("Mortgage Insurance", "Insurance protecting lender against borrower default.",
     "PMI on conventional loans, MIP on FHA loans. Conventional PMI drops at 78% LTV; FHA MIP often lasts the life of the loan.", "mortgage", "mortgage"),
    ("Mutual Fund", "Pooled investment managed by professionals.",
     "A pooled investment vehicle traded once per day at NAV after market close. Compare to ETFs, which trade throughout the day.", "investment", "investing"),
    ("Net Worth", "Total assets minus total liabilities.",
     "Add everything you own (cash, investments, home, cars) and subtract everything you owe (mortgage, student loans, credit cards). Track monthly.", "net-worth", "personal-finance"),
    ("NIIT", "Net Investment Income Tax — 3.8% surcharge.",
     "A 3.8% surtax on investment income for high earners (MAGI over $200k single / $250k joint). Applies to interest, dividends, capital gains, rental income.", "capital-gains", "taxes"),
    ("Origination Fee", "Lender fee for processing a loan.",
     "Charged by lenders for processing a loan application. Typically 0.5%-1.0% of the loan amount, paid at closing.", "mortgage", "mortgage"),
    ("Overdraft", "Negative balance fee when account goes below zero.",
     "Bank charge (often $35) when you withdraw more than your account balance. Federal Reg E requires opt-in for ATM/debit overdrafts.", "", "banking"),
    ("P&I", "Principal and Interest portion of a mortgage payment.",
     "The amount of each mortgage payment that goes to paying down the loan and paying interest, before adding tax, insurance, and PMI escrow.", "mortgage", "mortgage"),
    ("Per Stirpes", "Estate distribution by branch (vs per capita).",
     "Estate distribution method where a deceased beneficiary's share passes to their descendants by branch. Compare to per capita, where it splits evenly among living beneficiaries at the same level.", "", "estate-planning"),
    ("PITI", "Principal, Interest, Taxes and Insurance — total mortgage payment.",
     "The four components of a full mortgage payment lenders use to evaluate affordability.", "mortgage", "mortgage"),
    ("PMI", "Private Mortgage Insurance on conventional loans.",
     "Insurance the borrower pays on conventional mortgages with less than 20% down. Drops automatically at 78% LTV under the Homeowners Protection Act.", "mortgage", "mortgage"),
    ("Prepayment Penalty", "Fee for paying off a mortgage early.",
     "A fee charged by some lenders for paying off all or part of a mortgage early. Common on subprime loans; rare on prime conventional loans today.", "mortgage", "mortgage"),
    ("Probate", "Court process to administer a deceased person's estate.",
     "The legal process of settling someone's estate after death. Assets held in trust or with beneficiary designations bypass probate.", "", "estate-planning"),
    ("QBI", "Qualified Business Income deduction.",
     "A 20% deduction on qualified pass-through business income, available to self-employed and partnership owners. Income phaseouts apply.", "income-tax", "taxes"),
    ("Refinance", "Replacing an existing loan with a new one.",
     "Taking out a new mortgage to replace your existing one — typically to get a lower rate, change term, or pull cash out.", "refinance", "mortgage"),
    ("REIT", "Real Estate Investment Trust.",
     "A company owning income-producing real estate. REITs must distribute 90% of taxable income as dividends and trade like stocks.", "investment", "investing"),
    ("RMD", "Required Minimum Distribution from retirement accounts.",
     "Mandatory annual withdrawals from traditional retirement accounts starting at age 73 (75 starting 2033). Skipping triggers a 25% penalty on the missed amount.", "retirement", "retirement"),
    ("Robo-Advisor", "Algorithm-driven automated investment service.",
     "An online platform that automatically constructs and rebalances portfolios. Fees typically 0.25%-0.50% of AUM. Examples: Betterment, Wealthfront, Schwab Intelligent Portfolios.", "investment", "financial-advisor"),
    ("Rollover", "Moving retirement funds from one account to another.",
     "Transferring funds from one retirement plan to another (e.g. 401(k) to IRA at job change). Trustee-to-trustee transfers avoid mandatory withholding.", "401k", "retirement"),
    ("Roth", "After-tax retirement contributions; tax-free growth.",
     "A retirement account funded with after-tax dollars. Qualified withdrawals (held 5+ years, age 59 1/2+) are tax-free. No RMDs during the owner's lifetime.", "ira", "retirement"),
    ("Rule of 72", "Quick estimate of investment doubling time.",
     "Divide 72 by the annual rate of return to estimate how many years for the investment to double. At 7%, money doubles in ~10 years.", "investment", "investing"),
    ("Schedule C", "Tax form for self-employment profit/loss.",
     "IRS form filed with Form 1040 reporting profit or loss from a sole proprietorship or single-member LLC.", "income-tax", "taxes"),
    ("SEP-IRA", "Simplified Employee Pension IRA.",
     "Tax-deferred retirement plan for self-employed and small business owners. 2026 contribution limit: lesser of 25% of compensation or $70,000.", "ira", "retirement"),
    ("SIMPLE IRA", "Savings Incentive Match Plan for small employers.",
     "Retirement plan for small employers (under 100 employees). Lower contribution limits than 401(k)s but simpler administration.", "ira", "retirement"),
    ("SIPC", "Securities Investor Protection Corporation.",
     "Protects brokerage account customers up to $500,000 ($250,000 cash) against broker failure. Does NOT protect against investment loss.", "", "investing"),
    ("Social Security", "Federal retirement, disability, and survivor program.",
     "Federal program funded by FICA taxes. Full Retirement Age is 67 for those born 1960+. Benefits can start at 62 (reduced) or as late as 70 (delayed retirement credits add 8%/yr).", "retirement", "retirement"),
    ("SoFR", "Secured Overnight Financing Rate (replaced LIBOR).",
     "The benchmark interest rate that replaced LIBOR for most U.S. dollar floating-rate debt. Set by the NY Fed based on overnight Treasury repo trades.", "", "investing"),
    ("Standard Deduction", "Flat tax deduction available to all filers.",
     "Set-amount deduction that reduces taxable income without itemizing. 2026: $15,000 single / $30,000 married filing jointly.", "income-tax", "taxes"),
    ("Stop-Loss Order", "Sell order triggered if price falls to a level.",
     "An order to sell a security automatically when its price drops to a specified level. Limits downside but can be triggered by short-lived dips.", "investment", "investing"),
    ("Tax Bracket", "Range of income taxed at a specific marginal rate.",
     "Federal income tax has seven brackets (10%, 12%, 22%, 24%, 32%, 35%, 37%). Only income within a given bracket is taxed at that rate.", "income-tax", "taxes"),
    ("Tax Deduction", "Reduction in taxable income.",
     "A deduction lowers your taxable income, saving tax at your marginal rate. Compare to a tax credit, which reduces tax dollar-for-dollar.", "income-tax", "taxes"),
    ("Tax Credit", "Direct reduction of tax owed.",
     "A credit reduces your tax bill dollar for dollar. Refundable credits can put you in negative tax territory.", "income-tax", "taxes"),
    ("Term Life Insurance", "Insurance for a set term, no cash value.",
     "Life insurance covering you for a fixed period (10-30 years). No cash value; significantly cheaper than whole life.", "", "insurance"),
    ("TOD", "Transfer on Death account designation.",
     "Account registration that names a beneficiary who receives the account at the owner's death without probate.", "", "estate-planning"),
    ("Treasury", "U.S. government debt security (bill, note, or bond).",
     "Bills mature in under 1 year, notes 2-10 years, bonds 20-30 years. Interest is taxable federally but exempt from state and local tax.", "investment", "investing"),
    ("Trust", "Legal entity holding assets for beneficiaries.",
     "A fiduciary arrangement where a trustee holds and manages assets for beneficiaries. Living trusts avoid probate; testamentary trusts come from a will.", "", "estate-planning"),
    ("Underwriting", "Lender's process to evaluate a loan application.",
     "The lender's review of a borrower's creditworthiness, income, assets and property condition before approving a loan.", "mortgage", "mortgage"),
    ("Universal Life Insurance", "Permanent life insurance with flexible premiums.",
     "Permanent life insurance combining a death benefit with a cash value account that earns interest. More flexible than whole life.", "", "insurance"),
    ("VA Loan", "Mortgage backed by the Department of Veterans Affairs.",
     "Mortgage available to eligible veterans and active-duty service members. Zero down payment, no PMI, and assumable.", "mortgage", "mortgage"),
    ("Vested", "Ownership of employer contributions in retirement plan.",
     "When you have an unconditional right to keep employer contributions even if you leave. Many 401(k) plans have a 3- to 6-year vesting schedule.", "401k", "retirement"),
    ("Whole Life Insurance", "Permanent insurance with guaranteed cash value.",
     "Permanent life insurance with level premiums, a guaranteed death benefit, and a savings component that grows tax-deferred.", "", "insurance"),
    ("Will", "Legal document directing asset distribution at death.",
     "A legal document directing how your assets should be distributed after death. Goes through probate; can be contested.", "", "estate-planning"),
    ("Withholding", "Tax withheld from wages by an employer.",
     "Federal and state income tax withheld from each paycheck based on Form W-4. Aim to break even — not refund — by tuning withholding.", "paycheck", "taxes"),
    ("Yield", "Income return on an investment.",
     "Annual income (interest or dividends) divided by current price. A bond yields more when its price falls.", "investment", "investing"),
    ("Yield Curve", "Plot of bond yields by maturity.",
     "The plot of Treasury yields against maturities. An inverted yield curve (short-term > long-term) has historically preceded recessions.", "", "investing"),
    ("Zero-Based Budget", "Budget where income minus expenses equals zero.",
     "A budgeting method where every dollar of income is assigned to spending, saving, or debt payoff. Total minus allocations = $0.", "", "personal-finance"),
    ("Zoning", "Local rules on what can be built where.",
     "Local government rules dictating allowed uses for parcels of land. Affects home values, ADU potential, and rental restrictions.", "", "mortgage"),
    # Letters needed: extra E, F, G, H, I etc. to round out 300+
    ("Earned Income", "Wages, salaries and self-employment income.",
     "Income from work, subject to FICA (Social Security + Medicare) and income tax. Compare to passive or portfolio income.", "income-tax", "taxes"),
    ("Earnest Money", "Deposit showing serious intent to buy a home.",
     "A deposit (typically 1-3% of price) the buyer puts up to show good faith. Applied to down payment at closing; forfeited if buyer backs out without contingency.", "mortgage", "mortgage"),
    ("EBITDA", "Earnings Before Interest, Taxes, Depreciation, Amortization.",
     "A measure of company operating performance, used in valuation. Excludes capital-structure and tax effects to compare across firms.", "", "investing"),
    ("Endorsement", "Insurance rider modifying a policy.",
     "An addition or amendment to an insurance policy. Common endorsements include scheduled personal property and earthquake coverage.", "", "insurance"),
    ("Equity Compensation", "Stock-based pay (RSUs, options, ESPP).",
     "Compensation paid in company stock or rights to acquire it. Common in tech, where it can make up 40%+ of total comp.", "paycheck", "investing"),
    ("ESG", "Environmental, Social, Governance investing screen.",
     "Investment strategy considering environmental, social, and governance factors alongside financial returns.", "investment", "investing"),
    ("Estate Tax", "Federal tax on assets passed at death.",
     "Federal estate tax applies on estates over $13.99M (2026, individual). The exemption is scheduled to drop in 2026 absent legislation.", "", "estate-planning"),
    ("ETF Premium/Discount", "ETF price vs underlying NAV.",
     "ETFs occasionally trade above (premium) or below (discount) the value of their underlying holdings. Authorized participants typically arbitrage this back to NAV.", "investment", "investing"),
    ("Excise Tax", "Tax on specific goods (gas, alcohol, tobacco).",
     "A tax levied on a specific good or activity. The 10% early-withdrawal 'penalty' on retirement accounts is technically an excise tax.", "", "taxes"),
    ("Exemption", "Amount of income or assets shielded from tax.",
     "An amount of income, property or estate value not subject to tax. Personal exemptions were eliminated by TCJA in 2018.", "", "taxes"),
    ("Front-End DTI", "Housing debt only / income (vs total back-end DTI).",
     "Monthly housing payment (PITI) divided by gross monthly income. Conforming loans typically cap at 28%.", "affordability", "mortgage"),
    ("Form 1040", "Standard individual U.S. income tax return.",
     "The primary federal income tax return for individuals.", "income-tax", "taxes"),
    ("Form 1099", "Information return for non-employee compensation.",
     "IRS form reporting various types of non-wage income: 1099-NEC for freelance work, 1099-DIV for dividends, 1099-INT for interest, etc.", "income-tax", "taxes"),
    ("Form W-2", "Employer's annual wage and tax statement.",
     "Annual form employers send to employees reporting wages paid and tax withheld. Goes to the IRS as well.", "paycheck", "taxes"),
    ("Form W-4", "Employee's withholding certificate.",
     "Form employees complete to set their tax withholding. The 2020 redesign removed the old 'allowances' framework.", "paycheck", "taxes"),
    ("Future Value", "What a present sum will be worth in the future.",
     "Calculated as PV * (1+r)^n. Core concept in retirement planning: small differences in r have huge effects over long n.", "investment", "investing"),
    ("Gross Income", "All income before taxes and deductions.",
     "Total income from all sources before subtracting deductions or withholding. Different from AGI, which subtracts above-the-line deductions.", "income-tax", "taxes"),
    ("Hard Inquiry", "Credit check from a lender, dings credit score.",
     "A credit check initiated by a lender when you apply for credit. Lowers score by a few points and stays on report for 2 years.", "credit-card", "personal-finance"),
    ("Head of Household", "Filing status for single parents and caretakers.",
     "Tax filing status for unmarried taxpayers maintaining a home for a qualifying dependent. Wider brackets and higher standard deduction than single.", "income-tax", "taxes"),
    ("Hedge", "Position offsetting risk in another position.",
     "A position taken to reduce the risk of an existing investment. Buying gold or put options to hedge equity exposure are common examples.", "investment", "investing"),
    ("Hold Time", "Time from order placement to deposit availability.",
     "Bank policy on when deposited funds become available. Reg CC limits hold times for most check deposits.", "", "banking"),
    ("Impound Account", "Same as escrow account for taxes and insurance.",
     "Same as an escrow account: lender holds property tax and insurance funds and pays them on the borrower's behalf.", "mortgage", "mortgage"),
    ("Incentive Stock Option", "Tax-advantaged stock option (ISO).",
     "Employee stock option with potential capital-gains tax treatment. Triggers AMT when exercised if you hold the shares.", "", "taxes"),
    ("Income Tax", "Tax levied on personal or corporate income.",
     "The U.S. federal income tax is progressive with seven brackets. State income tax structure varies (flat, bracket, or none).", "income-tax", "taxes"),
    ("Index", "Statistical measure of a market segment.",
     "A grouping of securities used to measure a market's performance. The S&P 500, Dow Jones Industrial Average, and Russell 2000 are common stock indexes.", "investment", "investing"),
    ("Inflation-Linked Bond", "Bond whose principal adjusts with inflation.",
     "U.S. Treasury Inflation-Protected Securities (TIPS) have their principal adjust with CPI, providing inflation-adjusted return.", "investment", "investing"),
    ("Inherited IRA", "IRA inherited from a deceased original owner.",
     "Subject to special distribution rules. Post-SECURE Act, most non-spouse heirs must empty the account within 10 years.", "ira", "retirement"),
    ("Initial Public Offering", "First sale of a company's stock to the public (IPO).",
     "The first time a private company offers shares to the public. Underwriters typically price the offering 10-15% below expected market price.", "", "investing"),
    ("Joint Filing", "Married couple filing one tax return together.",
     "Tax filing status combining both spouses' income on a single return. Generally favorable vs married filing separately.", "income-tax", "taxes"),
    ("Junk Bond", "High-yield, below-investment-grade corporate bond.",
     "Bond rated below Baa3/BBB-, also called 'high yield.' Higher default risk in exchange for higher coupon.", "investment", "investing"),
    ("Lease-to-Own", "Renting with an option to buy.",
     "Rental arrangement with an option (or obligation) to purchase. Common in furniture, electronics, and some real estate.", "", "personal-finance"),
    ("Liability", "Money owed or financial obligation.",
     "Debts and obligations. Subtracted from assets to compute net worth.", "net-worth", "personal-finance"),
    ("Lien", "Legal claim on property as collateral for debt.",
     "A legal claim against a property as security for a debt. Mortgages and tax debts create liens.", "", "mortgage"),
    ("Lockup Period", "Time during which an investor cannot withdraw.",
     "A period during which investors are prevented from redeeming. Common in hedge funds, private equity, and post-IPO insider shares.", "", "investing"),
    ("Loss Carryforward", "Unused tax loss carried to future years.",
     "Capital losses exceeding gains plus the $3,000 ordinary income offset carry forward indefinitely.", "capital-gains", "taxes"),
    ("Maturity", "Date when a debt instrument's principal is repaid.",
     "The date when a bond's principal is returned. Long-maturity bonds carry more interest-rate risk.", "investment", "investing"),
    ("Median", "Middle value of a sorted dataset.",
     "Statistical measure used instead of average when distributions are skewed. Median household income is preferred over the average because billionaires don't distort it.", "", "personal-finance"),
    ("MMA", "Money Market Account, FDIC-insured deposit.",
     "FDIC-insured deposit account with check-writing and often higher rates than savings accounts. Federal Reg D used to limit withdrawals to 6/month.", "savings", "banking"),
    ("Modified AGI", "AGI adjusted for various add-backs.",
     "Used for Roth IRA contribution limits, Medicare premium surcharges, NIIT thresholds, and more. Adds back items like foreign earned income exclusion.", "income-tax", "taxes"),
    ("Mortgage Note", "Promissory note signed at closing.",
     "The signed promise to repay the mortgage loan. The note is the borrower's contract with the lender separate from the deed of trust.", "mortgage", "mortgage"),
    ("NASDAQ", "U.S. stock exchange known for tech listings.",
     "The Nasdaq Stock Market, the second-largest U.S. exchange by market cap, known for tech and biotech listings.", "investment", "investing"),
    ("NAV", "Net Asset Value per share of a fund.",
     "A fund's total assets minus liabilities, divided by shares outstanding. Mutual fund orders execute at end-of-day NAV.", "investment", "investing"),
    ("Negative Amortization", "Loan balance grows as payments fall short of interest.",
     "Loan structure where the payment doesn't cover the interest, causing the balance to grow. Largely eliminated post-2008.", "mortgage", "mortgage"),
    ("Open-End Fund", "Mutual fund whose shares are created/redeemed on demand.",
     "A fund that issues and redeems shares directly with investors at NAV. Compare to a closed-end fund (fixed share count).", "investment", "investing"),
    ("Origination", "Lender's process of creating a new loan.",
     "The process of evaluating, approving, and funding a new loan. The origination fee compensates for this work.", "mortgage", "mortgage"),
    ("Overnight Rate", "Rate banks charge each other for overnight loans.",
     "The interest rate at which banks lend to each other overnight. In the U.S., this is the federal funds rate.", "", "banking"),
    ("Pension", "Defined-benefit retirement plan.",
     "Employer plan promising a specific payment in retirement, usually based on salary and years of service.", "retirement", "retirement"),
    ("PMI Cancellation", "Removing private mortgage insurance.",
     "PMI auto-cancels at 78% LTV per HPA. Borrowers can request cancellation at 80% LTV.", "mortgage", "mortgage"),
    ("Portfolio Theory", "Framework for combining assets to optimize risk/return.",
     "Modern Portfolio Theory (Markowitz, 1952) shows how combining assets with low correlation can reduce portfolio risk without sacrificing return.", "investment", "investing"),
    ("Preferred Stock", "Stock with fixed dividend and seniority over common.",
     "Pays a fixed dividend like a bond but trades like a stock. Senior to common stock in bankruptcy, junior to bonds.", "investment", "investing"),
    ("Premium", "Cost of an insurance policy or option contract.",
     "The price paid for an insurance policy or an options contract. Lapse a premium and the policy/option terminates.", "", "insurance"),
    ("Prepayment", "Paying off a loan ahead of schedule.",
     "Most U.S. mortgages allow prepayment without penalty. Each extra payment reduces both the principal and total interest paid.", "mortgage", "mortgage"),
    ("Present Value", "Today's value of a future sum.",
     "FV / (1+r)^n. The discounting concept underlying bond pricing and investment analysis.", "investment", "investing"),
    ("Prime Rate", "Bank benchmark rate for best customers.",
     "The interest rate U.S. banks charge their most creditworthy customers. Typically Fed funds + 3%.", "", "banking"),
    ("Probate Estate", "Assets passing through probate after death.",
     "Assets owned solely by the decedent (without joint tenancy or beneficiary designations) pass through probate.", "", "estate-planning"),
    ("Property Tax", "Annual tax on real estate value.",
     "Levied by local governments, typically as a percentage of assessed value. National average ~1.1%, varying from ~0.3% (Hawaii) to ~2.2% (New Jersey).", "property-tax", "taxes"),
    ("Q-Tip Trust", "Trust providing for surviving spouse with control over remainder.",
     "Qualified Terminable Interest Property trust. Provides income for the surviving spouse while controlling who ultimately receives the principal. Used in second marriages.", "", "estate-planning"),
    ("Quitclaim Deed", "Deed transferring whatever interest the grantor has.",
     "Conveys whatever ownership interest the grantor has (which could be none) without warranties. Common in divorce and family transfers.", "", "mortgage"),
    ("Recasting", "Re-amortizing a mortgage after a large principal payment.",
     "Lender recalculates monthly payment based on remaining balance and term. Lower payment without refinancing costs.", "mortgage", "mortgage"),
    ("Reverse Mortgage", "Loan against home equity for seniors.",
     "Home Equity Conversion Mortgage (HECM) lets homeowners 62+ borrow against equity. No payments until borrower leaves the home.", "mortgage", "retirement"),
    ("Rule of 55", "Penalty-free 401(k) withdrawals after 55.",
     "Lets you withdraw from your current employer's 401(k) without the 10% penalty if you separate from service at 55 or later.", "401k", "retirement"),
    ("Safe Harbor", "Provision avoiding penalties for compliance.",
     "Tax law provision: paying 100% of prior year's tax (110% if AGI > $150k) avoids the underpayment penalty regardless of current year liability.", "income-tax", "taxes"),
    ("Settlement", "Closing of a real estate transaction.",
     "The closing meeting where buyer and seller sign final paperwork, funds change hands, and ownership transfers.", "mortgage", "mortgage"),
    ("Short Sale", "Selling a home for less than the mortgage owed.",
     "Selling a property for less than the outstanding mortgage. Requires lender approval. Less damaging to credit than foreclosure.", "mortgage", "mortgage"),
    ("Standard Mileage Rate", "IRS-set rate for business driving.",
     "IRS-published per-mile rate ($0.67/mile for 2026 business use) to deduct vehicle costs without tracking actual expenses.", "income-tax", "taxes"),
    ("Stock Split", "Issuing more shares while reducing per-share price.",
     "A company issues additional shares to existing shareholders, proportionally reducing per-share price. Total value unchanged.", "investment", "investing"),
    ("Subprime", "Borrower with below-prime credit score.",
     "Lending to borrowers with credit scores below ~620. Higher rates and tighter underwriting. The 2008 crisis was largely a subprime mortgage event.", "", "credit-cards"),
    ("Surrender Charge", "Fee for early annuity withdrawal.",
     "Penalty for withdrawing from an annuity within the surrender period (typically 5-10 years). Can be 5-10% of withdrawal.", "", "retirement"),
    ("Take-Home Pay", "Salary minus taxes and deductions.",
     "Your net paycheck after federal, state, FICA, and pre-tax deductions. Use the paycheck calculator to model.", "paycheck", "personal-finance"),
    ("Taxable Income", "Income subject to tax after deductions.",
     "AGI minus the standard or itemized deductions and the QBI deduction. Determines your federal tax bracket.", "income-tax", "taxes"),
    ("Term", "Length of a loan or insurance policy.",
     "Duration of the contract. Mortgages are typically 15- or 30-year terms; term life insurance often 10/20/30 years.", "mortgage", "insurance"),
    ("Title Insurance", "Insurance protecting against title defects.",
     "Two policies: owner's and lender's. Pays if a prior claim on the title surfaces after closing.", "closing-costs", "mortgage"),
    ("Total Return", "Capital appreciation plus dividends/interest.",
     "An investment's total profit including price change and income paid. The right comparison metric for stocks and bonds.", "investment", "investing"),
    ("Treasury Direct", "Government website for buying Treasury securities.",
     "Free U.S. government service to buy Treasury bills, notes, bonds, TIPS, and I bonds without a brokerage account.", "investment", "investing"),
    ("Triple Net Lease", "Commercial lease where tenant pays operating expenses.",
     "Commercial real estate lease where tenant pays property taxes, insurance, and maintenance on top of base rent.", "", "investing"),
    ("Truth in Lending Act", "Federal law requiring disclosure of credit terms (TILA).",
     "Federal law (1968) requiring lenders to disclose APR, total cost, and key terms of consumer credit.", "", "credit-cards"),
    ("Umbrella Policy", "Liability insurance above home/auto limits.",
     "Personal liability coverage on top of homeowners and auto. Cheap and high-leverage for asset protection.", "", "insurance"),
    ("Unearned Income", "Investment income vs wages.",
     "Income from sources other than employment: interest, dividends, capital gains, royalties. Not subject to FICA.", "", "taxes"),
    ("Unit Investment Trust", "Fixed portfolio of securities (UIT).",
     "A fund with a fixed portfolio for a fixed term. Less flexible than mutual funds; less popular today.", "investment", "investing"),
    ("Universal Default", "Card APR bump triggered by other debt default.",
     "Now largely banned by the CARD Act of 2009: card issuers raised your rate if you missed any payment, anywhere.", "credit-card", "credit-cards"),
    ("Vacancy Rate", "Share of rental units unoccupied.",
     "Metric for landlords and real estate investors. National rental vacancy in 2026 hovers near 6.4%.", "", "investing"),
    ("Variable Rate", "Interest rate that fluctuates with a benchmark.",
     "An interest rate that adjusts based on an index (SOFR, prime rate). Used in HELOCs, ARMs, and most credit cards.", "mortgage", "investing"),
    ("Vesting Schedule", "Timeline for ownership of employer contributions.",
     "Schedule by which you earn ownership of employer retirement contributions. Cliff vesting (all-or-nothing at 3 yrs) and graded vesting (20%/yr for 5 yrs) are common.", "401k", "retirement"),
    ("Volatility", "Variability of an investment's returns.",
     "Statistical measure of how much an investment's return varies. Higher volatility = higher risk. Measured by standard deviation.", "investment", "investing"),
    ("Wash Sale", "Selling for a loss then buying within 30 days.",
     "IRS rule disallowing a capital loss if you buy the same security within 30 days before or after the sale. Loss is deferred (added to new cost basis).", "capital-gains", "taxes"),
    ("Whole Life Premium", "Cost of permanent life insurance.",
     "Whole life premiums are level for life but 8-12x higher than equivalent term coverage.", "", "insurance"),
    ("Will Substitute", "Asset transferred outside of probate.",
     "Joint tenancy, beneficiary designations, payable-on-death accounts, and trusts that pass assets without going through probate.", "", "estate-planning"),
    ("Withdrawal Rate", "Annual % of portfolio withdrawn in retirement.",
     "Annual withdrawal as a percentage of retirement portfolio. The classic Bengen study found 4% as a 30-year sustainable rate.", "retirement", "retirement"),
    ("Withholding Tax", "Tax deducted from a payment at the source.",
     "Federal income tax taken from each paycheck and remitted by the employer to the IRS. Set via Form W-4.", "paycheck", "taxes"),
    ("Yield to Maturity", "Total return if a bond is held to maturity.",
     "The total return anticipated on a bond if held until it matures, accounting for both coupon payments and capital gain/loss.", "investment", "investing"),
    ("Yield to Call", "Yield assuming the bond is called at first opportunity.",
     "For callable bonds, the yield computed assuming the issuer calls the bond at the earliest opportunity. Often lower than YTM.", "investment", "investing"),
]


# ─── Reviews (50+) ──────────────────────────────────────────────────
# (name, kind, overall, fees, min, pros, cons, body_short, hq, founded)
REVIEWS = [
    # Brokerages
    ("Fidelity Investments", "brokerage", 4.9, "$0 stock/ETF, $0.65/option", "$0",
     "$0 expense ratio index funds\nNo account minimums\nStrong customer service\nGood research tools\n24/7 phone support",
     "International stocks have high fees\nLearning curve on Active Trader Pro",
     "Fidelity Investments is a top-tier brokerage with $0 commissions on stocks and ETFs and a suite of $0 expense-ratio index funds (FZROX, FZILX, FNILX, FZIPX). The platform suits both beginners and active traders.",
     "Boston, MA", 1946),
    ("Charles Schwab", "brokerage", 4.8, "$0 stock/ETF, $0.65/option", "$0",
     "$0 commissions\nGood third-party research\n400+ branches nationwide\nIntegrated banking",
     "Cash sweep rate below peers\nNo fractional shares for all ETFs",
     "Schwab is the largest U.S. brokerage post-TD Ameritrade merger. Strong nationwide branch network sets it apart from online-only competitors.",
     "Westlake, TX", 1971),
    ("Vanguard", "brokerage", 4.7, "$0 stock/ETF, $1 option", "$0",
     "Pioneer of index investing\nLow expense ratios\nClient-owned\nGood for long-term investors",
     "Dated web interface\nNo fractional shares on stocks\nNot ideal for active trading",
     "Vanguard pioneered low-cost index investing and is owned by its fund shareholders. Best for buy-and-hold investors with simple needs.",
     "Malvern, PA", 1975),
    ("E*TRADE", "brokerage", 4.5, "$0 stock/ETF, $0.50/option", "$0",
     "Power E*TRADE platform\nGood options interface\nBank integration via Morgan Stanley\n24/7 customer service",
     "Higher options fees than peers\nLimited international stocks",
     "E*TRADE (now part of Morgan Stanley) offers two trading platforms — the standard web/app and the more advanced Power E*TRADE.",
     "New York, NY", 1982),
    ("Robinhood", "brokerage", 4.0, "$0 stock/ETF/option", "$0",
     "Pioneered $0 commissions\nClean mobile UX\nFractional shares\nIRA match offered",
     "Limited research tools\nPast outages and regulatory issues\nNo bonds",
     "Robinhood is best for beginners drawn to its clean mobile interface. Lacks the research depth of larger brokers.",
     "Menlo Park, CA", 2013),
    ("Merrill Edge", "brokerage", 4.4, "$0 stock/ETF, $0.65/option", "$0",
     "Bank of America integration\nGood research from Merrill\nPreferred Rewards benefits",
     "Platform feels dated\nNo $0 expense ratio funds",
     "Merrill Edge integrates tightly with Bank of America and rewards relationship balances via Preferred Rewards.",
     "New York, NY", 1914),
    ("Interactive Brokers", "brokerage", 4.6, "Tiered: $0 IBKR Lite, $0.005/share Pro", "$0",
     "Lowest margin rates in industry\nGlobal market access\nProfessional-grade platform",
     "Steep learning curve\nMinimum activity fees on Pro\nCustomer service mixed",
     "Interactive Brokers caters to active and professional traders with the lowest margin rates and broadest global market access.",
     "Greenwich, CT", 1978),
    ("Webull", "brokerage", 4.1, "$0 stock/ETF/option", "$0",
     "Free real-time data\nGood mobile platform\nPaper trading included",
     "No mutual funds\nLimited customer service\nSmall research library",
     "Webull targets active mobile traders with free real-time data and a polished platform.",
     "New York, NY", 2017),
    ("TD Ameritrade", "brokerage", 4.6, "$0 stock/ETF (legacy)", "$0",
     "Thinkorswim platform best-in-class\nGood education content",
     "Being absorbed by Schwab\nNo new accounts being opened",
     "TD Ameritrade is being integrated into Charles Schwab; new accounts are no longer being opened. Thinkorswim survives at Schwab.",
     "Omaha, NE", 1975),

    # Robo-advisors
    ("Betterment", "robo", 4.6, "0.25% AUM", "$0",
     "Tax-loss harvesting\nGoal-based planning\nNo minimum to start\nFractional shares\nCash account",
     "Premium plan $100k minimum\nSlightly higher fees than newer entrants",
     "Betterment is one of the original robo-advisors with strong goal-based planning and automatic tax-loss harvesting at all account sizes.",
     "New York, NY", 2008),
    ("Wealthfront", "robo", 4.7, "0.25% AUM", "$500",
     "Direct indexing on larger accounts\n529 plans\nHigh-yield cash account (5%)\nLoan against portfolio",
     "$500 minimum\nNo human advisor access",
     "Wealthfront pairs robo-advisory with a high-yield cash account and tax-aware features like direct indexing for accounts over $100k.",
     "Palo Alto, CA", 2008),
    ("Schwab Intelligent Portfolios", "robo", 4.3, "$0 management fee (revenue from cash sweep)", "$5,000",
     "No advisory fee\nBacked by Schwab\nAuto-rebalancing\nTax-loss harvesting over $50k",
     "Holds 8-30% cash (drag on returns)\nNo tax-loss harvesting below $50k",
     "Schwab Intelligent Portfolios charges no advisory fee but holds significant cash positions (8-30%) which create a drag on returns.",
     "Westlake, TX", 2015),
    ("Vanguard Digital Advisor", "robo", 4.5, "0.15% AUM (net)", "$3,000",
     "Lowest fee among major robos\nBacked by Vanguard\nVanguard fund allocations",
     "$3,000 minimum\nNo tax-loss harvesting\nNo human advisor access",
     "Vanguard Digital Advisor offers the lowest fee of the major robos at 0.15% with Vanguard's signature low-cost fund allocations.",
     "Malvern, PA", 2020),
    ("Fidelity Go", "robo", 4.4, "$0 under $25k, 0.35% above", "$10",
     "$0 fee on small accounts\nNo expense ratios on Fidelity Flex funds\nIntegrated with Fidelity",
     "0.35% fee above $25k is high\nNo tax-loss harvesting",
     "Fidelity Go is free for accounts under $25,000 with $10 minimum, ideal for new investors building their first portfolio.",
     "Boston, MA", 2016),
    ("M1 Finance", "robo", 4.3, "$0 (M1 Plus subscription $10/mo)", "$0",
     "Customizable 'pie' portfolios\nFractional shares\nM1 borrow (margin)",
     "No tax-loss harvesting\nNo human advisor",
     "M1 Finance combines DIY 'pie' portfolio construction with automated rebalancing — a hybrid between robo and brokerage.",
     "Chicago, IL", 2015),

    # Banks
    ("Ally Bank", "bank", 4.7, "$0 monthly fee", "$0",
     "4.50% APY savings\nNo minimum balance\nFree wire transfers\n24/7 phone support\nFree ATM rebates",
     "No physical branches\nMobile app dated",
     "Ally Bank is a top-tier online-only bank with consistently competitive savings APYs (4.50% as of mid-2026) and no monthly fees.",
     "Sandy, UT", 2008),
    ("Marcus by Goldman Sachs", "bank", 4.6, "$0 monthly fee", "$0",
     "4.40% APY savings\nNo fees\nCD options\nGoldman Sachs backing",
     "No checking account\nNo physical branches",
     "Marcus by Goldman Sachs offers high-yield savings and CDs with no monthly fees and reasonable rates.",
     "New York, NY", 2016),
    ("Capital One 360", "bank", 4.5, "$0 monthly fee", "$0",
     "4.25% APY savings\n70,000+ ATMs\nCapital One Cafes in major cities",
     "Lower APY than top online banks\nLimited branch network",
     "Capital One 360 combines online banking convenience with a real ATM network and Cafe locations in major cities.",
     "McLean, VA", 1988),
    ("Discover Bank", "bank", 4.5, "$0 monthly fee", "$0",
     "4.30% APY savings\nCashback debit card\nNo overdraft fees\nGood mobile app",
     "Limited ATM network\nNo branches",
     "Discover Bank offers competitive online savings paired with a checking account that pays 1% cashback on debit purchases.",
     "Riverwoods, IL", 2009),
    ("SoFi", "bank", 4.4, "$0 monthly fee", "$0",
     "Up to 4.60% APY with direct deposit\nNo fees\nLoan and invest products integrated",
     "Requires direct deposit for top APY\nBranchless",
     "SoFi rewards direct-deposit customers with elevated APYs and integrates lending, investing, and budgeting in one app.",
     "San Francisco, CA", 2011),
    ("Chase Bank", "bank", 4.3, "$12/mo (waivable)", "$0",
     "Largest U.S. branch network\nStrong mobile app\nBig sign-up bonuses",
     "Low APYs on savings (0.01%)\nMonthly fees if conditions not met",
     "Chase is the largest U.S. bank by deposits with the best nationwide branch network, but pays minimal interest on savings.",
     "New York, NY", 2000),
    ("Bank of America", "bank", 4.0, "$12/mo (waivable)", "$0",
     "Large branch network\nIntegrated with Merrill brokerage\nPreferred Rewards tier benefits",
     "Low savings APYs\nMonthly fees common",
     "Bank of America's strength is its ATM/branch network and integration with Merrill investing. Savings APYs lag online banks.",
     "Charlotte, NC", 1904),
    ("Wells Fargo", "bank", 3.8, "$10-25/mo (waivable)", "$25",
     "Big branch network\nGood mortgage products",
     "Past scandals\nLow APYs\nHigher fees than online banks",
     "Wells Fargo offers a large branch network but lags online banks on rates and has lingering reputational issues.",
     "San Francisco, CA", 1852),

    # Lenders
    ("Rocket Mortgage", "lender", 4.5, "Origination ~$1,500", "Varies by loan",
     "Fully online application\nFast pre-approval\nGood customer service\nLarge lender",
     "Origination fees on higher side\nLess flexibility than community lenders",
     "Rocket Mortgage pioneered the fully digital mortgage application. The largest U.S. mortgage originator by volume.",
     "Detroit, MI", 1985),
    ("Better.com", "lender", 4.3, "No origination fee", "$0",
     "No origination, application, or underwriting fees\nFast pre-approval\nDigital-only experience",
     "Service quality has been inconsistent\nLimited loan products",
     "Better.com offers fee-free origination on most mortgages and a fully digital experience, though customer service has been mixed.",
     "New York, NY", 2016),
    ("Wells Fargo Home Mortgage", "lender", 4.0, "Standard origination", "Varies",
     "Branch access\nGood jumbo loan options\nFull range of products",
     "Slower than online lenders\nHistorical compliance issues",
     "Wells Fargo offers full-service mortgage products through its branch network with strong jumbo offerings.",
     "San Francisco, CA", 1852),
    ("Veterans United", "lender", 4.8, "VA-friendly fee structure", "Varies",
     "VA loan specialist\nNo down payment for veterans\nStrong customer ratings",
     "Limited to VA loans\nNot for non-veterans",
     "Veterans United is the largest dedicated VA lender, specializing in zero-down VA mortgages for service members and veterans.",
     "Columbia, MO", 2002),
    ("Bank of America Mortgage", "lender", 4.1, "Standard plus relationship discounts", "Varies",
     "Preferred Rewards discounts\nFirst-time buyer programs\nLarge branch network",
     "Slower than online competitors",
     "Bank of America offers competitive rates with Preferred Rewards discounts for high-balance customers.",
     "Charlotte, NC", 1904),
    ("LoanDepot", "lender", 4.2, "Origination 0.5-1.0%", "Varies",
     "Wide product range\nGood refi options\nLicensed in all 50 states",
     "Customer service varies\nHigher fees than no-fee lenders",
     "LoanDepot offers a wide range of mortgage products with both online and call-center support.",
     "Irvine, CA", 2010),

    # Insurers
    ("State Farm", "insurer", 4.4, "Bundling discounts available", "Varies",
     "Largest agent network\nStrong claims service\nGood for bundled policies",
     "Higher rates than direct insurers\nNo online-only quoting in some states",
     "State Farm is the largest U.S. auto insurer with a deep agent network — best for those who prefer in-person service.",
     "Bloomington, IL", 1922),
    ("Geico", "insurer", 4.5, "Direct-only, no agent commissions", "Varies",
     "Low rates\nStrong mobile app\nFast online quotes\nLicensed in all 50 states",
     "Limited agent support\nClaims complexity for major losses",
     "Geico is one of the most competitively priced auto insurers, especially for clean records.",
     "Chevy Chase, MD", 1936),
    ("Progressive", "insurer", 4.4, "Snapshot usage-based discount", "Varies",
     "Name Your Price tool\nUsage-based discounts via Snapshot\nGood SR-22 coverage",
     "Rates can climb after first renewal\nMixed claims reviews",
     "Progressive offers strong tools for shoppers (Name Your Price) and usage-based discounts via Snapshot.",
     "Mayfield Village, OH", 1937),
    ("Allstate", "insurer", 4.2, "Standard with agent network", "Varies",
     "Drivewise mileage discounts\nClaim Satisfaction Guarantee\nLarge agent network",
     "Higher rates for many drivers\nMixed reviews on rate increases",
     "Allstate combines a strong agent network with proprietary safety apps but tends to price above direct competitors.",
     "Northbrook, IL", 1931),
    ("USAA", "insurer", 4.9, "Member-only pricing", "Military affiliation required",
     "Lowest rates for eligible members\nExcellent customer service\nStrong financial strength",
     "Restricted to military and family\nLimited branch presence",
     "USAA offers the best combination of price and service in U.S. insurance — but only for military families and veterans.",
     "San Antonio, TX", 1922),
    ("Northwestern Mutual", "insurer", 4.6, "Premium pricing", "Varies",
     "Strong financial ratings\nDividend-paying whole life\nFull-service agent model",
     "Higher premiums\nUpsell pressure for permanent products",
     "Northwestern Mutual is the largest U.S. life insurer with a strong dividend history on whole-life policies.",
     "Milwaukee, WI", 1857),
    ("MassMutual", "insurer", 4.5, "Premium pricing", "Varies",
     "Strong dividend history\nFinancial planning services\nDisability insurance leader",
     "Higher whole-life premiums\nAgent-driven sales model",
     "MassMutual is a top mutual life insurer with particular strength in individual disability income insurance.",
     "Springfield, MA", 1851),

    # Cards
    ("Chase Sapphire Preferred", "card", 4.7, "$95 annual fee", "Good-Excellent credit",
     "60,000-pt sign-up bonus (~$750+)\n3x dining and online groceries\n25% boost on travel via Chase\nTransfer to 14 partners",
     "$95 annual fee\nForeign transaction fees waived only on travel",
     "Chase Sapphire Preferred is the best mid-tier travel card, with valuable points and a low annual fee.",
     "New York, NY", 2009),
    ("Chase Sapphire Reserve", "card", 4.6, "$550 annual fee", "Excellent credit",
     "$300 annual travel credit\n3x dining and travel\nPriority Pass lounges\n50% boost on Chase travel\n10x Lyft",
     "$550 fee\nValue contingent on travel spend",
     "Chase Sapphire Reserve is the premium card for frequent travelers — the $300 credit effectively halves the annual fee.",
     "New York, NY", 2016),
    ("American Express Platinum", "card", 4.5, "$695 annual fee", "Excellent credit",
     "Massive 5x flights direct/Amex Travel\n$200 hotel credit\n$240 digital ent credit\n$200 airline fee credit\nCenturion Lounge access",
     "$695 fee\nCredits require active redemption\nLess accepted than Visa",
     "AmEx Platinum is the premier luxury travel card with the broadest lounge access and the most credits — for travelers who actually use them.",
     "New York, NY", 1958),
    ("Capital One Venture X", "card", 4.5, "$395 annual fee", "Excellent credit",
     "75,000-mile sign-up bonus\n$300 annual Capital One Travel credit\n2x miles everywhere\nPriority Pass\nLow fee for premium tier",
     "$395 fee\nFewer transfer partners than Chase",
     "Capital One Venture X is the most affordable premium travel card with $300 credit, Priority Pass, and 2x on every purchase.",
     "McLean, VA", 2021),
    ("Citi Double Cash", "card", 4.6, "$0 annual fee", "Good credit",
     "Effective 2% cash back on everything\nNo annual fee\nIntro 0% on balance transfers\nSimple structure",
     "Forex fees\nLow APR period shorter than peers",
     "Citi Double Cash is the best flat-rate cash-back card with no annual fee — 1% when you buy + 1% when you pay.",
     "New York, NY", 2014),
    ("Wells Fargo Active Cash", "card", 4.5, "$0 annual fee", "Good credit",
     "Flat 2% cash rewards on everything\nNo annual fee\n0% intro APR\n$200 welcome bonus",
     "No 3-5% bonus categories\nForeign transaction fee",
     "Wells Fargo Active Cash matches Citi Double Cash on rewards with a simpler payment structure.",
     "San Francisco, CA", 2021),
    ("Discover it Cash Back", "card", 4.4, "$0 annual fee", "Good credit",
     "5% rotating categories (Q1, Q2 etc)\nUnlimited cashback match in year 1\nNo annual fee\nFICO score on statements",
     "Categories require activation\nLess accepted abroad",
     "Discover it Cash Back is great for category-rotators — Discover matches every dollar of cash back in your first year.",
     "Riverwoods, IL", 1986),
]


# ─── Promos (8) ─────────────────────────────────────────────────────
PROMOS = [
    ("WELCOME10", "10% off Premium SmartAsset Pro subscription for new users", 10),
    ("TAX2026", "$25 credit toward TurboTax via SmartAsset partner link", 25),
    ("ADVISOR50", "$50 toward your first hour with a matched advisor", 50),
    ("NEWSLETTER", "Free 30-day SmartReads Plus trial", 100),
    ("REFERRAL", "$20 referral credit when a friend signs up", 20),
    ("RETIREMENT", "Free retirement plan review (normally $99)", 100),
    ("VETERAN", "10% off any premium SmartAsset service for verified veterans", 10),
    ("STUDENT", "Free student loan refinance review for college grads", 100),
]


# ─── Extra glossary terms to push past 300 total ─────────────────
GLOSSARY_EXTRA = [
    ("Acceleration Clause", "Loan provision letting lender demand full repayment if default.",
     "A standard provision in mortgage and auto-loan contracts allowing the lender to demand the entire balance if you breach the contract (e.g. miss enough payments).", "", "mortgage"),
    ("Accredited Investor", "Investor meeting SEC income or net-worth thresholds.",
     "Income over $200k ($300k joint) for two years, or net worth over $1M excluding primary residence. Required for many private investments.", "", "investing"),
    ("Adjustable-Rate Mortgage", "Mortgage with periodically resetting interest rate.",
     "ARM rates are fixed for an initial period (3, 5, 7, 10 years) then adjust annually based on a benchmark plus margin.", "mortgage", "mortgage"),
    ("Aftermarket", "Trading outside regular market hours.",
     "Equity trading between 4:00 PM and 8:00 PM ET. Lower volume and wider spreads than regular hours.", "", "investing"),
    ("Aggressive Growth", "Investment strategy maximizing returns with high risk.",
     "Portfolio tilted toward small-cap, emerging-market, and high-beta stocks. Suited for long time horizons.", "investment", "investing"),
    ("Alpha", "Investment return above a benchmark.",
     "The excess return of an investment over a chosen benchmark, after adjusting for risk (beta).", "investment", "investing"),
    ("Amortizing Loan", "Loan that pays down principal over time.",
     "Mortgages, auto loans, and student loans are typically amortizing. Each payment reduces the balance.", "mortgage", "personal-finance"),
    ("Annual Fee", "Yearly cost charged for membership or use.",
     "Credit cards may charge $0-$695 annually. Premium cards justify the fee with credits and travel benefits.", "credit-card", "credit-cards"),
    ("Annuitization", "Converting a lump sum into a stream of income.",
     "The process of turning the cash value of an annuity into guaranteed periodic payments. Generally irrevocable.", "", "retirement"),
    ("Appraisal", "Professional estimate of a home's market value.",
     "Lender-ordered home valuation, typically $400-$700. Required for most purchase and refinance mortgages.", "mortgage", "mortgage"),
    ("Appreciation", "Increase in value over time.",
     "The rise in an asset's price. Average historical U.S. home price appreciation: ~3.8%/year.", "", "investing"),
    ("Arbitrage", "Profiting from price differences in two markets.",
     "Simultaneous buy and sell to capture a price gap. Usually closed quickly in efficient markets.", "", "investing"),
    ("Asset", "Anything of monetary value you own.",
     "Cash, investments, real estate, vehicles. Total assets minus total liabilities equals net worth.", "net-worth", "personal-finance"),
    ("Audit Trail", "Record of transactions for verification.",
     "Documentation chain for compliance or regulatory review. Important for businesses and complex personal finances.", "", "taxes"),
    ("Authorized User", "Person allowed to use someone else's credit card.",
     "Adding an authorized user can build their credit by inheriting the primary's payment history.", "credit-card", "personal-finance"),
    ("Balanced Fund", "Mutual fund holding both stocks and bonds.",
     "Hybrid fund with a fixed allocation (often 60/40 stocks/bonds). Built-in diversification.", "investment", "investing"),
    ("Balloon Payment", "Large final loan payment.",
     "A loan structure where most payments are interest-only or low, with a large principal due at the end. Risky if refinancing isn't certain.", "mortgage", "mortgage"),
    ("Bank Run", "Mass withdrawal of deposits.",
     "When many depositors withdraw at once, possibly causing bank failure. FDIC insurance reduces incentive.", "", "banking"),
    ("Bankruptcy", "Legal status of being unable to repay debts.",
     "Chapter 7 (liquidation) discharges most debts; Chapter 13 (reorganization) restructures over 3-5 years. Stays on credit 7-10 years.", "", "personal-finance"),
    ("Basis Point", "1/100th of a percentage point.",
     "1 bp = 0.01%. A 25-bp rate hike = 0.25%. Bond and rate markets quote in basis points.", "", "investing"),
    ("Bear", "Investor expecting prices to fall.",
     "Opposite of bull. A 'bearish' view forecasts declines.", "", "investing"),
    ("Bid-Ask Spread", "Difference between best buy and sell prices.",
     "Tighter spreads mean lower trading costs. Major stocks: pennies; thinly traded stocks: dollars.", "", "investing"),
    ("Blue Chip", "Large, well-established, financially sound company.",
     "Term borrowed from highest-value poker chips. S&P 500 components are commonly called blue chips.", "investment", "investing"),
    ("Book Value", "Company's accounting net worth.",
     "Assets minus liabilities on the balance sheet. Stock price vs book value gives the P/B ratio.", "", "investing"),
    ("Bond", "Debt security paying periodic interest.",
     "Issued by governments and corporations. Bondholder receives coupon payments and principal at maturity.", "investment", "investing"),
    ("Bond Yield", "Annual return on a bond.",
     "Coupon divided by current price. Yields rise when prices fall (and vice versa).", "investment", "investing"),
    ("Bridge Loan", "Short-term loan covering a financing gap.",
     "Often used when selling one home before buying another. Higher rates than conventional loans.", "mortgage", "mortgage"),
    ("Brokerage Account", "Investment account at a securities firm.",
     "Account at Fidelity, Schwab, Vanguard, etc. for buying stocks, bonds, ETFs, mutual funds.", "investment", "investing"),
    ("Bull", "Investor expecting prices to rise.",
     "Bullish view forecasts gains. Opposite of bear.", "", "investing"),
    ("Buy and Hold", "Long-term investment strategy.",
     "Buying securities and holding regardless of short-term market moves. Tax-efficient and historically successful.", "investment", "investing"),
    ("Cafeteria Plan", "Employer benefit plan letting employees pick pre-tax options.",
     "Section 125 plan: choose among health, life, dependent-care benefits paid with pre-tax dollars.", "paycheck", "personal-finance"),
    ("Call Option", "Right to buy a stock at a strike price.",
     "Bullish bet. Limited downside (premium paid) and theoretically unlimited upside.", "", "investing"),
    ("Cap Rate", "Real estate income yield.",
     "Net operating income divided by property value. Used to compare investment property opportunities.", "", "investing"),
    ("Capital Loss", "Loss from selling an asset below cost basis.",
     "Can offset capital gains plus up to $3,000 of ordinary income. Excess carries forward indefinitely.", "capital-gains", "taxes"),
    ("Cash Advance", "Borrowing cash from a credit card.",
     "High interest rate (often 25-30%), no grace period, and usually a 3-5% upfront fee. Avoid.", "credit-card", "credit-cards"),
    ("Cash Flow", "Net cash moving in and out.",
     "Personal: income minus expenses. Business: operating, investing, financing cash flows. Positive cash flow is sustainable.", "", "personal-finance"),
    ("Chapter 7", "Bankruptcy liquidating non-exempt assets.",
     "Discharges most unsecured debts in months. Stays on credit report for 10 years. Means-tested.", "", "personal-finance"),
    ("Chapter 13", "Bankruptcy with court-supervised repayment plan.",
     "Repayment plan over 3-5 years. Lets debtors keep secured assets like homes. On credit for 7 years.", "", "personal-finance"),
    ("Charge-Off", "Lender's accounting write-off of unpaid debt.",
     "Doesn't extinguish the debt — you still owe it, but the lender has booked the loss. Severely damages credit.", "", "credit-cards"),
    ("Charitable Trust", "Trust benefiting a charity.",
     "Charitable remainder trust pays income to non-charity, then balance to charity. CRT and CLT structures offer tax benefits.", "", "estate-planning"),
    ("Checking Account", "Bank account for everyday transactions.",
     "Provides debit card, checks, and electronic transfers. Usually pays minimal interest.", "", "banking"),
    ("Closed-End Fund", "Fund with fixed share count, traded like stock.",
     "Issues shares once at IPO; thereafter trades on exchange. Can sell at premium or discount to NAV.", "investment", "investing"),
    ("COBRA", "Continuation of employer health insurance after job loss.",
     "Federal law lets you keep employer health coverage up to 18 months, paying full premium plus 2% admin.", "", "insurance"),
    ("Cold Storage", "Crypto held offline for security.",
     "Hardware wallet or paper wallet, disconnected from internet. Reduces hacking risk.", "", "investing"),
    ("Collateral", "Asset pledged to secure a loan.",
     "Home for a mortgage, car for an auto loan. Lender can claim the collateral if borrower defaults.", "mortgage", "personal-finance"),
    ("Common Stock", "Standard equity share.",
     "Voting rights, last in line for dividends and bankruptcy proceeds. Most stocks traded are common.", "investment", "investing"),
    ("Compound", "Adding interest to principal so future interest grows.",
     "The mathematical heart of long-term investing. $1 compounded at 7% for 50 years becomes $29.46.", "investment", "investing"),
    ("Conforming Loan", "Mortgage meeting Fannie/Freddie guidelines.",
     "Loan within FHFA limits ($806,500 in 2026 for most areas). Lower rates than non-conforming jumbo loans.", "mortgage", "mortgage"),
    ("Conservative", "Investment strategy emphasizing capital preservation.",
     "Heavy in bonds, cash, dividend stocks. Lower expected return but smaller drawdowns.", "investment", "investing"),
    ("Consumer Price Index", "Inflation gauge tracking a basket of goods.",
     "BLS-published. Headline CPI vs core (excluding food and energy). Used for COLA adjustments.", "inflation", "investing"),
    ("Conversion", "Moving funds from traditional to Roth IRA.",
     "Triggers ordinary income tax on the amount converted. Can be strategic in low-income years.", "ira", "retirement"),
    ("Conveyance", "Legal transfer of title.",
     "Deed transferring property from seller to buyer. Recorded with the county recorder.", "", "mortgage"),
    ("Convertible Bond", "Bond convertible to stock at fixed ratio.",
     "Pays interest like a bond but can be converted to equity. Limited upside vs equity but better downside.", "", "investing"),
    ("Coupon", "Regular interest payment on a bond.",
     "A 5% coupon on a $1,000 bond pays $50/year. Paid semi-annually for most U.S. bonds.", "investment", "investing"),
    ("Covenant", "Loan agreement promise by borrower.",
     "Restrictions imposed by lender. Negative covenants prohibit certain actions; positive covenants require them.", "", "investing"),
    ("Coverdell ESA", "Tax-advantaged education savings account.",
     "$2,000 annual contribution limit. Tax-free growth and withdrawal for qualified education expenses, K-12 or higher.", "", "personal-finance"),
    ("Credit Limit", "Maximum charge allowed on a credit account.",
     "Set by issuer based on creditworthiness. Stay under 30% utilization for best credit score.", "credit-card", "credit-cards"),
    ("Credit Report", "Detailed record of credit history.",
     "Maintained by Equifax, Experian, TransUnion. Free annual report at annualcreditreport.com.", "credit-card", "personal-finance"),
    ("Currency Risk", "Foreign exchange exposure.",
     "Holdings denominated in foreign currency may gain or lose value based on FX moves.", "investment", "investing"),
    ("Day Order", "Order valid only until end of trading day.",
     "Default order duration. Cancels at 4:00 PM if not executed. Alternative: Good-Til-Cancelled (GTC).", "", "investing"),
    ("Day Trading", "Buying and selling within the same trading day.",
     "FINRA requires $25,000 minimum equity for pattern day traders. Most retail day traders lose money.", "", "investing"),
    ("Death Benefit", "Amount paid to beneficiary on policyholder's death.",
     "Generally tax-free to the beneficiary. The point of life insurance.", "", "insurance"),
    ("Deed", "Legal document transferring real estate ownership.",
     "Warranty deed (full guarantee) vs quitclaim deed (whatever interest grantor has). Recorded with county.", "", "mortgage"),
    ("Deductible", "Amount you pay before insurance covers.",
     "Higher deductible = lower premium. Common health insurance deductibles: $1,500-$8,000 individual.", "", "insurance"),
    ("Default", "Failure to make payments on a debt.",
     "Triggers acceleration clauses, late fees, credit damage, possible legal action.", "", "personal-finance"),
    ("Deflation", "General decline in prices.",
     "Opposite of inflation. Rare but problematic — encourages hoarding, can spiral into recession.", "inflation", "investing"),
    ("Delinquency", "Late payment status.",
     "30 days late hits credit. 60, 90, 120 days each worsen the damage. Default usually at 180 days.", "", "personal-finance"),
    ("Delta", "Option's price sensitivity to underlying stock.",
     "Range -1 to +1. Calls have positive delta; puts negative. ATM options have delta ~0.5.", "", "investing"),
    ("Derivative", "Security deriving value from underlying asset.",
     "Options, futures, swaps. Powerful tools when used for hedging; high-risk for speculation.", "", "investing"),
    ("Direct Deposit", "Electronic salary deposit to bank account.",
     "Faster, safer, often qualifies for fee waivers and elevated APYs at online banks.", "", "banking"),
    ("Disability Insurance", "Income replacement for inability to work.",
     "Short-term (3-6 mos) and long-term (until retirement) policies. Most workers underinsured here.", "", "insurance"),
    ("Discount Rate", "Rate Federal Reserve charges banks.",
     "Set by Fed. Direct lending facility used in emergencies. Federal funds rate is the main policy tool.", "", "investing"),
    ("Distribution", "Withdrawal from a retirement account or fund.",
     "May be taxable depending on account type and age. RMDs are mandatory distributions starting at 73.", "retirement", "retirement"),
    ("Diversifiable Risk", "Risk reducible through diversification.",
     "Firm-specific risk (e.g. one company's accounting fraud). Eliminated by holding broad index funds.", "investment", "investing"),
    ("DRIP", "Dividend Reinvestment Plan.",
     "Automatically reinvests dividends into more shares. Compounds returns and skips trading fees.", "investment", "investing"),
    ("Due Diligence", "Investigation before making a financial decision.",
     "Reading the prospectus, checking advisor's Form ADV, getting a home inspection.", "", "investing"),
    ("Earnest Money Deposit", "Buyer's good-faith deposit in home purchase.",
     "Typically 1-3% of price. Held in escrow; applied to down payment at closing or forfeited.", "", "mortgage"),
    ("Easement", "Legal right to use someone else's property.",
     "Utility easements, access easements. Disclosed in title commitment; can affect property use and value.", "", "mortgage"),
    ("Economy", "System of resource production and exchange.",
     "U.S. GDP roughly $28T (2025). Growth, employment, inflation drive market sentiment.", "", "investing"),
    ("ESPP", "Employee Stock Purchase Plan.",
     "Buy company stock at a 15% discount. Often the best risk-adjusted return available to employees.", "", "investing"),
    ("Estate", "Total assets and liabilities at death.",
     "Includes real estate, investments, retirement accounts, life insurance. Determined for estate tax purposes.", "", "estate-planning"),
    ("Exchange-Traded Note", "Debt security tracking an index.",
     "Unsecured debt of issuer, not an equity claim. Carries issuer credit risk in addition to market risk.", "", "investing"),
    ("Excise Tax (Retirement)", "Penalty tax on retirement account violations.",
     "Examples: 25% on missed RMD, 10% on excess contributions, 6%/year on undistributed excess.", "retirement", "taxes"),
    ("Executor", "Person responsible for settling an estate.",
     "Named in the will. Files final tax returns, distributes assets, manages probate.", "", "estate-planning"),
    ("Face Value", "Stated principal value of a bond.",
     "Also called 'par value.' Usually $1,000 for U.S. corporate bonds. Returned at maturity.", "investment", "investing"),
    ("Family Limited Partnership", "Estate planning vehicle for family-owned assets.",
     "FLP lets parents transfer wealth at discounted values for gift/estate tax purposes.", "", "estate-planning"),
    ("Federal Funds Rate", "Rate banks lend to each other overnight.",
     "Set by Federal Reserve. Influences short-term rates throughout the economy.", "", "investing"),
    ("FERS", "Federal Employees Retirement System.",
     "Three-part retirement for federal civilian workers: pension + Social Security + Thrift Savings Plan.", "", "retirement"),
    ("FHFA", "Federal Housing Finance Agency.",
     "Regulates Fannie Mae and Freddie Mac. Sets annual conforming loan limits.", "", "mortgage"),
    ("Fixed Annuity", "Annuity with guaranteed rate.",
     "Insurance company pays a guaranteed rate for a set period. Low risk; modest return.", "", "retirement"),
    ("Float", "Time between deposit and clearance.",
     "Float has shrunk dramatically — most deposits now clear next business day or sooner.", "", "banking"),
    ("Foreclosure", "Lender repossessing a defaulted-mortgage property.",
     "Process varies by state (judicial vs non-judicial). Devastating to credit; stays on report 7 years.", "", "mortgage"),
    ("Forex", "Foreign exchange market.",
     "Currency trading. World's largest financial market with ~$7T daily volume.", "", "investing"),
    ("Franchise Tax", "State tax on doing business.",
     "Levied by states on businesses operating in the state, regardless of income. Texas, Delaware, California notable.", "", "taxes"),
    ("Front-Load Fund", "Mutual fund with up-front sales charge.",
     "Class A shares charge 3-5.75% commission at purchase. Largely obsolete — most investors use no-load funds.", "investment", "investing"),
    ("Futures", "Contract to buy/sell at a future date and price.",
     "Standardized exchange-traded derivative. Used for hedging commodities, currency, and rates.", "", "investing"),
    ("Garnishment", "Legal seizure of wages or accounts.",
     "Court order requiring employer or bank to send funds to creditor. Federal limit: 25% of disposable income.", "", "personal-finance"),
    ("Gift Tax", "Federal tax on transfers exceeding annual limit.",
     "Annual exclusion: $18,000/recipient (2026). Above that, eats into lifetime estate/gift exemption.", "", "estate-planning"),
    ("Goodwill", "Intangible business value beyond hard assets.",
     "Brand, customer relationships, reputation. Important in M&A valuation.", "", "investing"),
    ("Grace Period", "Time after due date without penalty.",
     "Credit cards: 21-25 days from statement close to pay without interest. Mortgages: typically 15 days.", "credit-card", "credit-cards"),
    ("Grantor Trust", "Trust whose income is taxed to the grantor.",
     "The grantor retains some control or interest. Income flows through to the grantor's tax return.", "", "estate-planning"),
    ("Group Term Life", "Employer-provided life insurance.",
     "Often a free 1-2x salary benefit. Higher amounts may be employee-paid and portable on departure.", "", "insurance"),
    ("Growth Stock", "Stock expected to grow faster than market.",
     "Tech, biotech, consumer discretionary. High valuations, low dividends. Compare to value stocks.", "investment", "investing"),
    ("Guaranteed Investment Contract", "Insurance company investment guaranteeing return.",
     "GICs in 401(k) plans pay a fixed rate for a fixed term. Backed by insurer's credit.", "", "retirement"),
    ("Hardship Withdrawal", "Early retirement-account withdrawal for emergencies.",
     "Allowed for specific qualifying events. Subject to income tax plus 10% penalty under 59 1/2.", "401k", "retirement"),
    ("Holding Period", "How long an asset has been owned.",
     "Determines short-term vs long-term capital gains treatment. 1 year and 1 day for long-term.", "capital-gains", "taxes"),
    ("Holographic Will", "Handwritten will.",
     "Valid in some states without witnesses if entirely in testator's handwriting and signed.", "", "estate-planning"),
    ("Hostile Takeover", "Acquisition opposed by target's management.",
     "Tender offer or proxy fight bypass target's board. Can drive significant short-term stock gains.", "", "investing"),
    ("Hurdle Rate", "Minimum return for a project or fund.",
     "Hedge funds often charge performance fee only above hurdle. Project IRR must exceed hurdle to fund.", "", "investing"),
    ("Implied Volatility", "Market's forecast of future volatility from option prices.",
     "Higher IV = pricier options. VIX measures S&P 500 implied volatility.", "", "investing"),
    ("Income Statement", "Financial report of revenue, expenses, net income.",
     "Also called P&L. Standard quarterly business report. Top line revenue, bottom line net income.", "", "investing"),
    ("Inflation Risk", "Risk that inflation erodes real returns.",
     "Hits long-duration bonds hardest. Equities, TIPS, real estate provide better long-term hedges.", "inflation", "investing"),
    ("Insider Trading", "Trading on material non-public information.",
     "Illegal when based on confidential corporate info. Company insiders must report trades (Form 4).", "", "investing"),
    ("Intestate", "Dying without a will.",
     "State intestacy laws determine distribution. May not match your wishes. Write a will.", "", "estate-planning"),
    ("Investment Grade", "Bonds rated BBB-/Baa3 or higher.",
     "Lower default risk. Pension funds and insurers may be required to hold only investment-grade.", "", "investing"),
    ("ITIN", "Individual Taxpayer Identification Number.",
     "Issued by IRS to those who need to file taxes but don't have a Social Security number.", "", "taxes"),
]


# Merge the extras into the main glossary list. This keeps the seed
# loop simple and idempotent.
GLOSSARY = GLOSSARY + GLOSSARY_EXTRA
