"""Bulk extras for SmartAsset seed: extra articles, glossary, cities, reviews."""

# ─── Extra articles (~120) ──────────────────────────────────────────
EXTRA_ARTICLES = [
    # Retirement (24)
    ("How to Plan for Retirement in Your 50s",
     "Five tax-efficient catch-up moves you can still make.",
     "retire50s", "retirement", "retirement,age-50,catch-up"),
    ("Roth Conversion Ladder Explained",
     "How a five-year ladder lets you tap Roth conversions tax-free.",
     "roth_ladder", "retirement", "roth,conversion,ladder"),
    ("Annuities: When They Make Sense",
     "Income guarantees vs liquidity, with the math.",
     "annuities", "retirement", "annuities,income"),
    ("How to Withdraw from Retirement Accounts in Order",
     "The taxable-first, tax-deferred-second, Roth-last sequence.",
     "withdraw_order", "retirement", "withdrawal,sequence,retirement"),
    ("Average 401(k) Balance by Age in 2026",
     "Fed Survey of Consumer Finances data, broken out by decade.",
     "avg_401k_age", "retirement", "401k,benchmarks,2026"),
    ("Pension Lump Sum vs Monthly Annuity",
     "Use the 6% rule and the math on a real $300k offer.",
     "pension_choice", "retirement", "pension,lump-sum"),
    ("How Much You Need to Retire at 55",
     "The 25x rule, adjusted for an early-retirement decade of bridge years.",
     "retire_55", "retirement", "early-retirement,fire"),
    ("Social Security Spousal Benefits",
     "How to claim up to 50% of your spouse's benefit.",
     "ss_spousal", "retirement", "social-security,spousal"),
    ("Backdoor Roth IRA: Step-by-Step",
     "Annual workaround for households over the Roth income limit.",
     "backdoor_roth", "retirement", "backdoor,roth"),
    ("Mega Backdoor Roth Explained",
     "Stuff $46k after-tax into a Roth, if your plan allows it.",
     "mega_backdoor", "retirement", "mega-backdoor,roth"),
    ("SECURE 2.0 Retirement Provisions in 2026",
     "What changed: auto-enroll, RMD age, 529 rollovers, more.",
     "secure20", "retirement", "secure-act,2026"),
    ("Healthcare Costs in Retirement",
     "Fidelity's $165k-per-couple estimate, decomposed.",
     "health_retire", "retirement", "healthcare,retirement"),
    ("Solo 401(k) for the Self-Employed",
     "Up to $69k in 2026 if you wear both employee and employer hats.",
     "solo_401k", "retirement", "solo-401k,self-employed"),
    ("SEP-IRA vs SIMPLE IRA",
     "Two retirement vehicles for the self-employed and small businesses.",
     "sep_simple", "retirement", "sep-ira,simple"),
    ("Retiring Abroad: Tax & Visa Basics",
     "The U.S. tax exposure that follows you everywhere.",
     "retire_abroad", "retirement", "expat,retirement"),
    ("How to Roll Over a 401(k)",
     "The four options, and the trustee-to-trustee transfer rule.",
     "rollover", "retirement", "rollover,401k"),
    ("Inherited IRA Rules After SECURE Act",
     "The 10-year rule, exceptions, and the trap for non-spouse heirs.",
     "inherited_ira", "retirement", "inherited-ira,secure-act"),
    ("How to Calculate Your Retirement Number",
     "Three methods: 25x, income replacement, bottom-up.",
     "retire_num", "retirement", "retirement,number"),
    ("Variable Annuities: Fees You Need to Watch",
     "M&E, rider costs, and surrender schedules.",
     "var_annuity", "retirement", "variable-annuity"),
    ("Working in Retirement: Tax Impact",
     "How earnings before FRA trigger the Social Security earnings test.",
     "work_retire", "retirement", "earnings-test,retirement"),
    ("The Bucket Strategy for Retirement",
     "Cash / bonds / stocks tiers, refilled in down years.",
     "buckets", "retirement", "bucket-strategy,retirement"),
    ("Best States for Retirement Taxes",
     "Side-by-side ranking by income, pension and Social Security treatment.",
     "best_states_retire", "retirement", "states,retirement,taxes"),
    ("Working Past 70: Smart Move?",
     "Social Security max benefit caps at age 70 - the trade-offs.",
     "past70", "retirement", "social-security,age-70"),
    ("How to Coordinate Spousal Retirement Plans",
     "Two-income households need a joint glide path, not two single ones.",
     "spousal_plan", "retirement", "couples,retirement"),

    # Taxes (18)
    ("Standard Deduction vs Itemizing in 2026",
     "When the larger standard deduction beats salt-capped itemizing.",
     "std_vs_item", "taxes", "deductions,2026"),
    ("Tax Implications of Selling a Home",
     "Section 121 exclusion: $250k single / $500k joint.",
     "home_sale_tax", "taxes", "section-121,home-sale"),
    ("Charitable Giving Strategies for 2026",
     "Bunching, DAFs, QCDs - and when each beats cash.",
     "charity_2026", "taxes", "charity,daf,qcd"),
    ("Estimated Tax Payments: When and How",
     "1040-ES, due dates, and the safe-harbor rule.",
     "estimated_tax", "taxes", "estimated-tax,1040-es"),
    ("AMT in 2026: Who Pays It?",
     "Alternative Minimum Tax phaseout thresholds for the year.",
     "amt_2026", "taxes", "amt,phaseout"),
    ("Tax Loss Carryforward Explained",
     "$3k annual deduction, infinite carryforward.",
     "tlc", "taxes", "capital-loss,carryforward"),
    ("Net Investment Income Tax (NIIT)",
     "The 3.8% surcharge over $200k/$250k MAGI.",
     "niit", "taxes", "niit,investment-income"),
    ("How to Read Your W-2",
     "Box-by-box decoder for the most common pay-stub form.",
     "w2_decode", "taxes", "w-2,paystub"),
    ("Filing Your Taxes as a Freelancer",
     "1099-NEC, Schedule C, and the QBI deduction.",
     "freelance_tax", "taxes", "freelance,schedule-c"),
    ("Tax Brackets for Married Couples in 2026",
     "Joint vs separate filing - and the marriage penalty.",
     "married_brackets", "taxes", "married,brackets"),
    ("How to Amend a Tax Return",
     "Form 1040-X, three-year window, and what triggers an audit.",
     "amend", "taxes", "amend,1040x"),
    ("Foreign Earned Income Exclusion",
     "$126,500 (2026) - the FEIE for U.S. expats.",
     "feie", "taxes", "feie,expat"),
    ("Tax-Advantaged Accounts in Order of Priority",
     "401(k) match -> HSA -> Roth IRA -> 401(k) -> taxable - the standard stack.",
     "account_order", "taxes", "tax-advantaged,stack"),
    ("Selling Stock: Specific Lot vs FIFO",
     "How to control your gain - and save thousands.",
     "stock_lot", "taxes", "lot-selection,stocks"),
    ("Home Office Deduction for 2026",
     "Simplified vs actual-expense method.",
     "home_office_2026", "taxes", "home-office,deduction"),
    ("HSA: The Stealth Retirement Account",
     "Triple tax advantage, no RMDs - the math.",
     "hsa_retire", "taxes", "hsa,retirement"),
    ("Quarterly Self-Employment Tax",
     "15.3% on net SE income up to the SS wage base.",
     "se_tax", "taxes", "self-employment,quarterly"),
    ("How to Survive an IRS Audit",
     "Mail audit vs office audit vs field audit - prep checklist.",
     "audit", "taxes", "irs,audit"),

    # Investing (18)
    ("Dollar-Cost Averaging into a Down Market",
     "When buying weekly beats waiting for the bottom.",
     "dca_down", "investing", "dca,bear-market"),
    ("The Three-Fund Portfolio",
     "U.S. + international + bonds. That's it.",
     "three_fund", "investing", "three-fund,bogleheads"),
    ("How to Rebalance Your Portfolio",
     "Threshold vs calendar rebalancing - and a 5% drift rule.",
     "rebalance", "investing", "rebalance,portfolio"),
    ("Index Funds vs Active Funds in 2026",
     "SPIVA data: 85% of active large-cap funds lagged the S&P.",
     "spiva", "investing", "active-vs-index"),
    ("Best Vanguard Funds for a Roth IRA",
     "Five core funds and one tilt - the all-Vanguard portfolio.",
     "vanguard_funds", "investing", "vanguard,roth"),
    ("How to Buy Treasury Bonds Directly",
     "TreasuryDirect vs brokerage - and which has lower friction.",
     "buy_treasuries", "investing", "treasurydirect,bonds"),
    ("I Bonds: Inflation-Protected Savings",
     "The $15k annual cap and the 12-month lockup.",
     "i_bonds", "investing", "i-bonds,inflation"),
    ("TIPS: Treasury Inflation-Protected Securities",
     "Principal adjusts with CPI - the math on real yield.",
     "tips", "investing", "tips,inflation"),
    ("Sector ETFs: Worth the Concentration?",
     "Standard deviation jumps, returns mostly don't.",
     "sector_etf", "investing", "etfs,sectors"),
    ("Small-Cap vs Large-Cap Stocks",
     "Why the historical premium has narrowed since 2000.",
     "small_cap", "investing", "small-cap,size"),
    ("International Stocks: Still Worth Owning?",
     "Decade of underperformance vs the diversification argument.",
     "intl_stocks", "investing", "international,diversification"),
    ("Cryptocurrency in a Diversified Portfolio",
     "Why advisors recommend 0-5% allocation, max.",
     "crypto_alloc", "investing", "crypto,allocation"),
    ("Real Estate Investment Trusts (REITs)",
     "Yields, taxation, and the 75% rule.",
     "reits", "investing", "reits,real-estate"),
    ("Target-Date Funds: Set It and Forget It",
     "Glide-path mechanics and the expense-ratio trap.",
     "tdf", "investing", "target-date,tdf"),
    ("Investing in Stocks for Beginners",
     "Open a brokerage, buy a total-market ETF, automate.",
     "beginner_invest", "investing", "beginners,stocks"),
    ("The 60/40 Portfolio: Is It Dead?",
     "Why 2022 was the worst year ever for the 60/40 - and what changed.",
     "6040", "investing", "60-40,portfolio"),
    ("Margin: When (Rarely) to Use It",
     "Interest rates, maintenance calls, and the long-tail risks.",
     "margin", "investing", "margin,leverage"),
    ("Stock Options: Calls and Puts Explained",
     "The basics of buying a call - and why most retail loses money.",
     "options_basics", "investing", "options,calls,puts"),

    # Mortgage (16)
    ("Today's Mortgage Rates by State",
     "Top 10 lowest 30-year fixed rates as of this week.",
     "rates_state", "mortgage", "rates,by-state"),
    ("How to Get Pre-Approved for a Mortgage",
     "Documents, credit pull, and the validity window.",
     "preapproval", "mortgage", "pre-approval"),
    ("Mortgage Recasting: A Hidden Lever",
     "Lump sum + recast = lower payment without refinancing.",
     "recast", "mortgage", "recast,refinance"),
    ("USDA Loans for Rural Homebuyers",
     "Zero-down rural lending - eligibility map and income caps.",
     "usda", "mortgage", "usda,rural"),
    ("Reverse Mortgages: Pros and Cons",
     "HECM mechanics for homeowners 62+.",
     "reverse_mortgage", "mortgage", "reverse,hecm"),
    ("How Mortgage Rates Are Set",
     "The 10-yr Treasury, MBS spread, and your credit overlay.",
     "rate_mechanics", "mortgage", "rates,mbs"),
    ("Jumbo Loans in 2026",
     "Anything over $806,500 conforming - the underwriting bar.",
     "jumbo_2026", "mortgage", "jumbo,conforming"),
    ("HELOC vs Home Equity Loan",
     "Variable line vs fixed second mortgage.",
     "heloc_he", "mortgage", "heloc,home-equity"),
    ("Cash-Out Refinance: When It Makes Sense",
     "Consolidating high-rate debt at 7% mortgage rate.",
     "cash_out", "mortgage", "cash-out,refinance"),
    ("First-Time Homebuyer Programs by State",
     "Down-payment assistance, MCC certificates, more.",
     "ftb_state", "mortgage", "first-time,assistance"),
    ("Construction Loans: How They Work",
     "Two-close vs single-close construction-to-permanent.",
     "construction", "mortgage", "construction-loan"),
    ("Mortgage Insurance Premium vs PMI",
     "FHA MIP is for life; conventional PMI drops at 78% LTV.",
     "mip_pmi", "mortgage", "pmi,mip"),
    ("Buying a Second Home: Tax Rules",
     "Mortgage interest deduction limit, rental treatment.",
     "second_home", "mortgage", "second-home,tax"),
    ("How Much Are Closing Costs in 2026?",
     "3%-5% of price - by line item and by state.",
     "closing_2026", "mortgage", "closing-costs,2026"),
    ("Mortgage After Bankruptcy: How Long?",
     "Waiting periods for FHA (2 yrs) vs conventional (4 yrs).",
     "mortgage_bk", "mortgage", "bankruptcy,mortgage"),
    ("Rate Locks and Float-Downs",
     "When to lock, when to float, and the 'float-down' clause.",
     "rate_lock", "mortgage", "rate-lock,float-down"),

    # Banking (12)
    ("Best High-Yield Savings Rates This Week",
     "5%+ APYs at online banks, refreshed weekly.",
     "best_hysa", "banking", "hysa,rates"),
    ("Are Credit Unions Better Than Banks?",
     "Membership, dividend yields, and the trade-offs.",
     "cu_bank", "banking", "credit-union,bank"),
    ("How to Switch Bank Accounts in a Weekend",
     "Move direct deposit, autopays, and minimize the gap.",
     "switch_bank", "banking", "switch,bank"),
    ("Online Banks vs Brick-and-Mortar",
     "APYs vs branch access - which fits which use case.",
     "online_brick", "banking", "online-bank"),
    ("Sweep Accounts: Earning on Idle Cash",
     "Money-market sweeps vs FDIC sweeps - and the rate spread.",
     "sweep", "banking", "sweep,money-market"),
    ("Wire vs ACH vs Zelle: When to Use Each",
     "Speed, cost, reversibility, and limits.",
     "transfers", "banking", "ach,wire,zelle"),
    ("How to Avoid Bank Overdraft Fees",
     "Buffer accounts, opt-out rules, and free alternatives.",
     "no_overdraft", "banking", "overdraft,fees"),
    ("Money Market Funds vs Money Market Accounts",
     "MMF (a security) vs MMA (a deposit account) - tax + insurance.",
     "mmf_mma", "banking", "mmf,mma"),
    ("Brokerage Cash Yields in 2026",
     "Where each broker lands on default cash sweep rates.",
     "cash_yields", "banking", "brokerage,cash"),
    ("Foreign-Currency Accounts in the U.S.",
     "Hedging, multi-currency wallets, and FBAR reporting.",
     "fx_accounts", "banking", "forex,multi-currency"),
    ("Joint vs Single Bank Accounts",
     "Estate, gifting, and bankruptcy implications.",
     "joint_acct", "banking", "joint,single"),
    ("Closing a Bank Account Cleanly",
     "Avoid the dormant-account fee trap.",
     "close_acct", "banking", "close,account"),

    # Personal Finance (12)
    ("How to Build a Six-Month Emergency Fund",
     "Automated, separate, and high-yield - in that order.",
     "ef_buildout", "personal-finance", "emergency-fund,build"),
    ("The Real Cost of Buying Coffee Daily",
     "$5/day x 30 yrs at 7% = $185,000.",
     "coffee", "personal-finance", "spending,latte-factor"),
    ("Sinking Funds for Predictable Expenses",
     "Annual insurance + car + vacation - bucketized.",
     "sinking", "personal-finance", "sinking-funds"),
    ("How to Talk About Money with Your Spouse",
     "Money meetings, separate vs combined, and the 'his/hers/ours' setup.",
     "money_couples", "personal-finance", "couples,money"),
    ("Teaching Kids About Money by Age",
     "Allowance, savings jars, brokerage account at 16.",
     "kids_money", "personal-finance", "kids,allowance"),
    ("The 50/30/20 Budget Rule",
     "Needs/wants/savings split - when it works and when it doesn't.",
     "503020", "personal-finance", "budget,50-30-20"),
    ("Cash Envelopes in a Digital World",
     "Banking apps that replicate the envelope method.",
     "envelopes", "personal-finance", "envelopes,budget"),
    ("How to Recover from a Layoff Financially",
     "Severance, COBRA, unemployment, and the runway calc.",
     "layoff", "personal-finance", "layoff,severance"),
    ("Identity Theft: First 24 Hours",
     "Credit freeze, IRS PIN, and the FTC complaint.",
     "id_theft", "personal-finance", "identity-theft,fraud"),
    ("Buying vs Leasing Solar Panels",
     "20-yr ROI, lease pitfalls, and the resale impact.",
     "solar", "personal-finance", "solar,lease"),
    ("How to Save for Multiple Goals at Once",
     "Priority weights and a per-goal automation.",
     "multi_goals", "personal-finance", "goals,saving"),
    ("Side Hustles That Actually Pay in 2026",
     "What the IRS sees vs what the YouTube influencers claim.",
     "side_hustles", "personal-finance", "side-hustle,1099"),

    # Credit cards (8)
    ("Best Travel Credit Cards for 2026",
     "Premium picks, mid-tier picks, and the no-fee winner.",
     "best_travel", "credit-cards", "travel,cards"),
    ("Best Cash-Back Cards for 2026",
     "Flat-rate vs category rotators - the math.",
     "best_cb", "credit-cards", "cash-back"),
    ("Best Business Credit Cards for Sole Proprietors",
     "Earn-rate, expense-tracking, and 1099 friendliness.",
     "best_biz", "credit-cards", "business,cards"),
    ("Credit Card Churning: Is It Worth It?",
     "Sign-up bonuses vs the credit-score and time costs.",
     "churning", "credit-cards", "churning"),
    ("How to Manage Multiple Credit Cards",
     "Automation, calendar reminders, and the closing trap.",
     "many_cards", "credit-cards", "credit-cards,manage"),
    ("Credit Card Fraud: Liability Rules",
     "Zero-liability protection - and where it ends.",
     "cc_fraud", "credit-cards", "fraud,liability"),
    ("Pre-Approved vs Pre-Qualified Cards",
     "Soft pull, hard pull, and what each actually guarantees.",
     "preapprov_cards", "credit-cards", "pre-approved,pre-qualified"),
    ("Foreign Transaction Fees and the Cards That Skip Them",
     "Most travel cards charge 0%; most cash-back cards charge 3%.",
     "fx_fees", "credit-cards", "foreign-fee,travel"),
]
