"""Real source data harvested via Tavily for Google Search mirror.

Each record is keyed to a real search query and the source domain + URL
were captured from actual web search results (Tavily live calls, late
May 2026). This module is deterministic and used ONLY at seed time to
populate the ImageCard / VideoCard / ScholarPaper / FeaturedSnippet /
PaaBundle / KnowledgePanel tables in instance_seed/google_search.db.

Runtime routes never read this file directly — they query the SQLite
seed instead. This keeps byte-identical reset checks honest.
"""

# ---------------------------------------------------------------------------
# R4 — Image cards (24 entries). Each is tied to a real keyword that returns
# results on the upstream Google Images. Source attributions taken from real
# Tavily results — domain + title + slug are real, dims are typical.
# ---------------------------------------------------------------------------

IMAGE_CARDS = [
    # 1
    {'slug': 'aurora_borealis_lofoten', 'query': 'aurora borealis lofoten',
     'title': 'Aurora borealis over the Lofoten Islands, Norway',
     'source_domain': 'unsplash.com',
     'source_url': 'https://unsplash.com/s/photos/northern-lights-norway',
     'source_owner': 'Unsplash community',
     'dims': '4032x3024', 'color': 'green', 'size': 'large', 'type': 'photo',
     'license': 'cc0', 'license_label': 'Creative Commons - CC0',
     'alt': 'Photograph of green aurora curtains above snow-capped Lofoten peaks',
     'caption': 'Long-exposure capture of the aurora borealis arching over the Lofoten coast in northern Norway.'},
    # 2
    {'slug': 'lavender_valensole_sunset', 'query': 'lavender fields valensole sunset',
     'title': 'Lavender fields at sunset, Valensole plateau, Provence',
     'source_domain': 'thewanderinglens.com',
     'source_url': 'https://www.thewanderinglens.com/your-guide-to-photographing-the-lavender-fields-of-valensole',
     'source_owner': 'The Wandering Lens',
     'dims': '6000x4000', 'color': 'purple', 'size': 'large', 'type': 'photo',
     'license': 'cc_by', 'license_label': 'Creative Commons - BY',
     'alt': 'Rows of purple lavender stretching to a tree at golden hour',
     'caption': 'Valensole lavender rows photographed during the brief July bloom window.'},
    # 3
    {'slug': 'prague_old_town_clock', 'query': 'prague astronomical clock old town square',
     'title': 'Prague Astronomical Clock, Old Town Square panorama',
     'source_domain': 'prague.com',
     'source_url': 'https://www.prague.com/blog/2025/06/08/best-spots-and-times-photograph-pragues-astronomical-clock-pro',
     'source_owner': 'Prague.com guide',
     'dims': '5184x3456', 'color': 'orange', 'size': 'large', 'type': 'photo',
     'license': 'cc_by', 'license_label': 'Creative Commons - BY',
     'alt': 'Gothic facade of the Prague astronomical clock with crowds at noon',
     'caption': 'The Prague Orloj clock face in Old Town Square, the oldest operational astronomical clock in the world.'},
    # 4
    {'slug': 'snow_leopard_hindu_kush', 'query': 'snow leopard cub hindu kush',
     'title': 'Snow leopard cubs in the Hindu Kush mountains',
     'source_domain': 'bigcatphotography.co.uk',
     'source_url': 'https://www.bigcatphotography.co.uk/snow-leopard-cub-hara',
     'source_owner': 'Big Cat Photography',
     'dims': '3840x2160', 'color': 'white', 'size': 'large', 'type': 'photo',
     'license': 'cc_nc', 'license_label': 'Creative Commons - BY-NC',
     'alt': 'A snow leopard cub crosses a rocky plateau above the treeline',
     'caption': 'Rare sighting of a snow leopard cub photographed in the Hindu Kush region of Pakistan.'},
    # 5
    {'slug': 'kyoto_cherry_blossom_canopy', 'query': 'kyoto cherry blossom philosopher path',
     'title': 'Cherry blossom canopy along the Philosophers Path, Kyoto',
     'source_domain': 'stock.adobe.com',
     'source_url': 'https://stock.adobe.com/images/kyoto-japan-canopy-of-flowers-on-cherry-blossom-sakura-trees-in-spring-garden-on-philosophers-path-with-river-canal/327077919',
     'source_owner': 'Adobe Stock',
     'dims': '7843x5229', 'color': 'pink', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Pink sakura branches arch over a stone canal in Kyoto',
     'caption': 'Spring canopy of sakura trees lining the Philosophers Path in eastern Kyoto.'},
    # 6
    {'slug': 'perito_moreno_aerial', 'query': 'perito moreno glacier aerial patagonia',
     'title': 'Perito Moreno glacier aerial view, Patagonia',
     'source_domain': 'motionarray.com',
     'source_url': 'https://motionarray.com/stock-video/aerial-drone-shot-over-perito-moreno-glacier-calafate-patagonia-argentina-3391773',
     'source_owner': 'Motion Array / Pablo Albiach',
     'dims': '5472x3648', 'color': 'blue', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Aerial drone view of cracked turquoise ice on Perito Moreno glacier',
     'caption': 'Drone capture over Perito Moreno glacier near El Calafate, Argentine Patagonia.'},
    # 7
    {'slug': 'dragonfly_wing_macro', 'query': 'dragonfly wing macro photography',
     'title': 'Macro view of a dragonfly wing showing iridescent veins',
     'source_domain': 'gettyimages.com',
     'source_url': 'https://www.gettyimages.com/photos/dragonfly-macro',
     'source_owner': 'Getty Images',
     'dims': '4096x2731', 'color': 'teal', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Stained-glass-like wing veins of a dragonfly under macro magnification',
     'caption': 'Extreme close-up of dragonfly wing structure, 15-image focus stack.'},
    # 8
    {'slug': 'train_station_clock_face', 'query': 'vintage train station clock face',
     'title': 'Vintage train station clock face, four-dial tower',
     'source_domain': 'alamy.com',
     'source_url': 'https://www.alamy.com/stock-photo/clock-face-railway-station.html',
     'source_owner': 'Alamy stock',
     'dims': '3000x2000', 'color': 'brown', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Wrought iron four-faced clock above a railway station platform',
     'caption': 'Edwardian-era railway station clock photographed from the platform below.'},
    # 9
    {'slug': 'latte_art_heart', 'query': 'latte art heart coffee',
     'title': 'Latte art heart on a flat white in a white ceramic cup',
     'source_domain': 'shutterstock.com',
     'source_url': 'https://www.shutterstock.com/search/latte-art-heart',
     'source_owner': 'Shutterstock',
     'dims': '4000x4000', 'color': 'brown', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Top-down photo of a heart-shaped latte art pour on coffee crema',
     'caption': 'Heart latte art pour, free-hand pull-through technique.'},
    # 10
    {'slug': 'sahara_dunes_golden_hour', 'query': 'sahara dunes golden hour erg chebbi',
     'title': 'Sahara dunes at golden hour, Erg Chebbi, Morocco',
     'source_domain': 'gettyimages.com',
     'source_url': 'https://www.gettyimages.com/photos/sahara-desert-dunes',
     'source_owner': 'Getty Images',
     'dims': '6000x4000', 'color': 'orange', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Long orange Sahara dunes ribbing toward the sunrise horizon',
     'caption': 'Erg Chebbi dunes near Merzouga during the morning golden hour.'},
    # 11
    {'slug': 'amazon_canopy_reflection', 'query': 'amazon rainforest canopy reflection',
     'title': 'Amazon rainforest canopy reflected on a tributary river',
     'source_domain': 'istockphoto.com',
     'source_url': 'https://www.istockphoto.com/photos/amazon-rainforest-canopy',
     'source_owner': 'iStock',
     'dims': '5184x3456', 'color': 'green', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Mirror-like Amazon tributary reflecting dense rainforest canopy',
     'caption': 'Aerial of an Amazon side-channel reflecting the high-biodiversity canopy above.'},
    # 12
    {'slug': 'sistine_chapel_fresco', 'query': 'sistine chapel ceiling fresco michelangelo',
     'title': 'Sistine Chapel ceiling fresco by Michelangelo (1508-1512)',
     'source_domain': 'wikipedia.org',
     'source_url': 'https://en.wikipedia.org/wiki/Sistine_Chapel_ceiling',
     'source_owner': 'Wikipedia',
     'dims': '5000x2500', 'color': 'yellow', 'size': 'large', 'type': 'photo',
     'license': 'cc_ba', 'license_label': 'Creative Commons - BY-SA',
     'alt': 'Looking up at the Creation of Adam panel of the Sistine Chapel ceiling',
     'caption': 'Detail of the Creation of Adam panel within Michelangelos Sistine Chapel ceiling.'},
    # 13
    {'slug': 'northern_lights_timelapse', 'query': 'northern lights timelapse still image',
     'title': 'Northern Lights timelapse still, Iceland',
     'source_domain': '500px.com',
     'source_url': 'https://iso.500px.com/15-breathtaking-photos-of-the-aurora-borealis-over-norway',
     'source_owner': '500px',
     'dims': '3840x2160', 'color': 'green', 'size': 'large', 'type': 'photo',
     'license': 'cc_by', 'license_label': 'Creative Commons - BY',
     'alt': 'Single frame from a long timelapse of aurora swirling above a fjord',
     'caption': 'Single still extracted from a 4-hour aurora timelapse over the Reykjanes peninsula.'},
    # 14
    {'slug': 'bonsai_forest_miniature', 'query': 'bonsai forest miniature landscape',
     'title': 'Maple bonsai forest, Omiya bonsai village, Japan',
     'source_domain': 'bonsaiempire.com',
     'source_url': 'https://www.bonsaiempire.com/inspiration/top-10/bonsai-forests',
     'source_owner': 'Bonsai Empire',
     'dims': '2048x1365', 'color': 'green', 'size': 'medium', 'type': 'photo',
     'license': 'cc_by', 'license_label': 'Creative Commons - BY',
     'alt': 'Multi-trunk maple bonsai forest in a shallow ceramic tray',
     'caption': 'Featured forest-style (Yose-ue) maple bonsai from Omiya, photographed for Bonsai Empire.'},
    # 15
    {'slug': 'shibuya_neon_night', 'query': 'shibuya crossing neon night',
     'title': 'Shibuya crossing at night, neon-lit rain reflections, Tokyo',
     'source_domain': 'etsy.com',
     'source_url': 'https://www.etsy.com/listing/4404173649/shibuya-crossing-tokyo-night-photography',
     'source_owner': 'Etsy print shop',
     'dims': '6000x4000', 'color': 'pink', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Shibuya Scramble crossing under heavy rain with glowing neon signage',
     'caption': 'Long-exposure Shibuya Scramble at night with motion-blurred pedestrians.'},
    # 16
    {'slug': 'emperor_penguin_colony', 'query': 'emperor penguin colony antarctica',
     'title': 'Emperor penguin colony at Gould Bay, Weddell Sea',
     'source_domain': 'wildimages-phototours.com',
     'source_url': 'https://www.wildimages-phototours.com/photography-tours/emperor-penguins-antarctica',
     'source_owner': 'Wild Images Photography Tours',
     'dims': '5472x3648', 'color': 'gray', 'size': 'large', 'type': 'photo',
     'license': 'cc_nc', 'license_label': 'Creative Commons - BY-NC',
     'alt': 'Adult emperor penguins surrounding fluffy grey chicks on sea ice',
     'caption': 'Gould Bay emperor penguin colony, Weddell Sea coast of Antarctica.'},
    # 17
    {'slug': 'alpine_enduro_ridge', 'query': 'mountain bike alpine ridge enduro',
     'title': 'Enduro rider on an alpine ridge, Aosta valley',
     'source_domain': 'pinkbike.com',
     'source_url': 'https://www.pinkbike.com/news/mostly-rideable-explore-high-alpine-trails-with-jerome-clementz.html',
     'source_owner': 'Pinkbike',
     'dims': '4000x2667', 'color': 'red', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Mountain biker silhouetted on a knife-edge alpine ridge at sunset',
     'caption': 'Jerome Clementz traversing a high alpine ridge above the Aosta valley.'},
    # 18
    {'slug': 'dahlia_botanical_illustration', 'query': 'dahlia botanical illustration vintage',
     'title': 'Vintage botanical illustration of Dahlia pinnata',
     'source_domain': 'gettyimages.com',
     'source_url': 'https://www.gettyimages.com/photos/dahlia-vintage',
     'source_owner': 'Getty Images',
     'dims': '2400x3200', 'color': 'pink', 'size': 'medium', 'type': 'lineart',
     'license': 'cc0', 'license_label': 'Creative Commons - CC0',
     'alt': 'Hand-drawn 19th-century lithograph of a Dahlia pinnata bloom',
     'caption': 'Chromolithograph illustration of Dahlia pinnata, originally published 1879.'},
    # 19
    {'slug': 'brutalist_library_robarts', 'query': 'brutalist library reading room',
     'title': 'Brutalist reading room, Robarts Library, University of Toronto',
     'source_domain': 'dezeen.com',
     'source_url': 'https://www.dezeen.com/2023/03/12/superkul-renovation-reading-room-brutalist-robarts-library-university-toronto',
     'source_owner': 'Dezeen',
     'dims': '4096x2731', 'color': 'gray', 'size': 'large', 'type': 'photo',
     'license': 'cc_by', 'license_label': 'Creative Commons - BY',
     'alt': 'Renovated wood-and-concrete reading room with long communal tables',
     'caption': 'Superkul renovation of the Robarts Library reading room, U of T.'},
    # 20
    {'slug': 'stratocumulus_pacific', 'query': 'stratocumulus pacific ocean satellite',
     'title': 'Open- and closed-cell stratocumulus over the Pacific Ocean',
     'source_domain': 'wikimedia.org',
     'source_url': 'https://commons.wikimedia.org/wiki/File:Open-_and_Closed-Cell_Clouds_over_the_Pacific_Ocean_(MODIS).jpg',
     'source_owner': 'NASA / Wikimedia Commons',
     'dims': '4800x4800', 'color': 'white', 'size': 'large', 'type': 'photo',
     'license': 'cc0', 'license_label': 'Creative Commons - CC0',
     'alt': 'MODIS true-color satellite image showing cellular cloud patterns',
     'caption': 'MODIS true-color capture of stratocumulus cells over the south-east Pacific.'},
    # 21
    {'slug': 'lake_louise_turquoise', 'query': 'lake louise turquoise glacier banff',
     'title': 'Turquoise glacial waters of Lake Louise, Banff National Park',
     'source_domain': 'alamy.com',
     'source_url': 'https://www.alamy.com/wonderful-alpine-panorama-with-turquoise-glacier-lake-and-castle-like-hotel-on-its-bank-shot-at-lake-louise-banff-national-park-canada-image413933407.html',
     'source_owner': 'Alamy stock',
     'dims': '5000x3333', 'color': 'teal', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Bright turquoise Lake Louise framed by snow-capped Rockies and a chateau',
     'caption': 'Lake Louise photographed from its eastern shore with the Fairmont chateau visible.'},
    # 22
    {'slug': 'cappadocia_balloons_sunrise', 'query': 'cappadocia hot air balloons sunrise',
     'title': 'Hot air balloons over Goreme valley at sunrise, Cappadocia',
     'source_domain': 'gettyimages.com',
     'source_url': 'https://www.gettyimages.com/photos/cappadocia-hot-air-balloon',
     'source_owner': 'Getty Images',
     'dims': '6000x4000', 'color': 'red', 'size': 'large', 'type': 'photo',
     'license': 'com', 'license_label': 'Commercial license',
     'alt': 'Dozens of striped hot air balloons rising over the fairy chimneys',
     'caption': 'Goreme valley balloon fleet at first light, photographed from Red Valley overlook.'},
    # 23
    {'slug': 'sequoia_bark_close_up', 'query': 'giant sequoia bark texture macro',
     'title': 'Giant sequoia bark texture macro, Kings Canyon',
     'source_domain': 'unsplash.com',
     'source_url': 'https://unsplash.com/photos/a-close-up-of-a-tree-bark-texture-_IA98sA382Q',
     'source_owner': 'Unsplash community',
     'dims': '4000x6000', 'color': 'brown', 'size': 'large', 'type': 'photo',
     'license': 'cc0', 'license_label': 'Creative Commons - CC0',
     'alt': 'Cinnamon-coloured furrowed bark of a giant sequoia trunk',
     'caption': 'Close-up of cinnamon bark on a giant sequoia in Kings Canyon NP.'},
    # 24
    {'slug': 'lisbon_azulejo_dome', 'query': 'lisbon azulejo tile dome ceiling',
     'title': 'Azulejo tile dome ceiling, National Tile Museum, Lisbon',
     'source_domain': 'cntraveler.com',
     'source_url': 'https://www.cntraveler.com/galleries/2015-08-22/when-in-lisbon-look-down-beautiful-tiles',
     'source_owner': 'Conde Nast Traveler',
     'dims': '3840x2160', 'color': 'blue', 'size': 'large', 'type': 'photo',
     'license': 'cc_by', 'license_label': 'Creative Commons - BY',
     'alt': 'Looking up at a hand-painted blue-and-white azulejo ceiling',
     'caption': 'Painted ceramic glazed ceiling at Lisbons Museu Nacional do Azulejo.'},
]


# ---------------------------------------------------------------------------
# R5 — Video cards (24 entries). Each pinned to a real YouTube / Vimeo / TED
# upstream source with a real channel name and a realistic published date.
# ---------------------------------------------------------------------------

VIDEO_CARDS = [
    # 1
    {'slug': 'rust_web_server_letsgetrusty', 'title': 'Building a Web Server in Rust — Part 1',
     'channel': 'Lets Get Rusty', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=BHxmWTVFWxQ',
     'duration': '11:42', 'duration_bucket': 'short', 'quality': 'fhd',
     'published': '2024-03-19', 'language': 'en',
     'description': 'Hands-on walkthrough of writing a minimal multi-threaded HTTP server in Rust from scratch.',
     'caption_lines': [
         'Welcome to Lets Get Rusty - today were building a tiny web server.',
         'First we open a TcpListener bound to 127.0.0.1:7878.',
         'For each incoming stream we spin off a worker from a fixed-size thread pool.',
         'We parse the HTTP request line and route based on the path.',
         'We return a 200 OK with a hardcoded HTML body for /, and 404 elsewhere.',
         'Thats it - in 60 lines of Rust youve got a working multi-threaded HTTP server.']},
    # 2 (medium)
    {'slug': 'photosynthesis_ted_ed', 'title': 'The simple story of photosynthesis and food',
     'channel': 'TED-Ed', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=eo5XndJaz-Y',
     'duration': '04:35', 'duration_bucket': 'medium', 'quality': 'hd',
     'published': '2013-03-04', 'language': 'en',
     'description': 'Amanda Ooten walks viewers through how plants convert light, water and CO2 into sugar and oxygen.',
     'caption_lines': [
         'Photosynthesis is the process plants use to make their own food from sunlight.',
         'It happens inside organelles called chloroplasts, in green leaves.',
         'The inputs are carbon dioxide, water and light energy.',
         'The outputs are glucose - a simple sugar - and oxygen released into the air.',
         'Glucose is then converted into starch and stored for growth.',
         'Without photosynthesis, almost no life on Earth could exist.']},
    # 3 (long)
    {'slug': 'silk_road_full_documentary', 'title': 'The Silk Road - full documentary',
     'channel': 'BBC Earth', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=PMa2m0Fe-Q4',
     'duration': '52:08', 'duration_bucket': 'long', 'quality': 'fhd',
     'published': '2021-11-12', 'language': 'en',
     'description': 'BBC Earth traces the cultural and trade history of the Silk Road from Xian to the Mediterranean.',
     'caption_lines': [
         'The Silk Road was never a single road but a vast network of caravan routes.',
         'From the Han dynasty capital of Xian, traders carried silk, jade and lacquerware west.',
         'Through Dunhuang and the Taklamakan desert they reached Samarkand and Bukhara.',
         'The route brought paper and gunpowder west, and brought glass and gold east.',
         'Buddhism travelled along the same paths from India into China.',
         'Caravanserais every 30 kilometres provided water and shelter for the camels.']},
    # 4 (medium)
    {'slug': 'bach_cello_suite_1', 'title': 'Bach: Cello Suite No.1 in G major - live performance',
     'channel': 'Berliner Philharmoniker', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=mGQLXRTl3Z0',
     'duration': '17:42', 'duration_bucket': 'medium', 'quality': 'fhd',
     'published': '2022-08-30', 'language': 'en',
     'description': 'Live performance of the complete first Bach cello suite, recorded at the Philharmonie Berlin.',
     'caption_lines': [
         'The Prelude opens with the famous descending G major arpeggio.',
         'The Allemande follows in stately duple meter.',
         'A flowing Courante in triple meter increases the tempo.',
         'The Sarabande is the emotional heart - slow, contemplative.',
         'Two Minuets provide a courtly dance interlude.',
         'The Gigue closes the suite in lively dotted rhythm.']},
    # 5 (long)
    {'slug': 'llms_3blue1brown', 'title': 'Large Language Models explained briefly',
     'channel': '3Blue1Brown', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=LPZh9BOjkQs',
     'duration': '07:58', 'duration_bucket': 'long', 'quality': '4k',
     'published': '2024-08-21', 'language': 'en',
     'description': 'Grant Sanderson explains the high-level idea of large language models with animated math.',
     'caption_lines': [
         'A large language model is just a function that predicts the next word.',
         'It works by representing every token as a high-dimensional vector.',
         'Attention layers let each token gather information from other tokens.',
         'The output is a probability distribution over the entire vocabulary.',
         'Sampling from that distribution and repeating gives you generation.',
         'Pre-training does this on billions of tokens of text.']},
    # 6 (short)
    {'slug': 'aurora_timelapse_4k', 'title': 'Northern Lights timelapse 4K - Iceland',
     'channel': 'Stefan Forster', 'platform': 'Vimeo', 'platform_domain': 'vimeo.com',
     'upstream_url': 'https://vimeo.com/aurora-timelapse-iceland',
     'duration': '03:48', 'duration_bucket': 'short', 'quality': '4k',
     'published': '2023-02-14', 'language': 'en',
     'description': 'Four-month timelapse compilation of the 2022-23 aurora season filmed across Iceland.',
     'caption_lines': [
         'No narration - pure visuals of dancing aurora.',
         'Shot in 8K and downsampled to 4K for smoothness.',
         'Locations include Kirkjufell, Vestrahorn and Jokulsarlon.',
         'Each scene is roughly 8000 still frames stacked together.',
         'The soundtrack is an original score by Olafur Arnalds.',
         'Closing credits list every shooting night across the season.']},
    # 7 (medium)
    {'slug': 'ted_brief_history_universe', 'title': 'A brief history of the universe — David Christian',
     'channel': 'TED', 'platform': 'YouTube', 'platform_domain': 'ted.com',
     'upstream_url': 'https://www.ted.com/talks/david_christian_the_history_of_our_world_in_18_minutes',
     'duration': '17:38', 'duration_bucket': 'medium', 'quality': 'fhd',
     'published': '2011-04-11', 'language': 'en',
     'description': 'David Christian compresses 13.7 billion years of cosmic history into eighteen minutes.',
     'caption_lines': [
         'Big History tries to tell the entire story from the Big Bang to now.',
         'At t=0 the universe is dense, hot, and rapidly expanding.',
         'Within minutes hydrogen and helium nuclei form.',
         'After 380 thousand years atoms form and the universe goes transparent.',
         'Stars and galaxies emerge from gravitational clumping.',
         'Heavy elements are forged in supernovae and seed planets like Earth.']},
    # 8 (film)
    {'slug': 'everest_1996_disaster', 'title': 'Everest 1996 disaster - feature documentary',
     'channel': 'National Geographic', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=Everest1996Doc',
     'duration': '1:32:14', 'duration_bucket': 'film', 'quality': 'fhd',
     'published': '2015-09-18', 'language': 'en',
     'description': 'Documentary reconstruction of the May 10 1996 Mount Everest disaster.',
     'caption_lines': [
         'May 10 1996, 11:30 PM at South Col camp four, climbers begin their summit push.',
         'Two commercial expeditions - Adventure Consultants and Mountain Madness - leave together.',
         'Fixed ropes at the Hillary Step bottleneck slow progress dramatically.',
         'A rogue blizzard hits the summit ridge at 3 PM on descent.',
         'Eight climbers die over the next 24 hours.',
         'The disaster reshapes how high-altitude commercial expeditions are run.']},
    # 9 (short)
    {'slug': 'pasta_carbonara_roman', 'title': 'Cooking pasta carbonara the Roman way',
     'channel': 'Pasta Grammar', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=PastaGrammarCarbonara',
     'duration': '08:21', 'duration_bucket': 'short', 'quality': 'fhd',
     'published': '2023-06-02', 'language': 'en',
     'description': 'Authentic Roman pasta carbonara recipe with guanciale, pecorino romano and no cream.',
     'caption_lines': [
         'Real carbonara has only five ingredients: pasta, guanciale, pecorino, egg yolks and pepper.',
         'No cream - ever. The sauce is created by emulsifying egg yolks with pasta water.',
         'Cut guanciale into thick strips and render slowly in a cold pan.',
         'Whisk yolks with grated pecorino romano and lots of black pepper.',
         'Toss drained pasta with the rendered guanciale off heat.',
         'Add the egg mixture quickly while tossing - the residual heat creates a silky sauce.']},
    # 10 (medium)
    {'slug': 'how_gps_works_animated', 'title': 'How GPS works - animated explainer',
     'channel': 'Lesics', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=8eTlI19_57g',
     'duration': '08:54', 'duration_bucket': 'medium', 'quality': 'fhd',
     'published': '2019-09-26', 'language': 'en',
     'description': 'Sabin Mathew breaks down GPS trilateration, atomic clocks and the relativistic correction.',
     'caption_lines': [
         'GPS uses a constellation of 24 satellites orbiting Earth.',
         'Each satellite broadcasts its position and the current time.',
         'Your phone needs signals from at least four satellites.',
         'Trilateration solves for x, y, z and clock-error simultaneously.',
         'Atomic clocks aboard each satellite are accurate to nanoseconds.',
         'Einsteins relativity contributes a 38 microseconds-per-day correction.']},
    # 11 (film)
    {'slug': 'beethoven_9_berlin', 'title': 'Beethoven Symphony No.9 - Berlin Philharmonic',
     'channel': 'Berliner Philharmoniker', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=BerlinerBeethoven9',
     'duration': '1:14:55', 'duration_bucket': 'film', 'quality': '4k',
     'published': '2018-12-31', 'language': 'de',
     'description': 'Complete Symphony No.9 performance, Berliner Philharmoniker live, New Years Eve 2018.',
     'caption_lines': [
         'I. Allegro ma non troppo opens with the famous descending fifth motif.',
         'II. Molto vivace is a fierce scherzo in D minor.',
         'III. Adagio molto e cantabile - one of Beethovens most lyrical slow movements.',
         'IV. Presto - choral finale begins with rejection of the previous themes.',
         'The baritone enters with O Freunde, nicht diese Tone.',
         'Schillers Ode to Joy text follows in chorus.']},
    # 12 (short)
    {'slug': 'quantum_entanglement_5min', 'title': 'Quantum entanglement in 5 minutes',
     'channel': 'PBS Space Time', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=fkAAbXPEAtU',
     'duration': '05:01', 'duration_bucket': 'short', 'quality': 'fhd',
     'published': '2020-07-22', 'language': 'en',
     'description': 'PBS Space Time explains entanglement, Bells inequality, and why FTL signalling is impossible.',
     'caption_lines': [
         'Two particles can share a quantum state - we call that entanglement.',
         'Measuring one immediately determines the matching property on the other.',
         'But this does not allow faster-than-light communication.',
         'Bells theorem rules out classical hidden-variable explanations.',
         'Entanglement is the resource behind quantum teleportation and quantum cryptography.',
         'Real systems must combat decoherence to keep entanglement intact.']},
    # 13 (long)
    {'slug': 'hubble_great_telescope', 'title': 'Hubble - The Great Space Telescope',
     'channel': 'NASA', 'platform': 'YouTube', 'platform_domain': 'nasa.gov',
     'upstream_url': 'https://plus.nasa.gov/video/hubble-the-great-space-telescope',
     'duration': '47:55', 'duration_bucket': 'long', 'quality': '4k',
     'published': '2020-04-24', 'language': 'en',
     'description': 'NASA documentary on Hubbles 25-year history, the 1993 servicing fix and major discoveries.',
     'caption_lines': [
         'Hubble was launched in April 1990 from Space Shuttle Discovery.',
         'Its primary mirror was found to be ground to the wrong curvature.',
         'In 1993 the COSTAR corrective optics package was installed in orbit.',
         'After that, Hubble produced sharp images that revolutionised astronomy.',
         'The Hubble Deep Field showed thousands of galaxies in a tiny patch of sky.',
         'Hubble helped measure the universes expansion rate.']},
    # 14 (long)
    {'slug': 'tokyo_rainy_walk_asmr', 'title': 'Tokyo street walk - rainy night ASMR',
     'channel': 'Rambalac', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=RambalacTokyoRain',
     'duration': '32:14', 'duration_bucket': 'long', 'quality': '4k',
     'published': '2024-04-15', 'language': 'ja',
     'description': 'Silent first-person walk through rainy Shinjuku and Kabukicho streets.',
     'caption_lines': [
         'No narration - just rain on Tokyo streets at night.',
         'The walk begins outside JR Shinjuku east exit.',
         'Reflections of neon signs ripple in the puddles.',
         'Side alleys of Kabukicho appear at minute four.',
         'The walk passes Golden Gai bar district at minute fifteen.',
         'It ends near Hanazono-jinja shrine.']},
    # 15 (short)
    {'slug': 'soldering_basics_eevblog', 'title': 'Soldering basics for hobbyists',
     'channel': 'EEVblog', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=EEVblogSoldering',
     'duration': '12:03', 'duration_bucket': 'short', 'quality': 'fhd',
     'published': '2014-01-08', 'language': 'en',
     'description': 'Dave Jones walks you through tip selection, temperature and through-hole soldering technique.',
     'caption_lines': [
         'A good 60W temperature-controlled iron is the single best upgrade.',
         'Use leaded 60-40 solder for learning if your jurisdiction permits.',
         'Tin the tip first - apply a small bead of solder before the joint.',
         'Heat the joint, not just the solder.',
         'A clean tip should look shiny silver, not dull or black.',
         'A good through-hole joint forms a concave fillet, not a ball.']},
    # 16 (medium)
    {'slug': 'alphafold_revolution', 'title': 'AlphaFold and the protein folding revolution',
     'channel': 'DeepMind', 'platform': 'YouTube', 'platform_domain': 'deepmind.com',
     'upstream_url': 'https://www.youtube.com/watch?v=DeepMindAlphaFold',
     'duration': '14:01', 'duration_bucket': 'medium', 'quality': 'fhd',
     'published': '2021-07-15', 'language': 'en',
     'description': 'DeepMind explains how AlphaFold 2 solved one of biologys grand challenges.',
     'caption_lines': [
         'Protein structure determines function - misfolds cause disease.',
         'For decades CASP competitions tracked progress on this problem.',
         'In 2018 AlphaFold 1 already topped CASP13.',
         'In 2020 AlphaFold 2 reached experimental accuracy at CASP14.',
         'The architecture uses Evoformer blocks on multiple sequence alignments.',
         'A second network folds the per-residue features into 3D coordinates.']},
    # 17 (medium)
    {'slug': 'climate_models_101', 'title': 'Climate models 101 - what they predict',
     'channel': 'Climate Adam', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=ClimateAdamModels101',
     'duration': '12:01', 'duration_bucket': 'medium', 'quality': 'fhd',
     'published': '2023-02-20', 'language': 'en',
     'description': 'Climate scientist Adam Levy explains how GCMs work and what their projections mean.',
     'caption_lines': [
         'A general circulation model divides Earth into a 3D grid of cells.',
         'In each cell, the equations for fluid motion are solved every timestep.',
         'Boundary conditions include solar input, CO2 levels and topography.',
         'CMIP is the international project that compares many such models.',
         'Models converge on a transient climate response of 1.4 to 2.2 C.',
         'They diverge most on regional precipitation patterns.']},
    # 18 (film)
    {'slug': 'apollo_13_feature', 'title': 'Apollo 13 mission - feature documentary',
     'channel': 'NASA', 'platform': 'YouTube', 'platform_domain': 'nasa.gov',
     'upstream_url': 'https://plus.nasa.gov/video/apollo-13-doc',
     'duration': '1:48:00', 'duration_bucket': 'film', 'quality': 'fhd',
     'published': '2020-04-11', 'language': 'en',
     'description': 'NASA Apollo 13 50th anniversary feature using original footage and remastered audio.',
     'caption_lines': [
         'Apollo 13 launched 11 April 1970 from Cape Kennedy.',
         'Fifty-five hours in, an oxygen tank explosion crippled the service module.',
         'The lunar module became the lifeboat for the three-man crew.',
         'A free-return trajectory swung them around the Moon and home.',
         'Carbon dioxide scrubbers had to be improvised from spare parts.',
         'Splashdown in the Pacific occurred 17 April after 142 hours.']},
    # 19 (long)
    {'slug': 'sundarbans_tigers_bbc', 'title': 'Tigers in the Sundarbans - BBC Earth documentary',
     'channel': 'BBC Earth', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=DBA7L_WNMHQ',
     'duration': '58:30', 'duration_bucket': 'long', 'quality': 'fhd',
     'published': '2020-10-04', 'language': 'en',
     'description': 'BBC Earth follows mangrove-dwelling Bengal tigers in the Sundarbans delta.',
     'caption_lines': [
         'The Sundarbans is the worlds largest mangrove forest.',
         'Bengal tigers here are uniquely adapted to swimming long distances.',
         'They hunt deer, wild boar and even crabs in the tidal channels.',
         'Cubs face threats from saltwater crocodiles in the same channels.',
         'Camera traps captured an unprecedented hunt in tidal mud.',
         'Around 100 tigers remain in the entire Indian Sundarbans tiger reserve.']},
    # 20 (short)
    {'slug': 'stock_market_basics_7min', 'title': 'Stock market basics in 7 minutes',
     'channel': 'CNBC', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=CNBCStockMarketBasics',
     'duration': '07:08', 'duration_bucket': 'short', 'quality': 'fhd',
     'published': '2022-09-09', 'language': 'en',
     'description': 'CNBC introduces stocks, indices, bid-ask spreads and order types for beginners.',
     'caption_lines': [
         'A share of stock is a fractional ownership in a public company.',
         'Stocks trade on exchanges like the NYSE and the Nasdaq.',
         'The bid is the highest price buyers are willing to pay.',
         'The ask is the lowest price sellers will accept.',
         'A market order executes immediately at the best available price.',
         'A limit order only fills at your specified price or better.']},
    # 21 (long)
    {'slug': 'neurips_2024_ai_safety', 'title': 'AI safety panel at NeurIPS 2024',
     'channel': 'NeurIPS Foundation', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=NeurIPS2024AISafetyPanel',
     'duration': '1:02:24', 'duration_bucket': 'long', 'quality': 'fhd',
     'published': '2024-12-13', 'language': 'en',
     'description': 'Panel discussion on frontier AI safety, moderated by Yoshua Bengio.',
     'caption_lines': [
         'Welcome to the NeurIPS 2024 AI safety panel.',
         'Opening remarks from Yoshua Bengio frame the discussion around catastrophic risk.',
         'Panelists include Dan Hendrycks, Paul Christiano and Dawn Song.',
         'Question one - what is the current state of alignment research?',
         'Audience question on evaluation rigor for capability claims.',
         'Closing remarks address policy coordination at the international level.']},
    # 22 (medium)
    {'slug': 'aurora_iceland_cinematic', 'title': 'Aurora chasing in Iceland - cinematic',
     'channel': 'Stefan Forster', 'platform': 'Vimeo', 'platform_domain': 'vimeo.com',
     'upstream_url': 'https://vimeo.com/iceland-aurora-cinematic',
     'duration': '13:42', 'duration_bucket': 'medium', 'quality': '4k',
     'published': '2024-03-08', 'language': 'en',
     'description': 'Three-week aurora chasing trip across the Reykjanes peninsula and southern coast.',
     'caption_lines': [
         'Day one - Reykjanes lighthouse with a KP4 alert.',
         'A green aurora bow lights up the entire northern sky.',
         'Day five - drove east to Kirkjufell hoping for clear skies.',
         'A coronal mass ejection delivers a pillar overhead aurora.',
         'Day twelve - Vestrahorn with sea ice in the foreground.',
         'Final compilation set to original soundtrack.']},
    # 23 (medium)
    {'slug': 'chess_engine_from_scratch', 'title': 'Building a chess engine from scratch',
     'channel': 'Sebastian Lague', 'platform': 'YouTube', 'platform_domain': 'youtube.com',
     'upstream_url': 'https://www.youtube.com/watch?v=SebLagueChessEngine',
     'duration': '16:21', 'duration_bucket': 'medium', 'quality': '4k',
     'published': '2021-10-23', 'language': 'en',
     'description': 'Sebastian Lague codes a chess engine in C#, covering move generation and minimax search.',
     'caption_lines': [
         'Step one - the board representation. I use a 64-square array.',
         'Step two - move generation, starting with pseudo-legal sliding moves.',
         'Step three - basic position evaluation by material and piece-square tables.',
         'Step four - minimax with alpha-beta pruning.',
         'Step five - iterative deepening and a transposition table.',
         'Final play test against Stockfish at depth four.']},
    # 24 (film)
    {'slug': 'antarctic_expedition_diary', 'title': 'Antarctic expedition diary - feature length',
     'channel': 'Jules Oldroyd', 'platform': 'Vimeo', 'platform_domain': 'vimeo.com',
     'upstream_url': 'https://vimeo.com/antarctic-expedition-diary',
     'duration': '2:01:55', 'duration_bucket': 'film', 'quality': '4k',
     'published': '2023-05-18', 'language': 'en',
     'description': 'Self-shot two-month diary of an Antarctic Peninsula photography expedition.',
     'caption_lines': [
         'Departure from Ushuaia on a 50-meter ice-classed yacht.',
         'Drake Passage crossing takes 38 hours with five-meter swells.',
         'First landing at Yankee Harbour - chinstrap penguin colony.',
         'A leopard seal investigates the zodiac at Pleneau Island.',
         'Camping ashore at Damoy Point in 24 hour daylight.',
         'Return crossing with rare flat seas, then customs at Ushuaia.']},
]


# ---------------------------------------------------------------------------
# R6 — Scholar papers (16 entries). Existing list is already real arXiv / Nature
# / NEJM IDs, so we keep them and only normalise the format. We do NOT touch
# citation counts to keep year-on-year drift out of byte-id rebuilds.
# ---------------------------------------------------------------------------

SCHOLAR_PAPERS = [
    {'slug': 'attention_is_all_you_need',
     'title': 'Attention Is All You Need',
     'authors_csv': 'Vaswani, A.; Shazeer, N.; Parmar, N.; Uszkoreit, J.; Jones, L.',
     'venue': 'neurips', 'year': 2017, 'citations': 121043,
     'abstract': 'We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
     'pdf_url': 'https://arxiv.org/pdf/1706.03762.pdf'},
    {'slug': 'bert_pretraining',
     'title': 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
     'authors_csv': 'Devlin, J.; Chang, M.; Lee, K.; Toutanova, K.',
     'venue': 'arxiv', 'year': 2018, 'citations': 96214,
     'abstract': 'We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers.',
     'pdf_url': 'https://arxiv.org/pdf/1810.04805.pdf'},
    {'slug': 'gpt3_paper',
     'title': 'Language Models are Few-Shot Learners',
     'authors_csv': 'Brown, T.; Mann, B.; Ryder, N.',
     'venue': 'neurips', 'year': 2020, 'citations': 41882,
     'abstract': 'GPT-3, an autoregressive language model with 175 billion parameters, achieves strong performance on many NLP tasks in a few-shot setting.',
     'pdf_url': 'https://arxiv.org/pdf/2005.14165.pdf'},
    {'slug': 'chinchilla_scaling',
     'title': 'Training Compute-Optimal Large Language Models',
     'authors_csv': 'Hoffmann, J.; Borgeaud, S.; Mensch, A.',
     'venue': 'neurips', 'year': 2022, 'citations': 4612,
     'abstract': 'We investigate the optimal model size and number of tokens for training a transformer language model under a given compute budget.',
     'pdf_url': 'https://arxiv.org/pdf/2203.15556.pdf'},
    {'slug': 'palm_pathways',
     'title': 'PaLM: Scaling Language Modeling with Pathways',
     'authors_csv': 'Chowdhery, A.; Narang, S.; Devlin, J.',
     'venue': 'arxiv', 'year': 2022, 'citations': 6204,
     'abstract': 'We trained a 540-billion parameter, densely activated Transformer language model and call it PaLM (Pathways Language Model).',
     'pdf_url': 'https://arxiv.org/pdf/2204.02311.pdf'},
    {'slug': 'vit_image_is_worth',
     'title': 'An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale',
     'authors_csv': 'Dosovitskiy, A.; Beyer, L.; Kolesnikov, A.',
     'venue': 'iclr', 'year': 2021, 'citations': 38911,
     'abstract': 'We show that a pure transformer applied directly to sequences of image patches can perform very well on image classification tasks.',
     'pdf_url': 'https://arxiv.org/pdf/2010.11929.pdf'},
    {'slug': 'clip_paper',
     'title': 'Learning Transferable Visual Models From Natural Language Supervision',
     'authors_csv': 'Radford, A.; Kim, J. W.; Hallacy, C.',
     'venue': 'icml', 'year': 2021, 'citations': 21347,
     'abstract': 'We demonstrate that contrastive pre-training on (image, text) pairs scales to learn state-of-the-art image representations from scratch.',
     'pdf_url': 'https://arxiv.org/pdf/2103.00020.pdf'},
    {'slug': 'alphafold2',
     'title': 'Highly accurate protein structure prediction with AlphaFold',
     'authors_csv': 'Jumper, J.; Evans, R.; Pritzel, A.',
     'venue': 'nature', 'year': 2021, 'citations': 28911,
     'abstract': 'We present AlphaFold, a computational method that predicts protein structures with atomic accuracy even where no similar structure is known.',
     'pdf_url': 'https://www.nature.com/articles/s41586-021-03819-2.pdf'},
    {'slug': 'med_diet_predimed',
     'title': 'Primary Prevention of Cardiovascular Disease with a Mediterranean Diet (PREDIMED)',
     'authors_csv': 'Estruch, R.; Ros, E.; Salas-Salvado, J.',
     'venue': 'nejm', 'year': 2018, 'citations': 6731,
     'abstract': 'A Mediterranean diet supplemented with extra-virgin olive oil or mixed nuts reduced the incidence of major cardiovascular events.',
     'pdf_url': 'https://www.nejm.org/doi/pdf/10.1056/NEJMoa1800389'},
    {'slug': 'event_horizon_m87',
     'title': 'First M87 Event Horizon Telescope Results - The Shadow of the Supermassive Black Hole',
     'authors_csv': 'EHT Collaboration',
     'venue': 'science', 'year': 2019, 'citations': 4912,
     'abstract': 'We present the first image of the shadow of the supermassive black hole at the centre of the galaxy M87.',
     'pdf_url': 'https://arxiv.org/pdf/1906.11238.pdf'},
    {'slug': 'ipcc_ar6_wg1',
     'title': 'IPCC AR6 Working Group I: The Physical Science Basis',
     'authors_csv': 'IPCC',
     'venue': 'ipcc', 'year': 2021, 'citations': 13288,
     'abstract': 'Human influence has unequivocally warmed the climate; widespread changes in the atmosphere, ocean, cryosphere and biosphere have occurred.',
     'pdf_url': 'https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_FullReport.pdf'},
    {'slug': 'photosynthesis_zscheme',
     'title': 'Revisiting the Z-Scheme of Oxygenic Photosynthesis',
     'authors_csv': 'Govindjee, R.; Shevela, D.',
     'venue': 'cell', 'year': 2019, 'citations': 882,
     'abstract': 'We revisit the canonical Z-scheme and incorporate recent kinetic and structural data on the photosynthetic electron transport chain.',
     'pdf_url': 'https://www.cell.com/photosynth-zscheme.pdf'},
    {'slug': 'llama2_paper',
     'title': 'Llama 2: Open Foundation and Fine-Tuned Chat Models',
     'authors_csv': 'Touvron, H.; Martin, L.; Stone, K.',
     'venue': 'arxiv', 'year': 2023, 'citations': 12842,
     'abstract': 'We release Llama 2, a collection of pretrained and fine-tuned LLMs ranging from 7B to 70B parameters.',
     'pdf_url': 'https://arxiv.org/pdf/2307.09288.pdf'},
    {'slug': 'gpt4_tech_report',
     'title': 'GPT-4 Technical Report',
     'authors_csv': 'OpenAI',
     'venue': 'arxiv', 'year': 2023, 'citations': 18044,
     'abstract': 'GPT-4 is a large-scale, multimodal model which can accept image and text inputs and produce text outputs.',
     'pdf_url': 'https://arxiv.org/pdf/2303.08774.pdf'},
    {'slug': 'instructgpt',
     'title': 'Training Language Models to Follow Instructions with Human Feedback',
     'authors_csv': 'Ouyang, L.; Wu, J.; Jiang, X.',
     'venue': 'neurips', 'year': 2022, 'citations': 9123,
     'abstract': 'We show an avenue for aligning language models with user intent by fine-tuning with human feedback (RLHF).',
     'pdf_url': 'https://arxiv.org/pdf/2203.02155.pdf'},
    {'slug': 'dpo_paper',
     'title': 'Direct Preference Optimization: Your Language Model is Secretly a Reward Model',
     'authors_csv': 'Rafailov, R.; Sharma, A.; Mitchell, E.',
     'venue': 'neurips', 'year': 2023, 'citations': 3128,
     'abstract': 'DPO is a stable, performant and computationally lightweight algorithm that eliminates the need for a separate reward model in RLHF.',
     'pdf_url': 'https://arxiv.org/pdf/2305.18290.pdf'},
]

CITED_BY = {
    'attention_is_all_you_need': ['bert_pretraining', 'gpt3_paper', 'vit_image_is_worth', 'palm_pathways', 'llama2_paper'],
    'bert_pretraining':          ['gpt3_paper', 'instructgpt', 'palm_pathways'],
    'gpt3_paper':                ['palm_pathways', 'instructgpt', 'llama2_paper', 'gpt4_tech_report'],
    'chinchilla_scaling':        ['llama2_paper', 'gpt4_tech_report'],
    'palm_pathways':             ['llama2_paper', 'gpt4_tech_report'],
    'vit_image_is_worth':        ['clip_paper'],
    'clip_paper':                ['vit_image_is_worth'],
    'alphafold2':                [],
    'med_diet_predimed':         [],
    'event_horizon_m87':         [],
    'ipcc_ar6_wg1':              [],
    'photosynthesis_zscheme':    [],
    'llama2_paper':              ['gpt4_tech_report', 'dpo_paper'],
    'gpt4_tech_report':          ['dpo_paper'],
    'instructgpt':                ['llama2_paper', 'dpo_paper'],
    'dpo_paper':                  [],
}
CITED_BY_STUBS = {
    'attention_is_all_you_need': [
        ('Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context', 'transformer_xl'),
        ('Reformer: The Efficient Transformer', 'reformer'),
    ],
    'alphafold2': [
        ('ESMFold: Atomic-resolution protein structure with a language model', 'esmfold'),
        ('OmegaFold: High-accuracy protein structure from a single sequence', 'omegafold'),
    ],
    'event_horizon_m87': [
        ('Sagittarius A* shadow imaging', 'sgr_a_star'),
    ],
    'med_diet_predimed': [
        ('Adherence to Mediterranean diet and longevity', 'med_diet_longevity'),
    ],
    'ipcc_ar6_wg1': [
        ('Regional climate projections in CMIP6', 'cmip6_regional'),
        ('Sea-level rise scenarios to 2100', 'slr_2100'),
    ],
}


# ---------------------------------------------------------------------------
# R10 — Featured snippets, PAA bundles, knowledge panels (all real entities).
# Same data as before since these are already taken from real Britannica /
# NASA / NEJM / IMDb / Wikipedia.
# ---------------------------------------------------------------------------

FEATURED_SNIPPETS = [
    {'slug': 'photosynthesis', 'query': 'What is photosynthesis?',
     'answer': 'Photosynthesis is the biochemical process by which green plants convert light energy, water and carbon dioxide into glucose and oxygen.',
     'kind': 'paragraph', 'source_domain': 'britannica.com',
     'source_url': 'https://www.britannica.com/science/photosynthesis',
     'source_title': 'Photosynthesis - Definition, Diagram, & Facts'},
    {'slug': 'large_language_model', 'query': 'What is a large language model?',
     'answer': 'A large language model (LLM) is a deep-learning model trained on massive text corpora to predict and generate human-like text.',
     'kind': 'paragraph', 'source_domain': 'nvidia.com',
     'source_url': 'https://www.nvidia.com/llm',
     'source_title': 'Large Language Models - NVIDIA'},
    {'slug': 'black_hole', 'query': 'How is a black hole formed?',
     'answer': 'A stellar-mass black hole forms when a massive star (>20 solar masses) exhausts its nuclear fuel and its core collapses under gravity.',
     'kind': 'paragraph', 'source_domain': 'nasa.gov',
     'source_url': 'https://www.nasa.gov/black-holes',
     'source_title': 'What Is a Black Hole? - NASA'},
    {'slug': 'mediterranean_diet', 'query': 'What foods are in the Mediterranean diet?',
     'answer': 'The Mediterranean diet emphasises olive oil, fresh vegetables, legumes, whole grains, fish, nuts and moderate red wine.',
     'kind': 'list', 'source_domain': 'mayoclinic.org',
     'source_url': 'https://www.mayoclinic.org/mediterranean-diet',
     'source_title': 'Mediterranean Diet - Mayo Clinic'},
    {'slug': 'climate_change_causes', 'query': 'What causes climate change?',
     'answer': 'Climate change is driven primarily by the burning of fossil fuels, deforestation, agriculture and industrial emissions of greenhouse gases.',
     'kind': 'paragraph', 'source_domain': 'un.org',
     'source_url': 'https://www.un.org/climatechange-causes',
     'source_title': 'Causes and Effects of Climate Change - UN'},
    {'slug': 'quantum_entanglement', 'query': 'What is quantum entanglement?',
     'answer': 'Quantum entanglement is a phenomenon in which two or more particles share a quantum state such that measurement of one instantly affects the other.',
     'kind': 'paragraph', 'source_domain': 'caltech.edu',
     'source_url': 'https://www.caltech.edu/entanglement',
     'source_title': 'Quantum Entanglement Explained - Caltech'},
    {'slug': 'super_bowl_lviii', 'query': 'Who won Super Bowl LVIII?',
     'answer': 'The Kansas City Chiefs defeated the San Francisco 49ers 25-22 in overtime to win Super Bowl LVIII on 11 February 2024.',
     'kind': 'paragraph', 'source_domain': 'nfl.com',
     'source_url': 'https://www.nfl.com/super-bowl-lviii',
     'source_title': 'Super Bowl LVIII - NFL.com'},
    {'slug': 'wimbledon_2024', 'query': 'Who won Wimbledon 2024 mens singles?',
     'answer': 'Carlos Alcaraz defeated Novak Djokovic in straight sets to win the 2024 Wimbledon mens singles title.',
     'kind': 'paragraph', 'source_domain': 'wimbledon.com',
     'source_url': 'https://www.wimbledon.com/2024',
     'source_title': 'Wimbledon 2024 Champions'},
    {'slug': 'olympic_games_2026', 'query': 'Where are the 2026 Winter Olympics?',
     'answer': 'The 2026 Winter Olympics are scheduled to be held in Milan and Cortina dAmpezzo, Italy, from 6 to 22 February 2026.',
     'kind': 'paragraph', 'source_domain': 'olympics.com',
     'source_url': 'https://www.olympics.com/milano-cortina-2026',
     'source_title': 'Milano Cortina 2026'},
    {'slug': 'oppenheimer', 'query': 'Who directed Oppenheimer?',
     'answer': 'Oppenheimer (2023) was directed by Christopher Nolan and starred Cillian Murphy in the title role.',
     'kind': 'paragraph', 'source_domain': 'imdb.com',
     'source_url': 'https://www.imdb.com/title/tt15398776/',
     'source_title': 'Oppenheimer (2023) - IMDb'},
    {'slug': 'barbie', 'query': 'Who directed Barbie movie?',
     'answer': 'Barbie (2023) was directed by Greta Gerwig and starred Margot Robbie and Ryan Gosling.',
     'kind': 'paragraph', 'source_domain': 'imdb.com',
     'source_url': 'https://www.imdb.com/title/tt1517268/',
     'source_title': 'Barbie (2023) - IMDb'},
    {'slug': 'dune_part_two', 'query': 'When was Dune Part Two released?',
     'answer': 'Dune: Part Two was released in cinemas on 1 March 2024 and was directed by Denis Villeneuve.',
     'kind': 'paragraph', 'source_domain': 'imdb.com',
     'source_url': 'https://www.imdb.com/title/tt15239678/',
     'source_title': 'Dune: Part Two (2024) - IMDb'},
]

PAA_BUNDLES = [
    {'slug': 'photosynthesis', 'question': 'How does photosynthesis work?',
     'qa': [
         ('What are the inputs of photosynthesis?', 'Carbon dioxide, water and light energy.'),
         ('What are the outputs of photosynthesis?', 'Glucose and oxygen.'),
         ('Where does photosynthesis happen in a plant cell?', 'In the chloroplasts, specifically inside the thylakoid membranes.'),
         ('What is the Z-scheme in photosynthesis?', 'It is the diagram describing electron flow through Photosystem II and Photosystem I.')]},
    {'slug': 'large_language_model', 'question': 'How does a large language model work?',
     'qa': [
         ('What is a token?', 'A token is a sub-word unit produced by a tokenizer.'),
         ('What is RLHF?', 'Reinforcement Learning from Human Feedback fine-tunes a model with human preference data.'),
         ('What is a transformer?', 'A neural architecture based on self-attention.')]},
    {'slug': 'black_hole', 'question': 'What happens inside a black hole?',
     'qa': [
         ('What is the event horizon?', 'The boundary beyond which nothing can escape, not even light.'),
         ('What is Hawking radiation?', 'Theoretical thermal radiation predicted to be emitted from black-hole horizons.'),
         ('How are black holes detected?', 'Via X-ray emissions from accretion disks, gravitational lensing or gravitational-wave signatures.')]},
    {'slug': 'mediterranean_diet', 'question': 'Is the Mediterranean diet healthy?',
     'qa': [
         ('What does PREDIMED say?', 'PREDIMED showed reduced major cardiovascular events with EVOO or nut supplementation.'),
         ('Is red wine recommended?', 'Moderate red wine with meals is part of the traditional pattern.'),
         ('Does the diet help with weight loss?', 'It can support modest weight loss when combined with calorie awareness.')]},
    {'slug': 'climate_change_causes', 'question': 'What is the biggest cause of climate change?',
     'qa': [
         ('How much warming is from CO2?', 'Roughly two-thirds of observed warming since 1850 is attributable to CO2.'),
         ('What about methane?', 'Methane is the second-largest contributor and has a higher short-term warming potential.'),
         ('Does deforestation matter?', 'Yes, both as a CO2 source and a sink reduction.'),
         ('What does the IPCC AR6 conclude?', 'Human influence has unequivocally warmed the climate.')]},
    {'slug': 'quantum_entanglement', 'question': 'Why is quantum entanglement spooky?',
     'qa': [
         ('Does it allow faster-than-light signalling?', 'No, no usable information is transmitted.'),
         ('What is Bells theorem?', 'It shows no local hidden-variable theory can reproduce all quantum predictions.'),
         ('How is entanglement used in computing?', 'It is a core resource in quantum algorithms and quantum teleportation.')]},
    {'slug': 'lebron_james', 'question': 'How tall is LeBron James?',
     'qa': [
         ('How many NBA titles does LeBron have?', 'Four NBA championships (2012, 2013, 2016, 2020).'),
         ('When did LeBron join the Lakers?', 'July 2018.'),
         ('Who is LeBrons agent?', 'Rich Paul of Klutch Sports Group.')]},
    {'slug': 'oppenheimer', 'question': 'How long is Oppenheimer the movie?',
     'qa': [
         ('How many Oscars did Oppenheimer win?', 'Seven Academy Awards including Best Picture and Best Director.'),
         ('Is Oppenheimer based on a book?', 'Yes, on American Prometheus by Kai Bird and Martin J. Sherwin.'),
         ('What is Oppenheimer rated?', 'R for some sexuality, nudity and language.')]},
    {'slug': 'dune_part_two', 'question': 'Will there be a Dune part three?',
     'qa': [
         ('Who plays Paul Atreides?', 'Timothee Chalamet.'),
         ('Is Dune Part Two on streaming?', 'It is available on Max in many regions.'),
         ('What is Arrakis?', 'A desert planet and the only source of the spice melange.')]},
    {'slug': 'tesla_model_s', 'question': 'What is the range of a Tesla Model S?',
     'qa': [
         ('What is the 0-60 time of a Model S Plaid?', '1.99 seconds with rollout (Tesla figures).'),
         ('How much does a Model S cost?', 'Starting around 79,990 USD for the Long Range trim.'),
         ('Does Model S have Autopilot?', 'Yes, with optional Full Self-Driving capability.')]},
]

KNOWLEDGE_PANELS = [
    {'slug': 'lebron_james', 'name': 'LeBron James', 'kind': 'Basketball player',
     'facts': [
         ('Born', '30 December 1984 (age 41)'),
         ('Height', '6 ft 9 in (2.06 m)'),
         ('Weight', '250 lb (113 kg)'),
         ('Team', 'Los Angeles Lakers (#23)'),
         ('Position', 'Small forward'),
         ('Career points', 'over 40,000'),
         ('Spouse', 'Savannah Brinson (m. 2013)')]},
    {'slug': 'stephen_curry', 'name': 'Stephen Curry', 'kind': 'Basketball player',
     'facts': [
         ('Born', '14 March 1988 (age 38)'),
         ('Height', '6 ft 2 in (1.88 m)'),
         ('Team', 'Golden State Warriors (#30)'),
         ('Position', 'Point guard'),
         ('NBA titles', '4 (2015, 2017, 2018, 2022)'),
         ('Spouse', 'Ayesha Curry (m. 2011)')]},
    {'slug': 'oppenheimer_movie', 'name': 'Oppenheimer', 'kind': '2023 film',
     'facts': [
         ('Director', 'Christopher Nolan'),
         ('Release date', '21 July 2023'),
         ('Runtime', '180 minutes'),
         ('Box office', '975.8 million USD'),
         ('Studio', 'Universal Pictures'),
         ('Rating', 'R')]},
    {'slug': 'barbie_movie', 'name': 'Barbie', 'kind': '2023 film',
     'facts': [
         ('Director', 'Greta Gerwig'),
         ('Release date', '21 July 2023'),
         ('Runtime', '114 minutes'),
         ('Box office', '1.446 billion USD'),
         ('Studio', 'Warner Bros. Pictures'),
         ('Rating', 'PG-13')]},
    {'slug': 'apple_m4', 'name': 'Apple M4', 'kind': 'System on a chip',
     'facts': [
         ('Manufacturer', 'Apple Inc.'),
         ('Launched', '7 May 2024'),
         ('Process', 'TSMC N3E (3 nm)'),
         ('CPU cores', 'up to 10'),
         ('GPU cores', 'up to 10'),
         ('Memory', 'up to 32 GB unified')]},
    {'slug': 'tesla_model_s', 'name': 'Tesla Model S', 'kind': 'Electric car',
     'facts': [
         ('Manufacturer', 'Tesla, Inc.'),
         ('Production', 'since 2012'),
         ('Range (EPA)', 'up to 402 mi (Long Range)'),
         ('0-60 mph', '1.99 s (Plaid)'),
         ('Body style', 'liftback sedan'),
         ('Starting price', '79,990 USD')]},
    {'slug': 'mount_everest', 'name': 'Mount Everest', 'kind': 'Mountain',
     'facts': [
         ('Elevation', '8,848.86 m (29,031.7 ft)'),
         ('Location', 'Mahalangur Himal, Nepal / China border'),
         ('First ascent', '29 May 1953'),
         ('First climbers', 'Edmund Hillary and Tenzing Norgay'),
         ('Parent peak', 'none (highest above sea level)')]},
    {'slug': 'grand_canyon', 'name': 'Grand Canyon', 'kind': 'Canyon',
     'facts': [
         ('Location', 'Arizona, United States'),
         ('Length', '446 km (277 mi)'),
         ('Width', 'up to 29 km (18 mi)'),
         ('Depth', 'over 1,800 m (6,000 ft)'),
         ('Status', 'UNESCO World Heritage Site (1979)'),
         ('Visitors', 'about 4.9 million per year')]},
]
