"""R6 popular-topic expansion — programmatic catalog across 12 categories.

Format mirrors POP_TOPICS / POP_TOPICS_R3:
  (slug, name, query_text, summary, answer_token, [(kfact_key, kfact_value), ...])

Slugs are unique vs prior rounds (manually de-conflicted). All strings are
literal — no datetime / hash randomness — so this module yields the same
list every interpreter start.
"""

def _build():
    # Each category dict maps slug -> (name, qtext, summary, answer_token, kfacts)
    out = []

    # ---------- 1) Chess openings & terminology (40) -----------------------
    chess = [
        ('sicilian_defense', 'Sicilian Defense', 'sicilian defense chess', '1.e4 c5', 'aggressive asymmetric reply to 1.e4', 'A', '1.e4 c5'),
        ('ruy_lopez', 'Ruy Lopez', 'ruy lopez chess opening', 'Spanish Game, 1.e4 e5 2.Nf3 Nc6 3.Bb5', 'classical open game', 'C68', '1.e4 e5 2.Nf3 Nc6 3.Bb5'),
        ('queens_gambit', "Queen's Gambit", 'queens gambit chess', "1.d4 d5 2.c4", 'central pawn-trade gambit', 'D06', '1.d4 d5 2.c4'),
        ('kings_indian', "King's Indian Defence", 'king\'s indian defence chess', 'Hypermodern defence after 1.d4 Nf6 2.c4 g6 3.Nc3 Bg7', 'hypermodern Black defence', 'E60-E99', '1.d4 Nf6 2.c4 g6'),
        ('french_defense', 'French Defence', 'french defence chess', 'Solid reply 1.e4 e6', 'closed reply to 1.e4', 'C00-C19', '1.e4 e6'),
        ('caro_kann', 'Caro–Kann Defence', 'caro-kann defence chess', '1.e4 c6 prepares 2...d5', 'rock-solid Black system', 'B10-B19', '1.e4 c6'),
        ('italian_game', 'Italian Game', 'italian game chess', '1.e4 e5 2.Nf3 Nc6 3.Bc4', 'oldest recorded open game', 'C50-C54', '1.e4 e5 2.Nf3 Nc6 3.Bc4'),
        ('scotch_game', 'Scotch Game', 'scotch game chess', '1.e4 e5 2.Nf3 Nc6 3.d4', 'mid-19th-century open game', 'C44-C45', '1.e4 e5 2.Nf3 Nc6 3.d4'),
        ('english_opening', 'English Opening', 'english opening chess', '1.c4 flank opening', 'flank opening', 'A10-A39', '1.c4'),
        ('reti_opening', 'Réti Opening', 'reti opening chess', '1.Nf3 with delayed central commitment', 'hypermodern flank opening', 'A04-A09', '1.Nf3'),
        ('grunfeld_defense', 'Grünfeld Defence', 'grunfeld defence chess', '1.d4 Nf6 2.c4 g6 3.Nc3 d5', 'hypermodern counter-attacking system', 'D70-D99', '1.d4 Nf6 2.c4 g6 3.Nc3 d5'),
        ('nimzo_indian', 'Nimzo-Indian Defence', 'nimzo-indian defence chess', '1.d4 Nf6 2.c4 e6 3.Nc3 Bb4 — pins the c3 knight', 'classical positional Black defence', 'E20-E59', '1.d4 Nf6 2.c4 e6 3.Nc3 Bb4'),
        ('benoni_defense', 'Benoni Defence', 'benoni defence chess', '1.d4 Nf6 2.c4 c5', 'sharp, asymmetric Black defence', 'A60-A79', '1.d4 Nf6 2.c4 c5'),
        ('dutch_defense', 'Dutch Defence', 'dutch defence chess', '1.d4 f5', 'sharp Black defence vs 1.d4', 'A80-A99', '1.d4 f5'),
        ('alekhine_defense', "Alekhine's Defence", 'alekhine defence chess', '1.e4 Nf6 — invites White to over-extend the centre', 'hypermodern reply to 1.e4', 'B02-B05', '1.e4 Nf6'),
        ('pirc_defense', 'Pirc Defence', 'pirc defence chess', '1.e4 d6 2.d4 Nf6 3.Nc3 g6 — hypermodern setup', 'flexible Black system', 'B07-B09', '1.e4 d6 2.d4 Nf6'),
        ('modern_defense', 'Modern Defence', 'modern defence chess', '1.e4 g6 — fianchetto setup', 'hypermodern Black setup', 'B06', '1.e4 g6'),
        ('vienna_game', 'Vienna Game', 'vienna game chess', '1.e4 e5 2.Nc3', '19th-century open game', 'C25-C29', '1.e4 e5 2.Nc3'),
        ('center_game', 'Center Game', 'center game chess', '1.e4 e5 2.d4 exd4 3.Qxd4', 'old-school open game', 'C22', '1.e4 e5 2.d4'),
        ('london_system', 'London System', 'london system chess', '1.d4 Nf6 2.Nf3 followed by Bf4', 'club-popular d4 system', 'D02', '1.d4 with Bf4'),
        ('catalan_opening', 'Catalan Opening', 'catalan opening chess', '1.d4 Nf6 2.c4 e6 3.g3 — fianchetto + queen pawn', 'positional fianchetto system', 'E00-E09', '1.d4 Nf6 2.c4 e6 3.g3'),
        ('slav_defense', 'Slav Defence', 'slav defence chess', '1.d4 d5 2.c4 c6', 'classical solid Black defence', 'D10-D19', '1.d4 d5 2.c4 c6'),
        ('semi_slav', 'Semi-Slav Defence', 'semi-slav defence chess', '1.d4 d5 2.c4 c6 3.Nf3 Nf6 4.Nc3 e6', 'sharp hybrid of Slav and QGD', 'D43-D49', '1.d4 d5 2.c4 c6 3.Nf3 Nf6 4.Nc3 e6'),
        ('berlin_defense', 'Berlin Defence', 'berlin defence chess ruy lopez', '3...Nf6 in the Ruy Lopez — endgame-oriented', 'modern world-championship workhorse', 'C65-C67', '3...Nf6 in Ruy Lopez'),
        ('petroff_defense', 'Petroff Defence', 'petroff defence chess', '1.e4 e5 2.Nf3 Nf6 — symmetrical reply', 'symmetrical Black reply to 1.e4', 'C42-C43', '1.e4 e5 2.Nf3 Nf6'),
        ('najdorf_variation', 'Najdorf Variation', 'najdorf sicilian chess', 'Most-studied Sicilian line: 5...a6', 'sharp Sicilian main line', 'B90-B99', '5...a6 in Sicilian'),
        ('dragon_variation', 'Dragon Variation', 'dragon variation sicilian', 'Sicilian Dragon — fianchetto setup with ...g6/...Bg7', 'sharpest Sicilian with kingside fianchetto', 'B70-B79', '...g6 fianchetto in Sicilian'),
        ('marshall_attack', 'Marshall Attack', 'marshall attack ruy lopez', 'Aggressive 8...d5 gambit in the Ruy Lopez Closed', 'main-line gambit in Ruy Lopez', 'C89', '8...d5 in Closed Ruy Lopez'),
        ('kings_gambit', "King's Gambit", 'kings gambit chess', '1.e4 e5 2.f4 — Romantic gambit', '19th-century romantic gambit', 'C30-C39', '1.e4 e5 2.f4'),
        ('evans_gambit', 'Evans Gambit', 'evans gambit chess', '1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.b4 — 19th c. gambit', 'classical sacrificial line of the Italian', 'C51-C52', '4.b4 in Italian Game'),
        ('en_passant_rule', 'En passant', 'en passant chess rule', "Pawn capture rule: when a pawn advances two squares, an adjacent enemy pawn may capture it 'in passing' on the next move only.", 'special pawn-capture rule', 'rule', 'two-square pawn advance can be captured on the next move only'),
        ('castling_rule', 'Castling', 'castling chess rule', 'King-and-rook combined move; kingside (O-O) or queenside (O-O-O); both pieces unmoved, no check / through-check, squares clear.', 'king + rook combined move', 'rule', 'O-O kingside, O-O-O queenside; both pieces unmoved'),
        ('fifty_move_rule', 'Fifty-move rule', 'fifty move rule chess', '50 consecutive moves without a pawn move or capture — either side may claim a draw.', 'draw rule', 'rule', '50 moves with no pawn move / capture'),
        ('threefold_repetition', 'Threefold repetition', 'threefold repetition chess', 'Position repeated three times with the same player to move; either side may claim a draw.', 'draw rule', 'rule', 'position repeated 3× with same side to move'),
        ('elo_rating_system', 'Elo rating system', 'elo rating system chess', 'Statistical method by Arpad Elo for relative skill in zero-sum games; widely used by FIDE.', 'rating system by Arpad Elo', 'Arpad Elo (1903–1992)', 'FIDE adopted 1970'),
        ('zugzwang', 'Zugzwang', 'zugzwang chess', 'A position where any move worsens the side to move — common in king-and-pawn endgames.', 'compulsion-to-move concept', 'concept', 'any move worsens the position'),
        ('zwischenzug', 'Zwischenzug', 'zwischenzug chess', "An 'in-between move' — interpolating an unexpected threat before an expected recapture.", 'in-between tactical move', 'tactic', 'interpolated move before expected reply'),
        ('fischer_random', 'Fischer Random Chess', 'chess960 fischer random', 'Variant invented by Bobby Fischer with starting back-rank pieces shuffled across 960 positions.', 'variant invented by Bobby Fischer', 'Bobby Fischer (1996)', '960 starting positions'),
        ('opera_game', 'The Opera Game', 'opera game morphy chess', 'Famous 1858 miniature: Paul Morphy vs. Duke of Brunswick and Count Isouard at the Italian Opera in Paris.', 'famous Paul Morphy miniature (1858)', 'Paul Morphy (1858)', 'Italian Opera House, Paris'),
        ('immortal_game', 'The Immortal Game', 'immortal game anderssen chess', 'London 1851 friendly between Adolf Anderssen and Lionel Kieseritzky — celebrated for piece-sacrifice play.', 'Anderssen vs. Kieseritzky, London 1851', 'Adolf Anderssen vs Lionel Kieseritzky', 'London 1851'),
    ]
    for slug, name, q, summary, ans, k1, v1 in chess:
        out.append((slug, name, q, summary, ans, [
            ('Game', 'Chess'), ('ECO / category', k1 if k1 not in ('rule','concept','tactic') else k1),
            ('Key move / fact', v1), ('Era', 'classical / modern')]))

    # ---------- 2) Yoga poses (30) ------------------------------------------
    yoga = [
        ('downward_dog_pose', 'Downward-Facing Dog', 'downward facing dog yoga pose', 'Adho Mukha Svanasana — inverted V shape; staple of vinyasa sequences.', 'Sanskrit: Adho Mukha Svanasana', 'standing forward inversion', 'Adho Mukha Svanasana'),
        ('upward_dog_pose', 'Upward-Facing Dog', 'upward facing dog yoga pose', 'Urdhva Mukha Svanasana — chest opener with thighs off the floor.', 'Sanskrit: Urdhva Mukha Svanasana', 'back-bend prone', 'Urdhva Mukha Svanasana'),
        ('warrior_one_pose', 'Warrior I', 'warrior i yoga pose', 'Virabhadrasana I — lunging standing pose with arms overhead.', 'Sanskrit: Virabhadrasana I', 'standing lunge', 'Virabhadrasana I'),
        ('warrior_two_pose', 'Warrior II', 'warrior ii yoga pose', 'Virabhadrasana II — lateral lunge with arms outstretched.', 'Sanskrit: Virabhadrasana II', 'standing lunge', 'Virabhadrasana II'),
        ('warrior_three_pose', 'Warrior III', 'warrior iii yoga pose', 'Virabhadrasana III — single-leg balance with torso parallel to floor.', 'Sanskrit: Virabhadrasana III', 'single-leg balance', 'Virabhadrasana III'),
        ('tree_pose', 'Tree Pose', 'tree pose yoga', 'Vrikshasana — single-leg standing balance.', 'Sanskrit: Vrikshasana', 'standing balance', 'Vrikshasana'),
        ('triangle_pose', 'Triangle Pose', 'triangle pose yoga', 'Trikonasana — lateral standing stretch.', 'Sanskrit: Trikonasana', 'standing stretch', 'Trikonasana'),
        ('cobra_pose', 'Cobra Pose', 'cobra pose yoga', 'Bhujangasana — prone back-bend with elbows bent.', 'Sanskrit: Bhujangasana', 'back-bend prone', 'Bhujangasana'),
        ('childs_pose', "Child's Pose", 'childs pose yoga', 'Balasana — kneeling forward fold for rest between poses.', 'Sanskrit: Balasana', 'restorative kneeling', 'Balasana'),
        ('corpse_pose', 'Corpse Pose', 'corpse pose savasana yoga', 'Savasana — final relaxation lying flat on back.', 'Sanskrit: Savasana', 'final relaxation', 'Savasana'),
        ('mountain_pose', 'Mountain Pose', 'mountain pose yoga', 'Tadasana — foundation standing pose.', 'Sanskrit: Tadasana', 'standing foundation', 'Tadasana'),
        ('chair_pose', 'Chair Pose', 'chair pose yoga', 'Utkatasana — squat with arms overhead.', 'Sanskrit: Utkatasana', 'standing squat', 'Utkatasana'),
        ('boat_pose', 'Boat Pose', 'boat pose yoga', 'Navasana — V-balance on the sit bones.', 'Sanskrit: Navasana', 'seated balance', 'Navasana'),
        ('plank_pose', 'Plank Pose', 'plank pose yoga', 'Phalakasana — straight-arm full-body plank.', 'Sanskrit: Phalakasana', 'core strengthening', 'Phalakasana'),
        ('crow_pose', 'Crow Pose', 'crow pose yoga', 'Bakasana — arm balance with knees on triceps.', 'Sanskrit: Bakasana', 'arm balance', 'Bakasana'),
        ('headstand_pose', 'Headstand', 'headstand yoga', 'Sirsasana — inversion balanced on forearms and crown.', 'Sanskrit: Sirsasana', 'inversion', 'Sirsasana'),
        ('shoulder_stand', 'Shoulderstand', 'shoulderstand yoga', 'Salamba Sarvangasana — inversion on shoulders supporting lower back.', 'Sanskrit: Salamba Sarvangasana', 'inversion', 'Salamba Sarvangasana'),
        ('plow_pose', 'Plow Pose', 'plow pose yoga', 'Halasana — shoulderstand with feet behind head.', 'Sanskrit: Halasana', 'inversion', 'Halasana'),
        ('camel_pose', 'Camel Pose', 'camel pose yoga', 'Ustrasana — kneeling back-bend.', 'Sanskrit: Ustrasana', 'kneeling back-bend', 'Ustrasana'),
        ('bridge_pose', 'Bridge Pose', 'bridge pose yoga', 'Setu Bandha Sarvangasana — supine back-bend.', 'Sanskrit: Setu Bandha Sarvangasana', 'supine back-bend', 'Setu Bandha Sarvangasana'),
        ('wheel_pose', 'Wheel Pose', 'wheel pose yoga', 'Urdhva Dhanurasana — full back-bend on hands and feet.', 'Sanskrit: Urdhva Dhanurasana', 'full back-bend', 'Urdhva Dhanurasana'),
        ('pigeon_pose', 'Pigeon Pose', 'pigeon pose yoga', 'Eka Pada Rajakapotasana — deep hip opener.', 'Sanskrit: Eka Pada Rajakapotasana', 'hip opener', 'Eka Pada Rajakapotasana'),
        ('half_moon_pose', 'Half-Moon Pose', 'half moon pose yoga', 'Ardha Chandrasana — single-leg lateral balance.', 'Sanskrit: Ardha Chandrasana', 'standing balance', 'Ardha Chandrasana'),
        ('eagle_pose', 'Eagle Pose', 'eagle pose yoga', 'Garudasana — wrapped-limb standing balance.', 'Sanskrit: Garudasana', 'standing balance', 'Garudasana'),
        ('dancer_pose', 'Dancer Pose', 'dancer pose yoga', 'Natarajasana — single-leg back-bend balance.', 'Sanskrit: Natarajasana', 'standing balance back-bend', 'Natarajasana'),
        ('cat_cow_pose', 'Cat-Cow', 'cat cow pose yoga', 'Marjaryasana-Bitilasana — paired spinal flexion-extension warm-up.', 'Sanskrit: Marjaryasana / Bitilasana', 'spinal warm-up', 'Marjaryasana-Bitilasana'),
        ('lotus_pose', 'Lotus Pose', 'lotus pose yoga', 'Padmasana — cross-legged meditation seat.', 'Sanskrit: Padmasana', 'seated meditation', 'Padmasana'),
        ('half_lotus_pose', 'Half-Lotus Pose', 'half lotus pose yoga', 'Ardha Padmasana — accessible lotus variant.', 'Sanskrit: Ardha Padmasana', 'seated meditation', 'Ardha Padmasana'),
        ('seated_forward_fold', 'Seated Forward Fold', 'seated forward fold yoga', 'Paschimottanasana — hamstring stretch from seated position.', 'Sanskrit: Paschimottanasana', 'seated forward fold', 'Paschimottanasana'),
        ('reclining_bound_angle', 'Reclining Bound Angle Pose', 'reclining bound angle yoga', 'Supta Baddha Konasana — restorative supine hip opener.', 'Sanskrit: Supta Baddha Konasana', 'restorative hip opener', 'Supta Baddha Konasana'),
    ]
    for slug, name, q, summary, ans, k1, v1 in yoga:
        out.append((slug, name, q, summary, ans, [
            ('Tradition', 'Hatha yoga'), ('Pose type', k1),
            ('Sanskrit', v1), ('Difficulty', 'beginner / intermediate / advanced')]))

    # ---------- 3) Cuisines & national dishes (40) --------------------------
    cuisine = [
        ('italian_cuisine', 'Italian cuisine', 'italian cuisine', 'Italy', 'pasta, pizza, risotto, tiramisu'),
        ('french_cuisine', 'French cuisine', 'french cuisine', 'France', 'baguette, ratatouille, boeuf bourguignon'),
        ('japanese_cuisine', 'Japanese cuisine', 'japanese cuisine', 'Japan', 'sushi, ramen, tempura, sashimi'),
        ('chinese_cuisine', 'Chinese cuisine', 'chinese cuisine', 'China', '8 regional cuisines incl. Cantonese, Sichuan'),
        ('mexican_cuisine', 'Mexican cuisine', 'mexican cuisine', 'Mexico', 'tacos, mole, tamales, chiles en nogada'),
        ('indian_cuisine', 'Indian cuisine', 'indian cuisine', 'India', 'curry, biryani, dosa, tandoori dishes'),
        ('thai_cuisine', 'Thai cuisine', 'thai cuisine', 'Thailand', 'pad thai, tom yum, green curry'),
        ('greek_cuisine', 'Greek cuisine', 'greek cuisine', 'Greece', 'moussaka, gyros, souvlaki, baklava'),
        ('spanish_cuisine', 'Spanish cuisine', 'spanish cuisine', 'Spain', 'paella, tapas, gazpacho, jamón ibérico'),
        ('korean_cuisine', 'Korean cuisine', 'korean cuisine', 'Korea', 'kimchi, bibimbap, Korean BBQ, bulgogi'),
        ('vietnamese_cuisine', 'Vietnamese cuisine', 'vietnamese cuisine', 'Vietnam', 'phở, bánh mì, gỏi cuốn'),
        ('moroccan_cuisine', 'Moroccan cuisine', 'moroccan cuisine', 'Morocco', 'tagine, couscous, harira, pastilla'),
        ('lebanese_cuisine', 'Lebanese cuisine', 'lebanese cuisine', 'Lebanon', 'hummus, tabbouleh, kibbeh, manakish'),
        ('turkish_cuisine', 'Turkish cuisine', 'turkish cuisine', 'Türkiye', 'kebab, dolma, meze, börek, baklava'),
        ('ethiopian_cuisine', 'Ethiopian cuisine', 'ethiopian cuisine', 'Ethiopia', 'injera, doro wat, kitfo'),
        ('peruvian_cuisine', 'Peruvian cuisine', 'peruvian cuisine', 'Peru', 'ceviche, lomo saltado, ají de gallina'),
        ('brazilian_cuisine', 'Brazilian cuisine', 'brazilian cuisine', 'Brazil', 'feijoada, brigadeiro, churrasco'),
        ('argentine_cuisine', 'Argentine cuisine', 'argentine cuisine', 'Argentina', 'asado, empanadas, chimichurri'),
        ('german_cuisine', 'German cuisine', 'german cuisine', 'Germany', 'bratwurst, sauerbraten, schnitzel'),
        ('british_cuisine', 'British cuisine', 'british cuisine', 'United Kingdom', 'fish and chips, Sunday roast, full English breakfast'),
        ('irish_cuisine', 'Irish cuisine', 'irish cuisine', 'Ireland', 'Irish stew, soda bread, colcannon'),
        ('russian_cuisine', 'Russian cuisine', 'russian cuisine', 'Russia', 'borscht, pelmeni, blini, beef stroganoff'),
        ('polish_cuisine', 'Polish cuisine', 'polish cuisine', 'Poland', 'pierogi, bigos, kielbasa, żurek'),
        ('portuguese_cuisine', 'Portuguese cuisine', 'portuguese cuisine', 'Portugal', 'bacalhau, pastéis de nata, francesinha'),
        ('cajun_cuisine', 'Cajun cuisine', 'cajun cuisine', 'Louisiana, USA', 'gumbo, jambalaya, étouffée'),
        ('soul_food', 'Soul food', 'soul food cuisine', 'Southern United States', 'fried chicken, collard greens, cornbread'),
        ('peking_duck', 'Peking duck', 'peking duck', 'Beijing, China', 'roast duck with thin pancakes'),
        ('sushi_dish', 'Sushi', 'sushi japanese dish', 'Japan', 'vinegared rice with seafood / vegetables'),
        ('ramen_dish', 'Ramen', 'ramen japanese dish', 'Japan', 'wheat noodles in broth, four main bases'),
        ('paella_dish', 'Paella', 'paella spanish dish', 'Valencia, Spain', 'saffron rice with seafood / meat'),
        ('biryani_dish', 'Biryani', 'biryani indian dish', 'Indian subcontinent', 'layered spiced rice with meat or vegetables'),
        ('pho_dish', 'Phở', 'pho vietnamese dish', 'Vietnam', 'rice-noodle soup with herbs and beef or chicken'),
        ('pad_thai_dish', 'Pad Thai', 'pad thai dish', 'Thailand', 'stir-fried rice noodles with tamarind sauce'),
        ('tacos_dish', 'Tacos', 'tacos mexican dish', 'Mexico', 'small hand-held tortillas with filling'),
        ('croissant_dish', 'Croissant', 'croissant pastry', 'France (Austrian origin)', 'laminated butter pastry'),
        ('tiramisu_dish', 'Tiramisu', 'tiramisu italian dessert', 'Italy', 'mascarpone, espresso, ladyfinger dessert'),
        ('macaron_dish', 'Macaron', 'macaron french pastry', 'France', 'almond-meringue sandwich cookie'),
        ('dim_sum', 'Dim sum', 'dim sum chinese', 'Guangdong, China', 'small steamed or fried Cantonese snacks'),
        ('borscht_dish', 'Borscht', 'borscht soup', 'Eastern Europe', 'beetroot soup, served hot or cold'),
        ('falafel_dish', 'Falafel', 'falafel dish', 'Levant / Egypt', 'fried chickpea or fava-bean balls'),
    ]
    for slug, name, q, origin, signature in cuisine:
        out.append((slug, name, q,
                    f'{name} is associated with {origin}. Signature items include {signature}.',
                    f'{origin} — {signature}',
                    [('Origin', origin), ('Signature dishes', signature),
                     ('Category', 'cuisine / dish'), ('Type', 'food')]))

    # ---------- 4) Musical instruments (40) ---------------------------------
    instruments = [
        ('piano_instrument', 'Piano', 'piano instrument', 'keyboard, struck strings', 'invented by Bartolomeo Cristofori c. 1700', '88 keys (standard)'),
        ('violin_instrument', 'Violin', 'violin instrument', 'bowed string, four strings tuned in fifths', 'developed in northern Italy, 16th c.', 'G3 D4 A4 E5 tuning'),
        ('viola_instrument', 'Viola', 'viola instrument', 'bowed string, lower than violin', 'string family', 'C3 G3 D4 A4 tuning'),
        ('cello_instrument', 'Cello', 'cello instrument', 'bowed string, played seated', 'string family', 'C2 G2 D3 A3 tuning'),
        ('double_bass', 'Double bass', 'double bass instrument', 'largest bowed string, lowest pitch', 'string family', 'E1 A1 D2 G2 tuning'),
        ('guitar_instrument', 'Guitar', 'guitar instrument', 'plucked string, fretted', 'string family', '6 strings standard'),
        ('electric_guitar', 'Electric guitar', 'electric guitar instrument', 'amplified solid-body guitar', 'first commercial model 1932 Rickenbacker', '6 strings, pickups'),
        ('bass_guitar', 'Bass guitar', 'bass guitar instrument', 'four-string electric bass', 'invented by Paul Tutmarc, 1935', '4 strings, EADG tuning'),
        ('harp_instrument', 'Harp', 'harp instrument', 'plucked string, vertical frame', 'string family', '47 strings (concert harp)'),
        ('flute_instrument', 'Flute', 'flute instrument', 'woodwind, open-ended air column', 'woodwind family', 'C4 to C7 range'),
        ('clarinet_instrument', 'Clarinet', 'clarinet instrument', 'single-reed cylindrical woodwind', 'invented by Johann Christoph Denner c. 1700', 'B♭ standard tuning'),
        ('oboe_instrument', 'Oboe', 'oboe instrument', 'double-reed conical woodwind', 'woodwind family', 'concert pitch A'),
        ('bassoon_instrument', 'Bassoon', 'bassoon instrument', 'double-reed bass woodwind', 'woodwind family', 'B♭1 to E5 range'),
        ('saxophone_instrument', 'Saxophone', 'saxophone instrument', 'single-reed conical brass-body woodwind', 'invented by Adolphe Sax, 1846', 'alto, tenor, soprano, baritone'),
        ('trumpet_instrument', 'Trumpet', 'trumpet instrument', 'three-valve brass instrument', 'brass family', 'B♭ standard tuning'),
        ('trombone_instrument', 'Trombone', 'trombone instrument', 'slide brass instrument', 'brass family', 'tenor B♭ standard'),
        ('french_horn', 'French horn', 'french horn instrument', 'coiled brass with rotary valves', 'brass family', 'F or B♭ instrument'),
        ('tuba_instrument', 'Tuba', 'tuba instrument', 'largest brass, lowest pitch', 'brass family', 'BB♭ contrabass standard'),
        ('drums_instrument', 'Drum kit', 'drum kit instrument', 'collection of drums + cymbals', 'percussion family', 'snare, bass, toms, hi-hat'),
        ('snare_drum', 'Snare drum', 'snare drum', 'two-headed drum with snares', 'percussion family', 'wires under bottom head'),
        ('timpani_instrument', 'Timpani', 'timpani kettle drums', 'tunable orchestral kettle drums', 'percussion family', 'orchestral set of 4'),
        ('xylophone_instrument', 'Xylophone', 'xylophone instrument', 'wooden-bar pitched percussion', 'percussion family', 'wooden bars'),
        ('marimba_instrument', 'Marimba', 'marimba instrument', 'large wooden-bar percussion with resonators', 'percussion family', '5-octave concert marimba'),
        ('vibraphone_instrument', 'Vibraphone', 'vibraphone instrument', 'metal-bar percussion with rotating discs', 'percussion family', 'invented 1921'),
        ('cymbal_instrument', 'Cymbals', 'cymbals instrument', 'clashed or suspended bronze plates', 'percussion family', 'ride, crash, hi-hat'),
        ('accordion_instrument', 'Accordion', 'accordion instrument', 'free-reed bellows-driven keyboard', 'free-reed family', 'invented Vienna 1829'),
        ('harmonica_instrument', 'Harmonica', 'harmonica instrument', 'free-reed mouth-blown instrument', 'free-reed family', 'diatonic 10-hole common'),
        ('organ_instrument', 'Pipe organ', 'pipe organ instrument', 'wind-driven multi-rank keyboard', 'keyboard family', 'multiple manuals + pedalboard'),
        ('harpsichord_instrument', 'Harpsichord', 'harpsichord instrument', 'plucked-string keyboard, baroque', 'keyboard family', 'plucked strings'),
        ('mandolin_instrument', 'Mandolin', 'mandolin instrument', 'plucked-string lute family, courses of two', 'string family', '4 courses of doubled strings'),
        ('banjo_instrument', 'Banjo', 'banjo instrument', 'plucked-string with skin head', 'string family', '4 or 5 strings'),
        ('ukulele_instrument', 'Ukulele', 'ukulele instrument', 'small four-string Hawaiian guitar', 'string family', 'GCEA standard tuning'),
        ('sitar_instrument', 'Sitar', 'sitar instrument', 'plucked Indian classical string instrument', 'string family', 'sympathetic + main strings'),
        ('tabla_instrument', 'Tabla', 'tabla instrument', 'pair of Indian classical drums', 'percussion family', 'paired hand drums'),
        ('didgeridoo_instrument', 'Didgeridoo', 'didgeridoo instrument', 'Australian Aboriginal wind instrument', 'wind family', 'circular-breathing wind'),
        ('bagpipes_instrument', 'Bagpipes', 'bagpipes instrument', 'reed instrument with air bag and drones', 'reed family', 'Highland (Scottish) standard'),
        ('cajón_instrument', 'Cajón', 'cajon instrument', 'Peruvian box percussion', 'percussion family', 'box drum, hands'),
        ('djembe_instrument', 'Djembe', 'djembe instrument', 'West African goblet drum', 'percussion family', 'goblet shape, hands'),
        ('handpan_instrument', 'Handpan', 'handpan instrument', 'modern steel hand-played idiophone, 21st c.', 'idiophone family', 'invented ~2000'),
        ('theremin_instrument', 'Theremin', 'theremin instrument', 'electronic instrument played without contact', 'electronic family', 'invented by Léon Theremin 1928'),
    ]
    for slug, name, q, summary, ans, k1 in instruments:
        out.append((slug, name, q,
                    f'{name} — {summary}.', ans,
                    [('Category', 'musical instrument'), ('Family', summary.split(",")[0]),
                     ('Origin / notes', ans), ('Specs', k1)]))

    # ---------- 5) Architectural styles (30) --------------------------------
    arch = [
        ('gothic_architecture', 'Gothic architecture', 'gothic architecture', 'Medieval Europe, 12th–16th c.', 'pointed arches, flying buttresses, ribbed vaults'),
        ('romanesque_architecture', 'Romanesque architecture', 'romanesque architecture', 'Europe, 10th–12th c.', 'rounded arches, thick walls, barrel vaults'),
        ('byzantine_architecture', 'Byzantine architecture', 'byzantine architecture', 'Eastern Roman Empire 4th–15th c.', 'domes, mosaics, central plan'),
        ('renaissance_architecture', 'Renaissance architecture', 'renaissance architecture', 'Italy 14th–17th c.', 'classical orders, symmetry, proportion'),
        ('baroque_architecture', 'Baroque architecture', 'baroque architecture', 'Europe 17th–18th c.', 'movement, drama, gilded ornament'),
        ('rococo_architecture', 'Rococo architecture', 'rococo architecture', 'France 18th c.', 'asymmetric ornament, light pastels, shellwork'),
        ('neoclassical_architecture', 'Neoclassical architecture', 'neoclassical architecture', 'Europe 18th–19th c.', 'Greek/Roman revival, columns, pediments'),
        ('art_deco_architecture', 'Art Deco', 'art deco architecture', '1920s–1930s', 'geometric ornament, stepped massing, chrome'),
        ('art_nouveau_architecture', 'Art Nouveau', 'art nouveau architecture', '1890s–1910s', 'organic curves, whiplash lines, stained glass'),
        ('bauhaus_architecture', 'Bauhaus', 'bauhaus architecture', 'Germany 1919–1933', 'function-driven, geometric, glass + steel'),
        ('international_style', 'International Style', 'international style architecture', '1920s–1960s', 'flat roofs, ribbon windows, no ornament'),
        ('brutalism_architecture', 'Brutalism', 'brutalist architecture', '1950s–1970s', 'raw concrete, massing, exposed structure'),
        ('postmodern_architecture', 'Postmodern architecture', 'postmodern architecture', '1960s–1990s', 'historicist quotation, color, irony'),
        ('deconstructivism', 'Deconstructivism', 'deconstructivism architecture', 'late 1980s onward', 'fragmented forms, non-rectilinear geometry'),
        ('modernism_architecture', 'Modernist architecture', 'modernist architecture', 'mid-20th c.', 'form follows function, glass + steel + concrete'),
        ('greek_revival', 'Greek Revival', 'greek revival architecture', 'late 18th–mid 19th c.', 'Doric columns, pediments, white-painted façades'),
        ('victorian_architecture', 'Victorian architecture', 'victorian architecture', 'British Empire 1837–1901', 'Gothic Revival, Italianate, Queen Anne'),
        ('georgian_architecture', 'Georgian architecture', 'georgian architecture', 'Britain 1714–1830', 'symmetry, sash windows, brick'),
        ('colonial_architecture', 'Colonial architecture', 'colonial architecture', '16th–19th c. Americas', 'European styles adapted to colonial settings'),
        ('craftsman_style', 'Craftsman style', 'craftsman bungalow style', 'US 1900–1930', 'low-pitched gable, exposed rafters, porch'),
        ('prairie_style', 'Prairie School', 'prairie school architecture', 'US 1893–1920', 'horizontal lines, low roofs (Frank Lloyd Wright)'),
        ('mid_century_modern', 'Mid-century modern', 'mid century modern architecture', 'US 1945–1970', 'flat planes, large glass, indoor-outdoor flow'),
        ('googie_architecture', 'Googie architecture', 'googie architecture', 'US 1940s–1960s', 'Space Age motifs, upswept roofs, neon'),
        ('mission_revival', 'Mission Revival', 'mission revival architecture', 'US late 19th c.', 'stucco walls, red tile roofs, arcades'),
        ('mudejar_architecture', 'Mudéjar architecture', 'mudejar architecture', 'Iberia 12th–16th c.', 'Islamic + Christian fusion, brick, geometric tile'),
        ('moorish_architecture', 'Moorish architecture', 'moorish architecture', 'al-Andalus 8th–15th c.', 'horseshoe arches, muqarnas, courtyards'),
        ('shinto_architecture', 'Shinto shrine architecture', 'shinto shrine architecture', 'Japan, ancient onward', 'thatched roofs, torii gates, raised plinth'),
        ('mughal_architecture', 'Mughal architecture', 'mughal architecture', 'South Asia 16th–18th c.', 'red sandstone + white marble, bulbous domes'),
        ('khmer_architecture', 'Khmer architecture', 'khmer architecture angkor', 'Cambodia 9th–15th c.', 'stepped pyramids, galleries (Angkor Wat)'),
        ('mesoamerican_architecture', 'Mesoamerican pyramids', 'mesoamerican pyramid architecture', 'Mesoamerica c. 1000 BC–1500 AD', 'stepped pyramids, ceremonial platforms'),
    ]
    for slug, name, q, era, features in arch:
        out.append((slug, name, q,
                    f'{name} is an architectural style associated with {era}. Characteristic features include {features}.',
                    f'{era} — {features}',
                    [('Era / region', era), ('Key features', features),
                     ('Category', 'architectural style'), ('Type', 'architecture')]))

    # ---------- 6) Mythological figures (35) --------------------------------
    myth = [
        ('zeus_greek_myth', 'Zeus', 'zeus greek mythology', 'Greek', 'king of the gods, ruler of the sky'),
        ('hera_greek_myth', 'Hera', 'hera greek mythology', 'Greek', 'queen of the gods, marriage'),
        ('poseidon_greek_myth', 'Poseidon', 'poseidon greek mythology', 'Greek', 'god of the sea, earthquakes, horses'),
        ('hades_greek_myth', 'Hades', 'hades greek mythology', 'Greek', 'god of the underworld'),
        ('athena_greek_myth', 'Athena', 'athena greek mythology', 'Greek', 'goddess of wisdom and strategic warfare'),
        ('apollo_greek_myth', 'Apollo', 'apollo greek mythology', 'Greek', 'god of music, prophecy, sun'),
        ('artemis_greek_myth', 'Artemis', 'artemis greek mythology', 'Greek', 'goddess of the hunt and the moon'),
        ('ares_greek_myth', 'Ares', 'ares greek mythology', 'Greek', 'god of war'),
        ('aphrodite_greek_myth', 'Aphrodite', 'aphrodite greek mythology', 'Greek', 'goddess of love and beauty'),
        ('hermes_greek_myth', 'Hermes', 'hermes greek mythology', 'Greek', 'messenger god, travel, commerce'),
        ('dionysus_greek_myth', 'Dionysus', 'dionysus greek mythology', 'Greek', 'god of wine and ecstatic ritual'),
        ('hephaestus_greek_myth', 'Hephaestus', 'hephaestus greek mythology', 'Greek', 'smith god of fire and forge'),
        ('hercules_myth', 'Heracles (Hercules)', 'heracles hercules mythology', 'Greek / Roman', 'divine hero of the twelve labours'),
        ('odin_norse_myth', 'Odin', 'odin norse mythology', 'Norse', 'Allfather, war, wisdom, poetry'),
        ('thor_norse_myth', 'Thor', 'thor norse mythology', 'Norse', 'god of thunder, wielder of Mjölnir'),
        ('loki_norse_myth', 'Loki', 'loki norse mythology', 'Norse', 'trickster god'),
        ('freyja_norse_myth', 'Freyja', 'freyja norse mythology', 'Norse', 'goddess of love, fertility, war'),
        ('freyr_norse_myth', 'Freyr', 'freyr norse mythology', 'Norse', 'god of fertility, peace, sunshine'),
        ('balder_norse_myth', 'Baldr', 'baldr norse mythology', 'Norse', 'shining god, son of Odin and Frigg'),
        ('jupiter_roman_myth', 'Jupiter', 'jupiter roman mythology', 'Roman', 'king of the gods, sky and thunder'),
        ('venus_roman_myth', 'Venus', 'venus roman mythology', 'Roman', 'goddess of love and beauty'),
        ('mars_roman_myth', 'Mars', 'mars roman mythology', 'Roman', 'god of war'),
        ('mercury_roman_myth', 'Mercury', 'mercury roman mythology', 'Roman', 'messenger god, commerce'),
        ('neptune_roman_myth', 'Neptune', 'neptune roman mythology', 'Roman', 'god of the sea'),
        ('isis_egyptian_myth', 'Isis', 'isis egyptian mythology', 'Egyptian', 'goddess of magic and motherhood'),
        ('osiris_egyptian_myth', 'Osiris', 'osiris egyptian mythology', 'Egyptian', 'god of the afterlife and resurrection'),
        ('horus_egyptian_myth', 'Horus', 'horus egyptian mythology', 'Egyptian', 'sky god, falcon-headed'),
        ('anubis_egyptian_myth', 'Anubis', 'anubis egyptian mythology', 'Egyptian', 'god of embalming and the dead'),
        ('ra_egyptian_myth', 'Ra', 'ra egyptian mythology', 'Egyptian', 'sun god, king of the gods'),
        ('amaterasu_japanese_myth', 'Amaterasu', 'amaterasu japanese mythology', 'Japanese / Shinto', 'sun goddess, ancestress of imperial family'),
        ('susanoo_japanese_myth', 'Susanoo', 'susanoo japanese mythology', 'Japanese / Shinto', 'storm god, brother of Amaterasu'),
        ('quetzalcoatl_myth', 'Quetzalcoatl', 'quetzalcoatl aztec mythology', 'Aztec / Mesoamerican', 'feathered-serpent deity'),
        ('huitzilopochtli_myth', 'Huitzilopochtli', 'huitzilopochtli aztec mythology', 'Aztec', 'sun god, patron of Tenochtitlán'),
        ('viracocha_myth', 'Viracocha', 'viracocha inca mythology', 'Inca', 'creator god of the Andean peoples'),
        ('inti_myth', 'Inti', 'inti inca mythology', 'Inca', 'sun god, ancestor of the Inca emperors'),
    ]
    for slug, name, q, tradition, role in myth:
        out.append((slug, name, q,
                    f'{name} is a deity / figure of {tradition} mythology, traditionally associated with {role}.',
                    f'{tradition} mythology — {role}',
                    [('Tradition', tradition), ('Role / domain', role),
                     ('Category', 'mythology'), ('Type', 'deity / mythic figure')]))

    # ---------- 7) Animal species (50) -------------------------------------
    animals = [
        ('blue_whale', 'Blue whale', 'blue whale', 'Balaenoptera musculus', 'largest animal ever known to have existed'),
        ('killer_whale', 'Orca', 'orca killer whale', 'Orcinus orca', 'apex marine predator, member of dolphin family'),
        ('humpback_whale', 'Humpback whale', 'humpback whale', 'Megaptera novaeangliae', 'known for breaching and complex songs'),
        ('sperm_whale', 'Sperm whale', 'sperm whale', 'Physeter macrocephalus', 'largest-brained animal'),
        ('great_white_shark', 'Great white shark', 'great white shark', 'Carcharodon carcharias', 'large lamniform shark, apex predator'),
        ('hammerhead_shark', 'Hammerhead shark', 'hammerhead shark', 'family Sphyrnidae', 'cephalofoil-shaped head'),
        ('manta_ray', 'Manta ray', 'manta ray', 'Mobula birostris', 'filter-feeding pelagic rays'),
        ('giant_squid', 'Giant squid', 'giant squid', 'Architeuthis dux', 'deep-sea cephalopod up to 13 m'),
        ('octopus_species_r6', 'Octopus (cephalopods)', 'octopus species cephalopod', 'order Octopoda', 'soft-bodied eight-armed cephalopods'),
        ('clownfish_animal', 'Clownfish', 'clownfish anemone fish', 'Amphiprioninae', 'mutualistic with sea anemones'),
        ('lion_species_r6', 'Lion (Panthera leo)', 'lion panthera leo species', 'Panthera leo', 'pride-living large cat, savanna apex'),
        ('tiger_species_r6', 'Tiger (Panthera tigris)', 'tiger panthera tigris species', 'Panthera tigris', 'largest extant cat'),
        ('leopard_animal', 'Leopard', 'leopard species', 'Panthera pardus', 'solitary spotted big cat'),
        ('snow_leopard', 'Snow leopard', 'snow leopard species', 'Panthera uncia', 'high-altitude Asian cat'),
        ('cheetah_species_r6', 'Cheetah (Acinonyx jubatus)', 'cheetah acinonyx jubatus species', 'Acinonyx jubatus', 'fastest land animal, up to 112 km/h'),
        ('jaguar_animal', 'Jaguar', 'jaguar species', 'Panthera onca', 'largest cat in the Americas'),
        ('puma_animal', 'Cougar', 'cougar puma species', 'Puma concolor', 'wide-ranging American cat'),
        ('lynx_animal', 'Lynx', 'lynx species', 'genus Lynx', 'tufted-eared mid-size cat'),
        ('grey_wolf', 'Gray wolf', 'gray wolf species', 'Canis lupus', 'pack-living canid, broad Holarctic range'),
        ('red_fox', 'Red fox', 'red fox species', 'Vulpes vulpes', 'most widespread carnivoran'),
        ('arctic_fox', 'Arctic fox', 'arctic fox species', 'Vulpes lagopus', 'tundra fox with seasonal coat'),
        ('coyote_animal', 'Coyote', 'coyote species', 'Canis latrans', 'North-American canid'),
        ('grizzly_bear', 'Grizzly bear', 'grizzly bear species', 'Ursus arctos horribilis', 'North-American brown-bear subspecies'),
        ('polar_bear', 'Polar bear', 'polar bear species', 'Ursus maritimus', 'sea-ice obligate carnivore'),
        ('panda_bear', 'Giant panda', 'giant panda species', 'Ailuropoda melanoleuca', 'bamboo-eating bear endemic to China'),
        ('sun_bear', 'Sun bear', 'sun bear species', 'Helarctos malayanus', 'smallest bear, Southeast Asian'),
        ('elephant_african', 'African elephant', 'african elephant species', 'Loxodonta africana', 'largest land animal'),
        ('elephant_asian', 'Asian elephant', 'asian elephant species', 'Elephas maximus', 'endangered South & SE Asian elephant'),
        ('rhino_white', 'White rhinoceros', 'white rhinoceros species', 'Ceratotherium simum', 'largest extant rhino'),
        ('rhino_black', 'Black rhinoceros', 'black rhinoceros species', 'Diceros bicornis', 'critically endangered African rhino'),
        ('hippopotamus_species_r6', 'Hippopotamus (species)', 'hippopotamus species amphibius', 'Hippopotamus amphibius', 'large semi-aquatic African mammal'),
        ('giraffe_species_r6', 'Giraffe (Giraffa camelopardalis)', 'giraffe camelopardalis species', 'Giraffa camelopardalis', 'tallest land animal'),
        ('zebra_animal', 'Plains zebra', 'plains zebra species', 'Equus quagga', 'most common zebra, broad sub-Saharan range'),
        ('horse_animal', 'Horse', 'horse domestic species', 'Equus ferus caballus', 'domesticated odd-toed ungulate'),
        ('cattle_animal', 'Cattle', 'cattle domestic species', 'Bos taurus / B. indicus', 'domesticated bovine, primary livestock'),
        ('pig_animal', 'Pig', 'pig domestic species', 'Sus scrofa domesticus', 'domesticated even-toed ungulate'),
        ('sheep_animal', 'Sheep', 'sheep domestic species', 'Ovis aries', 'domesticated ruminant, wool / meat'),
        ('goat_animal', 'Goat', 'goat domestic species', 'Capra hircus', 'domesticated mountain ruminant'),
        ('chicken_animal', 'Chicken', 'chicken domestic species', 'Gallus gallus domesticus', 'most numerous bird on Earth'),
        ('duck_animal', 'Mallard', 'mallard duck species', 'Anas platyrhynchos', 'ancestor of most domestic ducks'),
        ('eagle_bald', 'Bald eagle', 'bald eagle species', 'Haliaeetus leucocephalus', 'national bird of the United States'),
        ('eagle_golden', 'Golden eagle', 'golden eagle species', 'Aquila chrysaetos', 'wide-ranging Holarctic eagle'),
        ('owl_snowy', 'Snowy owl', 'snowy owl species', 'Bubo scandiacus', 'circumpolar Arctic owl'),
        ('penguin_emperor', 'Emperor penguin', 'emperor penguin species', 'Aptenodytes forsteri', 'largest penguin, Antarctic'),
        ('penguin_king', 'King penguin', 'king penguin species', 'Aptenodytes patagonicus', 'second-largest penguin'),
        ('parrot_macaw', 'Scarlet macaw', 'scarlet macaw species', 'Ara macao', 'large neotropical parrot'),
        ('kangaroo_red', 'Red kangaroo', 'red kangaroo species', 'Osphranter rufus', 'largest extant marsupial'),
        ('koala_species_r6', 'Koala (Phascolarctos cinereus)', 'koala phascolarctos species', 'Phascolarctos cinereus', 'eucalypt-feeding Australian marsupial'),
        ('platypus_species_r6', 'Platypus (Ornithorhynchus anatinus)', 'platypus ornithorhynchus species', 'Ornithorhynchus anatinus', 'egg-laying mammal of Australia'),
        ('komodo_dragon', 'Komodo dragon', 'komodo dragon species', 'Varanus komodoensis', 'largest living lizard'),
    ]
    for slug, name, q, latin, note in animals:
        out.append((slug, name, q,
                    f'{name} ({latin}) is a species notable for being {note}.',
                    f'{latin} — {note}',
                    [('Scientific name', latin), ('Notable for', note),
                     ('Category', 'animal species'), ('Type', 'biology')]))

    # ---------- 8) Astronomical objects (35) -------------------------------
    astro = [
        ('andromeda_galaxy', 'Andromeda Galaxy', 'andromeda galaxy', 'spiral galaxy, M31; ~2.5 million light-years away'),
        ('milky_way', 'Milky Way', 'milky way galaxy', 'barred spiral galaxy containing the Solar System'),
        ('large_magellanic_cloud', 'Large Magellanic Cloud', 'large magellanic cloud galaxy', 'satellite galaxy of the Milky Way, ~163,000 ly away'),
        ('small_magellanic_cloud', 'Small Magellanic Cloud', 'small magellanic cloud galaxy', 'satellite galaxy of the Milky Way, ~200,000 ly away'),
        ('triangulum_galaxy', 'Triangulum Galaxy', 'triangulum galaxy m33', 'M33; third-largest in the Local Group'),
        ('whirlpool_galaxy', 'Whirlpool Galaxy', 'whirlpool galaxy m51', 'M51; interacting spiral galaxy'),
        ('sombrero_galaxy', 'Sombrero Galaxy', 'sombrero galaxy m104', 'M104; bright unbarred spiral with dust lane'),
        ('crab_nebula', 'Crab Nebula', 'crab nebula m1', 'M1; supernova remnant from 1054 AD'),
        ('orion_nebula', 'Orion Nebula', 'orion nebula m42', 'M42; diffuse nebula, stellar nursery'),
        ('eagle_nebula', 'Eagle Nebula', 'eagle nebula m16', 'M16; site of the "Pillars of Creation"'),
        ('horsehead_nebula', 'Horsehead Nebula', 'horsehead nebula', 'dark nebula in Orion'),
        ('ring_nebula', 'Ring Nebula', 'ring nebula m57', 'M57; planetary nebula in Lyra'),
        ('cat_eye_nebula', "Cat's Eye Nebula", 'cats eye nebula', 'planetary nebula in Draco'),
        ('pleiades_cluster', 'Pleiades', 'pleiades star cluster', 'M45; open cluster, "Seven Sisters"'),
        ('hyades_cluster', 'Hyades', 'hyades star cluster', 'nearest open cluster to the Sun'),
        ('omega_centauri', 'Omega Centauri', 'omega centauri cluster', 'largest globular cluster orbiting the Milky Way'),
        ('sagittarius_a_star', 'Sagittarius A*', 'sagittarius a star', 'supermassive black hole at the Milky Way center'),
        ('m87_galaxy', 'Messier 87', 'messier 87 galaxy', 'elliptical galaxy hosting the first imaged black hole'),
        ('alpha_centauri', 'Alpha Centauri', 'alpha centauri star system', 'closest star system to the Sun, ~4.37 ly away'),
        ('proxima_centauri', 'Proxima Centauri', 'proxima centauri star', 'closest individual star to the Sun, ~4.24 ly'),
        ('betelgeuse_star', 'Betelgeuse', 'betelgeuse star', 'red supergiant in Orion'),
        ('rigel_star', 'Rigel', 'rigel star', 'blue supergiant in Orion'),
        ('sirius_star', 'Sirius', 'sirius star', 'brightest star in the night sky'),
        ('vega_star', 'Vega', 'vega star', 'fifth-brightest star in the night sky'),
        ('polaris_star', 'Polaris', 'polaris north star', 'current pole star of the Northern Hemisphere'),
        ('mercury_solar_planet', 'Mercury (planet, Solar System)', 'mercury planet solar system', 'smallest planet in the Solar System'),
        ('venus_solar_planet', 'Venus (planet, Solar System)', 'venus planet solar system', "second planet from the Sun, Earth's hottest neighbor"),
        ('mars_solar_planet', 'Mars (planet, Solar System)', 'mars planet solar system', 'fourth planet from the Sun, the "Red Planet"'),
        ('jupiter_solar_planet', 'Jupiter (planet, Solar System)', 'jupiter planet solar system', 'largest planet in the Solar System'),
        ('saturn_solar_planet', 'Saturn (planet, Solar System)', 'saturn planet solar system', 'sixth planet from the Sun, famous for rings'),
        ('uranus_solar_planet', 'Uranus (planet, Solar System)', 'uranus planet solar system', 'seventh planet, ice giant tilted on its side'),
        ('neptune_solar_planet', 'Neptune (planet, Solar System)', 'neptune planet solar system', 'eighth planet, ice giant with strong winds'),
        ('pluto_dwarf', 'Pluto', 'pluto dwarf planet', 'dwarf planet in the Kuiper belt'),
        ('comet_halley', "Halley's Comet", 'halleys comet', 'short-period comet, 76-year orbit, next perihelion 2061'),
        ('asteroid_belt', 'Asteroid belt', 'asteroid belt', 'region between Mars and Jupiter with most known asteroids'),
    ]
    for slug, name, q, summary in astro:
        out.append((slug, name, q,
                    f'{name} — {summary}.',
                    summary,
                    [('Object class', summary.split(',')[0]),
                     ('Notable fact', summary),
                     ('Category', 'astronomical object'), ('Type', 'astronomy')]))

    # ---------- 9) Dance styles (25) ---------------------------------------
    dance = [
        ('ballet_dance', 'Ballet', 'ballet dance', 'highly technical Western theatre dance, originated in 15th-c. Italy'),
        ('tango_dance', 'Tango', 'tango dance', 'partner dance, originated 1880s Río de la Plata'),
        ('flamenco_dance', 'Flamenco', 'flamenco dance', 'Andalusian art form, song + dance + guitar'),
        ('salsa_dance', 'Salsa', 'salsa dance', 'partner Latin dance, Cuban + New York roots, 1960s–70s'),
        ('bachata_dance', 'Bachata', 'bachata dance', 'partner dance from Dominican Republic, mid-20th c.'),
        ('merengue_dance', 'Merengue', 'merengue dance', 'national dance of the Dominican Republic'),
        ('samba_dance', 'Samba', 'samba dance', 'Brazilian dance, Afro-Brazilian roots, Carnival anthem'),
        ('rumba_dance', 'Rumba', 'rumba dance', 'Cuban dance, Afro-Cuban origins'),
        ('cha_cha_dance', 'Cha-cha-cha', 'cha cha cha dance', 'Cuban ballroom dance, 1950s'),
        ('foxtrot_dance', 'Foxtrot', 'foxtrot dance', 'smooth ballroom dance, 1914'),
        ('waltz_dance', 'Waltz', 'waltz dance', 'triple-time partner dance, Vienna 18th–19th c.'),
        ('viennese_waltz', 'Viennese Waltz', 'viennese waltz dance', 'fast rotating waltz, Vienna 19th c.'),
        ('quickstep_dance', 'Quickstep', 'quickstep dance', 'fast ballroom dance, 1920s'),
        ('paso_doble', 'Paso doble', 'paso doble dance', 'Spanish-style ballroom dance, bullfighter march'),
        ('jive_dance', 'Jive', 'jive dance', 'energetic swing ballroom dance, 1930s'),
        ('lindy_hop', 'Lindy Hop', 'lindy hop dance', 'partner swing, Harlem 1920s–30s'),
        ('charleston_dance', 'Charleston', 'charleston dance', 'fast jazz dance, 1920s'),
        ('breakdance', 'Breakdancing', 'breakdancing breaking', 'street dance, NYC 1970s; Olympic event 2024'),
        ('hip_hop_dance', 'Hip-hop dance', 'hip hop dance', 'street and studio styles from hip-hop culture'),
        ('contemporary_dance', 'Contemporary dance', 'contemporary dance', '20th-c. concert dance, post-modern lineage'),
        ('modern_dance', 'Modern dance', 'modern dance', 'early 20th-c. break from ballet (Graham, Cunningham)'),
        ('tap_dance', 'Tap dance', 'tap dance', 'percussive dance with metal-soled shoes, US 19th c.'),
        ('belly_dance', 'Belly dance', 'belly dance', 'Middle Eastern dance, hip and torso articulation'),
        ('hula_dance', 'Hula', 'hula dance', 'Native Hawaiian dance form'),
        ('bharatanatyam_dance', 'Bharatanatyam', 'bharatanatyam dance', 'classical Indian dance, Tamil Nadu origin'),
    ]
    for slug, name, q, summary in dance:
        out.append((slug, name, q,
                    f'{name} is a dance form — {summary}.',
                    summary,
                    [('Origin', summary.split(',')[-1].strip() if ',' in summary else summary),
                     ('Style', summary), ('Category', 'dance'), ('Type', 'performing art')]))

    # ---------- 10) Board / card games (30) --------------------------------
    games = [
        ('monopoly_game', 'Monopoly', 'monopoly board game', 'real-estate trading board game, 1935 Parker Brothers'),
        ('scrabble_game', 'Scrabble', 'scrabble board game', 'word-tile board game, 1948 by Alfred Butts'),
        ('chess_game', 'Chess (game)', 'chess board game', 'two-player strategy game, 6th-c. India origin'),
        ('go_game', 'Go (game)', 'go board game', 'territorial board game, 4th-c. BC China'),
        ('shogi_game', 'Shogi', 'shogi japanese chess', 'Japanese variant of chess with drop rule'),
        ('xiangqi_game', 'Xiangqi', 'xiangqi chinese chess', 'Chinese chess, played on board intersections'),
        ('checkers_game', 'Checkers', 'checkers draughts game', 'two-player diagonal-move board game, ancient'),
        ('backgammon_game', 'Backgammon', 'backgammon game', "two-player race game with dice, one of the world's oldest"),
        ('risk_game', 'Risk (game)', 'risk board game', 'global-strategy board game, 1957 Albert Lamorisse'),
        ('clue_game', 'Cluedo (Clue)', 'cluedo clue board game', 'murder-mystery deduction game, 1949 Anthony Pratt'),
        ('catan_game', 'Catan', 'settlers of catan board game', 'resource-trading board game, 1995 Klaus Teuber'),
        ('ticket_to_ride', 'Ticket to Ride', 'ticket to ride board game', 'rail-route board game, 2004 Alan R. Moon'),
        ('carcassonne_game', 'Carcassonne', 'carcassonne board game', 'tile-laying board game, 2000 Klaus-Jürgen Wrede'),
        ('pandemic_game', 'Pandemic', 'pandemic board game', 'cooperative disease-fighting board game, 2008 Matt Leacock'),
        ('dominion_game', 'Dominion (card game)', 'dominion deck building', 'deck-building card game, 2008 Donald X. Vaccarino'),
        ('codenames_game', 'Codenames', 'codenames party game', 'team word-association game, 2015 Vlaada Chvátil'),
        ('uno_game', 'UNO', 'uno card game', 'shedding-type card game, 1971 Merle Robbins'),
        ('poker_game', 'Poker', 'poker card game', 'family of betting card games using ranked hands'),
        ('texas_holdem', "Texas hold 'em", 'texas holdem poker', 'most popular poker variant'),
        ('bridge_game', 'Contract bridge', 'contract bridge card game', 'four-player partnership card game'),
        ('hearts_game', 'Hearts (card game)', 'hearts card game', 'evasion-type trick-taking card game'),
        ('spades_game', 'Spades (card game)', 'spades card game', 'partnership trick-taking card game'),
        ('blackjack_game', 'Blackjack', 'blackjack card game', 'comparing card game between player and dealer'),
        ('solitaire_game', 'Klondike (solitaire)', 'klondike solitaire', 'classic one-player card patience game'),
        ('mahjong_game', 'Mahjong', 'mahjong tile game', 'tile-based game, 19th-c. China'),
        ('reversi_game', 'Reversi (Othello)', 'reversi othello game', 'flip-disk strategy board game, 1883'),
        ('connect_four', 'Connect Four', 'connect four game', 'two-player vertical four-in-a-row game'),
        ('battleship_game', 'Battleship (game)', 'battleship game', 'two-player guessing game on a grid'),
        ('jenga_game', 'Jenga', 'jenga game', 'physical block-stacking party game, 1983'),
        ('twister_game', 'Twister', 'twister game', 'physical dexterity party game, 1966 Milton Bradley'),
    ]
    for slug, name, q, summary in games:
        out.append((slug, name, q,
                    f'{name} — {summary}.',
                    summary,
                    [('Type', 'board / card game'),
                     ('Designer / origin', summary), ('Category', 'game'),
                     ('Players', '2+')]))

    # ---------- 11) Photography concepts (25) ------------------------------
    photo = [
        ('aperture_photography', 'Aperture (photography)', 'aperture photography', 'opening in the lens diaphragm that controls light and depth of field'),
        ('shutter_speed', 'Shutter speed', 'shutter speed photography', 'length of time the sensor / film is exposed'),
        ('iso_sensitivity', 'ISO (sensitivity)', 'iso sensitivity photography', 'sensor sensitivity setting; higher ISO = more noise'),
        ('exposure_triangle', 'Exposure triangle', 'exposure triangle photography', 'aperture + shutter speed + ISO interaction'),
        ('depth_of_field', 'Depth of field', 'depth of field photography', 'zone of acceptable sharpness in an image'),
        ('rule_of_thirds', 'Rule of thirds', 'rule of thirds composition', 'compositional guideline placing subjects on 3×3 grid intersections'),
        ('golden_hour', 'Golden hour', 'golden hour photography', 'warm-light period shortly after sunrise / before sunset'),
        ('blue_hour', 'Blue hour', 'blue hour photography', 'twilight period producing blue cast in the sky'),
        ('bokeh_effect', 'Bokeh', 'bokeh photography effect', 'aesthetic out-of-focus blur'),
        ('hdr_photography', 'HDR photography', 'high dynamic range hdr photography', 'extended dynamic range from multiple exposures'),
        ('long_exposure', 'Long exposure', 'long exposure photography', 'shutter open for seconds to minutes for motion blur'),
        ('panning_photography', 'Panning (photography)', 'panning photography technique', 'tracking a moving subject during exposure for sharp subject / blurred background'),
        ('astrophotography', 'Astrophotography', 'astrophotography', 'photography of celestial objects'),
        ('macrophotography', 'Macro photography', 'macro photography', 'extreme close-up photography'),
        ('street_photography', 'Street photography', 'street photography', 'candid public-space photography'),
        ('portrait_photography', 'Portrait photography', 'portrait photography', 'photography focused on the human face / subject'),
        ('landscape_photography', 'Landscape photography', 'landscape photography', 'photography of natural and rural scenery'),
        ('product_photography', 'Product photography', 'product photography', 'commercial photography of items for sale'),
        ('wedding_photography', 'Wedding photography', 'wedding photography', 'event coverage of weddings'),
        ('photojournalism', 'Photojournalism', 'photojournalism', 'photography that tells news stories'),
        ('film_photography', 'Film photography', 'film photography', 'photography using analog photographic film'),
        ('large_format_photography', 'Large-format photography', 'large format photography', 'photography on film 4×5 in. or larger'),
        ('cyanotype_process', 'Cyanotype', 'cyanotype process', 'historic blue-toned photographic printing process, 1842'),
        ('daguerreotype_process', 'Daguerreotype', 'daguerreotype process', 'first commercial photographic process, 1839'),
        ('lightroom_software', 'Adobe Lightroom', 'adobe lightroom software', 'industry-standard photo editing and management software'),
    ]
    for slug, name, q, summary in photo:
        out.append((slug, name, q,
                    f'{name} — {summary}.',
                    summary,
                    [('Category', 'photography'), ('Concept / process', summary),
                     ('Type', 'visual art'), ('Field', 'photography')]))

    # ---------- 12) Wine regions & coffee (25) -----------------------------
    wine = [
        ('bordeaux_wine', 'Bordeaux wine', 'bordeaux wine region', 'wine produced in the Bordeaux region of southwestern France'),
        ('burgundy_wine', 'Burgundy wine', 'burgundy wine region', 'wine from the Burgundy (Bourgogne) region of France'),
        ('champagne_wine', 'Champagne (wine)', 'champagne wine region', 'sparkling wine from the Champagne region of France'),
        ('chablis_wine', 'Chablis wine', 'chablis wine region', 'unoaked Chardonnay from northern Burgundy'),
        ('rhone_wine', 'Rhône wine', 'rhone wine region', 'wine from the Rhône valley of France'),
        ('alsace_wine', 'Alsace wine', 'alsace wine region', 'aromatic whites from northeastern France'),
        ('rioja_wine', 'Rioja (wine)', 'rioja wine region', 'wine from the Rioja region of northern Spain'),
        ('priorat_wine', 'Priorat (wine)', 'priorat wine region', 'wine from a small DOQ region in Catalonia'),
        ('chianti_wine', 'Chianti wine', 'chianti wine region', 'Sangiovese-based wine from Tuscany'),
        ('barolo_wine', 'Barolo wine', 'barolo wine region', 'Nebbiolo-based DOCG wine from Piedmont'),
        ('barbaresco_wine', 'Barbaresco wine', 'barbaresco wine region', 'Nebbiolo-based DOCG wine from Piedmont'),
        ('mosel_wine', 'Mosel wine', 'mosel wine region', 'Riesling-focused German wine region along the Moselle'),
        ('napa_valley_wine', 'Napa Valley wine', 'napa valley wine region', 'wine from Napa County, California, USA'),
        ('sonoma_wine', 'Sonoma County wine', 'sonoma county wine region', 'wine from Sonoma County, California, USA'),
        ('willamette_valley', 'Willamette Valley AVA', 'willamette valley wine region', 'Oregon Pinot Noir wine region'),
        ('mendoza_wine', 'Mendoza wine', 'mendoza wine region', 'largest wine region in Argentina, Malbec heartland'),
        ('barossa_wine', 'Barossa Valley wine', 'barossa valley wine region', 'Australian Shiraz wine region'),
        ('marlborough_wine', 'Marlborough wine', 'marlborough wine region', 'Sauvignon Blanc heartland of New Zealand'),
        ('arabica_coffee', 'Arabica coffee', 'arabica coffee species', 'Coffea arabica, ~60% of world coffee production'),
        ('robusta_coffee', 'Robusta coffee', 'robusta coffee species', 'Coffea canephora, hardier with higher caffeine'),
        ('espresso_coffee', 'Espresso', 'espresso coffee', 'pressurized brewing method, Italian origin'),
        ('cappuccino_coffee', 'Cappuccino', 'cappuccino coffee', 'espresso with steamed and foamed milk'),
        ('latte_coffee', 'Caffè latte', 'caffe latte coffee', 'espresso with mostly steamed milk'),
        ('cold_brew_coffee', 'Cold brew coffee', 'cold brew coffee method', 'coffee brewed with cool water over 12+ hours'),
        ('pourover_coffee', 'Pour-over coffee', 'pour over coffee method', 'manual filter-coffee brewing method'),
    ]
    for slug, name, q, summary in wine:
        out.append((slug, name, q,
                    f'{name} — {summary}.',
                    summary,
                    [('Category', 'wine / coffee'), ('Notable fact', summary),
                     ('Type', 'beverage'), ('Field', 'beverage culture')]))

    # ---------- 13) Famous battles & treaties (40) ------------------------
    battles = [
        ('battle_of_hastings', 'Battle of Hastings', 'battle of hastings 1066', '14 October 1066 — Norman Conquest of England'),
        ('battle_of_waterloo', 'Battle of Waterloo', 'battle of waterloo 1815', '18 June 1815 — end of the Napoleonic Wars'),
        ('battle_of_marathon', 'Battle of Marathon', 'battle of marathon 490 bc', '490 BC — Athenian victory over Persia'),
        ('battle_of_thermopylae', 'Battle of Thermopylae', 'battle of thermopylae 480 bc', '480 BC — 300 Spartans stand against Xerxes'),
        ('battle_of_gettysburg', 'Battle of Gettysburg', 'battle of gettysburg 1863', '1–3 July 1863 — turning point of US Civil War'),
        ('battle_of_stalingrad', 'Battle of Stalingrad', 'battle of stalingrad 1942 1943', 'Aug 1942 – Feb 1943 — turning point of WWII Eastern Front'),
        ('battle_of_midway', 'Battle of Midway', 'battle of midway 1942', '4–7 June 1942 — turning point in Pacific WWII'),
        ('battle_of_normandy', 'Battle of Normandy', 'battle of normandy d-day 1944', 'D-Day landings, 6 June 1944'),
        ('battle_of_britain', 'Battle of Britain', 'battle of britain 1940', 'July–October 1940 — RAF vs. Luftwaffe'),
        ('siege_of_leningrad', 'Siege of Leningrad', 'siege of leningrad 1941 1944', '872-day siege, 1941–1944'),
        ('battle_of_actium', 'Battle of Actium', 'battle of actium 31 bc', '2 September 31 BC — Octavian defeats Antony and Cleopatra'),
        ('battle_of_cannae', 'Battle of Cannae', 'battle of cannae 216 bc', '2 August 216 BC — Hannibal\'s tactical masterpiece'),
        ('siege_of_constantinople', 'Fall of Constantinople', 'fall of constantinople 1453', '29 May 1453 — Ottoman conquest'),
        ('battle_of_lepanto', 'Battle of Lepanto', 'battle of lepanto 1571', '7 October 1571 — Holy League defeats Ottomans'),
        ('battle_of_yorktown', 'Siege of Yorktown', 'siege of yorktown 1781', '28 September – 19 October 1781 — end of American Revolutionary War'),
        ('battle_of_trafalgar', 'Battle of Trafalgar', 'battle of trafalgar 1805', '21 October 1805 — Nelson defeats Franco-Spanish fleet'),
        ('battle_of_agincourt', 'Battle of Agincourt', 'battle of agincourt 1415', '25 October 1415 — Henry V\'s longbow victory'),
        ('battle_of_tours', 'Battle of Tours', 'battle of tours 732', '10 October 732 — Charles Martel halts Umayyad expansion'),
        ('battle_of_kursk', 'Battle of Kursk', 'battle of kursk 1943', '5 July – 23 August 1943 — largest tank battle in history'),
        ('battle_of_okinawa', 'Battle of Okinawa', 'battle of okinawa 1945', '1 April – 22 June 1945 — largest amphibious assault in the Pacific'),
        ('treaty_of_versailles', 'Treaty of Versailles', 'treaty of versailles 1919', '28 June 1919 — formal end of WWI'),
        ('treaty_of_westphalia', 'Peace of Westphalia', 'peace of westphalia 1648', '1648 — basis of modern state sovereignty'),
        ('magna_carta_1215', 'Magna Carta', 'magna carta 1215', '15 June 1215 — charter limiting royal authority'),
        ('treaty_of_tordesillas', 'Treaty of Tordesillas', 'treaty of tordesillas 1494', '7 June 1494 — Spain and Portugal divide New World'),
        ('declaration_of_independence', 'United States Declaration of Independence', 'declaration of independence 1776', '4 July 1776 — Continental Congress'),
        ('us_constitution', 'United States Constitution', 'united states constitution 1787', 'Adopted 17 September 1787; supreme law of the US'),
        ('bill_of_rights_us', 'United States Bill of Rights', 'us bill of rights 1791', 'First 10 amendments to US Constitution, ratified 1791'),
        ('emancipation_proclamation', 'Emancipation Proclamation', 'emancipation proclamation 1863', '1 January 1863 — Lincoln frees Confederate slaves'),
        ('un_charter', 'Charter of the United Nations', 'un charter 1945', '26 June 1945 — founding document of the UN'),
        ('udhr_1948', 'Universal Declaration of Human Rights', 'universal declaration human rights 1948', '10 December 1948 — UN General Assembly'),
        ('geneva_conventions', 'Geneva Conventions', 'geneva conventions 1949', '12 August 1949 — laws of war'),
        ('nato_treaty', 'North Atlantic Treaty', 'north atlantic treaty nato 1949', '4 April 1949 — founding of NATO'),
        ('treaty_of_rome', 'Treaty of Rome', 'treaty of rome 1957', '25 March 1957 — established European Economic Community'),
        ('paris_agreement', 'Paris Agreement', 'paris agreement climate 2015', '12 December 2015 — UN climate accord'),
        ('outer_space_treaty', 'Outer Space Treaty', 'outer space treaty 1967', '27 January 1967 — foundation of space law'),
        ('kyoto_protocol', 'Kyoto Protocol', 'kyoto protocol 1997', '11 December 1997 — UNFCCC climate treaty'),
        ('camp_david_accords', 'Camp David Accords', 'camp david accords 1978', '17 September 1978 — Egypt and Israel'),
        ('good_friday_agreement', 'Good Friday Agreement', 'good friday agreement 1998', '10 April 1998 — Northern Ireland peace'),
        ('antarctic_treaty', 'Antarctic Treaty System', 'antarctic treaty 1959', '1 December 1959 — peaceful, scientific use of Antarctica'),
        ('lateran_treaty', 'Lateran Treaty', 'lateran treaty 1929', '11 February 1929 — established Vatican City'),
    ]
    for slug, name, q, summary in battles:
        out.append((slug, name, q,
                    f'{name} — {summary}.',
                    summary,
                    [('Date', summary.split('—')[0].strip()),
                     ('Notable fact', summary.split('—')[-1].strip() if '—' in summary else summary),
                     ('Category', 'battle / treaty'), ('Type', 'history')]))

    # ---------- 14) Programming concepts (40) -----------------------------
    progc = [
        ('big_o_notation', 'Big O notation', 'big o notation', 'mathematical notation describing the limiting behaviour of a function'),
        ('binary_search', 'Binary search', 'binary search algorithm', 'O(log n) search in sorted arrays'),
        ('breadth_first_search', 'Breadth-first search', 'breadth first search bfs', 'graph traversal exploring neighbours layer by layer'),
        ('depth_first_search', 'Depth-first search', 'depth first search dfs', 'graph traversal that goes as deep as possible'),
        ('dijkstras_algorithm', "Dijkstra's algorithm", 'dijkstra shortest path algorithm', 'single-source shortest paths in a non-negative-weight graph'),
        ('bellman_ford_algorithm', 'Bellman–Ford algorithm', 'bellman ford algorithm', 'shortest paths even with negative edge weights'),
        ('floyd_warshall_algorithm', 'Floyd–Warshall algorithm', 'floyd warshall algorithm', 'all-pairs shortest paths, O(n^3)'),
        ('a_star_algorithm', 'A* search', 'a star search algorithm', 'heuristic-guided best-first search'),
        ('quicksort_algorithm', 'Quicksort', 'quicksort algorithm', 'O(n log n) average comparison sort by Tony Hoare'),
        ('mergesort_algorithm', 'Merge sort', 'merge sort algorithm', 'O(n log n) divide-and-conquer comparison sort'),
        ('heapsort_algorithm', 'Heapsort', 'heapsort algorithm', 'O(n log n) sort using a binary heap'),
        ('radix_sort', 'Radix sort', 'radix sort algorithm', 'non-comparison sort by digit'),
        ('kmp_algorithm', 'Knuth–Morris–Pratt algorithm', 'kmp string search algorithm', 'O(n + m) string-search algorithm'),
        ('boyer_moore_algorithm', 'Boyer–Moore string-search algorithm', 'boyer moore string search algorithm', 'fast practical string-search algorithm'),
        ('rabin_karp_algorithm', 'Rabin–Karp algorithm', 'rabin karp string search', 'hashing-based string-search algorithm'),
        ('rsa_algorithm', 'RSA cryptosystem', 'rsa cryptosystem algorithm', 'public-key cryptosystem by Rivest, Shamir, Adleman, 1977'),
        ('aes_cipher', 'Advanced Encryption Standard', 'aes advanced encryption standard', 'symmetric block cipher adopted by NIST in 2001'),
        ('diffie_hellman', 'Diffie–Hellman key exchange', 'diffie hellman key exchange', 'public-key key-agreement protocol, 1976'),
        ('sha_2', 'SHA-2', 'sha-2 hash family', 'family of cryptographic hash functions standardized by NIST'),
        ('md5_hash', 'MD5', 'md5 hash algorithm', '128-bit cryptographic hash function (deprecated for security)'),
        ('tcp_protocol', 'Transmission Control Protocol', 'tcp transmission control protocol', 'reliable byte-stream transport layer protocol'),
        ('ip_protocol', 'Internet Protocol', 'ip internet protocol', 'principal communications protocol of the internet'),
        ('http_protocol_r6', 'HTTP (Hypertext Transfer Protocol)', 'http hypertext transfer protocol web', 'application-layer protocol for distributed hypermedia'),
        ('https_protocol', 'HTTPS', 'https hypertext transfer protocol secure', 'HTTP over TLS — encrypted hypertext transfer'),
        ('dns_protocol', 'DNS', 'dns domain name system', 'hierarchical decentralized naming system for the internet'),
        ('rest_architecture', 'REST', 'rest representational state transfer', 'architectural style of network-based software systems'),
        ('graphql_api', 'GraphQL', 'graphql api', 'query language for APIs, developed by Facebook in 2012'),
        ('grpc_protocol', 'gRPC', 'grpc remote procedure call', 'high-performance RPC framework developed by Google'),
        ('mvc_pattern', 'Model–View–Controller', 'mvc model view controller pattern', 'software architectural pattern, Trygve Reenskaug 1979'),
        ('design_pattern_singleton', 'Singleton pattern', 'singleton design pattern', 'restricts class instantiation to one object'),
        ('design_pattern_factory', 'Factory method', 'factory method design pattern', 'creational pattern that defers instantiation to subclasses'),
        ('design_pattern_observer', 'Observer pattern', 'observer design pattern', 'one-to-many dependency between objects'),
        ('functional_programming', 'Functional programming', 'functional programming paradigm', 'paradigm treating computation as evaluation of mathematical functions'),
        ('oop_paradigm', 'Object-oriented programming', 'object oriented programming oop', 'paradigm based on the concept of objects with state + behaviour'),
        ('garbage_collection', 'Garbage collection (computing)', 'garbage collection memory management', 'automatic memory management technique'),
        ('virtual_machine', 'Virtual machine', 'virtual machine computing', 'software emulation of a computer system'),
        ('container_technology', 'Linux containers', 'linux containers lxc docker', 'OS-level virtualization for resource-isolated processes'),
        ('git_vcs_r6', 'Git (version control)', 'git version control system distributed', 'distributed version-control system by Linus Torvalds, 2005'),
        ('docker_software_r6', 'Docker (containers)', 'docker container platform', 'platform for developing and running containerized apps, 2013'),
        ('kubernetes_software', 'Kubernetes', 'kubernetes container orchestration', 'open-source container-orchestration system, 2014'),
    ]
    for slug, name, q, summary in progc:
        out.append((slug, name, q,
                    f'{name} — {summary}.',
                    summary,
                    [('Category', 'computer science / programming'),
                     ('Concept / technology', name),
                     ('Definition', summary),
                     ('Type', 'CS concept')]))

    return out

POP_TOPICS_R6 = _build()
