"""Drugs.com deepening — vanilla-level expansion.

Adds 6 new model families (Forum, Glossary, Refill, Recall, Pharmacy,
HealthNews, SideEffectReport, ContactPharmacistMsg, DosageCalculation,
SavedComparison), ~30 new routes (15+ POST), seed functions, and pure-data
constants. Wired from app.py via `from _deepen import register_deepening`.

Designed to:
  * extend the seed DB additively — existing rows untouched
  * remain byte-identical across rebuilds (no datetime.now / no random salts)
  * round-trip through normalize_seed_db_layout() in app.py (idempotent)
"""
from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timedelta
from flask import (
    abort, current_app, flash, jsonify, redirect, render_template,
    request, url_for,
)
from flask_login import current_user, login_required


MIRROR_REFERENCE_DATE = datetime(2026, 5, 12, 12, 0, 0)


# ---------------------------------------------------------------------------
# Static data
# ---------------------------------------------------------------------------
GLOSSARY_TERMS = [
    ("absorption", "The process by which a drug enters the bloodstream from the site of administration."),
    ("adherence", "The extent to which a patient takes medication as prescribed."),
    ("adverse-event", "An undesirable experience associated with the use of a medical product."),
    ("agonist", "A drug or substance that binds to a receptor and activates it to produce a biological response."),
    ("antagonist", "A drug that blocks the action of another substance at a receptor site."),
    ("antibiotic", "A medication that fights bacterial infections by killing bacteria or stopping their growth."),
    ("antibody", "A protein produced by the immune system that targets and neutralizes specific antigens."),
    ("anticoagulant", "A medication that prevents blood clot formation; commonly called a blood thinner."),
    ("antihistamine", "A drug that blocks the action of histamine, used to treat allergies."),
    ("antipyretic", "A medication that reduces fever."),
    ("bioavailability", "The proportion of a drug that enters circulation and produces an active effect."),
    ("biologic", "A medicine derived from living organisms or their components."),
    ("biosimilar", "A biologic medicine that is highly similar to an already-approved reference biologic."),
    ("black-box-warning", "The strongest warning required by the FDA, indicating a serious risk."),
    ("brand-name", "The trade name a manufacturer uses to market a drug."),
    ("clinical-trial", "A research study that tests new medical approaches in people."),
    ("contraindication", "A specific situation in which a drug should not be used because of potential harm."),
    ("controlled-substance", "A drug whose manufacture, possession, or use is regulated by government."),
    ("dosage", "The amount and frequency of medication to be taken."),
    ("efficacy", "The ability of a drug to produce the desired beneficial effect."),
    ("excipient", "An inactive substance used as a carrier for the active ingredients of a medication."),
    ("fda", "The U.S. Food and Drug Administration, which regulates drugs and medical devices."),
    ("generic-drug", "A medication that contains the same active ingredients as a brand-name drug."),
    ("half-life", "The time required for the concentration of a drug to decrease by half in the body."),
    ("immunosuppressant", "A drug that reduces the strength of the body's immune system."),
    ("indication", "A condition or symptom for which a drug is approved or commonly used."),
    ("infusion", "A method of giving fluids or medications directly into a vein over time."),
    ("interaction", "A change in a drug's effect when taken together with another substance."),
    ("loading-dose", "A higher initial dose to quickly reach therapeutic concentrations."),
    ("metabolism", "The chemical breakdown of a drug by the body, primarily in the liver."),
    ("nsaid", "Non-steroidal anti-inflammatory drug used to reduce pain, fever, and inflammation."),
    ("off-label", "Use of a drug for a purpose not specifically approved by the FDA."),
    ("opioid", "A class of drugs used to treat pain that act on the opioid receptors."),
    ("otc", "Over-the-counter — medication available without a prescription."),
    ("pharmacokinetics", "The study of how a drug moves through the body."),
    ("pharmacodynamics", "The study of how a drug affects the body."),
    ("placebo", "An inactive substance used as a control in clinical trials."),
    ("polypharmacy", "The simultaneous use of multiple medications by one patient."),
    ("potency", "The amount of drug required to produce a given effect."),
    ("prescription", "A written order from a licensed healthcare provider for a medication."),
    ("prophylaxis", "Action taken to prevent disease."),
    ("pharmacist", "A healthcare professional licensed to dispense prescription medications."),
    ("rebound-effect", "The return or worsening of symptoms when a medication is stopped."),
    ("refractory", "Resistant to treatment with standard therapies."),
    ("renal-clearance", "The rate at which the kidneys remove a drug from the bloodstream."),
    ("rx", "Symbol for a medical prescription."),
    ("ssri", "Selective serotonin reuptake inhibitor — a class of antidepressants."),
    ("sublingual", "Administered by being placed under the tongue."),
    ("synergy", "An effect where two drugs together produce a greater response than either alone."),
    ("teratogen", "A substance that may cause birth defects when used during pregnancy."),
    ("therapeutic-index", "The ratio of the toxic dose to the effective dose of a drug."),
    ("titration", "Gradually adjusting the dose of a medication to reach the optimum effect."),
    ("tolerance", "Decreased response to a drug after repeated use."),
    ("topical", "Applied to the surface of the body, such as creams or ointments."),
    ("transdermal", "Delivered through the skin via patch."),
    ("withdrawal", "Symptoms that occur after stopping a drug the body has become dependent on."),
    ("xenobiotic", "A chemical substance found in an organism that is not naturally produced by it."),
    ("anaphylaxis", "A severe, potentially life-threatening allergic reaction."),
    ("bioequivalence", "Two drug formulations produce the same effect at the same dose."),
    ("cyp450", "A family of liver enzymes responsible for metabolizing most drugs."),
    ("dailymed", "The official FDA drug labeling database."),
    ("drug-class", "A group of medications that work in similar ways or treat similar conditions."),
    ("excretion", "The removal of a drug from the body, primarily via urine or feces."),
    ("formulary", "A list of prescription drugs covered by a health insurance plan."),
    ("hepatotoxicity", "Liver damage caused by exposure to a substance, often a drug."),
    ("indication-creep", "Gradual expansion of a drug's approved uses beyond its original indication."),
    ("jaundice", "Yellowing of skin and eyes caused by elevated bilirubin, sometimes drug-induced."),
    ("kinetics", "The movement of drugs in the body, including absorption, distribution, metabolism, excretion."),
    ("lipid-lowering", "Medications that reduce cholesterol or triglyceride levels."),
    ("maintenance-dose", "A dose given to maintain therapeutic effect after the loading dose."),
    ("nephrotoxicity", "Kidney damage caused by a substance or medication."),
    ("ototoxicity", "Damage to hearing or balance caused by certain drugs."),
    ("polymorphism", "Genetic variations that affect how individuals metabolize drugs."),
    ("qt-prolongation", "An electrical disturbance in the heart that can be caused by certain drugs."),
    ("steady-state", "When drug intake equals drug elimination in the body."),
    ("therapeutic-window", "The range of drug doses that produce a therapeutic effect without unacceptable toxicity."),
    ("uremia", "Buildup of waste products in the blood due to kidney failure."),
    ("vaccine", "A biological preparation that provides immunity to a specific disease."),
    ("warning-label", "Required information on drug packaging about risks and proper use."),
    ("xerostomia", "Dry mouth, a common side effect of many medications."),
    ("zero-order-kinetics", "Drug elimination that occurs at a constant rate independent of concentration."),
    ("absorption-rate-constant", "A measure of how quickly a drug is absorbed into the bloodstream."),
    ("clearance", "The volume of plasma from which a drug is removed per unit of time."),
    ("distribution", "The dispersion of a drug throughout body fluids and tissues."),
    ("elimination", "Removal of a drug from the body via metabolism and excretion."),
    ("first-pass", "Drug metabolism that occurs before reaching systemic circulation, mostly in liver."),
    ("genotype", "An individual's genetic makeup that may influence drug response."),
    ("hapten", "A small molecule that triggers an immune response only when attached to a carrier."),
    ("intramuscular", "Injected into a muscle."),
    ("intravenous", "Injected directly into a vein."),
    ("kappa-receptor", "A type of opioid receptor in the central nervous system."),
    ("levothyroxine", "A synthetic form of thyroid hormone used to treat hypothyroidism."),
    ("monoclonal-antibody", "A laboratory-produced molecule that mimics the immune system's ability to fight pathogens."),
    ("nebulizer", "A device that turns liquid medicine into a fine mist for inhalation."),
    ("oral-bioavailability", "The fraction of an orally administered drug that reaches systemic circulation."),
    ("placental-transfer", "The passage of substances from mother to fetus across the placenta."),
    ("quinolone", "A class of broad-spectrum antibacterial drugs."),
    ("receptor", "A protein molecule that receives chemical signals from outside a cell."),
    ("statin", "A class of drugs that lower cholesterol by inhibiting HMG-CoA reductase."),
    ("therapeutic-equivalence", "Drugs that produce the same clinical effect and safety profile."),
    ("urinary-excretion", "The elimination of drugs and their metabolites through urine."),
    ("volume-of-distribution", "A pharmacokinetic parameter relating the amount of drug to its plasma concentration."),
]


FORUM_CATEGORIES = [
    ("general", "General Discussion", "Open conversations about medications and health."),
    ("side-effects", "Side Effects", "Share and discuss medication side effects."),
    ("dosage-questions", "Dosage Questions", "Ask about dosing, missed doses, and adjustments."),
    ("drug-interactions", "Drug Interactions", "Talk about real-world drug-drug and drug-food interactions."),
    ("pregnancy-breastfeeding", "Pregnancy & Breastfeeding", "Medication safety during pregnancy and breastfeeding."),
    ("chronic-conditions", "Chronic Conditions", "Long-term medication management."),
    ("mental-health", "Mental Health Meds", "Antidepressants, anxiolytics, and mood stabilizers."),
    ("pain-management", "Pain Management", "Opioids, NSAIDs, and chronic pain therapies."),
    ("pediatric", "Pediatric", "Medication questions for children."),
    ("seniors", "Seniors", "Polypharmacy and age-related drug concerns."),
]

# Forum topics: (category_slug, title, body)
FORUM_TOPICS_RAW = [
    ("general", "Switching from brand to generic atorvastatin",
     "Insurance no longer covers Lipitor — anyone made the switch to generic atorvastatin? Same results?"),
    ("general", "Pharmacist gave me a different shape pill",
     "My metformin used to be round white; the new refill is oval. Same imprint and dose. Should I worry?"),
    ("general", "How do you remember to take meds at the same time?",
     "I keep forgetting my morning dose. Any apps or tricks people use?"),
    ("general", "Cost of insulin in the US — what's working?",
     "Pharmacy quoted $400 for a vial. Are coupon programs reliable long term?"),
    ("general", "FDA approval timeline for new biosimilars",
     "Following several biosimilars in review. Anyone tracking expected launch dates for the next 12 months?"),
    ("general", "Saving money with 90-day supplies",
     "My doctor wrote a 90-day script for lisinopril and it's far cheaper. Pros and cons of bulk fills?"),
    ("general", "First-time prescription anxiety",
     "Just got my first long-term medication. Any tips for managing the anxiety of starting something new?"),
    ("general", "Returning expired medication",
     "What's the proper way to dispose of expired prescriptions? Is the pharmacy take-back program safe?"),
    ("side-effects", "Lisinopril dry cough — when does it stop?",
     "Started lisinopril two weeks ago and the dry cough is constant. Does this resolve or do I need to switch?"),
    ("side-effects", "Metformin GI upset — anyone tolerate ER better?",
     "Immediate release wrecks my stomach. Did extended release fix the issue for you?"),
    ("side-effects", "Statin muscle aches — coenzyme Q10 worth trying?",
     "Calf cramps started with atorvastatin. Doctor mentioned CoQ10 but is there real evidence?"),
    ("side-effects", "SSRI brain zaps when missing a dose",
     "Skipped my sertraline one day and had brain zaps. Normal? Worried about long-term effects."),
    ("side-effects", "Warfarin and bruising",
     "Bruising more easily — INR is in range. Anyone else find this acceptable?"),
    ("side-effects", "Gabapentin causing daytime drowsiness",
     "Started 300mg three times daily. Drowsy all day. Will tolerance develop?"),
    ("side-effects", "Levothyroxine and hair thinning",
     "Six months in and noticing more hair shedding. Could be the dose."),
    ("side-effects", "Allergic reaction to penicillin — rash spreading",
     "Day 3 of amoxicillin and small red rash on my torso. Stop or push through?"),
    ("dosage-questions", "Missed a dose of warfarin — what now?",
     "Forgot last night's dose. Do I double up or skip and continue?"),
    ("dosage-questions", "Splitting metformin into smaller doses",
     "Can I split 1000mg metformin tablets to take 500mg twice daily?"),
    ("dosage-questions", "Pediatric dosing for amoxicillin",
     "5-year-old daughter has ear infection. Doctor wrote 400mg/5mL twice daily. How to measure accurately?"),
    ("dosage-questions", "When to take levothyroxine",
     "Morning or evening — which works better for absorption? I keep reading conflicting advice."),
    ("dosage-questions", "Tapering off prednisone safely",
     "Been on 20mg prednisone for 6 weeks. What's a safe taper schedule?"),
    ("dosage-questions", "Pill cutter accuracy",
     "How accurate are pill cutters for splitting 50mg sertraline tablets in half?"),
    ("dosage-questions", "Sustained release vs immediate release",
     "Doctor offered both for my hypertension. What's the actual difference in real life?"),
    ("dosage-questions", "Doubling missed Eliquis dose",
     "Missed yesterday's dose. Should I double today or skip?"),
    ("drug-interactions", "Grapefruit juice and statins",
     "I love grapefruit. Is the interaction with atorvastatin really that significant?"),
    ("drug-interactions", "Warfarin and vitamin K — leafy greens",
     "How strict should I be about salads while on warfarin?"),
    ("drug-interactions", "Ibuprofen and lisinopril",
     "Got mixed messages from pharmacist and PCP. Is occasional ibuprofen really off limits with lisinopril?"),
    ("drug-interactions", "SSRI and St. John's Wort",
     "Why is this combination considered dangerous? Serotonin syndrome explained?"),
    ("drug-interactions", "Antibiotic and birth control",
     "Pharmacist warned about reduced effectiveness. Which antibiotics actually matter?"),
    ("drug-interactions", "Alcohol and metronidazole",
     "How long after the last dose is it safe to drink?"),
    ("pregnancy-breastfeeding", "SSRI during pregnancy — risk vs untreated depression",
     "Trying to weigh continuing sertraline vs the risks of untreated depression in pregnancy."),
    ("pregnancy-breastfeeding", "Tylenol vs ibuprofen while breastfeeding",
     "Which pain reliever is preferred while nursing a newborn?"),
    ("pregnancy-breastfeeding", "Metformin in pregnancy",
     "My OB switched me to insulin. Why not continue metformin?"),
    ("pregnancy-breastfeeding", "Lactation safety database recommendations",
     "What sources does everyone trust for breastfeeding medication info?"),
    ("chronic-conditions", "Long-term PPI use risks",
     "On omeprazole for 5 years. Should I be tapering off?"),
    ("chronic-conditions", "Diabetes meds and weight gain",
     "Most diabetes drugs caused weight gain. Are any weight-neutral or weight-loss favorable?"),
    ("chronic-conditions", "Methotrexate folic acid schedule",
     "RA patient. What day of the week do you take folic acid relative to MTX?"),
    ("chronic-conditions", "Switching insulins — Lantus to Toujeo",
     "Insurance change forced a switch. Same dose? Adjust?"),
    ("mental-health", "Switching SSRIs — washout period needed?",
     "Going from sertraline to escitalopram. How does the cross-taper work?"),
    ("mental-health", "Lithium levels — how often to check",
     "Stable for 2 years. Quarterly checks reasonable or overkill?"),
    ("mental-health", "Benzo taper after a year",
     "On clonazepam 1mg daily. Doctor wants to taper. Experiences?"),
    ("mental-health", "ADHD meds and sleep",
     "Adderall makes me sleep poorly. Switch to non-stimulant?"),
    ("pain-management", "Tramadol vs codeine",
     "Doctor offered either. What are the differences?"),
    ("pain-management", "Topical NSAIDs vs oral",
     "Knee pain. Tried voltaren gel — works as well as oral?"),
    ("pain-management", "Long-term opioid pain management",
     "Chronic back pain. How are people managing without escalation?"),
    ("pediatric", "Acetaminophen weight-based dosing for toddlers",
     "How do you calculate the right dose for a 28-lb toddler?"),
    ("pediatric", "Liquid medication dropper accuracy",
     "Dropper that came with the prescription seems imprecise."),
    ("pediatric", "Antibiotic refrigeration requirements",
     "Pediatric amoxicillin says refrigerate. What if it sits out a few hours?"),
    ("seniors", "Polypharmacy concerns — 12 daily medications",
     "84yo father on 12 prescriptions. How to advocate for a deprescribing review?"),
    ("seniors", "Falls and benzodiazepines",
     "Mother fell after starting lorazepam. Are alternatives safer?"),
    ("seniors", "Beers Criteria for elderly",
     "Anyone use the Beers List with their physician?"),
]


HEALTH_NEWS_RAW = [
    # (slug, title, category, body, days_offset)
    ("fda-approves-new-weight-loss-pill-2026", "FDA Approves New Once-Daily Weight Loss Pill",
     "fda-alerts",
     "The FDA approved a new GLP-1 receptor agonist pill for chronic weight management in adults. The drug demonstrated 15% average body weight reduction over 68 weeks in phase 3 trials.", 2),
    ("statin-meta-analysis-cardiovascular-benefit", "New Meta-Analysis Confirms Cardiovascular Benefit of Statins in Adults Over 75",
     "clinical-trials",
     "A pooled analysis of 28 trials with 186,000 patients found statins reduce major adverse cardiovascular events by 21% in primary prevention even in patients over 75.", 5),
    ("aspirin-primary-prevention-update", "USPSTF Updates Aspirin Recommendation for Primary Prevention",
     "fda-alerts",
     "The U.S. Preventive Services Task Force narrowed its recommendation for low-dose aspirin in primary prevention of cardiovascular disease, citing bleeding risks in older adults.", 7),
    ("metformin-cognitive-decline-study", "Metformin Linked to Reduced Dementia Risk in Diabetic Patients",
     "clinical-trials",
     "Observational data from 95,000 diabetic patients suggests metformin use was associated with a 28% lower risk of dementia compared with sulfonylureas.", 10),
    ("ozempic-shortage-update-2026", "Ozempic Supply Returns to Normal Across U.S. Pharmacies",
     "fda-alerts",
     "Novo Nordisk announced that semaglutide injection supplies have stabilized after 18 months of intermittent shortages affecting diabetic and weight-loss patients.", 12),
    ("biosimilar-humira-uptake", "Humira Biosimilar Uptake Reaches 38% in U.S. Market",
     "new-drug-approvals",
     "Two years after launch, adalimumab biosimilars now account for 38% of prescriptions, with payer formulary changes driving recent acceleration.", 15),
    ("warfarin-replacement-doac-shift", "DOACs Now Outprescribed Warfarin 4-to-1 in Atrial Fibrillation",
     "clinical-trials",
     "Direct oral anticoagulants such as apixaban and rivaroxaban now make up 80% of new anticoagulant prescriptions for atrial fibrillation in the U.S.", 18),
    ("opioid-prescribing-decline-continues", "Opioid Prescribing Continues 12-Year Decline",
     "fda-alerts",
     "CDC data show opioid prescriptions fell another 4% in the past year, reaching the lowest per-capita level since 2008.", 20),
    ("ssri-pregnancy-safety-meta", "Large Cohort Study Reaffirms SSRI Safety in Pregnancy",
     "clinical-trials",
     "A study of 1.8 million pregnancies found no statistically significant increased risk of major congenital malformations from first-trimester SSRI exposure.", 22),
    ("antibiotic-stewardship-outcomes", "Outpatient Antibiotic Stewardship Cuts Prescriptions 18%",
     "clinical-trials",
     "A multi-state stewardship program reduced inappropriate outpatient antibiotic prescribing by 18% over 24 months.", 25),
    ("methotrexate-folate-confirmed", "Folic Acid Supplementation Standard for Methotrexate Patients Now Universal",
     "fda-alerts",
     "Updated rheumatology guidelines call for universal folic acid co-prescription with methotrexate after the latest tolerability data.", 28),
    ("levothyroxine-formulation-bioequivalence", "FDA Clarifies Levothyroxine Brand-to-Generic Switching Guidance",
     "fda-alerts",
     "New FDA guidance recommends rechecking TSH 4-6 weeks after any levothyroxine product switch due to subtle bioavailability differences.", 30),
    ("insulin-cap-impact-six-months", "$35 Insulin Cap: First Six Months Show 14% Adherence Improvement",
     "clinical-trials",
     "Medicare data on the $35 insulin out-of-pocket cap show a 14% improvement in 90-day adherence rates in the first six months.", 33),
    ("naloxone-otc-uptake", "Over-the-Counter Naloxone Saved an Estimated 6,200 Lives in First Year",
     "new-drug-approvals",
     "Modeling based on overdose reversal reports estimates OTC naloxone access has prevented thousands of deaths in its inaugural year of availability.", 35),
    ("hypertension-target-trial-2026", "Lower BP Target of 120/80 Confirmed in High-Risk Adults",
     "clinical-trials",
     "A 12,000-patient trial confirms cardiovascular benefit of targeting systolic BP under 120 mmHg in high-risk adults aged 50+.", 38),
    ("alzheimer-disease-modifying-2026", "Second Disease-Modifying Alzheimer's Drug Approved by FDA",
     "new-drug-approvals",
     "The FDA approved a second monoclonal antibody targeting amyloid-beta plaques for early Alzheimer's disease, showing 27% slowing of cognitive decline.", 40),
    ("antiviral-flu-baloxavir-uptake", "Single-Dose Flu Antiviral Baloxavir Sees Surge in Use",
     "fda-alerts",
     "Pharmacy data show baloxavir prescriptions doubled this flu season as patients prefer one-dose treatment over five-day oseltamivir courses.", 42),
    ("birth-control-otc-progestin-2-year-report", "OTC Progestin-Only Pill: Two-Year Real-World Report",
     "clinical-trials",
     "The first daily birth control pill available over-the-counter has been used by over 4 million Americans with no new safety signals reported.", 45),
    ("vaccine-rsv-older-adults-uptake", "RSV Vaccine Uptake Reaches 42% in Adults 75+",
     "new-drug-approvals",
     "CDC reports RSV vaccination rates exceed 40% in adults aged 75 and older two years after initial approval.", 48),
    ("hiv-prep-lenacapavir-injectable", "Twice-Yearly HIV PrEP Injection Now Available",
     "new-drug-approvals",
     "Lenacapavir, the first twice-yearly injectable HIV pre-exposure prophylaxis, has been approved by the FDA following landmark efficacy data.", 50),
    ("ssri-discontinuation-syndrome-recognition", "Updated Guidelines Recognize SSRI Discontinuation Syndrome",
     "fda-alerts",
     "Major psychiatric guidelines now formally recognize SSRI discontinuation syndrome and recommend taper schedules of at least 4 weeks.", 53),
    ("inhaler-environment-impact-shift", "Pulmonologists Push for Lower-Emission Inhalers",
     "clinical-trials",
     "New guidance encourages dry-powder inhalers over metered-dose where clinically appropriate due to environmental impact.", 56),
    ("acetaminophen-pregnancy-update", "Acetaminophen-in-Pregnancy Studies Show No Definitive Risk",
     "clinical-trials",
     "A new sibling-controlled analysis weakens previously raised concerns about acetaminophen use during pregnancy and neurodevelopmental outcomes.", 60),
    ("ozempic-rare-side-effect-pancreatitis", "FDA Reviewing Pancreatitis Reports With GLP-1 Agonists",
     "fda-alerts",
     "The FDA is reviewing post-marketing reports of pancreatitis among patients on semaglutide and tirzepatide.", 64),
    ("compounded-glp1-warning", "FDA Warns Against Compounded Semaglutide From Unverified Sources",
     "fda-alerts",
     "Patients are warned to verify any compounded semaglutide they receive comes from a state-licensed pharmacy.", 68),
    ("antibiotic-resistance-global-2026", "Antibiotic Resistance Now Causes 1.4 Million Deaths Per Year",
     "clinical-trials",
     "The Global Burden of Antibiotic Resistance estimates 1.4 million directly attributable deaths annually.", 72),
    ("blood-pressure-home-monitoring", "Home BP Monitoring Now Recommended for All Hypertension Patients",
     "clinical-trials",
     "Updated guidelines recommend home blood pressure monitoring for all hypertensive patients to refine medication titration.", 76),
    ("vitamin-d-supplementation-2026", "Routine Vitamin D Screening No Longer Recommended in Healthy Adults",
     "fda-alerts",
     "USPSTF concludes that routine vitamin D screening in asymptomatic adults does not improve outcomes.", 80),
    ("cannabis-prescription-drug-interactions", "Pharmacists Flag Cannabis-Prescription Interactions in 18% of Reviews",
     "clinical-trials",
     "Community pharmacy data show clinically meaningful cannabis-prescription drug interactions in nearly one in five medication therapy management sessions.", 84),
    ("medicare-negotiation-drug-prices-2026", "Medicare Drug Price Negotiation Lowers 10 Common Drug Prices",
     "fda-alerts",
     "The first round of Medicare price negotiations cut prices on 10 high-spend drugs including apixaban, rivaroxaban, and empagliflozin.", 88),
]


DRUG_RECALLS_RAW = [
    # (slug, drug_name, lot, severity, reason, days_offset)
    ("metformin-extended-release-recall-2026-04", "Metformin ER 500mg", "MFR-2026-04-001",
     "Class II",
     "Trace levels of NDMA detected above the acceptable daily intake threshold.", 4),
    ("losartan-50mg-impurity-recall", "Losartan 50mg", "LOS-50-2026-03-X12",
     "Class II",
     "Manufacturing impurity detected during routine testing.", 7),
    ("amoxicillin-pediatric-suspension-recall", "Amoxicillin 250mg/5mL Suspension", "AMX-PED-2026-01-44",
     "Class III",
     "Mislabeling of suspension strength on outer carton.", 11),
    ("losartan-100mg-recall", "Losartan 100mg", "LOS-100-2026-02-44",
     "Class II",
     "Out-of-specification dissolution results in extended stability testing.", 15),
    ("metoprolol-succinate-er-recall", "Metoprolol Succinate ER 50mg", "MET-ER-2026-02-99",
     "Class II",
     "Failed dissolution testing affecting potency.", 22),
    ("hydrochlorothiazide-12-5mg-recall", "Hydrochlorothiazide 12.5mg", "HCT-12-2026-01-77",
     "Class III",
     "Cosmetic defect — chipped tablets in approximately 0.4% of units.", 28),
    ("furosemide-40mg-recall", "Furosemide 40mg", "FUR-40-2026-01-23",
     "Class II",
     "Out-of-specification dissolution testing in stability sample.", 35),
    ("ranitidine-recall-class-i", "Ranitidine 150mg", "RAN-150-2026-01-09",
     "Class I",
     "Elevated NDMA levels — voluntary nationwide recall.", 38),
    ("warfarin-2mg-recall", "Warfarin 2mg", "WAR-2-2026-01-54",
     "Class II",
     "Tablet hardness out of specification.", 42),
    ("levothyroxine-100mcg-recall", "Levothyroxine 100mcg", "LEV-100-2026-01-12",
     "Class II",
     "Subpotent assay results during stability testing.", 46),
    ("sildenafil-20mg-recall", "Sildenafil 20mg", "SIL-20-2026-01-08",
     "Class III",
     "Labeling error on patient information leaflet.", 50),
    ("alprazolam-0-5mg-recall", "Alprazolam 0.5mg", "ALP-05-2026-01-77",
     "Class II",
     "Foreign particulate matter detected.", 55),
    ("clopidogrel-75mg-recall", "Clopidogrel 75mg", "CLO-75-2026-01-66",
     "Class II",
     "Impurity above the acceptable daily intake threshold.", 58),
    ("simvastatin-20mg-recall", "Simvastatin 20mg", "SIM-20-2026-01-44",
     "Class III",
     "Discoloration of tablets in a small portion of lots.", 62),
    ("omeprazole-20mg-recall", "Omeprazole 20mg", "OME-20-2026-01-37",
     "Class II",
     "Dissolution failure in extended-stability tests.", 66),
    ("losartan-25mg-recall", "Losartan 25mg", "LOS-25-2026-01-22",
     "Class II",
     "Trace nitrosamine impurity above ICH guideline.", 70),
    ("atorvastatin-10mg-recall", "Atorvastatin 10mg", "ATO-10-2026-01-19",
     "Class III",
     "Carton labeling error — incorrect lot number printed.", 74),
    ("sertraline-50mg-recall", "Sertraline 50mg", "SER-50-2026-01-15",
     "Class II",
     "Subpotent assay during shelf-life testing.", 78),
    ("gabapentin-300mg-recall", "Gabapentin 300mg", "GAB-300-2026-01-13",
     "Class III",
     "Mislabeled bottle count.", 82),
    ("ibuprofen-200mg-recall", "Ibuprofen 200mg", "IBU-200-2026-01-11",
     "Class II",
     "Possible glass particulate from filling line.", 88),
    ("valsartan-160mg-recall", "Valsartan 160mg", "VAL-160-2026-01-05",
     "Class I",
     "NDEA impurity confirmed above acceptable threshold.", 95),
    ("metformin-1000mg-recall", "Metformin 1000mg", "MET-1000-2026-01-04",
     "Class II",
     "Tablet weight variation outside specification.", 100),
    ("nizatidine-recall", "Nizatidine 150mg", "NIZ-150-2026-01-02",
     "Class I",
     "Elevated nitrosamine impurity.", 108),
    ("rosuvastatin-10mg-recall", "Rosuvastatin 10mg", "ROS-10-2026-01-01",
     "Class III",
     "Slight color variation observed in stability samples.", 115),
    ("losartan-hctz-recall", "Losartan/HCTZ 50-12.5mg", "LHC-2025-12-31",
     "Class II",
     "Trace nitrosamine detected.", 122),
]


PHARMACIES_RAW = [
    # (slug, name, chain, address, city, state, zip_code, phone, hours)
    ("cvs-main-st-springfield", "CVS Pharmacy #4521", "CVS",
     "100 Main St", "Springfield", "IL", "62701", "(217) 555-0101", "Mon-Fri 8a-10p, Sat-Sun 9a-9p"),
    ("walgreens-elm-st-springfield", "Walgreens #1234", "Walgreens",
     "250 Elm St", "Springfield", "IL", "62702", "(217) 555-0202", "24 hours"),
    ("rite-aid-oak-ave", "Rite Aid #888", "Rite Aid",
     "55 Oak Ave", "Springfield", "IL", "62701", "(217) 555-0303", "Mon-Sat 7a-11p"),
    ("walmart-pharmacy-mall-blvd", "Walmart Pharmacy #9012", "Walmart",
     "9000 Mall Blvd", "Springfield", "IL", "62703", "(217) 555-0404", "Mon-Fri 9a-9p, Sat 9a-7p, Sun 10a-6p"),
    ("costco-pharmacy-industrial", "Costco Pharmacy #245", "Costco",
     "1500 Industrial Pkwy", "Springfield", "IL", "62704", "(217) 555-0505", "Mon-Fri 10a-8:30p"),
    ("kroger-pharmacy-stadium-dr", "Kroger Pharmacy #7766", "Kroger",
     "3000 Stadium Dr", "Springfield", "IL", "62701", "(217) 555-0606", "Mon-Sat 9a-9p"),
    ("publix-pharmacy-orange-blvd", "Publix Pharmacy", "Publix",
     "445 Orange Blvd", "Orlando", "FL", "32801", "(407) 555-0707", "Mon-Fri 9a-9p, Sat 9a-7p"),
    ("cvs-times-square", "CVS Pharmacy Times Square", "CVS",
     "1500 Broadway", "New York", "NY", "10036", "(212) 555-0808", "24 hours"),
    ("walgreens-loop-chicago", "Walgreens Chicago Loop", "Walgreens",
     "151 N State St", "Chicago", "IL", "60601", "(312) 555-0909", "24 hours"),
    ("hy-vee-pharmacy-iowa", "Hy-Vee Pharmacy", "Hy-Vee",
     "1500 Pleasant St", "Des Moines", "IA", "50309", "(515) 555-1010", "Mon-Fri 8a-9p, Sat 9a-7p"),
    ("safeway-pharmacy-bayview", "Safeway Pharmacy", "Safeway",
     "1000 Bayview Dr", "San Francisco", "CA", "94117", "(415) 555-1111", "Mon-Fri 9a-9p"),
    ("rite-aid-pacific-coast", "Rite Aid #555", "Rite Aid",
     "2500 Pacific Coast Hwy", "Los Angeles", "CA", "90015", "(213) 555-1212", "Mon-Sat 8a-10p"),
    ("walmart-pharmacy-houston", "Walmart Pharmacy Houston", "Walmart",
     "8500 Westheimer Rd", "Houston", "TX", "77063", "(713) 555-1313", "Mon-Sat 9a-9p, Sun 10a-6p"),
    ("walgreens-buckhead", "Walgreens Buckhead", "Walgreens",
     "3500 Peachtree Rd NE", "Atlanta", "GA", "30326", "(404) 555-1414", "24 hours"),
    ("cvs-back-bay", "CVS Pharmacy Back Bay", "CVS",
     "200 Boylston St", "Boston", "MA", "02116", "(617) 555-1515", "Mon-Fri 7a-11p, Sat-Sun 8a-10p"),
    ("walgreens-georgetown", "Walgreens Georgetown", "Walgreens",
     "1600 Wisconsin Ave NW", "Washington", "DC", "20007", "(202) 555-1616", "24 hours"),
    ("cvs-belmont-shore", "CVS Belmont Shore", "CVS",
     "5200 E 2nd St", "Long Beach", "CA", "90803", "(562) 555-1717", "Mon-Sun 8a-10p"),
    ("rite-aid-portland-pearl", "Rite Aid Pearl District", "Rite Aid",
     "900 NW Lovejoy", "Portland", "OR", "97209", "(503) 555-1818", "Mon-Sat 8a-10p, Sun 9a-9p"),
    ("walmart-bentonville", "Walmart Pharmacy Bentonville", "Walmart",
     "406 S Walton Blvd", "Bentonville", "AR", "72712", "(479) 555-1919", "Mon-Fri 9a-9p"),
    ("costco-seattle-fourth-ave", "Costco Seattle Fourth Ave", "Costco",
     "4401 4th Ave S", "Seattle", "WA", "98134", "(206) 555-2020", "Mon-Fri 10a-8:30p"),
]


# Refill reminders to seed for alice (3 saved drugs already)
ALICE_REFILL_REMINDERS = [
    # (drug_slug, days_supply, frequency, next_refill_offset_days)
    ("ibuprofen", 30, "daily", 11),
    ("metformin", 90, "twice-daily", 28),
    ("atorvastatin", 30, "nightly", 4),
]


# Bob's refill reminders
BOB_REFILL_REMINDERS = [
    ("lisinopril", 30, "daily", 9),
    ("hydrochlorothiazide", 30, "daily", 15),
]


# Side effect reports — seeded for forum credibility (alice, bob, carol, david)
SIDE_EFFECT_REPORTS_RAW = [
    # (drug_slug, severity, body, days_offset, username)
    ("lisinopril", "moderate", "Persistent dry cough developed after 2 weeks of use. Stopping the medication resolved it within 5 days.", 6, "alice_j"),
    ("metformin", "mild", "Loose stools and stomach discomfort during first 2 weeks; resolved after switching to extended-release.", 11, "bob_c"),
    ("atorvastatin", "moderate", "Muscle aches in calves; CK levels were borderline elevated.", 18, "alice_j"),
    ("warfarin", "severe", "Significant bruising and one episode of gum bleeding within 3 weeks of starting therapy.", 25, "david_k"),
    ("ibuprofen", "mild", "Mild stomach upset when taken without food.", 32, "carol_d"),
    ("sertraline", "mild", "Initial nausea for first week; resolved with food.", 39, "alice_j"),
    ("gabapentin", "moderate", "Daytime drowsiness even at the lowest titration step.", 46, "bob_c"),
    ("levothyroxine", "mild", "Mild palpitations after dose increase; resolved with dose reduction.", 53, "carol_d"),
    ("alprazolam", "moderate", "Daytime grogginess and difficulty concentrating.", 60, "david_k"),
    ("clopidogrel", "mild", "Easy bruising — typical and within expected range.", 67, "alice_j"),
    ("omeprazole", "mild", "Headache during the first week, resolved.", 74, "bob_c"),
    ("amlodipine", "mild", "Mild lower leg edema after 4 weeks.", 81, "carol_d"),
    ("losartan", "mild", "Dizziness when standing up quickly during first week.", 88, "david_k"),
    ("simvastatin", "moderate", "Muscle aches in thighs after 3 weeks.", 95, "alice_j"),
    ("metoprolol", "mild", "Fatigue and exercise intolerance.", 102, "bob_c"),
]
